### ISSUE TITLE
Error 404 when connected in the backend

### ISSUE THREAD

**Issue by echavaillaz** [dmitryd/typo3-realurl#101]
Hi Dmitry,

When a user is connected in the backend, realurl generate only error 404 in the frontend.
It is not possible to reproduce when no user is connected in the backend (the rewrite works).

Thanks

**Comment by dmitryd** [comment]
Sorry, I cannot confirm the issue. You have to provide more information if you want me to fix it.

**Comment by echavaillaz** [comment]
Ok which kind of information do you need exactly?

**Comment by dmitryd** [comment]
Your realurl config, your page tree, example urls that cannot be decoded.

**Comment by echavaillaz** [comment]
Ok, so my config :

**Comment by dmitryd** [comment]
What is the type of `a_section_page`? Why is it excluded from the URL?

**Comment by echavaillaz** [comment]
It's a page with the CType 199 (Menu Separator). This is for this reason that the page is excluded.

**Comment by dmitryd** [comment]
Please, change to folder or use `Enable bad behavior` in the extension properties. This should solve the problem.

Separators are not supposed to have subpages. They are pure visual separators for menu items.

**Comment by echavaillaz** [comment]
Ok when using a folder it's solved.
Si it's not a bug, you can close.

Thanks for the answers.

**Comment by dmitryd** [comment]
Thanks!
