### ISSUE TITLE
Different domains for language-switching do not work (_DOMAINS-feature)

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#103]
I am using the _DOMAINS feature for language switching. When there is a page where the german name is equal to the english name, there will be two entries in the UrlCache for the same page:
![duplicateentry in url-cache](https://cloud.githubusercontent.com/assets/209159/14143159/0da3caee-f68a-11e5-9672-0424b0437569.png)

When I try to load www.example.de/service/ I get the german version. But I also get the german version when I try to load www.example.com/service/. I think the Parameters in the UrlCache overwrite the parameters from the domain (which should not happen)

My domains configuration:
```php
'_DOMAINS' => [
	'encode' => [
		[
			'GETvar' => 'L',
			'value' => '0',
			'useConfiguration' => 'www.example.de',
			'urlPrepend' => 'http://www.example.de',
		],
		[
			'GETvar' => 'L',
			'value' => '1',
			'useConfiguration' => 'www.example.com',
			'urlPrepend' => 'http://www.example.com',
		],
	],
	'decode' => [
		'www.example.de' => [
			'GETvars' => [
				'L' => '0',
			],
			'useConfiguration' => 'www.example.de'
		],
		'www.example.com' => [
			'GETvars' => [
				'L' => '1',
			],
			'useConfiguration' => 'www.example.com'
		],
	],
],
```

**Comment by SOFTWORK** [comment]
Same Problem here, cache ignores the L var

**Comment by SOFTWORK** [comment]
The Problem, with content is fixed now, but the title tag has always the problem with wrong language, thanks for fixing this

**Comment by dmitryd** [comment]
Realurl is only about encoding and decoding urls. Nothing to do with a title tag at all.
