### ISSUE TITLE
FEATURE: Enable UrlCache when logged in as Admin

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#104]
Currently the UrlCache is disabled when logged in as admin (see Utility::getCache())

This makes it hard to detect bugs before going live. When I am developing, I am always logged in in the TYPO3-backend. Then of course all URLs work fine, but when I deploy to the live-system, suddenly URLs don't work because of undetected bugs like #103 or #76.

This could be prevented, if I can force the cache to be enabled even for admin users. That way I would realize sooner, if the cache is a problem.

**Comment by dmitryd** [comment]
No, this will not change. Use a different browser instead.
