### ISSUE TITLE
"uniqueInPid" setting only for browsable doktypes

### ISSUE THREAD

**Issue by sorenmalling** [dmitryd/typo3-realurl#106]
The following settings in pages.php (TCA override)

`$GLOBALS['TCA']['pages']['columns']['title']['config']['eval'] =
	isset($GLOBALS['TCA']['pages']['columns']['title']['config']['eval']) ?
		$GLOBALS['TCA']['pages']['columns']['title']['config']['eval'] .= ',uniqueInPid' :
		'uniqueInPid';`

make it impossible to have more than one "divider" page named "-------" - currently, the second one is renamed to "-------0"

Perhaps using columnsOverrides from the TCA[1] could be of help. I will look into this once the current project ( where i found this issue) is done (~1 week from now) 

[1] https://docs.typo3.org/typo3cms/TCAReference/Reference/Types/Index.html#columnsoverrides

**Comment by dmitryd** [comment]
I plan to remove that eval.

**Comment by sorenmalling** [comment]
@dmitryd Okay - if so, feel free to close this ticket. If you wan't me to fix it, just let me know and i will try and use the columnoverrides solution
