### ISSUE TITLE
Conflict with workspaces

### ISSUE THREAD

**Issue by geraldaistleitner** [dmitryd/typo3-realurl#107]
if workspaces are used wrong cache entries may be produced.
Example:

Structure in Live Workspace:
Page
 - Subpage (id=3954)

Structure in Devel Workspace:
Page
** - Subpage (id=3986)**
 - Subpage (id=3954)

**Subpage** is a copy of Subpage and has the same title.

In some cases the **Subpage** ID is written into the decode cache.
Wrong decode cache entry:
a:3:{s:11:"rootpage_id";s:1:"1";s:2:"id";i:3986;s:8:"GET_VARS";a:1:{s:1:"L";s:1:"0";}}
Right decode cache entry:
a:3:{s:11:"rootpage_id";s:1:"1";s:2:"id";s:4:"3954";s:8:"GET_VARS";a:1:{s:1:"L";s:1:"0";}}

if the wrong cache entry is generated typo3 will generate a 404 Error.

**Comment by dmitryd** [comment]
Realurl does not support workspaces. It is too much trouble to support.
