### ISSUE TITLE
Icons for TYPO3 6.2 - 8

### ISSUE THREAD

**Issue by xperseguers** [dmitryd/typo3-realurl#110]
The "pill" as backend module icon is suboptimal since it is not white on a plain color background as the other modules. As such, realurl is not as smoothly integrated in BE as it should be.

Here are a few icons I prepared this morning, as a suggestion for replacement. 64x64 is the size for the module icon, whereas I switched from gif to png for extension icon and used a 32x32 instead of the standard 16x16 in order to be crisp on retina display since TYPO3 supports it and this looks much nicer on modern screens and "the same" on non-retina ones.

I hope this is fine with you and thanks for your maintenance job.

![module](https://cloud.githubusercontent.com/assets/646805/14198642/d13a560a-f7dc-11e5-90c6-b7ad5ba80832.png)

![ext_icon](https://cloud.githubusercontent.com/assets/646805/14198641/d12d4bfe-f7dc-11e5-8b20-effc69a96a56.png)

![ext_icon-alt2](https://cloud.githubusercontent.com/assets/646805/14198644/d1424590-f7dc-11e5-8f8b-70259516403d.png)

![ext_icon-alt](https://cloud.githubusercontent.com/assets/646805/14198643/d140c65c-f7dc-11e5-97f4-a20adec82a60.png)

(3 alternative extension icons...)

**Comment by dmitryd** [comment]
It depends. I got messages from people, who liked that pill icon.

**Comment by xperseguers** [comment]
Must be April's Fool, but if really true, then please at least make it crisp, not blurry, and blending in rest of TYPO3 would be nice, so a *white* pill maybe?

**Comment by dmitryd** [comment]
Well, at the moment it is not that top priority. As you may see, there are other issues that are more important. Icon is the lowest priority on my list...

**Comment by xperseguers** [comment]
Sure! sorry for disturbing! ^^

**Comment by dmitryd** [comment]
Shouldn't be closed but I will take care only after more important issues (bugs) are resolved.

**Comment by NeoBlack** [comment]
Yes, I understand you, replace the icons is so much work.

**Comment by maddy2101** [comment]
Luckily this is a community. Work is done: https://typo3.org/extensions/repository/view/nice_icon_realurl
Thank you for the effort, Xavier.

**Comment by cedricziel** [comment]
Meanwhile, in a parallel universe where people are nice to each other, someone creates a pull request for the freaking icons instead of taking the same time to write a sarcastic comment.

**Comment by dmitryd** [comment]
Btw, [Contributing](https://github.com/dmitryd/typo3-realurl/wiki/Contributing) on the wiki.

**Comment by dmitryd** [comment]
Since there is no pull request, there is a separate ext for it and the author himself closed the issue before, I will close it as well. If you want to change icons, make a pull request as other contributors do.

Conversation is locked to prevent useless comments.
