### ISSUE TITLE
banUrlsRegExp and pagebrowser pages

### ISSUE THREAD

**Issue by christophlehmann** [dmitryd/typo3-realurl#114]
I have a guestbook with a pagebrowser. The pagebrowser parameter is `tx_veguestbook_pi1[pointer]`.

When i open the guestbook.html with
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT'] = array(
        'cache' => array(
                'banUrlsRegExp' => '/tx_veguestbook_pi1|tx_solr|tx_indexed_search|(?:^|\?|&)q=/'
        ),
```
i suppress cache entries with "tx_veguestbook_pi1", but when i open the page guestbook.html?tx_veguestbook_pi1[pointer]=1 it generates a cache entry.

Is it a bug? I would expect that I have only one cache entry for guestbook.html and not a second one for guestbook.html?tx_veguestbook_pi1[pointer]=1

Is there a way to suppress the second entry?

**Comment by dmitryd** [comment]
I will check if it is a bug or not.

In general, you should not ban page browser. This config entry is only for parameters with random values. Page browser has values that should be cached. If you ban it from caching, you will slower done your site.

**Comment by dmitryd** [comment]
Yes, this was a bug.

**Comment by dmitryd** [comment]
Thank you for reporting.

**Comment by christophlehmann** [comment]
Thanks for fixing!
