### ISSUE TITLE
Expired Path ignored for BE Users

### ISSUE THREAD

**Issue by s-ude** [dmitryd/typo3-realurl#115]
The cache is turned off for BE users which of course is basically a good thing - for cache reading and writing.

However, it results in a situation where an old URL (expired e.g. due to a page renaming) is still working for normal visitors of the website (they are being redirected to the new URL of the page) but a user logged in to the BE is getting a 404 error.

Actually I can't decide whether this is really a bug or just the plain result of the architecture. Though it is odd that a BE user has less working FE-URLs than a normal visitor.

What do you think about this behaviour?

**Comment by dmitryd** [comment]
I think:
* BE user does not need expired pages
* You can always use a second browser if you do not need caching

Please, ask questions in mailing lists.

**Comment by s-ude** [comment]
This is an absolutely valid view, I agree. I just wanted to make sure that this behaviour is noted/known since a (SEO-scared) content manager stumbled upon the effects of these mechanics.

But in this case this issue can be closed.
(I did not use the mailing list because I think it is an issue which can but be closed without a fix.)

**Comment by dmitryd** [comment]
Okay, thank you!
