### ISSUE TITLE
Redirect to correct localized path

### ISSUE THREAD

**Issue by FlorianX** [dmitryd/typo3-realurl#116]
TYPO3 6.2.19
RealURL 1.13.5

Hey,

is there a solution to redirect automatically to the correct localized pagepath?
E.g.:

Client request
domain.com/en/unternehmen --> Redirect to --> domain.com/en/company
domain.com/en/impressum --> Redirect to --> domain.com/en/imprint

Thanks for your help!

**Comment by dmitryd** [comment]
This place is for bugs. Please, ask questions in TYPO3 mailing lists.

**Comment by FlorianX** [comment]
Sorry for that, could you send me an link to the mailing list of real url?

**Comment by dmitryd** [comment]
There are no lists for realurl but there are general lists like typo3.english or other lists if you prefer other language.

Information is here: https://typo3.org/community-support/mailing-lists/

**Comment by FlorianX** [comment]
for some others: http://lists.typo3.org/pipermail/typo3-english/2016-April/095270.html

**Comment by dmitryd** [comment]
Just for the sake of completeness: redirects are not related to realurl.
