### ISSUE TITLE
Changing default language bug

### ISSUE THREAD

**Issue by Naberd** [dmitryd/typo3-realurl#118]
we have changed default language in our installation of typo3 7.6 with queries in database.
and made a default language as new one.
query to create new language from default:
`create table old_pages_language_overlay like pages_language_overlay;`
`insert into old_pages_language_overlay (pid,tstamp,title, nav_title, keywords, description, doktype, hidden, deleted) select uid,tstamp,title, nav_title, keywords, description, doktype, hidden, deleted from pages;`
`update old_pages_language_overlay set sys_language_uid = 1;`
`insert into pages_language_overlay (pid,tstamp,title, nav_title, keywords, description, doktype, sys_language_uid, hidden, deleted) select pid,tstamp,title, nav_title, keywords, description, doktype, sys_language_uid, hidden, deleted from old_pages_language_overlay;`

and query to set pagetree to use contents of the other language as default: 
`update pages p inner join pages_language_overlay plo on plo.pid = p.uid set p.nav_title = plo.nav_title, p.title = plo.title, p.keywords = plo.keywords, p.description = plo.description where plo.sys_language_uid = 3;`

according to our setup now site by default uses language 1 which where made from default, pages are indeed in that language, but url's are used from default instead of pages_language_overlay in this case.

why is that happening i don't understand but when we are downloading file trough ajax call it does return file based on the pages_language_overlay  url  which results in 404

**Comment by dmitryd** [comment]
Questions are not answered in the bug tracker. Please, use mailing lists.

**Comment by dmitryd** [comment]
https://github.com/dmitryd/typo3-realurl/wiki/Contributing#bug-reporting
