### ISSUE TITLE
Page Type Seperator

### ISSUE THREAD

**Issue by Mojo1** [dmitryd/typo3-realurl#119]
I actually don't fully understand why subpages of separator page type aren't decoded anymore.
I guess it's a design decision and not a tecnical issue.

Official docu states
https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/PageTypes/Index.html

So it says they are also intended for frontend navigation. As a fact they can't be used for frontend navigation because links stop working if page is placed beneath a seperator if realurl 2.x is enabled.

For this it would be good to know why this design decision has been taken.

**Comment by dmitryd** [comment]
Bug tracker is for bugs. Please, do not ask questions here. And read the wiki before you ask...

**Comment by Mojo1** [comment]
Ok, so in my view it's a bug, just tried to express it in a nice way.
TYPO3 documentation states "is usable for frontend navigation" - implementation doesn't follow specification. Thus it's broke, thus it's a bug. There is not any specification that sperator shouldn't hold subpage. It's possible to create some at least.

For sure it's a matter of interpretation. For me this way it doesn't make sense. But fair enough...

Pro for having behaviour like 1.x:
Backend:
Seperator can in opposite to folder not hold data - so it's a good way to indicate that beneath the seperator there is a different section holding pages for a certain purpose. I don't want my editors to create data on folders which are intended to be a seperator. (I know i can set according permissions but that's not the point)

Frontend:
Let's say i want a menu having on top level dynamically some pages linked and some pages not linked. On second level everything is linked. How to write according TypoScript? 
So far it was possible to handle this with page type seperator. Linked pages are standard pages not linked pages are type seperator as it is a seperator. Still there is a submenu.

Status realurl 2.x I have to extend pages tca to offer a custom field to give editor the possibility to control weather a page should be linked or not.

**Comment by dmitryd** [comment]
Did not read the wiki yet? 😄

**Comment by Mojo1** [comment]
Which Wiki are you talking about? The "How to install TYPO3" Wiki or the "How to grow wonderfull roses" Wiki?
In case you are refering to Wiki of this github project yes I have read it. In case you are refering to any other Wiki please give reference so other people can understand what you are talking about.

In specail this two chapters fetched my very special attention
https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x#about-https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#page-types

They you state "They should not have subpages".
This in my opinion is a misconception of you. That's all I am saying. In my personal view it does not make sense and there is no reason why a separator should not have submenus and also in any other source i didn't find a statement why this shouldn't be allowed. Abusing a folder to simulate a separator is not the solution i guess. 
Espacially the frontend usecase I posted in my post before should clarify what I am talking about. 
Anyway in the end of the day we could say page type "seperator" in TYPO3 is undefinied as long as you can't give reference in which it's stated different.
So maybe I upload an addon of realurl to TER soon with the new feature "Enable Separators in TMENU"

**Comment by BoBaH83** [comment]
enable the "enableBadBehavior" via extension manager and you can use separators

https://github.com/dmitryd/typo3-realurl/blob/58c86bfff36987610ab8d1ba1d703796f531422c/Classes/Decoder/UrlDecoder.php#L1066
