### ISSUE TITLE
Recursion problem with shortcut page 

### ISSUE THREAD

**Issue by christophlehmann** [dmitryd/typo3-realurl#120]
In Realurl 1.x it was possible to have a pagetree like

```
+ forum (exclude_from_speaking_url=1, shortcut to subpage "forum")
++ forum (not_in_menu=1)
++ page3
++ page4
```

With Realurl 2 i get "ERR_TOO_MANY_REDIRECTS"

**Comment by dmitryd** [comment]
exclude + "forum" and "forum" is a problem. If names were different or no exclusion, realurl could resolve it.

realurl is not always magical :(

**Comment by christophlehmann** [comment]
No Problem,  there are definitly better ways to do it, so lets close it
