### ISSUE TITLE
No language in encoded url on index.php?=XXXX

### ISSUE THREAD

**Issue by schaefdavid** [dmitryd/typo3-realurl#122]
How to reproduce:

- I used the same config as in realUrl 1.13 - and there it worked.

I am in the backend and I click on show page. The page http://domain.tld/index.php?id=1234 is opened. Normally the pages are encoded like: http://domain.tld/lang/menu/submenu. But then the pages are encoded without the lang:  http://domain.tld/lang/menu/submenu.

It seems that 'valueDefault' of configuration is not evaluated.

**Comment by dmitryd** [comment]
Please, [read the wiki](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-languages) and check/adjust your configuration.

**Comment by schaefdavid** [comment]
yes - this is exactly my configuration. if "'valueDefault' => 'lang',", the behaviour on realurl 1.13 and realurl 2 is exactly the same: the lang in the econded urls on this page is mssing: http://domain.tld/menu/submenu.

**Comment by dmitryd** [comment]
That's right. Language is not set. Why would it appear in the URL?

Adjust your config as described in the wiki.

This is not a bug and should be discussed in the mailing list, not here.
