### ISSUE TITLE
Filename Configuration with Filename Suffix does not work correctly

### ISSUE THREAD

**Issue by timhorstmann** [dmitryd/typo3-realurl#123]
In realurl 1.x it was possible to define a dot + filesuffix as key in filename Configuration:

```
'fileName' => array(
  'index' => array(
   '.xml' => array(
    'keyValues' => array(
     'type' => 30,
    ),
   ),
 )
```
 
With realurl 2.x this configuration produces an url like

someURL/pathsegment/.xml

but URL should look like

someURL/pathsegment.xml

**Comment by dmitryd** [comment]
Thanks for reporting!
