### ISSUE TITLE
404 for pages within "Menu Separator" in Frontend while logged in to Backend

### ISSUE THREAD

**Issue by ikkez** [dmitryd/typo3-realurl#124]
When I'm logged in to the TYPO3 Backend, then a lot of rewritten frontend links lead to 404. I know that link building is only started when you are visiting the page while not logged in, but already working/rewritten page links stop to work while logged in. As soon as I log out, it works again. 
I noticed that this only occurs for pages that are childs of a "menu separator" page. My "separator" page has the "Exclude from speaking URL" option set, but it does not seem to make a difference if I enable or disable that.
This worked fine in 1.x and was broken now after upgrade to 2.x.

**Comment by dmitryd** [comment]
Wait until 2.0.12.

**Comment by ikkez** [comment]
So is this already fixed? When to expect the next release?
