### ISSUE TITLE
Shortcut to translated pages use original language 

### ISSUE THREAD

**Issue by davdenic** [dmitryd/typo3-realurl#126]
I have a page

Kontakt (DE)
Translated to 
Contact (en)

And I have a navigation with shortcuts like

/de/service/kontakt

The english version shortcut to

/en/service/kontakt

Instead of /en/service/contact

Thanks you:)

**Comment by dmitryd** [comment]
Possibly related to #103

**Comment by dmitryd** [comment]
Cannot reproduce this either in the current development version. I suggest to wait till 2.0.12 and see if it is reproducible.

**Comment by dmitryd** [comment]
Solved "in-house" (at snowflake).
