### ISSUE TITLE
Dynamic page products issue

### ISSUE THREAD

**Issue by morinfa** [dmitryd/typo3-realurl#127]
Hello,

We use realurl extension to handle nice URLs for our dynamic pages of products. A single page can handle the display of all products using product ID in URL (e.g. http://localhost/product/1, http://localhost/product/2, http://localhost/product/3...).
All products pages are cached using cHash attribute (which is hidden by realurl using the correct configuration).
It works great if all products links are generated using typolink function.

The problem is that realurl cache tables containing cHash and mapping URL are truncated by a hook on TYPO3 clear cache.
So after a clear cache, all nice URLs are no more working until they are regenerated using typolink function. All products pages are no more accessible until their URLs are regenerated, which can take time because we have thousands of products with multiple languages.

We currently handle this issue by "warming up" realurl cache table (i.e. regenerating all products URL with typolink function). It can take several minutes. during this time products page are not available.

Is there a clean way to address this issue ?

Regards,
Fabrice

**Comment by dmitryd** [comment]
FYI: questions are not answered in the bug tracker.

https://github.com/dmitryd/typo3-realurl/wiki/Contributing#bug-reporting

**Comment by morinfa** [comment]
I'm really sorry but I asked on TYPO3 forum : https://forum.typo3.org/index.php?t=msg&goto=739516&#msg_739516, and got no answer.
Where is the best place to ask ?

**Comment by dmitryd** [comment]
According to the link above: “All questions should be addressed to the TYPO3 **mailing lists**.”

https://typo3.org/community-support/mailing-lists/

For now don't ask the question there because there is no real answer to this problem. I need to think a little and may solve this in the next version.

Thanks for brining the problem!
