### ISSUE TITLE
Speed up delete query?

### ISSUE THREAD

**Issue by lochmueller** [dmitryd/typo3-realurl#129]
There are same queries like `DELETE FROM tx_realurl_uniqalias_cache_map WHERE url_cache_id IN (SELECT uid FROM tx_realurl_urlcache WHERE page_id=740);` that are run nearly a minute and scan 120.039 records (in my case). Perhaps this query need same love (Index, Code restructure)?!

I add a Index for "url_cache_id" but this was not the right solution?!?!

Thanks for realurl 2.x,
Tim

**Comment by dmitryd** [comment]
Thanks for reporting. I think I know what can be the cause.

**Comment by nedt** [comment]
@dmitryd we had the same problem. Adding the fix didn't help, the index still isn't used. Seems like it'd be better to use a join like:
`DELETE tx_realurl_uniqalias_cache_map
FROM tx_realurl_uniqalias_cache_map
JOIN tx_realurl_urlcache ON tx_realurl_uniqalias_cache_map.url_cache_id = tx_realurl_urlcache.uid
WHERE tx_realurl_urlcache.page_id=?;`

**Comment by dmitryd** [comment]
Try analyzing the table twice using mysql console. The index works here. I doubt the join will be better. Joins are usually worse than subqueries.
