### ISSUE TITLE
realurl brakes simulatestatic after switching from 1.13.6 to 2.12 on Typo3 6.2.21

### ISSUE THREAD

**Issue by sksksksk** [dmitryd/typo3-realurl#130]
I'm was using Typo3 6.2.21 with simulatestatic and realurl 1.13.6 and multiple sites under their own domain record. Sites where simulatestatic was enabled worked and the sites where realurl was enabled, worked, too.

After upgrading to realurl 2.12, the sites with enabled simulatestatic stopped working. I had URLs of the form
http://xxx.yyy.zzz/PAGEID.html
and I get a 404 error with message
Segment "PAGEID" was not a keyword for a postVarSet as expected on page with id="ROOTPAGEID".

I switched back to 1.13.6 but it would be interesting to know if there is a solution to this.

**Comment by dmitryd** [comment]
Realurl cannot be installed together with simulatestatic. Simulatestaic is marked as conflicting extension. TYPO3 warned you, doesn't it?

**Comment by sksksksk** [comment]
no, it did not warn me. Not when I installed 1.13 and neither when I upgraded to 2. I just realized that it is marked as conflicting even on the 1.13 version. This is really curious. 

So I suppose I have to stick with 1.13 until all sites are switched to realurl, and then make the upgrade

**Comment by dmitryd** [comment]
Yes, this is the best. Simulatestatic is a very old technology. Realurl 1.x had a special check for it but 2.x lacks this check.

Let's keep this open for a while. I will have a look if I can add that check again.

**Comment by sksksksk** [comment]
Thanks for taking time to work on this.

I've tested the latest version, and it works now partially.

If I set 'respectSimulateStaticURLs' => 'TRUE' for a domain in the realurl configuration file, URLs of the form
http://xxx.yyy.zzz/PAGEID.0.html work
but URLs of the form
http://xxx.yyy.zzz/PAGEID.html do still not work.

I get something like
Segment "PAGEID" was not a keyword for a postVarSet as expected on page with id=DOMAIN_ROOT_PAGE_ID. 

Is there some other setting needed for this?

**Comment by dmitryd** [comment]
If you use /page.html, it will not looks like a simulateStatic URL for RealURL. Rather it will look like a normal URL of RealURL.

**Comment by sksksksk** [comment]
yes, I get that.

I assumed that as long as realurl is not enabled for a domain, realurl would be completely inactive and would not try to make any kind of url transformations.

**Comment by dmitryd** [comment]
Disabling RealURL for the domain is possible only with TypoScript. However when RealURL is executed to decode the URL, there is no page id and therefore there is no TypoScript.

[Documentation](https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#enabling-the-extension):

> By default the extension is disabled and will not encode URLs. **It will still decode URLs** but the encoding must be enabled with the following TypoScript setup option:

**Comment by sksksksk** [comment]
you are right of course.

For anyone who might get here:

A possible workaround would be to use rewrite rules with a rewritecondition on the hostname
RewriteCond %{HTTP_HOST} ^www\.DOMAIN\.gr [NC]
RewriteRule ([0-9]+)\.html$ /index.php?id=$1 [R=302,NE,QSA,L]

This will redirect requests only for the specified domain. It rewrites PAGEID.html to /index.php?id=PAGEID and will also add all remaining query strings. The temporary redirect (302) could be replaced by a permanent one (301)
