### ISSUE TITLE
Reason: No news entry found

### ISSUE THREAD

**Issue by typo3ua** [dmitryd/typo3-realurl#132]
Hello, everybody!

I have:
TYPO3 7.6.5
EXT: news 4.2.1
EXT: realurl 2.0.9

List news:
www.doamin.ltd/news/ - good work.
Detail news:
www.doamin.ltd/news/detail/where-can-i-get-some/ - good work.

Then I updated my current "realurl" to "EXT: realurl 2.0.12" and on detail view news page I get error: 

Reason: No news entry found

List news:
www.doamin.ltd/news/ - good work.
Detail news:
www.doamin.ltd/news/detail/where-can-i-get-some/ - I get error: Reason: No news entry found

**Comment by dmitryd** [comment]
[Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)

**Comment by typo3ua** [comment]
Thanks!
