### ISSUE TITLE
Problem with uppercase / lowercase

### ISSUE THREAD

**Issue by 0joker01** [dmitryd/typo3-realurl#134]
Hi,
i have installed latest TYPO3 7.6.5 version with default demo content. When i click on the top menu "About" -> "TYPO3", i get "Page not found" error on the "/about/typo3/" url. But when i change "/about/typo3/" url to "/about/Typo3/" or "/about/TYPO3/", it's works.

**Comment by dmitryd** [comment]
Not a bug in RealURL. Have a look to `.htaccess` in your home directory:

```
RewriteRule ^(typo3/|fileadmin/|typo3conf/|typo3temp/|uploads/|favicon\.ico) - [L]
```

If there is a `typo3` in url, it will not be passed to RealURL and will not work.
