### ISSUE TITLE
404 File not found if page named like directory

### ISSUE THREAD

**Issue by AMunkAT** [dmitryd/typo3-realurl#135]
Hi,

I've discovered following issue:

- I have one page with name downloads in an directory service
- directory service is excluded from speaking url
- I have one directory with name downloads

ROOT
-Service (Exclude from speaking URL)
--Downloads (Page)
-Downloads (Directory)

- if page not found handling is enabled, i got a 404 error if i go to /downloads
- if the directory downloads is renamed, everything works fine

Best regards

**Comment by dmitryd** [comment]
Those are exactly items 3 and 4 in the documentation: https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#limitations

**Comment by AMunkAT** [comment]
Thank you!
Sorry for issue
