### ISSUE TITLE
Redirect of RSS page to first sub page

### ISSUE THREAD

**Issue by Patta** [dmitryd/typo3-realurl#138]
Since v2.0.13 rss pages like https://domain.Info/rss.xml redirect (307 temporary redirect) to the configurated sub page of the root page. In my case to https://domain.Info/home/

Home is the first sub page under root. So for normal request the redirect is correct. But for the RSS page (Type 100, default realurl and ttnews config) it shouldn't.

I switched back to v2.0.11 and it works. Updated again to v2.0.13, the RSS page redirect again to home.

Is this an configuration Issue with default real url RSS config or are there changes in the last two releases?

THX

**Comment by Patta** [comment]
TYPO3 6.2.21

**Comment by dmitryd** [comment]
There are two things here. Firsts, the redirect should happen but to `/home/rss.xml`. In your case detected page will be your shortcut page. RealURL will return shortcut page to TYPO3 and let TYPO3 handle it. TYPO3 will see that it is a shortcut and redirect to a shortcut target after checking for valid page type. However there is a bug in RealURL that makes `type` lost. This will be fixed but redirect will still happen.

**Comment by potofcoffee** [comment]
I think this is a bug introduced in commit ed9086ae49d7fc1931c4ff57ca7079c8ffacc239, with the changes in UrlEncoder.php at lines 911ff. In the current state, the condition in line 911 causes all fileName/index configurations not starting with a dot to be completely ignored. I think this condition simply misses an "`else`" section:

Adding `} else $this->encodedUrl .= '/'.$fileName;` in line 919 worked for me.

**Comment by Patta** [comment]
thanks for fast release. but its not working. redirect to non `rss.xml` page exists.
