### ISSUE TITLE
Mountpoint support across domains

### ISSUE THREAD

**Issue by kkretsch** [dmitryd/typo3-realurl#140]
I'm using a fresh TYPO3 7.6.5 with realurl 2.0.14 with auto configuration active.
As I have two seperate root domain trees in my installation I wanted to include a subtree from one into a subtree mountpoint in the other domain. It sort of links correctly but gets that nasty MP=1-22 like parameter appended. Whats even worse: If I skip that parameter it jumps back to the home page of that domain.

I'm sure that worked within an older project some years ago I have no longer access to, it was a TYPO3 6.2 version, no idea what realurl version was current to that time.

Any work around, patches, hope for the future?

**Comment by kkretsch** [comment]
Small addition: I just checked on a 6.2 TYPO3 installation with a 1.x realurl extension. There it still works with mountpoint as-the-should. You stay inside the domain and get content from the other domain tree without any additional parameters.

As there are still some source fragments to find when searching for "mountpint" I think it should still work somehow even without that MP parameters. Anyone out there with similar problems?

**Comment by ajindra** [comment]
Yes, I am struggeling with this at the moment, using TYPO3 6.2.22 and RealURL 2.0.14. Same situation as you described: One page in Domain A gets mounted from several (about 90 ;-)) other pages in other Domains within the same pagetree (about 15000 pages). It works for a short moment, when tx_realurl_pathcache and tx_realurl_urlcache are emptied (truncated). I'm still searching the entries which are responsible for the malfunction. With RealUrl 1.x it worked.

**Comment by itekne** [comment]
Hi,
Same problem here with a TYPO3 7.6.6 multisites platform, realurl 2.0.14 and ... mount points (same situation as @ajindra described).
In my case, links to pages mounting another domain pages will work until the realurl cache tables get filled. After a short moment, my links leads to 404 error or "To many redirects" 500 error (https://github.com/dmitryd/typo3-realurl/issues/93).

**Comment by ajindra** [comment]
It leads to an error as soon as there are two entries in the pathcache, one without the mpvar being set:
```
| uid   | page_id | language_id | rootpage_id | mpvar    | pagepath       | expire | pid |
| ---   | ---     | ---         | ---         | ---      | ---            | ---    | --- |
| 10021 | 891     | 0           | 1626        |          | diverses/suche | 0      | 0   |
| 10022 | 891     | 0           | 1626        | 891-1628 | diverses/suche | 0      | 0   |
```
When I delete the entries with no mpvar set, the page works (once, then the entry is created again).

**Comment by dmitryd** [comment]
@ajindra Thanks for the hint.

I have no estimates for the fix yet but I will try to find time.

**Comment by p2media** [comment]
We are having a similar issue as described form [@ajindra above](https://github.com/dmitryd/typo3-realurl/issues/140#issuecomment-218377015).

After some time of back-tracing we found that the MP requestVar is missing in the `UrlCacheEntry` while decoding. The first time the URL will be decoded `UrlDecoder` can determine the proper MountPoint. 
For some reason `UrlDecoder->runDecoding` can not fetch a `UrlCacheEntry` the second time, thus the MountPoint is missing in $requestVariables.

This will cause the error `ID was outside the domain` in `\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController:1544` and TYPO3 will display the 404 error page.

**Comment by dmitryd** [comment]
Do you still have problems with it if you use version 2.1.7? I just tried to reproduce it and cannot. I am using the following page tree:

![page-tree](https://cloud.githubusercontent.com/assets/306133/23124975/c239f9ae-f780-11e6-9bbf-47d5233b26d2.png)

Every mount point mounts the page pointed to by the red arrow. Mounted pages A1, A2, and A3 are accessible from the second domain as well as from the first domain.

**Comment by kkretsch** [comment]
I just updated from 2.1.5 to 2.1.7 on that site, refreshed as much cached as I could and it seems to work correctly!
Until now I did not see any additional but unwanted MP parameters, just plain urls as it should be.

Thanks.

**Comment by dmitryd** [comment]
I would like to thank [TYPO3 Agentur p2 media](www.p2media.de.), who sponsored the work on this issue. They were great, professional and fast in answering questions and providing help with this issue!
