### ISSUE TITLE
Realurl breaks reference index update

### ISSUE THREAD

**Issue by pgampe** [dmitryd/typo3-realurl#141]
The easiest way would be to add the column, but you could also try to disable the reference index stuff on this table (if this is even possible).

array(4 items)
   caller => "TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery" (60 chars)
   ERROR => "Unknown column 'uid' in 'field list'" (36 chars)
   lastBuiltQuery => "SELECT uid FROM tx_realurl_pathcache WHERE 1=1" (46 chars)
   debug_backtrace => "call_user_func#21 // {closure}# // TYPO3\CMS\Backend\Http\Application->run#2
      0 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Backend\Ht
      tp\BackendModuleRequestHandler->handleRequest#302 // TYPO3\CMS\Backend\Http\
      BackendModuleRequestHandler->dispatchModule#92 // TYPO3\CMS\Core\Http\Dispat
      cher->dispatch#201 // call_user_func_array#41 // TYPO3\CMS\Lowlevel\View\Dat
      abaseIntegrityView->mainAction# // TYPO3\CMS\Lowlevel\View\DatabaseIntegrity
      View->main#261 // TYPO3\CMS\Lowlevel\View\DatabaseIntegrityView->func_refind
      ex#214 // TYPO3\CMS\Core\Database\ReferenceIndex->updateIndex#332 // TYPO3\C
      MS\Core\Database\DatabaseConnection->exec_SELECTquery#1182 // TYPO3\CMS\Core
      \Database\DatabaseConnection->debug#314" (723 chars)

**Comment by dmitryd** [comment]
Column exists. [See the code](https://github.com/dmitryd/typo3-realurl/blob/development/ext_tables.sql#L56).

Please, read the [upgrade guide](https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x) before posting bugs 😄
