### ISSUE TITLE
sectionIndex is dropped?

### ISSUE THREAD

**Issue by lochmueller** [dmitryd/typo3-realurl#143]
Hey Dmitry,

realurl do not respect the "sectionIndex" that is part of the LD. 

If realurl is disabled this URL is generated:
`http://test.local.de/index.php?id=118#cp119`
If I active realurl the totalURL is:
`http://test.local.de/product.html`

Quick solution is, to change a line in the Encoder ( EXT:realurl/Classes/Encoder/UrlEncoder.php ):
`$encoderParameters['LD']['totalURL'] = $this->encodedUrl;`
->
`$encoderParameters['LD']['totalURL'] = $this->encodedUrl . (isset($encoderParameters['LD']['sectionIndex']) ? $encoderParameters['LD']['sectionIndex'] : '');`

But I do not know is this is the right location? Perhaps a configuration error? I do not found any occurrences of "sectionIndex" in the realurl extension at all?

Regards,
Tim

**Comment by dmitryd** [comment]
> realurl do not respect the "sectionIndex" that is part of the LD.

It never did. Probably, a missing feature that should be implemented.
