### ISSUE TITLE
be usergroups access lists

### ISSUE THREAD

**Issue by hartundweich** [dmitryd/typo3-realurl#144]
RealUrl is producing empty entires in the "Tables (listing)" and "Tables (modifiy)" section of access control in BE usergroups - see attached screenshot. I think these entries are for the three tables which are created by realurl. But I don't think that these tables are necessary in the access control in BE usergroups?
If they are necessary it would be nice to see an icon and a text in the access control list.

![realurlacl](https://cloud.githubusercontent.com/assets/18597291/14712354/0aeb7c7a-07dd-11e6-8572-4fce9fe30ea7.png)

**Comment by clausharup** [comment]
I just stumbled upon the same issue :-)
![screen](https://cloud.githubusercontent.com/assets/3328955/14716684/5d323684-07ee-11e6-9dd2-7a9a5d2daf3b.gif)
