### ISSUE TITLE
update wizard fails to alter table

### ISSUE THREAD

**Issue by ikkez** [dmitryd/typo3-realurl#147]
`ALTER TABLE tx_realurl_pathcache ADD uid int(11) NOT NULL auto_increment;`
This does not work as the table from 1.x already contains an auto_incremented pkey. I'm not sure if it works to tell the wizard to drop the other key, before performing the alter statement.

**Comment by dmitryd** [comment]
Read the docs before posting.

https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x
