### ISSUE TITLE
unable to use access-controled pages in frontend while logged in to backend

### ISSUE THREAD

**Issue by ikkez** [dmitryd/typo3-realurl#148]
while i am logged in to the typo3 backend, I am not able to access realurl pages that lead to protected page for fe_user groups.. just get 404. When I log out for the typo3 backend, the realurl links suddenly work again.

**Comment by dmitryd** [comment]
What realurl version do you use?

**Comment by ikkez** [comment]
It was the latest. Realurl 2.0.14 with TYPO3 7.6.6

**Comment by tpinne** [comment]
I have a similar behavior for some pages which are not access restricted. If I'm logged into the backend some of my main navigation links (2 of 5) show the content of the homepage. If I'm logged out everything works as expected. These 2 pages do not have any configuration or page type or anything else different as the other pages.
Clearing every cache (even on DB level) does not change the behavior.

Realurl 2.0.14 and TYPO3 7.6.4

**Comment by dmitryd** [comment]
Realurl now acts the same regardless of BE user login. So the issue should not be actual anymore.
