### ISSUE TITLE
Realurl section in 'Edit Page' disappeared after Typo3 update (TYPO3 7.6.6 only!)

### ISSUE THREAD

**Issue by thomasmstein** [dmitryd/typo3-realurl#152]
Dmitry,
I noticed that after an update from Typo3 7.6.5 to 7.6.6 the "**Speaking URL path segment:**" and "**Exclude from speaking URL:**" sections disappeared from the bottom of the 'Edit Page' (while the RealURL administration module remains accessible)
I am running Typo3 with bootstrap_package 7.0.2.
Is there a way to reactivate that section.
Thanks
Thomas

![edit_page_no_realurl](https://cloud.githubusercontent.com/assets/17682916/14972857/17d6df56-1124-11e6-9b3f-2cc0659f8e9a.png)

**Comment by schnappenberger** [comment]
You wil find it in Tab Categories ...

**Comment by dmitryd** [comment]
Patch version is supposed not to break things or introduce incompatible changes. Looks like it is not the case with TYPO3 7.6.6. There are too many reports about broken things there.

**Comment by thomasmstein** [comment]
Frank and Dmitry,
Many thanks for the hint and quick response. I presume that the Speaking URL section was not supposed to be ending up under the Category tab ... ;-)  ?
Cheers
Thomas

**Comment by wouter90** [comment]
This is a core bug which is fixed already and will be pary of 7.6.7
