### ISSUE TITLE
wrong path from internet explorer

### ISSUE THREAD

**Issue by cybergwei** [dmitryd/typo3-realurl#155]
realurl with ie11 and edge has seems to be not working well but with firefox, chrome and safari all is fine.

expample link is => https://show.server.com/deutschland/kontakt/standorte/geschaeftsstellen/dummy/ (also in source)

when i click on that link - microsoft browser changed itself to https://show.server.com/deutschland/kontakt/standorte/deutschland/kontakt/standorte/geschaeftsstellen/dummy_2/

here you see first url part is repeated so i got error404 page. 

but when i open the dev page with that url in firefox, chrome, etc. is't working perfecty like a charme.
i tried different working realurl configs and without ssl - ie isn't working.

disable realurl ms browser are working.

i'm using 7.6.4, standard htaccess

regards

**Comment by dmitryd** [comment]
[Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)
