### ISSUE TITLE
UrlEncoder->createAliasForValue fails to detect sys_language_uid without 'L' parameter

### ISSUE THREAD

**Issue by lukastaferner** [dmitryd/typo3-realurl#156]
Hi,

I think I found a bug: when creating an alias with createAliasForValue() the curren sysLanguageUid is detected with:
$languageUrlParameter = $configuration['languageGetVar'] ?: 'L';
$languageUid = isset($this->originalUrlParameters[$languageUrlParameter]) ? (int)$this->originalUrlParameters[$languageUrlParameter] : 0;

This will return 0 if the language is set via TS Condition / Domain Record.
The function  setLanguage() respects those settings so I would suggest to use 
$languageUid = $this->sysLanguageUid; instead.

Greetings,

Lukas

**Comment by dmitryd** [comment]
This will break language selector on pages like news detail.

**Comment by lukastaferner** [comment]
Hi, I dont get your point . .  setLanguage()  first checks $this->sysLanguageUid = (int)$this->urlParameters['L']; and then else's for $this->sysLanguageUid = (int)$this->tsfe->sys_language_uid.

Its he same functionality as in 
$languageUid = isset($this->originalUrlParameters[$languageUrlParameter]) ? (int)$this->originalUrlParameters[$languageUrlParameter] : 0; 
but adds the sys_language_uid

Thanks!

Lukas

**Comment by lukastaferner** [comment]
[UrlEncoderPatch.txt](https://github.com/dmitryd/typo3-realurl/files/252332/UrlEncoderPatch.txt)

**Comment by dmitryd** [comment]
Encoder must encode URL as it is given by TYPO3. So if there is no language variable, than there is no such variable. It cannot just take current language.

Please, read the wiki about setting up languages in TYPO3 for realurl.

**Comment by lukastaferner** [comment]
Hi Dmitry,
my setup:
domain.com
 sys_language_uid  = 0
domain.net
 sys_language_uid  = 1

This works fine, except for lookup table (returns results for sys_language_uid = 0 on domain .net which should return sys_language_uid  = 1).

Current solutions:
 *) Add L Parameter (i do not want to make the url longer)
 *) Add viewsfor each domain / sys_language_uid -> not very handy
 *) Spoof the 'L'-getVar with if(domain=.com)

Or am I wrong and miss someting?

Greetings,

Lukas

P.s. Which section of the wiki do you refer to?

**Comment by dmitryd** [comment]
Imagine that you are on the news page. You have several languages there. TYPO3 tells realurl to encode the following URLs:

* EN: /index.php?tx_yourext[uid]=123&L=0
* DE: /index.php?tx_yourext[uid]=123&L=1
* FR: /index.php?tx_yourext[uid]=123&L=2

How this will work with your patch?

**Comment by dmitryd** [comment]
Wiki: [Configuring languages](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-languages)

**Comment by dmitryd** [comment]
It looks to me like you are simply missing `config.linkVars = L` in your TypoScript.

**Comment by lukastaferner** [comment]
// Default for domain.com
config {
	sys_language_uid = 0
}
[globalString = IENV:HTTP_HOST=domain.net] 
	config {
		sys_language_uid = 1
	}
[global]

I just do not have L as language var, my server decides according to the host header.

**Comment by dmitryd** [comment]
Sorry, your config cannot work with realurl. You have to change it or stop using realurl or do some other trick. Realurl relies on having `L` for language handling.

**Comment by lukastaferner** [comment]
So when I encode 
domain.com?tx_yourext[uid]=123 encodes to domain.com/{value for sys_lang_uid=0}

Unfortunately 
domain.net?tx_yourext[uid]=123 *also* encodes to domain.net/{value for sys_lang_uid=0}

**Comment by lukastaferner** [comment]
I have this config up and running for ~ 5 years :)

I added views  (select * from myext where sys_language.uid = 1) and added them to the realurl config for the domain, but it is very unhandy. I hoped there wouls be a solution in the new version!

Probably my path is bad. Bu the idea is to 

*) get the L vars first
*) if there is none, get the sys_language_uid
*) then match against languageExceptionUids

What do you think about this?

Thank you!

Lukas

**Comment by dmitryd** [comment]
I cannot help you with this because it is not a realurl bug. This place is only for bugs. If you need help, please, see [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
