### ISSUE TITLE
Exclude path doesn't work on 2.0.14

### ISSUE THREAD

**Issue by ses** [dmitryd/typo3-realurl#158]
Hi,

i use TYPO3 7.6.6 and RealUrl 2.0.14
i check the point in the page: tx_realurl_exclude
but its dont work :(

you have the problems?
thanks, Sebastian

**Comment by ses** [comment]
here a stackoverflow link:
http://stackoverflow.com/questions/37220922/typo3-7-6-tx-news-4-2-1-no-detail-name-in-realurl

**Comment by ses** [comment]
i need this in the realurlconf.php ?

`$TYPO3_CONF_VARS['FE']['addRootLineFields'] .= ',tx_realurl_pathsegment,tx_realurl_exclude,tx_realurl_pathoverride';`

**Comment by ses** [comment]
its the last page:
-root
-- overview <- news list
--- detail <- news detail = tx_realurl_exclude // i dont need this page in the url

**Comment by dmitryd** [comment]
This place is for bugs, not for questions. See [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).

**Comment by dmitryd** [comment]
Specially for you added a FAQ item: [Excluding pages does not work](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#excluding-pages-does-not-work#excluding-pages-does-not-work)
