### ISSUE TITLE
AbsRefPrefix is not cached

### ISSUE THREAD

**Issue by Razrael** [dmitryd/typo3-realurl#16]
I have issues with "absRefPrefix = /". It only occurs when I'm not logged into the Backend. The encoder would not start otherwise.

Basically the AbsRefPrefix is not saved to the cache nor is it reapplied in the decoder.
If I change the order [in the code](https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Encoder/UrlEncoder.php#L677-L678) it runs mostly correct. But there are still some duplicated wrong URL's in the cache.

I do not know if the prefix should be saved from the encoder or be reapplied in the decoder.

**Comment by dmitryd** [comment]
absRefPrefix should not be cached but it should be re-applied when the item is fetched from cache.

Looks like the call to ```reapplyAbsRefPrefix()``` should be moved to stay after the condition.
