### ISSUE TITLE
Realurl Nginx and Pages / Folder with same titles BE MODE

### ISSUE THREAD

**Issue by Davka** [dmitryd/typo3-realurl#163]
Hi, how have a problem with the latest version with Typo3 6.2.2 and Nginx.
After migrating to Nginx and updating the extension RealURL some pages no longer work or end in Redirect Loop (usually once inside the BE is logged in).

The errors are certainly due to our strange constellation of sites but did not occur under Apache2:

For example:

-> Folder A (excluded from speaking URL)
     -> Page A (Forwards to Home)
        -> Page Home

If you call the page now on, the URL is: example.org//A/Home

I would like to describe my NGINX on HTTPS and WWW, but the order does not work because too many redirects are performed.

**Comment by dmitryd** [comment]
Not a bug. Given your page structure, RealURL behaves correctly because it works from the home page, which seems to be `Folder A` in your case. Such behavior is expected.

For further help see [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
