### ISSUE TITLE
Feature request: permalink behaviour

### ISSUE THREAD

**Issue by mhirdes** [dmitryd/typo3-realurl#164]
First of all, thanks a lot four your work.

We have the problem, that when an editor changes the title of the page, that the URL to the page also changes and the old page throws an 404. Therefore we have two feature requests:

With our cs_seo extension we hook the page settings and add an JavaScript which fills the segment path if it's empty. Maybe in realURL the default value of the path segment could be the page title? So if an editor creates a new page also the path segment is set? Then if the editor changes the title, the old URL still exists.

On the other hand it would be amazing, that if the path of a page changes, automatically a 301 redirect will be created. You left out the redirects in new versions of RealURL. But you said, that maybe you write a new extension for it? So maybe you can integrate this feature, too? 

Thank you very much in advance for your answer.

**Comment by dmitryd** [comment]
RealURL does not delete cache entries when pages are renamed. Therefore there should be non 404. Of course, if there is no cache entry, than there is nothing to remember.

For the 301, it is partially implemented but not complete. I need to finish that functionality.

**Comment by mhirdes** [comment]
Thanks for your quick response.

The 301 feature would help us a lot. 

Do you see aalso a way that the path segment field is filled in by default?

Thanks a lot again.

**Comment by dmitryd** [comment]
> Do you see aalso a way that the path segment field is filled in by default?

No. There is no need for that. RealURL cache keeps **all** expired (=renamed) URLs for a certain amount of time (30 days if I remember correctly), which is enough for search engines to update links.

**Comment by mhirdes** [comment]
That's true. If the 301 feature is online there is no need for that. I'm looking forward about this feature.

**Comment by dmitryd** [comment]
Target version: 2.0.1

**Comment by dmitryd** [comment]
Note that due to certain limitations redirection is only possible if there was an encoding for the expired page. If you have something like a breadcramb on the page, it is enough.
