### ISSUE TITLE
Realurl 2.x.x regression with tx_news and paginate widget. Pagination does not work anymore.

### ISSUE THREAD

**Issue by Treedent** [dmitryd/typo3-realurl#165]
TYPO3 7.6.6
Realurl 2.0.14
Tx_news 4.2.1

realurl configuration for widget : 
 'postVarSets' => array(
        '_DEFAULT' => array(  
                'page' => array(
                                array(
                                    'GETvar' => 'tx_news_pi1[@widget_0][currentPage]',
                                ),
                ),
           ),
.....

The pagination link is well produced (www.domain.com/news/page/2/), but it give me a 303  'See Other' Apache error, then a 404 'Not found' apache error.
Is there an additionnal realurl configuration to make the tx_news paginate widget working properly with realurl 2.x.x.

**Comment by dmitryd** [comment]
This place is only for bugs. If you need support, see (here](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
