### ISSUE TITLE
Misleading docs about userFunc?

### ISSUE THREAD

**Issue by liayn** [dmitryd/typo3-realurl#166]
https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#userfunc
says
> pathParts – a reference to the array with segments. The function must remove processed segments for decoding and append them for encoding.

This seems correct for the decoder, but not for the encoder, since it takes care of appending the part on its own.

```
$userFuncParameters = array(
				'pObj' => &$this,
				'value' => $getVarValue,
				'decodeAlias' => false,
				'pathParts' => &$segments,
				'setup' => $configuration,
			);
			$getVarValue = GeneralUtility::callUserFunction($configuration['userFunc'], $userFuncParameters, $this);
			$segments[] = rawurlencode($getVarValue);
```

Or do I understand this in a wrong way?

**Comment by dmitryd** [comment]
Documentation is updated.
