### ISSUE TITLE
No possiblity to retrieve getValue in encodeTitle_userProc

### ISSUE THREAD

**Issue by liayn** [dmitryd/typo3-realurl#168]
Formerly the member `orig_paramKeyValues` was publicly available and could be used in the `encodeTitle_userProc` hook to retrieve the original value of a GET parameter.
All members of the UrlEncoder are now protected, which is good, but now there is no way to retrieve the GET parameter, where the `$processedTitle` originated from.

I propose to hand over this information, as well as the language information, to the `cleanUpAlias` method as well as the hook.

I'll push a PR.

**Comment by dmitryd** [comment]
See #150.

**Comment by liayn** [comment]
Yes and no... the language information is still not there.

**Comment by liayn** [comment]
But I don't insist on this for the time being. I can live with #150 of course. Thanks.

**Comment by liayn** [comment]
When will you release a new version which includes #150?

**Comment by dmitryd** [comment]
Another accessor can be added. Just write what you need.

**Comment by dmitryd** [comment]
No plans yet but you can use dev version for now.

**Comment by liayn** [comment]
Language is post-processed in `\DmitryDulepov\Realurl\Encoder\UrlEncoder::createAliasForValue` so, an accessor is not sufficient in that case.

But in terms of accessor, it would be nice to have `\DmitryDulepov\Realurl\Utility::convertToSafeString` available in this hook. Unfortunately it is not static, even though it has no dependencies on members. Moreover the `strtolower` should be controllable via parameter.
May I push a PR for that?

**Comment by dmitryd** [comment]
There is a `$this->getUtility()` method now. Or you can instantiate `Utility` class.

> Moreover the `strtolower` should be controllable via parameter.

You can but for the external use of the function only. Default behavior should stay as it is. RealURL should lowercase URLs as it always did.

**Comment by liayn** [comment]
sure!
