### ISSUE TITLE
[PHP Warning] Invalid argument (foreach()) ConfigurationReader.php

### ISSUE THREAD

**Issue by mickedplay** [dmitryd/typo3-realurl#170]
![php](https://cloud.githubusercontent.com/assets/17031230/15450578/337e19a2-1f9f-11e6-9c57-1dff845d55f5.png)
Throws ~15 warnings on nearly every login and sometimes while working in the backend

**Comment by mickedplay** [comment]
I hope It'll get fixed soon, because it throws ~120 new errors per day.

**Comment by dmitryd** [comment]
Are you sure it is an error in RealURL and not in your config? Truly speaking I cannot fix anything here because you did not provide error message.

**Comment by mickedplay** [comment]
I'm not really sure, but since I added a little fix, there's no error anymore (line 14): http://pastebin.com/H1VcHQE7
But thanks anyway.
