### ISSUE TITLE
Multilanguage default language sys_language_uid=1 problem

### ISSUE THREAD

**Issue by RosenbauerSolbach** [dmitryd/typo3-realurl#171]
Hello,

following setting making some problems to translate urls correctly:

sys_language_uid = 0 is for englisch
sys_language_uid = 1 is for german

Default language is german if no language parameter is in url. 
So, the wanted result should look like:

www.example.de/kontakt (german contact page)
www.example.de/en/contact (englisch contact page)

RealUrl 2.0.14 produces following result:

www.example.de/contact (german contact page)
www.example.de/en/contact (englisch contact page)

**Comment by RosenbauerSolbach** [comment]
Hi, 

I did some debugging and found out, that in UrlDecoder.php no data from $this->tsfe is set. For example: the value of sys_language_uid is always 0. It´s also strange that the uid for current page is NULL.

In UrlDecoder.php I tried some debugging output.
                
```
protected function setLanguageFromQueryString() {
        \TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($this);
        \TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($this->tsfe);
        
        ...
}
```

If no L-Parameter is in URL I tried to set $this->detectedLanguageId to "1" by following:
```
protected function setLanguageFromQueryString() {
        $this->detectedLanguageId = (int)GeneralUtility::_GP('L');      
        if ( !GeneralUtility::_GP('L') ) {
                $this->detectedLanguageId = $GLOBALS['TSFE']->sys_language_uid;
        } 
}
```
But as I mentioned above $GLOBALS['TSFE']->sys_language_uid stays "0". 

My solution is to set a new variable in realUrl_conf.php
```
$TYPO3_CONF_VARS['EXTCONF']['realurl']['_DEFAULT'] = array(
        ...

        'defaultLanguageUid' => 1

        ...
);       
```
And I changed UrlDecoder.php to:
```
protected function setLanguageFromQueryString() {
        $this->detectedLanguageId = (int)GeneralUtility::_GP('L');      
        if ( !GeneralUtility::_GP('L') && $this->configuration->get('defaultLanguageUid') ) {
                $this->detectedLanguageId = $this->configuration->get('defaultLanguageUid');

        } 
} 
```
I don´t know if this is a good and clean solution. Maybe there is another workaround. But it would be nice if such a realUrl behaviour is implemented in a future release of realUrl

**Comment by dmitryd** [comment]
> I did some debugging and found out, that in UrlDecoder.php no data from $this->tsfe is set. For example: the value of sys_language_uid is always 0.

Of course. The value comes from TypoScript. TypoScript depends on page id. When RealURL is executed, its job is to find page id. Therefore there is no id, no TypoScript and no `sys_language_uid`.

Default language id in TYPO3 is always `0`.

**Comment by RosenbauerSolbach** [comment]
Okay, this supports my suggestion, that everything in UrlDecoder.php happens before TYPO3 begins to deliver anything. 

But what about my changes to get the correct RealURL result? Is it correct or do you have another idea?

**Comment by dmitryd** [comment]
```php
protected function setLanguageFromQueryString() {
        $this->detectedLanguageId = (int)GeneralUtility::_GP('L');      
        if ( !GeneralUtility::_GP('L') && $this->configuration->get('defaultLanguageUid') ) {
                $this->detectedLanguageId = $this->configuration->get('defaultLanguageUid');

        } 
}
```
This code will not work if the URL looks like '/for/bar/?L-0`.

**Comment by tzcccc** [comment]
protected function setLanguageFromQueryString() {
	$this->detectedLanguageId = (int)GeneralUtility::_GP('L');
        $defaultLanguageUid = $this->configuration->get('init/defaultLanguageUid');
        if ( GeneralUtility::_GP('L') === NULL && is_numeric($defaultLanguageUid) ) {
            $this->detectedLanguageId = $defaultLanguageUid;
        }
}

**Comment by dmitryd** [comment]
Should work in 2.1.0. But I prefer to keep the option undocumented because this should not be abused. It is better to stick to TYPO3 conventions and have zero as the default language.

**Comment by manikandankasi** [comment]
Oops, an error occurred!
An exception occurred while executing 'SELECT * FROM `tt_content` WHERE (`sys_language_uid` IN (0, -1) AND colPos IN () ) AND (`tt_content`.`pid` = ?) AND ((`tt_content`.`deleted` = 0) AND ((`tt_content`.`t3ver_wsid` = 0) OR (`tt_content`.`t3ver_state` <= 0))) ORDER BY `sorting` ASC LIMIT 100' with params [1]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) AND (`tt_content`.`pid` = ?) AND ((`tt_content`.`deleted` = 0) AND ((`tt_con' at line 1


I got this error while creating a grid Flux content element

**Comment by dmitryd** [comment]
@manikandankasi I am happy for you.
