### ISSUE TITLE
Config option "languageExceptionUids" broken

### ISSUE THREAD

**Issue by robert-heinig** [dmitryd/typo3-realurl#172]
It seems to have no effect at all.
Was this feature removed?

**Comment by dmitryd** [comment]
[About asking questions in the bug tracker](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)
[Configuration Reference](https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference)

**Comment by robert-heinig** [comment]
I searched the configuration reference, but did not see that´s it´s only avaiable for "lookUpTable".
But it was avaibale for 1.x and there is no note that it was removed for "pagePath"?

**Comment by dmitryd** [comment]
True, no note.
