### ISSUE TITLE
RealURL-Config with tx_news issue

### ISSUE THREAD

**Issue by bluesunlite** [dmitryd/typo3-realurl#173]
Hi everybody,

I have a little problem configuring RealURL for tx_news. With all the RealURL-versions 1.xx it was working like a charme with the following code inside realurl_conf.php. But this won't work with RealURL-versions 2.xx. Does anybody know why? How can I fix this?

Thanks a lot:

`<?php
   $TYPO3_CONF_VARS['FE']['addRootLineFields'].= ',title,alias';
   $TYPO3_CONF_VARS['EXTCONF']['realurl'] = 
   array( 
      '_DEFAULT' => array(
         'init' => array(
            'enableCHashCache' => 1,
            'appendMissingSlash' => 'ifNotFile',
            'enableUrlDecodeCache' => 1,
            'enableUrlEncodeCache' => 1,
			'appendMissingSlash' => 'ifNotFile,redirect',
			'postVarSet_failureMode' => 'redirect_goodUpperDir',
			'enableAllUnicodeLetters' => 0,
			'doNotRawUrlEncodeParameterNames' => 1,
        ),
        'redirects' => array(),
        'preVars' => array(
           
            array(
                'GETvar' => 'L',
                'valueMap' => array(
                    'en' => '1',
                    'de' => '2',
                ),
                'noMatch' => 'bypass',
				'defaultValue' => 'de',
            ),
        ),
        'pagePath' => array(
            'type' => 'user',
            'userFunc' => 'EXT:realurl/class.tx_realurl_advanced.php:&tx_realurl_advanced->main',
            'spaceCharacter' => '-',
            'languageGetVar' => 'L',
            'expireDays' => 3,
			'firstHitPathCache'=>1,
			'disablePathCache' => FALSE,
			'autoUpdatePathCache' => TRUE,
			'firstHitPathCache' => TRUE,
            'rootpage_id' => 1
        ),
        'fileName' => array (
            'defaultToHTMLsuffixOnPrev'=> 1
        ),
        'fixedPostVars' => array(
		// news detail configuration
					'newsDetailConfiguration' => array(
                        array(
                                'GETvar' => 'tx_news_pi1[action]',
                                'valueMap' => array(
                                        'detail' => '',
                                ),
                                'noMatch' => 'bypass'
                        ),
                        array(
                                'GETvar' => 'tx_news_pi1[controller]',
                                'valueMap' => array(
                                        'News' => '',
                                ),
                                'noMatch' => 'bypass'
                        ),
                        array(
                                'GETvar' => 'tx_news_pi1[news]',
                                'lookUpTable' => array(
                                        'table' => 'tx_news_domain_model_news',
                                        'id_field' => 'uid',
                                        'alias_field' => 'title',
                                        'addWhereClause' => ' AND NOT deleted',
                                        'useUniqueCache' => 1,
                                        'useUniqueCache_conf' => array(
                                                'strtolower' => 1,
                                                'spaceCharacter' => '-'
                                        ),
                                        'languageGetVar' => 'L',
                                        'languageExceptionUids' => '',
                                        'languageField' => 'sys_language_uid',
                                        'transOrigPointerField' => 'l10n_parent',
                                        'autoUpdate' => 1,
                                        'expireDays' => 180,
                                )
                        )
                ),
				
				'newsTagConfiguration' => array(
                        array(
                                'GETvar' => 'tx_news_pi1[overwriteDemand][tags]',
                                'lookUpTable' => array(
                                        'table' => 'tx_news_domain_model_tag',
                                        'id_field' => 'uid',
                                        'alias_field' => 'title',
                                        'addWhereClause' => ' AND NOT deleted',
                                        'useUniqueCache' => 1,
                                        'useUniqueCache_conf' => array(
                                                'strtolower' => 1,
                                                'spaceCharacter' => '-'
                                        )
                                )
                        )
                ),
		'27' => 'newsDetailConfiguration',
		'55' => 'newsDetailConfiguration', // For additional detail pages, add their uid as well
		),

        'postVarSets' => array(
            '_DEFAULT' => array(
                // news archive parameters
                'archive' => array(
                    array(
                        'GETvar' => 'tx_news_pi1[year]' ,
                        ),
                    array(
                        'GETvar' => 'tx_news_pi1[month]' ,
                        'valueMap' => array(
                            'january' => '01',
                            'february' => '02',
                            'march' => '03',
                            'april' => '04',
                            'may' => '05',
                            'june' => '06',
                            'july' => '07',
                            'august' => '08',
                            'september' => '09',
                            'october' => '10',
                            'november' => '11',
                            'december' => '12',
                            )
                        ),
                    ),
                // news pagebrowser
                'browse' => array(
                    array(
                        'GETvar' => 'tx_news_pi1[pointer]',
                        ),
                    ),
                // news categories
                'select_category' => array (
                    array(
                        'GETvar' => 'tx_news_pi1[cat]',
                        ),
                    ),
					
                // news articles and searchwords
                'article' => array(
                    array(
                        'GETvar' => 'tx_news_pi1[tt_news]',
                        'lookUpTable' => array(
                            'table' => 'tx_news_domain_model_news',
                            'id_field' => 'uid',
                            'alias_field' => 'title',
                            'addWhereClause' => ' AND NOT deleted',
                            'useUniqueCache' => 1,
                            'useUniqueCache_conf' => array(
                                'strtolower' => 1,
                                'spaceCharacter' => '-',
                                ),
                            ),
                        ),
                    array(
                        'GETvar' => 'tx_news_pi1[backPid]',
                    ),
                    array(
                        'GETvar' => 'tx_news_pi1[swords]',
                        ),
                    ),
                ),
            ),
    ),
);
?>`

**Comment by dmitryd** [comment]
Read [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
