### ISSUE TITLE
Inconsistent behavior with port in URL: www.example.com:8081

### ISSUE THREAD

**Issue by fabtho** [dmitryd/typo3-realurl#174]
TYPO3: 7.6.9
realurl: 2.0.14

I have a multi domain installation running on port 8081 with two domains configured via domain entry in different root-page: www.example.com/www.test.com. I also have 4 language defined. (5 with default)

I use the port 8081 for the development only, so its not permanent.

So www.example.com:8081 / www.test.com:8081 are visible in the Browser-Address. TYPO3 is not knowing anything about this port. Port configuration is done with apache.

I generate  realurl_autoconfig.php, having www.example.com and www.test.com in the configuration and the 4 languages as preVars. (en => 1)

Result:

The language navigation is still showing www.example.com:8081/&L=1, and not, as expected www.example.com:8081/en/

Workaround:

If I edit the realurl_autoconfig.php and change the domains to www.example.com:8081 / www.test.com:8081 it works as expected: www.example.com:8081/en/

So it looks like realurl compares the request domain to the configured domains. I suggest to split the port, as TYPO3 does not know about the port because its configured in apache.

What do you think?

**Comment by dmitryd** [comment]
You have to do manual configuration. Automatic configuration is not suitable for such cases. It is made for very simple standard installations. It takes data from domain records and does not take ports into account.
