### ISSUE TITLE
Allow same pathsegment for different languages

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#175]
Currently the `tx_realurl_pathsegment` field of the `pages_language_overlay` table has the `eval`-configuration uniqueInPid. This means, it is not possible to use the same pathsegment for different languages. But it is possible to have the same segment in different (similar) languages. Then they will get a number appended. Example:
en/login/
de/login0/

I think it is ok, to drop the `eval`-field and allow the same segment for multiple page-translations (with the assumption, that a page only has translations with different `sys_language_uid`).

**Comment by dmitryd** [comment]
Use `alias` field instead.

**Comment by rvock** [comment]
Thanks, this works.

What is the difference between the `alias` field and the `tx_realurl_pathsegment`? As far as I can see, the pathsegment would only be needed, if I also set `tx_realurl_pathoverride`. Otherwise the `alias` field behaves like the pathsegment (with pathsegment having a higher priority based on `EncodeDecoderBase::$pageTitleFields`)

This would still mean, that I cannot use the same `tx_realurl_pathsegment` for different translations with `tx_realurl_pathoverride` (which would be an easy fix, if `uniqueInPid ` was removed from `eval` for `tx_realurl_pathsegment`)

**Comment by dmitryd** [comment]
Path segment works fine without override. It is just another field to specify a segment.

Unique there ensures that no other page can have the same value. Same value creates hard to resolve issues with encoding/decoding.

Just use alias. It is exactly made for that purpose: same segment in all languages.

**Comment by rvock** [comment]
I am not talking about removing `uniqueInPid` for pages. I totally agree with you that this would lead to issues. I am talking about `pages_language_overlay`. These translations of one page all have the same `pid`, but different `sys_language_uid`. So a URL to one of these translated pages will always contain the language var which ensures that the generated path will be different. And it doesn't make sense to add multiple translation with the same `sys_language_uid`, which would generate problems with the same url.

As a side note: `uniqueInPid` does not protect against the same URL for different pages if the pages have different parents, the same `tx_realurl_pathsegment` and have `tx_realurl_pathoverride` set.

## Example ##

#### pages ####

uid | pid | title | tx_realurl_pathsegment
--- | --- | --- | ---
2 | 1 | Login | login

#### pages_language_overlay ####

uid | pid | title | tx_realurl_pathsegment
--- | --- | --- | ---
3 | 2 | Anmelden | login
4 | 2 | Aanmelden | login

This currently results in the following URLs:
- en/login/
- de/login/
- nl/login0/

Only changing `pages_language_overlay` (and NOT `pages`) will lead to these URLs:
- en/login/
- de/login/
- nl/login/
