### ISSUE TITLE
Wrong links across domain

### ISSUE THREAD

**Issue by SventB** [dmitryd/typo3-realurl#176]
I'm using typolinkEnableLinksAcrossDomains=1 and with realurl disabled, the generated link is right (e.g. domain2.com/index.php?id=123&L=1, while ID 123 is a page in a different domain but same TYPO3 Backend), but with realurl enabled, the resulting link is domain2.com/en/ (the deeplink to page 123 is missing).

I'm using TYPO3 7.6.9, realurl 2.0.14.

**Comment by dmitryd** [comment]
Try development version from git.

**Comment by drlimbo** [comment]
I have the same problem as SventB on multiple projects. 
Typo3 7.6.9 and latest 6.2.x - realurl 2.0.14 & realurl development branch

With realurl 1.13.6 Cross-Domain-Links work well.

**Comment by dmitryd** [comment]
Try development version.

**Comment by dmitryd** [comment]
Tested with development version (future 2.1.0), there it works.

And you really need `config.typolinkEnableLinksAcrossDomains = 1`!

**Comment by drlimbo** [comment]
I tested again with development branch and Typo3 7.6.9
I already had "config.typolinkEnableLinksAcrossDomains = 1" enabled
BUT the problem still exists. 

_The Link on domain1.tld points to domain2.tld/ instead of domain2.tld/link/to/page/_

**Comment by SventB** [comment]
Still not working (TYPO3 7.6.11, realurl 2.1.4)

**Comment by SventB** [comment]
Ok found the error :)
You have to set rootpage_id:
`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['www.seconddomain.com']['pagePath']['rootpage_id'] = 123;`

**Comment by drlimbo** [comment]
setting $GLOBALS['TYPO3_CONF_VARS']... for every domain is pain in the.. 
for a typo3 installation with 50+ Domains this sounds like a lot of work.. i'd like to prevent!
isn't there a way to get this informations from sys_domain records like realurl v1 did?

**Comment by gautamsinh** [comment]
Hello ,
I have already set  $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['www.domain2.com']['pagePath']['rootpage_id'] = 123;  
but still its not working 
I have use typo3 version 7.6
 realurl 2.0.10

Thanks in advance
