### ISSUE TITLE
The identity property "..." is no UID

### ISSUE THREAD

**Issue by SventB** [dmitryd/typo3-realurl#177]
For url www.domain.de/restaurants/details/gasthof-hasen/ I'm getting error

> Exception while property mapping at property path "":The identity property "gasthof-hasen" is no UID.

for a detail view of a record (extension built with extbase/fluid). This error occures perhaps at 1 record from 1000, there are 15000 records in total.

But all informations realurl needs to "translate" the speaking url in the uid are present in the database:

In table tx_realurl_uniqalias I have this record:

> uid: 33981
> tstamp: 1463584259
> tablename: tx_rrrestaurants_domain_model_restaurant
> field_alias: title
> field_id: uid
> value_alias: gasthof-hasen
> value_id: 52924
> lang: 0
> expire: 0

In table tx_realurl_urldecodecache I have this record:

> url_hash: 9c5c07237000cbf862f85a1c2480829f
> spurl: restaurants/details/gasthof-hasen/
> content: [BLOB - 146 Bytes]
> page_id: 287
> rootpage_id: 1
> tstamp: 1465257119

In table tx_realurl_urlencodecache I have this record:

> url_hash: 5258ca4e247a92f840effc3f047a3a0c
> origparams: www.domain.de | id=287&L=0&tx_rrrestaurants_restaurants%5Brestaurant%5D=52924&cHash=f5e590d7e0227f22e7364e7e4294e435
> content: restaurants/details/gasthof-hasen/
> page_id: 287
> tstamp: 1464858820

If I delete the records from the realurl tables and generate the speaking url again, the url works again, but the error returns later, for a different url.

TYPO3 version is 6.2.25, realurl version is 1.13.6.

**Comment by dmitryd** [comment]
Please, seek for help in mailing lists because this is not directly related to realurl. I am unable to solve problems in your installation.

**Comment by dimitri-koenig** [comment]
@SventB: Did you find a solution for this issue? I have the same issue, with realurl 2.2.1 and TYPO3 7.6.21 and couldn't find a solution yet.

**Comment by SventB** [comment]
I had/have so many problems with realurl, I do not know exactly how I solved this.
I think I've added the UID of the record to the speaking url. Or I updated to version 2 of realurl.

**Comment by ursbraem** [comment]
I'm having this issue as well with TYPO3 8. 

It occurs when an inexistant slug for an extbase item (detail view) is called. `Exception while property mapping at property path "": The identity property "loremipsum" is no UID.`. By enabling `pageNotFoundOnCHashError` in Localconf I could hide it, now a general 404 is thrown. 

To the other posters: Any news on this? I think it makes sense that it's probably not a RealURL bug – but of course it shows up when using RealURL... I found some posts saying that extbase error handling is incomplete.. Any hints?

**Comment by dmitryd** [comment]
This happens when you clear RealURL data, for example. RealURL needs to encode aliases before it can use them for decoding.

**Comment by ursbraem** [comment]
> This happens when you clear RealURL data, for example. RealURL needs to encode aliases before it can use them for decoding.

I see (now I also understand why you warn in BE from clearing the realURL cache 😀). Has that always been the case? I was under the impression an URL provides enough RESTful information for RealURL to resolve it if it doesn't have it in the cache. Probably that's cHash interfering with it?

In my case, the problem is that the requested item has been deleted. So the URL can't be created.

The issue is that extbase doesn't help transforming the error into a 404, so each extension developer has to do it him/herself ([example](https://github.com/georgringer/news/blob/master/Classes/Controller/NewsBaseController.php#L46))

What I'm testing now is 

                        //'addWhereClause' => ' AND NOT deleted',
                        'enable404forInvalidAlias' => 1,

It seems to work...

**Comment by dmitryd** [comment]
@ursbraem 

> I was under the impression an URL provides enough RESTful information for RealURL to resolve it if it doesn't have it in the cache.

Wrong impression :)

> Probably that's cHash interfering with it?

cHash will not be generated at all during decoding.

**Comment by ursbraem** [comment]
> Wrong impression

What is missing then?

**Comment by dmitryd** [comment]
Given the URL `/path/to/my/page/detail/my-item-alias/` RealURL cannot decode `my-item-alias` if it is an alias of the record. Therefore you get 0 as record uid. This is why you should never clear realurl data.
