### ISSUE TITLE
Copy page populates "Speaking URL path segment" with "0" and thus breaks realurl path

### ISSUE THREAD

**Issue by bennorz** [dmitryd/typo3-realurl#180]
I recently updated Realurl from 1.12.8 to 2.0.14 on a 6.2.3 t3

Upon copy&pasting an exisiting page the "Speaking URL path segment" of the new page is set to "0" and the path segment is obmitted.

Is this regular behavior? What can I do against it?

**Comment by dmitryd** [comment]
Duplicate of #175.

**Comment by bennorz** [comment]
I don't quite see how this is a duplicate. We have only a single language in our System. The "Speaking URL path segment" field in the page that is being copied is empty.
