### ISSUE TITLE
DB Error: DB Check >> Record Statistics

### ISSUE THREAD

**Issue by WolfOnTour** [dmitryd/typo3-realurl#181]
Typo3: 6.2.25
realurl: 2.0.14 

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM tx_realurl_urlcache WHERE pid NOT IN ....

SELECT uid,pid, FROM tx_realurl_urlcache WHERE pid NOT IN (...)
SELECT uid,pid, FROM tx_realurl_uniqalias WHERE pid NOT IN (...)
SELECT uid,pid, FROM tx_realurl_pathcache WHERE pid NOT IN (...)
SELECT uid,pid >> **,** <<  FROM tx_realurl_.....

**Comment by dmitryd** [comment]
Sorry but this is useless because you did not provide any information when this error happens. RealURL definitely does not have such code.

Closing.

**Comment by WolfOnTour** [comment]
Look at the screenshot:
https://img1.picload.org/image/rgwrwrdo/zwischenablage01.jpg

How else can I help you?

**Comment by dmitryd** [comment]
This is already fixed in the development version. See #131.
