### ISSUE TITLE
Real Url Config File gets deleted

### ISSUE THREAD

**Issue by ses2013** [dmitryd/typo3-realurl#184]
When copy & paste a Page Tree the file "realurl_autoconf.php" gets deleted in typo3conf folder if 
"basic.enableAutoConf" is = 0
Haven't tried = 1.

**Comment by dmitryd** [comment]
Please, do some appreciation and spell extension name correctly. It is not "Real Url", it is "RealURL" or "realurl".

`realurl_autoconf.php` can be deleted and regenerated at any moment by the extension. This is not a bug.
