### ISSUE TITLE
RealURL 2.x delivers pagetitles in default language instead of localized patch segments for L<>0 when not logged in in BE

### ISSUE THREAD

**Issue by bernhardberger** [dmitryd/typo3-realurl#186]
I just stumbled across an issue with realurl 2.x (latest stable or dev, doesn't matter) delivering wrong page titles on localized records when not logged in in the backend.

I use EXT:google_services to create XML sitemaps of our websites.

Internally it uses:
` $url = $obj->getUriBuilder()
                ->setTargetPageUid($uid)
                ->build();`

to build the frontend urls for the pages.

Expected output for /fr/sitemap.xml would be forexample:

If I take the page "search" for example which is localized in french with the title "rechercher" I would expect the following output:
`http://domain.tld/fr/rechercher/`
but it delivers
`http://domain.tld/fr/search/`

instead. As you see it recognizes the L parameter and mapps it to "fr" but it doesn't get me the localized segment anymore...

Only when not logged in in backend. Disabling cache and clearing the install tool cache don't change anything.

My TypoScript setup regarding language:
`
config {
    sys_language_uid = 0
    language = en
    locale_all = en_GB
    htmlTag_langKey = en
    sys_language_overlay = hideNonTranslated
    sys_language_mode = strict
    linkVars = L
}

[globalVar = GP:L = 1]
    config.sys_language_uid = 1
    config.language = fr
    config.locale_all = fr_FR
    config.htmlTag_langKey = fr
[global]
`

**Comment by dmitryd** [comment]
Please, do not post local problems here. This place is for real bugs. See wiki about getting help in mailing lists.

**Comment by bernhardberger** [comment]
This isn't a local problem. This is reproducable across various 7.6 + realurl 2.x installations.

I just tried to support you with our local configurations so it may be easier to debug...

**Comment by dmitryd** [comment]
[Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)

**Comment by bernhardberger** [comment]
what a joke.. sorry for reporting a bug!

**Comment by dmitryd** [comment]
This conversation is closed because the reporter uses the language and words that I cannot accept.

The issue is valid and will be fixed.
