### ISSUE TITLE
Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php line 1248 

### ISSUE THREAD

**Issue by abma** [dmitryd/typo3-realurl#187]
I'm getting this warning message in the typo3 log from time to time.

we use realurl 2.0.14 + typo 7.6.9.

**Comment by dmitryd** [comment]
Please, update your database in the install tool. It seems you are missing some columns.

**Comment by abma** [comment]
typo3 says its up to date and i compared ext_tables.sql with the existing rows in db that no column is missing.

an idea whats wrong then?

**Comment by abma** [comment]
SELECT * FROM `pages` WHERE `tx_realurl_pathoverride` = '1'
returns no results

**Comment by dmitryd** [comment]
In TYPO3 it will return empty array, so there will be no such warning. The warning will appear only if the query fails. Usually it fails due to wrong database structure.

I do not know what goes wrong here :(

**Comment by abma** [comment]
i'm not very familiar with typo3. is there an easy way to show the resulting sql-query?

**Comment by abma** [comment]
just a wild guess:
'tx_realurl_pathoverride=1 AND ' . 'tx_realurl_pathsegment=' . $this->databaseConnection->fullQuoteStr($path, 'pages') . $this->pageRepository->enableFields('pages', 1, array('fe_group' => true))

is this correct?

fullQuoteStr(...)  and 
$this->pageRepository->enableFields(...)

is appended to one string.

is the bracked of fullQuoteStr closed to early?

**Comment by dmitryd** [comment]
Yes, this is correct.

**Comment by abma** [comment]
i think i got it:

fullQuoteStr() seems to fail when url contains some special char like german umlauts: äöü

to reproduce the error if have to open an url which doesn't need to exist but contains an umlaut:

example.org/äöü/

**Comment by abma** [comment]
i guess this could be fixed when $path is converted to the correct encoding or converting the db to utf8.

Is/will utf8 be mandatory at some point for the typo3 db?

**Comment by dmitryd** [comment]
My database is always in UTF-8. Change yours :)

Closing because not a realurl issue.

**Comment by abma** [comment]
thanks, i've converted the db to utf-8 and the error is gone.
