### ISSUE TITLE
PHP 7 compat: Fix foreach by reference

### ISSUE THREAD

**Issue by Chrissitopher** [dmitryd/typo3-realurl#189]
At three places in realurl a `foreach` is used with a reference, which throws a deprecation error in PHP 7. These places, with line numbers from realurl 2.0.14, are:

#### Classes\Decoder\UrlDecoder.php
* foreachByReference
 * Line 785: `					foreach ($children as &$child) {`

#### Classes\EncodeDecoderBase.php
* foreachByReference
 * Line 219: `		foreach ($pathParts as &$part) {`

#### Classes\Encoder\UrlEncoder.php
* foreachByReference
 * Line 717: `			foreach ($segments as &$segment) {`

**Comment by dmitryd** [comment]
Thank you. I will fix it in 2.1.0.
