### ISSUE TITLE
 No icons visible in Info Module > RealURL Management

### ISSUE THREAD

**Issue by echavaillaz** [dmitryd/typo3-realurl#19]
Hi,

In TYPO3 7 LTS the backend module is not more usable because there is no more icons to manage the path cache for example. The problem is that the icons are loaded from the folder "gfx" who has been deleted in TYPO3 7.

![2015-12-15_1630](https://cloud.githubusercontent.com/assets/11553717/11814844/40e1ee34-a349-11e5-898c-445df7b99b6a.png)

Thanks a lot!

**Comment by dmitryd** [comment]
There are no plans to update version 1.x soon (unless somebody makes a fix and a pull request). I am trying to finish version 2 as soon as possible. It will have BE modules as well.

**Comment by echavaillaz** [comment]
Done : https://github.com/dmitryd/typo3-realurl/pull/20
