### ISSUE TITLE
Fluid form validation leads to HMAC validation error when using realurl on TYPO3 6.2.x

### ISSUE THREAD

**Issue by jacobsenj** [dmitryd/typo3-realurl#190]
I've got a fluid form, which does add some 
<details><summary>hidden validation parameters.</summary>
```html
<div>
...
<input type="hidden" name="tx_extension_pi2[__trustedProperties]" value="a:4:{s:6:&quot;filter&quot;;a:4:{s:9:&quot;continent&quot;;i:1;s:7:&quot;country&quot;;i:1;s:7:&quot;vehicle&quot;;i:1;s:5:&quot;brand&quot;;i:1;}s:6:&quot;action&quot;;i:1;s:6:&quot;sortBy&quot;;i:1;s:9:&quot;sortOrder&quot;;i:1;}2eb7360e14bed59fc5db85eddceb1bfc9d5e7651">
</div>
```
</details>
A part of the hidden validation parameters is an array holding keys like __trustedProperties which is a serialized array of the allowed form fields.

When disabling realurl my form will show this string value in typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php:64:
```
a:4:{s:6:"filter";a:4:{s:9:"continent";i:1;s:7:"country";i:1;s:7:"vehicle";i:1;s:5:"brand";i:1;}s:6:"action";i:1;s:6:"sortBy";i:1;s:9:"sortOrder";i:1;}
```

if I enable realurl the following contents are shown there:
```
a:4:{s:6:\"filter\";a:4:{s:9:\"continent\";i:1;s:7:\"country\";i:1;s:7:\"vehicle\";i:1;s:5:\"brand\";i:1;}s:6:\"action\";i:1;s:6:\"sortBy\";i:1;s:9:\"sortOrder\";i:1;}
```

which then leads to the error message 
`#1320830018: The given string was not appended with a valid HMAC`

I tracked everything down to the use of `$_GET` in ext:realurl. It seems to be the source of the problem because I also found this code in
<details>
<summary>typo3/sysext/core/Classes/Utility/GeneralUtility.php _GET() method</summary>
```php
		// Removes slashes since TYPO3 has added them regardless of magic_quotes setting.
		if (isset($value)) {
			if (is_array($value)) {
				self::stripSlashesOnArray($value);
			} else {
				$value = stripslashes($value);
			}
		}
		return $value;
```
</details>

and then modified the usage of `$_GET` in
<details>
<summary>typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php:1140</summary>
```
	protected function mergeWithExistingGetVars(array &$requestVariables) {
	    $getParams = GeneralUtility::_GET();
		if (count($getParams) > 0) {
			$flatGetArray = $this->parseQueryStringParameters($this->createQueryStringFromParameters($getParams));
			ArrayUtility::mergeRecursiveWithOverrule($requestVariables, $flatGetArray);
		}
	}
```
</details>

which stopped the HMAC error from appearing again. I would suggest to replace all $_GET usages with the TYPO3 GeneralUtility method. If you agree I would create a pull request for this.

**Comment by dmitryd** [comment]
Most likely this has something to do with PHP settings because we have projects that do not have this error. Please, check that. If you use PHP<5.4.0, you should have `magic_quotes_` set to off.

Replacing *all* usages of `$_GET` is not possible because realurl has to set some values there.

**Comment by jacobsenj** [comment]
I'm using 5.5.37 locally and 5.5.28 on preview/live where this is occuring, too. And the one change I did in  mergeWithExistingGetVars() was fixing the problem so my replace all $_GET usages would just be that one.

I wonder what else could be the issue since it seems to be working for you.

**Comment by dmitryd** [comment]
Before something is changed, I have to understand why the problem happens. No blind change just because "I did something and now it works". Let's look at the code in `GeneralUtility`:

```php
    public static function _GET($var = null)
    {
        $value = $var === null ? $_GET : (empty($var) ? null : $_GET[$var]);
        // This is there for backwards-compatibility, in order to avoid NULL
        if (isset($value) && !is_array($value)) {
            $value = (string)$value;
        }
        return $value;
    }
```

Effectively this can be changed to the following in case with `mergeWithExistingGetVars()`:

```php
    public static function _GET($var = null)
    {
        $value = $_GET;
        return $value;
    }
```

So the value of $_GET is returned without any changes. Now to realurl:
```php
	protected function mergeWithExistingGetVars(array &$requestVariables) {
		if (count($_GET) > 0) {
			$flatGetArray = $this->parseQueryStringParameters($this->createQueryStringFromParameters($_GET));
			ArrayUtility::mergeRecursiveWithOverrule($requestVariables, $flatGetArray);
		}
	}
```

So what will change if `$_GET` is replaced with `$_GET` returned unchanged from the function?

Do I miss something in my analysis?

**Comment by jacobsenj** [comment]
As I am using TYPO3 6.2.x the GeneralUtility method looks like
<details>
<summary>this</summary>
```php
	static public function _GET($var = NULL) {
		$value = $var === NULL ? $_GET : (empty($var) ? NULL : $_GET[$var]);
		// Removes slashes since TYPO3 has added them regardless of magic_quotes setting.
		if (isset($value)) {
			if (is_array($value)) {
				self::stripSlashesOnArray($value);
			} else {
				$value = stripslashes($value);
			}
		}
		return $value;
	}
```
</details>

So there would be the stripped slashes as difference.

It seemed to be the location where it was caused. But there needs to be more going on, as even with real url disabled the `$_GET` contains the slashes in the parameters:
https://www.dropbox.com/s/wnd22o37q2x4ebm/Screenshot%202016-07-04%2014.09.16.png?dl=0

even though the parameter in the url does not have them (no %5C in front of %22):
```
...[__trustedProperties]=a%3A4%3A%7Bs%3A6%3A%22filter%22%3Ba%3A4%3A%7Bs%3A9%3A%22continent%22%3Bi%3A1%3Bs%3A7%3A%22country%22%3Bi%3A1%3Bs%3A7%3A%22vehicle%22%3Bi%3A1%3Bs%3A5%3A%22brand%22%3Bi%3A1%3B%7Ds%3A6%3A%22action%22%3Bi%3A1%3Bs%3A6%3A%22sortBy%22%3Bi%3A1%3Bs%3A9%3A%22sortOrder%22%3Bi%3A1%3B%7D2eb7360e14bed59fc5db85eddceb1bfc9d5e7651&...
```

But `#1320830018: The given string was not appended with a valid HMAC`only occurs while realurl is enabled. I'm now back at searching the reason for it not working.

**Comment by jacobsenj** [comment]
It is really weird, I'm dumping from typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php:64 with 
```php
debug($string, $hmac);
```

I get this with unmodified realurl 2.0.14
![screenshot 2016-07-04 15 37 59](https://cloud.githubusercontent.com/assets/399303/16562435/5855c8ee-41fd-11e6-81c6-fba21c9d6219.png)

If I call it via index.php?id=... (not using realurl urldecoder) or if I comment out typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php:796 it works:
![screenshot 2016-07-04 15 31 19](https://cloud.githubusercontent.com/assets/399303/16562405/36c59b14-41fd-11e6-9c14-75bc04342cd5.png)

**Comment by jacobsenj** [comment]
It seems TYPO3 6.2.x ist adding the slashes as the `$_GET` does not contain them if I dump it right before the bootstrapping.

**Comment by dmitryd** [comment]
Yes, seems so:
```php
        static public function _GET($var = NULL) {
                $value = $var === NULL ? $_GET : (empty($var) ? NULL : $_GET[$var]);
                // Removes slashes since TYPO3 has added them regardless of magic_quotes setting.
                if (isset($value)) {
                        if (is_array($value)) {
                                self::stripSlashesOnArray($value);
                        } else {
                                $value = stripslashes($value);
                        }
                }
                return $value;
        }
```

**Comment by dmitryd** [comment]
Why do you submit the form using $_GET?

**Comment by jacobsenj** [comment]
The form is a filter for a list. Because the filtered list should be linkable the form posts using $_GET.
