### ISSUE TITLE
Page Drag&Drop (copy paste) issue / Unknown column 'uid' in 'field list' / SELECT uid FROM tx_realurl_pathcache

### ISSUE THREAD

**Issue by vincentmans** [dmitryd/typo3-realurl#192]
Drag&Drop with copy in pagetree fails. Pages are copied but not completed. TYPO3 7.6.9 and RealURL latest.

Update: it happens also with normal page Copy & Paste.

TYPO3 Debug Console:

exception

[{"tid":56,"action":"Commands","method":"copyNodeAfterDestination","type":"rpc","result":{"success":false,"message":"PHP Warning: Invalid argument supplied for foreach() in \/home\/sites\/clients\/.../typo3\/sysext\/core\/Classes\/DataHandling\/DataHandler.php line 3635"},"debug":""}]

exec_SELECTquery

array(4 items)
   caller => "TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery" (60 chars)
   ERROR => "Unknown column 'uid' in 'field list'" (36 chars)
   lastBuiltQuery => "SELECT uid FROM tx_realurl_pathcache WHERE pid=6667" (51 chars)
   debug_backtrace => "call_user_func#21 // {closure}# // TYPO3\CMS\Backend\Http\Application->run#2
      0 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Backend\Ht
      tp\AjaxRequestHandler->handleRequest#302 // TYPO3\CMS\Backend\Http\AjaxReque
      stHandler->dispatch#89 // TYPO3\CMS\Backend\Http\RouteDispatcher->dispatch#1
      71 // call_user_func_array#54 // TYPO3\CMS\Core\ExtDirect\ExtDirectRouter->r
      outeAction# // TYPO3\CMS\Core\ExtDirect\ExtDirectRouter->processRpc#87 // ca
      ll_user_func_array#139 // TYPO3\CMS\Backend\Tree\Pagetree\ExtdirectTreeComma
      nds->copyNodeAfterDestination# // TYPO3\CMS\Backend\Tree\Pagetree\Commands::
      copyNode#263 // TYPO3\CMS\Backend\Tree\Pagetree\Commands::processTceCmdAndDa
      taMap#135 // TYPO3\CMS\Core\DataHandling\DataHandler->process_cmdmap#212 // 
      TYPO3\CMS\Core\DataHandling\DataHandler->copyPages#3318 // TYPO3\CMS\Core\Da
      taHandling\DataHandler->copySpecificPage#3556 // TYPO3\CMS\Core\Database\Dat
      abaseConnection->exec_SELECTgetRows#3621 // TYPO3\CMS\Core\Database\Database
      Connection->exec_SELECTquery#377 // TYPO3\CMS\Core\Database\DatabaseConnecti
      on->debug#314" (1077 chars)

**Comment by dmitryd** [comment]
Looks like your `tx_realurl_pathcache` does not contain `uid` field. This means you did not update the database. See https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x

**Comment by vincentmans** [comment]
That's weird because it's all new... but I see that's the problem indeed. Thanks, sorry for bothering.
