### ISSUE TITLE
realURL language switching for alias based pages?

### ISSUE THREAD

**Issue by nicedp** [dmitryd/typo3-realurl#193]
I have an issue regarding realURL alias page switch. I have a custom module for products, for each product i have URL in both available languages (de & en). But when i switch to language then it doesn't take me to the same page i was on.

For Example: product page For German language is /de/produkte/product-details/gewindeschieber-typ-g4/ and if i switch it to english language then it should switched to english url(/en/produkte/product-details/threaded-slide-gate-type-g4/) of same product. But it goes to /en/produkte/product-details/

Please let me know How to fix this issue ?

**Comment by nicedp** [comment]
I have solved this issue...
Surprised to see didn't get single comment.. A very neutral community :(

**Comment by dmitryd** [comment]
This place is not community. This is a bug tracker, where people put only confirmed bugs. If you need community help, check [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
