### ISSUE TITLE
Path issues with shortcuts

### ISSUE THREAD

**Issue by pduersteler** [dmitryd/typo3-realurl#194]
Based on docs and known issues, I'm not sure if this is really an issue from a technical POV, but I'd say it is from an editor's point.

Page tree:
```
[0] instance
  - [1] web root
    - [2] products
  - [9] footer navigation (sysfolder)
    - [10] products (shortcut to: 2)
```

It's clear that 2 and 10 will have the exact same path as the sysfolder is excluded from speaking url's. However, as 10 only points to 2, I'd assume that this should work. 

It actually works, but unless you're logged into the BE, you end up in a redirect loop.

TYPO3 7.6.9, realurl 2.0.14

**Comment by dmitryd** [comment]
This will work properly if you move 9 inside 1 (better) or use [linking across domains](https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#typolinkenablelinksacrossdomains) (worse) in you TypoScript. TYPO3 does not resolve shortcuts correctly if they are outside of the current root page and you have linking across domains activated. This is not a realurl issue.

Basic generic rule: all pages and resources of your site should be inside your root page.

**Comment by pduersteler** [comment]
Thanks for the answer. I just double-checked and my displayed page-tree is wrong. Basically, 9 and 10 are inside 1;

```
[0] instance
  - [1] web root
    - [2] products
    - [9] footer navigation (sysfolder)
      - [10] products (shortcut to: 2)
```

This case does not work for us, actually. A workaround for this I just discovered is to set "exclude from speaking url" on shortcut page 10. URL's are generated properly then, and the redirect loop disappears.

To have the example as imminent as our real-life case, the structure actually is nested, which may also influence the whole thing:

```
[0] instance
  - [1] web root
    - [2] products
      - [3] ABC
    - [9] footer navigation (sysfolder)
      - [10] products (shortcut to: 2)
        - [11] ABC (shortcut to: 3)
```

**Comment by dmitryd** [comment]
You can also check [this limitation](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#limitations). RealURL does not support same title on the same level. "Same level" is calculated after exclusions. So if you exclude 9 from the first example, than 2 and 10 are on the same level. In the second example, if you exclude 2, 9 and 10, than 3 and 11 are on the same level and it is not supported.

**Comment by dmitryd** [comment]
I think this can be closed, right?

**Comment by pduersteler** [comment]
Yes. At first I though "why would one like to create a shortcut page with a speaking URL", but it makes sense somehow. Thanks!
