### ISSUE TITLE
All entries in tx_realurl_pathcache have expire = 0 | realurl 2.1.0

### ISSUE THREAD

**Issue by clausharup** [dmitryd/typo3-realurl#196]
No matter what I do in the configuration (init -> pagePath -> expireDays) the expire is set to 0....

I found in both UrlEncoder.php & UrlDecorder:

`$cacheEntry->setExpiration(0);
....
$this->cache->putPathToCache($cacheEntry);`

As I see it - the configuration `expireDays` has no effect?!?!?!

**Comment by dmitryd** [comment]
Please, do not ask questions in the bug tracker.
