### ISSUE TITLE
Error in DataHandler.php - missing check for is array

### ISSUE THREAD

**Issue by clausharup** [dmitryd/typo3-realurl#197]
public function processCmdmap_postProcess($command, $table, $id) {
		if ($command === 'move' && $table === 'pages') {
			$this->expireCachesForPageAndSubpages((int)$id, 0);

			$languageOverlays = BackendUtility::getRecordsByField('pages_language_overlay', 'pid', $id);
			if(is_array($languageOverlays)){
				foreach ($languageOverlays as $languageOverlay) {
					$this->expireCachesForPageAndSubpages($languageOverlay['pid'], $languageOverlay['sys_language_uid']);
				}
			}
		}
	}

**Comment by dmitryd** [comment]
Thank you.
