### ISSUE TITLE
UrlDecoder with $pageTitleFields might fail without cache (not logged in in BE) due to page accepted with title but not tx_realurl_pathsegment

### ISSUE THREAD

**Issue by AndreasA** [dmitryd/typo3-realurl#201]
In realurl 1.x it was possible to have to pages in this order in the page tree on the same Level:
[1] Demo --> abc
[2] Demo  --> xyz

the value in "[]" corresponds to the uid.
Now page with uid 1 has set  tx_realurl_pathsegment to "foo" and 
the one with uid 2 to "demo"

If one tried to access "demo/xyz"
this worked fine in realurl 1.x as the pathsegment was always "more" important than the title.

Now, however this fails without cache because once any field of a page correspond to a field in the pageTitleFields the loops are stopped and therefore the segment for demo will not result in UID: 2 but UID: 1 to be used.

A solution might be to switch the loops: going first through all fields, therefore all pages would be searched for a corresponding 'tx_realurl_pathsegment' before going to the next field.

**Comment by dmitryd** [comment]
It is not possible now to have pages with the same name on the same level. Please, check [Limitations](https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#limitations), item 3. You will need to rename one of pages. There will be no other solution for this, sorry.

**Comment by AndreasA** [comment]
So that means that now (in contras tto 1.x) the page name consists of all those values instead of the first valid one?

Because in 1.x if I created two different realurl path segments it worked. However that is not the case with 2.x

**Comment by dmitryd** [comment]
Yes, it is not the case. RealURL tries to be compatible as much as possible with 1.x but there are certain limitations.

It is quite easy to understand this particular limitation. Suppose, in your case realurl gets an URL like /demo/test/, which is not in the cache. Which "Demo" page it should be? This is ambiguous, so it cannot be resolved properly. Therefore, no several pages with the same name are allowed on the same logical level. Strictly speaking, realurl 1.x also failed in certain cases with this. With 2.x there is a clear requirement now that such problem should not happen.

**Comment by AndreasA** [comment]
If you ask me it is not ambigous because multiple "Demo" pages according to the page title
might use a different realurl_pathsegment and that one could be unique.
So there are two pages which are unique according tot he realurl pathsegment or the alias but are not unique anymore, if all fields are used.
I am not even talking about only having one of those pages set the realurl pathsegment but all that have the same page title.
It would work (and still be unique) if the fields were prioritized to determine the unique page (which would be the case if the order were different).

But the current solution is OK too though it was quite nice to determine unique path segments using the realurl pathsegment (without having to change the page title).

**Comment by dmitryd** [comment]
Not relevant anymore I think. On decoding this will happen only of there is no cache and it is unlikely now. Also there will be no wrong entry in the cache because the decoder does not put anything to the cache.
