### ISSUE TITLE
ID was outside the domain

### ISSUE THREAD

**Issue by kersten** [dmitryd/typo3-realurl#21]
Hi,

I recognized that using the same name for a page leads to this error:

```#1294587215: ID was outside the domain<br /> <br /> Additionally, http://domain.com/page-not-found/ was not found while trying to retrieve the error document```

This is irritating because the docs say that only pages are not allowed to have the same name under the same domain root. Did I get this wrong? This would kill multisite installs if no page in the complete tree structure is allowed to have the same name.

Or did I just miss something? With my old version of TYPO3 6.2 LTS this setup worked.

Current System: 7.6.2
typo3-realurl: dev-development

**Comment by dmitryd** [comment]
Please, set up rootpage_id values correctly in the configuration for all domains and use TYPO3 mailing lists for asking questions. RealURL works fine in such case *if* configured correctly.
