### ISSUE TITLE
Non-Breaking-Spaces are removed from url

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#218]
If a page title contains a non-breaking-space (ALT+Space on OS X), it will not be replaced with a - like a normal space but removed completely.

Example:
`page 1` will be encoded as `page-1`
`page 2` (note the nbsp between page and 2) will be encoded as `page2`

The Utility::convertToSafeString can easily be adjusted to respect all space-characters (nbsp, tab, normal space):
```php
// the space in the next line is a non-breaking space
$processedTitle = preg_replace('/[ \s\-+_]+/u', $spaceCharacter, $processedTitle);
```

**Comment by dmitryd** [comment]
Note: breaks compatibility.

**Comment by rvock** [comment]
Hm, yes, it breaks compatibility. If a page title had a non-breaking-space before, the url would not contain it. If this url is saved or linked somewhere, this old link would not work after this change.

I think, this would only affect very few pages, because a non-breaking-space will nearly never appear in a title. On windows, you only can input it with copy&paste or with ALT+0-1-6-0 . On OS X you can input it with Alt+Space.

If you want backwards compatibility, I could adjust the createPathCacheEntry-method in UrlDecoder:
https://github.com/dmitryd/typo3-realurl/blob/25f1ba4c454aa017b1c0c461792a8512c5b5c202/Classes/Decoder/UrlDecoder.php#L343

This method could also check if the url would match `segment` with nbsp removed...

**Comment by rvock** [comment]
You're right, it was a normal space. I had the hex-codes mixed up.

**Comment by dmitryd** [comment]
See #219
