### ISSUE TITLE
_DOMAINS

### ISSUE THREAD

**Issue by basvandertogt** [dmitryd/typo3-realurl#221]
Hello!

Is it possible to use _DOMAINS config for only one language and the rest of the languages by preVars?

So what i want is:
domain.com (default English)
domain.com/nl/ (Dutch)
domain.com/de/ (German)
domain.es (Spanish)

With this config default and Spanish are working but Dutch and German not:

Using TYPO3 7.6.3 and Realurl 2.0.14

`$TYPO3_CONF_VARS['EXTCONF']['realurl'] = array (
    '_DEFAULT' => array (
        'init' => array (
            'enableCHashCache' => 1,
            'appendMissingSlash' => 'ifNotFile,redirect[301]',
            'enableUrlDecodeCache' => 1,
            'enableUrlEncodeCache' => 1,
        ),

        'redirects' => array (),

        'pagePath' => array (
            'type' => 'user',
            'userFunc' => 'EXT:realurl/class.tx_realurl_advanced.php:&tx_realurl_advanced->main',
            'spaceCharacter' => '-',
            'languageGetVar' => 'L',
            'expireDays' => 7,
            'rootpage_id' => 1,
        ),

        'fixedPostVars' => array (
        ),

        'preVars' => array (
            array (
                'GETvar' => 'no_cache',
                'valueMap' => array (
                    'nc' => 1,
                ),
                'noMatch' => 'bypass',
            ),
            array (
                'GETvar' => 'L',
                'valueMap' => array (
                    'nl' => 1,
                    'de' => 2,
//                    'es' => 3
                ),
                'noMatch' => 'bypass',
            ),
        ),

        'postVarSets' => array (
            '_DEFAULT' => array(
            ),
        ),

        'fileName' => array (
            'index' => array (
                'sitemap.xml' => array (
                    'keyValues' => array (
                        'type' => 105,
                    ),
                ),
            ),
        ),
    ),

    '_DOMAINS' => array(
        'encode' => array(
            array(
                'GETvar' => 'L',
                'value' => '0',
                'useConfiguration' => '_DEFAULT',
                'urlPrepend' => 'http://sis.dev'
            ),
            array(
                'GETvar' => 'L',
                'value' => '1',
                'useConfiguration' => '_DEFAULT',
                'urlPrepend' => 'http://sis.dev'
            ),
            array(
                'GETvar' => 'L',
                'value' => '2',
                'useConfiguration' => '_DEFAULT',
                'urlPrepend' => 'http://sis.dev'
            ),
            array(
                'GETvar' => 'L',
                'value' => '3',
                'useConfiguration' => '_DEFAULT',
                'urlPrepend' => 'http://sises.dev'
            )
        ),
        'decode' => array(
            'sis.dev' => array(
                'GETvars' => array(
                    'L' => '0',
                ),
                'useConfiguration' => '_DEFAULT'
            ),
            'sisnl.dev' => array(
                'GETvars' => array(
                    'L' => '1',
                ),
                'useConfiguration' => '_DEFAULT'
            ),
            'sisde.dev' => array(
                'GETvars' => array(
                    'L' => '2',
                ),
                'useConfiguration' => '_DEFAULT'
            ),
            'sises.dev' => array(
                'GETvars' => array(
                    'L' => '3',
                ),
                'useConfiguration' => '_DEFAULT'
            )
        )
    ),
);`

Regards,
Bas

**Comment by dmitryd** [comment]
[Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)

**Comment by basvandertogt** [comment]
Thank you. I wrote a topic in the English mailinglist 12 days ago but i get no response on it. Someone else is looking for the same answer so it would be nice if someone can point me in the right direction.
