### ISSUE TITLE
defaultToPHPsuffixOnPrev with .php

### ISSUE THREAD

**Issue by in-session** [dmitryd/typo3-realurl#223]
Hi,

first many thanks for the great extension :-)
Small question we makes relaunch of a website, but all URL suffix are with php.
Have you any idea how we can add .php instead .html?

Current we have made a copy of the extension and changed the part inside the UrllEncoder Classes, but this is not a option for long term support.

`	protected function handleFileNameSetDefaultSuffix() {
		if ($this->encodedUrl) {
			$suffixValue = $this->configuration->get('fileName/defaultToPHPsuffixOnPrev');
			if ($suffixValue) {
				if (!is_string($suffixValue) || strpos($suffixValue, '.') === FALSE) {
					$suffixValue = '.php';
				}
				if ($this->encodedUrl !== '') {
					$this->encodedUrl = rtrim($this->encodedUrl, '/');
				}
				$this->encodedUrl .= $suffixValue;
			}
		}
	}`

Many Thanks Best Regards Chris

**Comment by dmitryd** [comment]
[Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)
