### ISSUE TITLE
Unique Aliases pr. site - feature request

### ISSUE THREAD

**Issue by hdj-typoconsult** [dmitryd/typo3-realurl#226]
Hello Dmitry

We have a TYPO3 7 installation with 4 sites. Each site has a folder containing extbase objects "products". Several of these products share the same name for example lotion, shampoo etc between sites. 

Danish site product folder:
![danish-site-product-folder1](https://cloud.githubusercontent.com/assets/11867059/17517656/9bedb342-5e44-11e6-8f09-826c3311ded7.png)

Finnish site product folder:
![finnish-site-product-folder2](https://cloud.githubusercontent.com/assets/11867059/17517875/bafa72c4-5e45-11e6-90a7-397752634836.png)

Since the value_alias in table tx_realurl_uniqalias must be unique we end up with entries like lotion, lotion-1, lotion-2, lotion-3. 

Our current configuration:
```
'fixedPostVars' => array(
		'596' => array(
			array(
				'GETvar' => 'tx_tcdermalog_plugin[product]',
				'lookUpTable' => array(
					'table' => 'tx_tcdermalog_domain_model_product',
					'id_field' => 'uid',
					'alias_field' => 'name',
					'addWhereClause' => ' AND NOT deleted',
					...
					'useUniqueCache' => 1,
					'useUniqueCache_conf' => array(
						'strtolower' => 1,
						'spaceCharacter' => '-',
					),
				),
			),
		),
```

Would it be possible to relate value_aliases to a rootpage_id? More or less the same way as in table tx_realurl_urlcache where its possible to have identical speaking_urls in different sites), so that its possible to have identical aliases across sites but unique pr. rootpage_id. So that for example each site can have the alias ”lotion” without appended numbers.  

![table](https://cloud.githubusercontent.com/assets/11867059/17517534/204b8732-5e44-11e6-8dbb-8f3becc30b10.png)

Kind regards

Henrik D. Jensen
TypoConsult

**Comment by tbal** [comment]
@hdj-typoconsult Did you found a way to achieve this? I have the same problem.
I think #475 is also related to this.

**Comment by hdj-typoconsult** [comment]
We did not found a solution unfortunately. But we made a work-around using the alias_field. 
'alias_field' => 'CONCAT(name, " ", "-en")', to make each url pr. country unique.
