### ISSUE TITLE
missing titles in TCA

### ISSUE THREAD

**Issue by graphag** [dmitryd/typo3-realurl#227]
These titles are shown when editing backend usergroups (see screenshot). 
I personally do not care about the missing icons, but having a title would be less confusing. 

![realurl](https://cloud.githubusercontent.com/assets/20947558/17551693/e3510ed4-5efb-11e6-96d3-f297c253096a.png)

 $GLOBALS['TCA']['tx_realurl_pathcache'] = array(
 	'ctrl' => array(
		'title' => 'Realurl pathcache',
 		'label' => 'pagepath',
 		'hideTable' => 1,
 	),
 
 $GLOBALS['TCA']['tx_realurl_uniqalias'] = array(
 	'ctrl' => array(
		'title' => 'Realurl uniqalias',
 		'label' => 'value_alias',
 		'hideTable' => 1,
 	),
 
 $GLOBALS['TCA']['tx_realurl_urlcache'] = array(
 	'ctrl' => array(
		'title' => 'Realurl urlcache',
 		'label' => 'speaking_url',
 		'hideTable' => 1,
 	),`

**Comment by dmitryd** [comment]
Already fixed in the current development version.
