### ISSUE TITLE
Backendmodul is empty in TYPO3 8.2

### ISSUE THREAD

**Issue by fischhase** [dmitryd/typo3-realurl#228]
Dear RealURL-Team,

I tried to use RealURL width TYPO3 8.2. The first impression was promising. The paths where created correctly. Everythings workd fine if I am logged in TYPO3.  After logging out I got error messages in the frontend: 

`caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
   ERROR => 'Unknown column 'expire' in 'order clause'' (41 chars)
   lastBuiltQuery => 'SELECT * FROM tx_realurl_urlcache WHERE rootpage_id=1 AND original_url='id=2
      ' ORDER BY expire LIMIT 1' (101 chars)
`
`Uncaught TYPO3 Exception
#1: PHP Warning: Invalid argument supplied for foreach() in /usr/www/users/abppjo/websites/wk-hohe-heide.de/typo3conf/ext/realurl/Classes/Cache/DatabaseCache.php line 198 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
/usr/www/users/abppjo/typo3/typo3_src-8.2.0/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 112.`

In the backend modul there are no entries shown at all. So I can't flush the cache etc. 

I hope I could help a littlebit making realsurl TYPO3 8 ready. If you have questions, please ask.

Thanks and regards
Martin

**Comment by dmitryd** [comment]
Update the database in the Install tool.

**Comment by fischhase** [comment]
ahhh! ok. Thanks, that worked :-)
