### ISSUE TITLE
Wrong URL when cross-linking to other domains?

### ISSUE THREAD

**Issue by p2media** [dmitryd/typo3-realurl#229]
We are using multiple domain records in the same TYPO3 installation. Our tree looks something like this:
```
[0] root
+- [1] www.example.tld
   +- [2] page1
+- [20] a.example.tld
   +- [25] page1
```
We want to link from pageUid 25 to pageUid 2, but we only get a URL to the rootpage http://www.example.tld/ and not http://www.example.tld/page.html as aspected.

Of course we are using the following configuration:
```
config {
	typolinkCheckRootline = 1
	typolinkEnableLinksAcrossDomains = 1
	tx_realurl_enable = 1
}
```

Additionally we are generating the `_DOMAINS` configuration dynamically (see https://github.com/dmitryd/typo3-realurl/pull/142/commits/8b405d46ed0d97ddc409067d8962bbe624121d5c).
Could this be a problem?

**Comment by dmitryd** [comment]
Sorry, I do not answer questions in the bug tracker. You need to read [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) if you wants answers to questions and general help. I only fix confirmed bugs reported here.

**Comment by p2media** [comment]
First I thought that it was a bug, but then I realized that my config was not properly generated 😓 
Thanks for you help anyway!
