### ISSUE TITLE
Missing fallback if lookUpTable has no result

### ISSUE THREAD

**Issue by abmerlin** [dmitryd/typo3-realurl#232]
Hi, 
I have the big problem that my realurl setting doses not work after an update. The problem is that I use lookUpTable and sometimes there is no result in the Table. In the old version the realurl return the id - not nice but the only way to get a correct url. 

I have added the following code in the UrlEncode.php at line 326:
```
            else  {
                $aliasValue=$this->databaseConnection->fullQuoteStr($getVarValue, $configuration['table']);
                if ($configuration['useUniqueCache']) { // If cache is to be used, store the alias in the cache:
                    $result = $this->storeInAliasCache($configuration, $aliasValue, $getVarValue, $languageUid);
                } else { // If no cache for alias, then just return whatever value is appropriate:
                    $result = $aliasValue;
                }
            }
```

Is it possible to add this to the repository?

Thanks
Andreas

**Comment by dmitryd** [comment]
Hm. Correct url for non-existing item?
