### ISSUE TITLE
RealURL path segment gets populated with random (?) numbers when moving pages

### ISSUE THREAD

**Issue by AlphawolfWMP** [dmitryd/typo3-realurl#234]
Howdy,

using TYPO3 6.2.x we've come across a weird issue with RealURL 2.0.14 that results in populating a page's path segment field with random (?) numbers when moving a page via drag'n'drop.

**Before page move:**
![Before moving](http://screens.schloebe.de/image_2016-08-18_15_18_49_001.png)

**After page move:**
![After moving](http://screens.schloebe.de/image_2016-08-18_15_20_21_001.png)

Which makes speaking urls change from `/aktuell/magazin/` to `/aktuell/<number>/` or the path segment is omitted if the number that's been inserted into a path segment field is `0` (which turns `/aktuell/magazin/` to `/aktuell/`).

Is it a bug or a feature?

Thank you!

**Comment by bennorz** [comment]
I have the same problem. It doesn't always happen, which makes debugging complicated.

I only use one language so it's not a localization problem

**Comment by AlphawolfWMP** [comment]
Yep, same here. We only use only 1 language as well.

**Comment by bennorz** [comment]
See also: https://github.com/dmitryd/typo3-realurl/issues/180
