### ISSUE TITLE
Missing Realurl management module to create redirects

### ISSUE THREAD

**Issue by mathias-noethiger** [dmitryd/typo3-realurl#235]
I'm missing the realurl management module which used to be inside the TYPO3 info module. 
Now there is a specific real URL module, but no possibility to add redirects there :-(

After a website relaunch it was great to have a statistic of no more found pages and the a direct possibility to create redirections. 

The functionality was there until version 2.0.0 but disappeared in the latest version. Will it come back? Or is it somewhere else?

**Comment by dmitryd** [comment]
[Documentation](https://github.com/dmitryd/typo3-realurl/wiki/Differences-between-RealURL-1.x-and-2.x#redirects)

**Comment by mathias-noethiger** [comment]
A module that's writes directly into the htaccess would be great than. It not a good idea to let project managers and SEO specialist work inside the htaccess directly :-/

**Comment by dmitryd** [comment]
Not a subject of realurl. Have you checked TER? There are many redirect extensions there.

**Comment by mathias-noethiger** [comment]
Yes someone mentioned: https://docs.typo3.org/typo3cms/extensions/ods_redirects/ 
Probably we try out this extension. The documentation does not make such a good impression...
