### ISSUE TITLE
Cache is disabled in if BE_USER session is active causing cache lookup in UrlDecoder to return NULL

### ISSUE THREAD

**Issue by sorenmalling** [dmitryd/typo3-realurl#237]
## Case:
Implementing a "UrlEncoder" hook to create a url for a "pages" doktype consisting of two fields.
Clicking the created link (domain.tld/{field1}-{field2}) in the frontend ends up with a "HTTP 404".
Clicking the created link in a "incognito" session with no BE_USER/editor session, the url returns the expected page from the pagetree.

The issue is caused by the CacheFactory returning NullCache when a BE_USER session is present since it uses this "getCache" method

https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Utility.php#L97

which is if it used this method from the cache factory

https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Cache/CacheFactory.php#L41

## Proposed solution:

Remove the "getCache" entrypoint from the "Utility" class and only use the CacheFactory.

The Utility->getCache() is only used in ./Classes/EncodeDecoderBase.php. To respect the "cache/disable" configuration parameter this will be moved to the "CacheFactory->getCache" method, to return a NullBackend.

**Comment by dmitryd** [comment]
Cache is disabled if BE user is logged in by design. This will not change. The reason is simple: BE user may have hidden pages that he needs to see and FE user should not. These pages should not get into cache.

You should make your hook work on both sides: encoding and decoding. You should also remember that URL cache can be cleared at any moment by the user. Therefore the decoder should be able to parse URL without using cache.

**Comment by sorenmalling** [comment]
Thanks for the feedback.

Since the Cache is disablde when being logged in as a backend user, it doesn't matter if i implement the UrlCache and PathCache for the decoding, since it will never do a lookup there, to find the path being requested.

Can you perhaps give a bullet point on the theory about implementing this correctly, when the cache is disabled upon request with a BE session?

**Comment by dmitryd** [comment]
I am not sure what your use case is. Do you need to override page path decoding or parameter decoding? For the page path it will be complicated. You will need and xclass and override protected methods but they are moving around and change parameters, so it will be complicated.

**Comment by AndreasA** [comment]
With the recent changes this also means that the correct cHash values will not be available during decoding which means that as long as the admin panel is not calling set_no_cache
it is actually necessary to have valid cache entries too.

**Comment by dmitryd** [comment]
In 2.1.0 url cache will be active for BE users too.

**Comment by AndreasA** [comment]
When can 2.1.0 be expected?
