### ISSUE TITLE
PreVars Not Existing Path Segment Bug

### ISSUE THREAD

**Issue by r3h6** [dmitryd/typo3-realurl#239]
A multilingual site with prevars configuration using defaultValue.
When calling a non existing path with only one segment like /foobar always the home page with status 200 is returned instead of a 404 page.
When calling a path with two or more segments like /foo/bar everything is fine.

**Comment by dmitryd** [comment]
Please, attach configuration. Cannot fix anything without it.

**Comment by r3h6** [comment]
If prevars has noMatch = bypass, it works fine:
If using the configuration below, all path with one segment will find the home page.
(Which can fill the cache quickly...)

/de/ => Returns german home page = OK
/fr/ => Returns french home page = OK
/it/ => Returns german home page = NOK, expect 404
/foobar.html => Returns german home page = NOK, expect 404

Shouldn't the default value only be respected for encoding?
When decoding with this configuration, it seems it simply replaces the segment with the default value and the path used for page path is "/"...

```
<?php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']=array (
  '_DEFAULT' =>
  array (
    'init' =>
    array (
      'appendMissingSlash' => 'ifNotFile,redirect',
      'emptyUrlReturnValue' => '/',
    ),
    'pagePath' =>
    array (
      'rootpage_id' => '1',
    ),
    'fileName' =>
    array (
      'defaultToHTMLsuffixOnPrev' => 0,
      'acceptHTMLsuffix' => 1,
      'index' =>
      array (
        'print' =>
        array (
          'keyValues' =>
          array (
            'type' => 98,
          ),
        ),
      ),
    ),
    'preVars' =>
    array (
      0 =>
      array (
        'GETvar' => 'L',
        'valueMap' =>
        array (
          'de' => '0',
          'fr' => '1',
        ),
        'valueDefault' => 'de',
      ),
    ),
  ),
);
```

**Comment by dmitryd** [comment]
Behaviour is correct. You have a preVar with `valueDefault`. Your non-exsting segment is checked by `valueMap`, it is not found and transformed by `valueDefault` to `0` (`de`).

Please, read the Integrator's manual on the wiki about setting up languages correctly.

**Comment by chesio** [comment]
Hi @r3h6 , I had a similar problem, I wanted all following requests to return 404 error:

1. /existing-language/non-existing-page
1. /non-existing-language
1. /existing-page-without-language

If you use `noMatch = bypass`, then 1. and 2. works, but not 3. If you have `valueDefault` set or simply nothing, then only 1. works.

A work-around that I found to be working in my case is to edit "final" line in root `.htaccess`, so any unexpected front-end request is not passed to TYPO3:
<pre>RewriteRule ^(de/|en/|sitemap.xml$|$) index.php [L]</pre>

Of course, you must have a proper 404 handler set on the server.

Greets,
Česlav
