### ISSUE TITLE
TYPO3 8.x compatibility

### ISSUE THREAD

**Issue by patkar** [dmitryd/typo3-realurl#240]
| Q | A
| --- | ---
| Bug? | yes and no ;)
| New Feature? | no
| Version used | dev-master

#### Actual Behavior

 Only compatible to TYPO3 8.0

#### Expected Behavior

Should be compatible to all upcoming TYPO3 8.x sprint releases :)

And have a 2.1.x version released with at least after every sprint release and fixed compatibility / updated composer requirements.

#### Steps to Reproduce

Yet not installable due to composer requirements.

#### Possible Solutions

Do you need help with testing and fixing compatibility?

**Comment by dmitryd** [comment]
Please, do not make "fancy" reports. Write short and precisely. All this could be written as "RealURL composer requirements prevent it from working with TYPO3 8.x".

Please, read also about [contributing](https://github.com/dmitryd/typo3-realurl/wiki/Contributing).

**Comment by patkar** [comment]
Damn it, yes or no, you need help making compatible or not?

I'll use my issue template every time and I'll continue with that. Simple.

**Comment by dmitryd** [comment]
In that case I do not need your help. Thanks.

**Comment by patkar** [comment]
![This is not how it works](https://imgflip.com/i/1a43j0)

**Comment by patkar** [comment]
![This is not how it works](https://cloud.githubusercontent.com/assets/993350/18266341/84ec00ea-741a-11e6-8479-a676d47ce966.jpg)

**Comment by dmitryd** [comment]
User is blocked from this project due to spam and loosing my time for nothing.
