### ISSUE TITLE
realURL creates pagePath sometimes with default-pagetitle and sometimes with translated-pagetitle

### ISSUE THREAD

**Issue by nelbarr** [dmitryd/typo3-realurl#241]
I am using realURL v2.0.11

In some cases realURL does not use the translated-pagetitle to create a pagePath, but uses the defaultlanguage-pagetitle. 

I did not change much in the realurl_conf and using L as the language-parameter. 

I cleared all realURL-Tables to test if it is just wrong path in the cache, but even with empty realurl-tables realURL rebuild the "wrong" pagePaths.

This "wrong" pagePaths will not work when logged into the backend.

I am not sure if it is a bug or a hidden configuration (in realURL v1.x it would be  missing languageGetVar  entry in the conf).

To hotfix it for now I changed the function getCache() in the Ultility.php  and always return a NullCache for the moment.

**Comment by nelbarr** [comment]
Looks good so far, thanks for the hint! 
(having ugly Mount Point URLs now, but I guess thats just some configuration problems)

**Comment by nelbarr** [comment]
I am sorry I confirmed too early. 
I updated to 2.0.14, cleared ALL realurl tables. 

When I first called the "wrong" URL "/ch/the-shoe/home" I got a 404 (thats fine)
But as soon as I called the right URL "/ch/der-schuh/home" the wrong URL is also working again


There is nothing in tx_realurl_pathcache
But the "wrong" URL is in tx_realurl_urlcache

I did it 2 times now and can reproduce it.

**Comment by dmitryd** [comment]
> there were many fixes for localisation in the development version. Please, try that and see if it helps.

:)
