### ISSUE TITLE
Compatibility with CMS 8.3

### ISSUE THREAD

**Issue by haassie** [dmitryd/typo3-realurl#243]
Due to limitations in composer manifest, it's not possible to use the extension in CMS 8.3. 

Are you already working on this? Or should I create a Pull request?

**Comment by dmitryd** [comment]
PR would be good but I will be able to merge it only after testing with 8.x master branch. This is currently in plans. But still, make a PR, please :)

**Comment by dmitryd** [comment]
PR would be good but I will be able to merge it only after testing with 8.x master branch. This is currently in plans. But still, make a PR, please :)
