### ISSUE TITLE
Wrong content delivered when chashcache is empty and fixedPostVars-URLs are accessed

### ISSUE THREAD

**Issue by cweiske** [dmitryd/typo3-realurl#245]
## Problem
Realurl 1.13.6 stores invalid entries in the url decode cache when the chashcache has no entry for the current URL.

This leads to wrong content delivered for those URLs (often the same content, since all get the same `newHash`).

## Situation
Plugin that pages data, and a realurl configuration that maps the necessary GET parameter into the URL:
```
$TYPO3_CONF_VARS['EXTCONF']['realurl']['_DEFAULT'] = [
    'init' => [
        'enableCHashCache'     => true,
        'enableUrlDecodeCache' => true,
        ...
    ],
    ....
    'fixedPostVars' => [
        23 => [
            ['GETvar' => 'page'],
        ]
    ],
    ...
];
```
This gives us paged URLs for the `news` page 23:

URL | Decoded URL
--- | -----------
`/news/` | `/?id=23&page=`
`/news/2/` | `/?id=23&page=2`
`/news/3/` | `/?id=23&page=3`

## Triggering the error

1. Empty frontend cache
2. Empty all realurl cache tables (`TRUNCATE TABLE tx_realurl_chashcache; TRUNCATE TABLE tx_realurl_urldecodecache; TRUNCATE TABLE tx_realurl_urlencodecache;`)
3. Open URL `/news/`. The correct content is delivered since the FE cache is empty. Since page 2 is linked on the page, a `chashcache` record is created for it.
4. Open URL `/news/2/`. Since there is a `chashcache` entry for it, the correct content is delivered
5. Open URL `/news/4/`. There is no `chashcache` entry for it because TYPO3 did not yet generate a page that links to it. The content of `/news/` is shown!

This is because realurl does not add a `cHash` parameter to the GET variables,  and `TypoScriptFrontendController` internally ignores the GET variable and thus generates the same `newHash` as it does for `/news/`. Thus it delivers the content of `/news/`.

The problem gets worse because realurl creates an entry for `/news/4/` in the `urldecodecache`, without the `cHash` parameter. This means that - even if in the meantime another page call leads to a `chashcache` entry for `/news/4/` - it will never be used because the url decode cache does not contain it.

## Migitation
- At first, realurl should not store entries in `urldecodecache` if they have GET parameters with values and no `cHash`.
-- This prevents the problem that the wrong page content is shown even if in the meantime a correct `chashcache` entry for the URL is generated
- Until 1. happens, TYPO3 still delivers the wrong content. Caching should be disabled for requests that have GET parameters with values but no `cHash`.
-- When pages contain links to themselves (which they often do because of `<link rel=canonical>`), then already the second request to the page leads to a correct cache.

## Patch
```
--- class.tx_realurl.php	2016-09-09 11:18:29.735450793 +0200
+++ class.tx_realurl.php	2016-09-09 11:19:01.986369837 +0200
@@ -1762,6 +1762,16 @@
 
 
 				if (!$this->isBEUserLoggedIn() && $this->canCachePageURL($cachedInfo['id'])) {
+					if (isset($cachedInfo['GET_VARS']) && count($cachedInfo['GET_VARS'])
+						&& !isset($cachedInfo['GET_VARS']['cHash'])
+						&& implode('', $cachedInfo['GET_VARS']) != ''
+					) {
+						//do not cache URLs with additional GET parameters but without cHash
+						//but do not require cHash if the get vars have no value
+						//disable page cache so the correct content is returned to the user
+						$GLOBALS['TSFE']->set_no_cache();
+						return;
+					}
 					$rootpage_id = intval($cachedInfo['rootpage_id']);
 					$hash = md5($speakingURIpath . $rootpage_id);
 
```

**Comment by dmitryd** [comment]
The situation you describe is not a bug in realurl. Steps show that you deliberately removed information that realurl needs to create proper cHash. So you should not expect proper URLs after you did so. You should not clear `tx_realurl_chashcache`.

More... Realurl 1.x is not supported anymore. There will be no fixes or changes for that version.

**Comment by cweiske** [comment]
realurl not being able to "recover" from an empty cache table is certainly a bug.

Cache tables are ephemeral by definition, and emptying them should not lead to a broken system.

----

I understand that realurl 1.x is not supported anymore, but I thought it would be nice for others to see that there is a fix.

**Comment by dmitryd** [comment]
> realurl not being able to "recover" from an empty cache table is certainly a bug.

No, it is not a bug. If the table has a "cache" word in its name, it does not mean you can clear it when you want. You can clear decode and encode caches, and realurl gives you tools for that (BE modules). But it does not let you to clear chash cache for a reason: it is not the thing that you should touch. It is required for a proper work of realurl. If you clear it, wrong behavior is expected. When people ask me what tables they can clear, I tell them that it is errorlog, urldecodecache, and urlencodecache. Clearing anything else is unsafe.

What you propose as a solution (set_no_cache) is not a "recovery" either.

**Comment by cweiske** [comment]
> What you propose as a solution (set_no_cache) is not a "recovery" either.
It gives realurl the chance to add missing entries to the `chashcache` table, while still delivering correct content. 

It's not instant recovery but a two-step process - which is better than the previous situation.

----

I think we can stop discussing now since we have different views on this issue. Thanks for maintaining realurl.

**Comment by lisardo2** [comment]
Well i think that this problem is now really up to date ... Because of this security fix for the core we have to empty all real url tables: https://typo3.org/teams/security/security-bulletins/typo3-core/typo3-core-sa-2016-022/ " If extensions like realurl are used, it is required to flush their caches (and TYPO3 caches as well), so that the new cHash is stored, once the pages are requested." - so the patch of cweiske  seems to be the only way to deal with this problem. I found a description of the problem here: http://stackoverflow.com/questions/39595580/what-to-do-after-typo3-security-update-from-13-09-2016 - Answer 2.
