### ISSUE TITLE
"Speaking URL path segment" automatically inserts numbers if same name

### ISSUE THREAD

**Issue by Shentao83** [dmitryd/typo3-realurl#248]
Hi, I have a multilanguage Website with Asian languages (Chinese, Thai and Japanese), so I have to input English "Speaking URL path segments". The language are separated through Subfolders /hk/ or /jp/ or /cn/ etc. 

If the same page has several path segments with the same name, RealUrl now automatically sets 0, 1, 2 and so forth behind the path segment (I guess this is newly intended to avoid colliding with same names). This is actually not needed at all, since through the subfolders, I already have separated paths, so there won't be any collision anyway. Is there an option to turn off this behaviour without editing the database itself? 

Current:
www.domain.com/de/seite.html
www.domain.com/en/page.html
www.domain.com/cn/page0.html
www.domain.com/jp/page1.html
www.domain.com/hk/page2.html
www.domain.com/th/page3.html

Past/Desired:
www.domain.com/de/seite.html
www.domain.com/en/page.html
www.domain.com/cn/page.html
www.domain.com/jp/page.html
www.domain.com/hk/page.html
www.domain.com/th/page.html

**Comment by dmitryd** [comment]
Related to #234, already fixed.
