### ISSUE TITLE
Same detail page for different urls if query parameter L > 0

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#250]
Hello @dmitryd,
my Realurl is on last commit of development branch https://github.com/dmitryd/typo3-realurl/commit/bfff818130c8dd6fb368b59f6e23167850a4d1a7

If L != 0 then a detail page, like a news post, always display the same post, no matter what the post url is.
With L=0 there is not this problem.

Debugging the code, in method `decodeUrl` it checks `if ($this->isSpeakingUrl())` and then it calls `$this->setLanguageFromQueryString();` but if it's a speaking url it means that there could not be a L query parameter and `$this->detectedLanguageId` remains 0.

Subsequently, the method `getUrlFromCacheBySpeakingUrl` is called with `$this->detectedLanguageId = 0` so, even if there's a record for this speaking url in `tx_realurl_urldata`, the row is discarded cause `((int)$variables['L'] === (int)$languageId)` is false (1 != 0).

It could be that I don't understand the Realurl logic but this doesn't seem correct.

Best regards.

**Comment by dmitryd** [comment]
> Debugging the code, in method `decodeUrl` it checks `if ($this->isSpeakingUrl())` and then it calls `$this->setLanguageFromQueryString();` but if it's a speaking url it means that there could not be a L query parameter and `$this->detectedLanguageId` remains 0.

Not exactly so. This sets the initial value of the detected language id because L is not necessarily configured in preVars and it still can be in the URL. Later function named `decodePreVars` will change it if found in the speaking URL.

> Subsequently, the method `getUrlFromCacheBySpeakingUrl` is called with `$this->detectedLanguageId = 0` so, even if there's a record for this speaking url in `tx_realurl_urldata`, the row is discarded cause `((int)$variables['L'] === (int)$languageId)` is false (1 != 0).

Thanks for analysis. This looks like a bug (related to #103). I will check.

**Comment by dmitryd** [comment]
Could you check if this solves the issue for you? Thanks!

**Comment by webian** [comment]
Issue solved. Thanks a lot!
