### ISSUE TITLE
Fluid page link to different pid using addQueryString not working

### ISSUE THREAD

**Issue by maechler** [dmitryd/typo3-realurl#251]
There is an issue when using the Fluid ViewHelper `<f:link.page>` and realurl. We are using TYPO3 7.6.10 and realurl 2.0.15.

If you are for instance on a page with uid 1 and want to link to a page with uid 2 and set the addQueryString option, the link will be generated for uid 1 instead of 2.

e.g.

```
We are on page 1
<f:link.page pageUid="2" addQueryString="1">Page 2</f:link.page>
```

The link generated will be for uid 1. The problem is that the url to encode will look like `"yourpage.com?id=2&id=1"`. In the foreach loop of the function `DmitryDulepov\Realurl\Encoder\UrlEncoder->parseUrlParameters` we overwrite `$this->urlParameters['id'] = 2` with `$this->urlParameters['id'] = 1`.

I am not sure whether something changed in the typolink function or something changed with realurl 2, but it used to work with TYPO3 6.2.26 and realurl 1.12.8.

A temporary workaround is to exclude the id from the query string parameters:

```
We are on page 1
<f:link.page pageUid="2" addQueryString="1" argumentsToBeExcludedFromQueryString="{0: 'id'}">Page 2</f:link.page>
```

**Comment by dmitryd** [comment]
In PHP the second argument with the same name always overrides the first one. You can run this example using shell:
```bash
php -r 'parse_str("id=2&id=1&L=1", $vars); print_r($vars);'
```
The result is:
```
Array
(
    [id] => 1
    [L] => 1
)
```
`addQueryString` will override the `id` parameter if applied to the existing URL. Docs [warn you](https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Typolink/Index.html):

> Notice that this does not check for any duplicate parameters! This is not a problem: **Only the last parameter of the same name will be applied.**

What docs do not say, however, is that `addQueryString` is applied **after** the `id` parameter is added to the string: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/TypoScript/TemplateService.php#L1570-L1605

So the id from the `addQueryString` will take precedence. It was always like that in the TYPO3 core. I am not going to check with realurl 1.x but I believe it will behave identically.

If you use `addQueryString`, you always have to exclude some variables. See this code: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L6341-L6356 (method `getUrlToCurrentLocation`).

If you send `id=2&id=1`, this is ambiguous and you cannot expect proper results. Realurl will not recover for caller's mistakes. Please, make sure that you create proper unambiguous URLs.

**Comment by maechler** [comment]
Well, thanks for the explanations! I guess then it would be nice if the Fluid PageViewHelper would handle this and let the parameter `pageUid` overwrite the added query string.

**Comment by dmitryd** [comment]
This should be a bug report for that viewhelper :) I am aware of such behaviour of this viewhelper because we quite often use it with `addQueryString` but I am so used to exclude other parameters that to me the current behaviour is natural.

**Comment by maechler** [comment]
https://forge.typo3.org/issues/77946
