### ISSUE TITLE
Release for "id" bugfix?

### ISSUE THREAD

**Issue by AndreasA** [dmitryd/typo3-realurl#252]
I know you don't want such questions but the "id" bugfix would be good to have the latest security bugfix.

When will be the release for the "id" bugfix?
Also the bug if one is logged into the backend and detail page?

**Comment by dmitryd** [comment]
https://github.com/dmitryd/typo3-realurl/wiki/Contributing:

> Issue tracker is not the place to ask questions! All questions should be addressed to the TYPO3 mailing lists. Questions in the bug tracker will be closed immediately without answers. See [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) if you need help with RealURL.

**Comment by dmitryd** [comment]
If you continue to put spam the issue tracker, I will ban you from the project.
