### ISSUE TITLE
Realurl 2.0.15 broken with TYPO3 7.6.11

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#253]
Realurl 2.0.15 will break with TYPO3 7.6.11 (and possibly with 6.2.27) because the cHash now includes the page id.

Example Typoscript:
```
page = PAGE
page.10 = TEXT
page.10.typolink.parameter = 1,0,&test=1
page.10.typolink.useCacheHash = 1

config.tx_realurl_enable = 1
```

Clicking the link will give this error:
```
ID parameter needs to be passed for the cHash calculation! As a temporary not recommended workaround, you can set $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] to false to avoid this error.
```

This happens, because realurl unsets the id from the parameters:
https://github.com/dmitryd/typo3-realurl/blob/7c440b/Classes/Encoder/UrlEncoder.php#L183

**Comment by dmitryd** [comment]
1. This happens only if you set this option to `true`. Its default value is `false`.
1. This is [already solved](https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L1163-L1166) in the development version.

Nothing to do. Please, check the code before reporting issues, ok? :) Thanks!

**Comment by koernchen02** [comment]
Hello Dmitry, 
now I'm confused... https://typo3.org/news/article/cache-flooding-in-typo3-frontend/ states that you found an issue which led to this option beeing `true` by default for TYPO3 versions 6.2.27, 7.6.11 or 8.3.1 and up. So if people want to patch their TYPO3 installation, they have to enable `$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId']` ! 

I'm currently only able to use RealURL dev-v2.1.x with 7.6.11 in a Production Site.

**Comment by dmitryd** [comment]
> which led to this option beeing true by default for TYPO3 versions 6.2.27, 7.6.11 or 8.3.1 and up

It is `true` only for new installations. If you are upgrading, it is `false`. Set it to `false` if you use realurl < 2.1.0 or use realurl development version if want to set the option to `true`. With composer you can use `"dmitryd/typo3-realurl" => "dev-development"`.

Realurl 2.0.15 was released before that security announcement, so it does not support this option. And 2.1.0 is not yet ready to be released.

**Comment by koernchen02** [comment]
Thanks a lot for your feedback and for pointing that out!
So realurl > v2.0.15 might support the option or will the next version be 2.1.x?

**Comment by dmitryd** [comment]
The answer is in my post above.
