### ISSUE TITLE
Old path for a detail page should throw 404

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#258]
Hello @dmitryd,
with this config http://pastebin.com/8fDsDEne, let's assume there's a product whose detail page had this path:
`/path/to/old/prod/product-name`
then the product is moved to a new page with uid 20 (the old page with uid 10 still exists) and now it's detail page has this path:
`/path/to/new/prod/product-name`

The site is browsed with the old path (coming from search engine by example)
Realurl doesn't finds (getFromUrlCache) a record in tx_realurl_urldata with `speaking_url = /path/to/old/prod/product-name` so it does the decoding (doDecoding) and it does find (decodePath) the old page with uid 10. It goes on and decodePostVarSets and then creates a cache entry for product-name but with the old page uid and without cHash.

This creates a detail page with duplicated content, bad for SEO, while I think it should return a 404 instead.
(Also I think, but I'm not sure cause I'm still checking, that this cache entry causes TYPO3 to display the wrong detail page in some cases)

What's your opinion? Am I missing something?

**Comment by dmitryd** [comment]
Realurl's tasks are only to decode or encode the URL. The page still exists. postVar is still configured. Why would realurl throw a 404? It is not realurl's job. Under such conditions it works absolutely correctly. Remove that old page or do redirections in `.htaccess` or whatever. Realurl does not do any application logic because it does not know anything about it.

Not a bug, not doable by realurl. Sorry.

**Comment by webian** [comment]
@dmitryd I understand your point but unluckily the old page can rarely be removed because it has other products and handle this old->new map of the product detail URLs with .htaccess is not possible to implement because it can't be automatic and also there are too many products that can change path in the lifetime of a website.

I could implement a code that throws a 404 if the pageId returned by decodePath is not equal to the product pid. But where can I hook this code? Shouldn't a hook be present in doDecoding just before the cache entry is populated or somewhere else?

Or maybe, even if it's not his job, Realurl could do us a favor and have an option to check if a product/news/comment/etc has a particular pid, the one discovered by decodePath.

**Comment by dmitryd** [comment]
> Or maybe, even if it's not his job, Realurl could do us a favor and have an option to check if a product/news/comment/etc has a particular pid, the one discovered by decodePath.

Of course. If it could also cook breakfast on Sundays, it would be cool :)

Seriously speaking: no, it will not do that. Its your job, not realurl's. You are the developer, so do your job about **your** application logic. Realurl is strictly about encoding and decoding. No other logic. If you do not know how to do it, you may find or hire somebody else to do it. The market is open and full of developers and integrators.

Everybody should do his/her part of the job. Realurl does its part: decoding and encoding only. Nothing else.

**Comment by dmitryd** [comment]
By the way, what you want to do, is easily doable via realurl configuration. Since I strongly believe in self-education, I will not say more. Please, try to find the answer yourself. Or you can check "Getting help" on the wiki and ask people in mailing lists or Slack.

**Comment by webian** [comment]
I appreciate the fact that you worry that I'm not able to develop or that I didn't read the documentation, you're very kind and careful but this is not my case :)
From the tone of your reply seems to me that you think I'm one who want things handed on a plate for free. Again, it's not my case as you can see from my bug reports where I hope that it's clear that I invest a lot of time debugging and trying to understand how Realurl works, even with my limitations. Keep in mind that I'm not the creator of Realurl and so it's harder for me to get the logic and follow the progression of the extension. Some things that for you, the creator, are obvious, for one external can be hard to understand.
But if you say that I can find the answer of my issue in the documentation the I trust you and I'll read it again.

By the way, I still think that could be useful to have a hook inside Realurl that allow a developer to use what Realurl already "discovered" decoding the speaking url like the page uid and other request variables.

**Comment by dmitryd** [comment]
Ok, you won. I will give you straight solution to save time for us both.

https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#postvarsets

> Notice the _DEFAULT keyword at the second line of the example above. It tells RealURL that postVarSets under it can be used for any page. If you want to limit postVarSets to specific pages, use exact page ids.

“Just do it” © Nike.

**Comment by webian** [comment]
Thanks but I don't think that this can solve this issue.

Maybe it's not clear but I have a tree of pages that act as categories.
Simplifying:
```
Page-10
Page-20
  Page-21
  Page-22
  ...
  Page-x
Page-30
...
Page-150
  Page-151
  ...
  Page-y
...
Page-z
```
Clients move a product from Page-22 to Page-151
Old url `/path/to/page-22/prod/product-name/`
New url `/path/to/page-151/prod/product-name/`

It's not feasible to build all those configurations (one for each page id).

**Comment by dmitryd** [comment]
Than you are on your own with this problem. No other help from realurl is possible because client's record movements are not in scope of realurl.

**Comment by webian** [comment]
Actually the solution of this issue is to use `userFunc` in `postVarSets` and finally check if pid of the product is equal or not to the id that decodePath() returns.

**Comment by dmitryd** [comment]
And you call userFunc easier than configuration? :)

**Comment by webian** [comment]
As I already said I think that "It's not feasible to build all those configurations (one for each page id)".
Or I didn't understand what you mean, in this case please give me an example if possible.

**Comment by dmitryd** [comment]
I suggest to ask for help in Slack user group or mailing lists.

**Comment by webian** [comment]
I already did it, no answer but luckily I found solution using userFunc.
I was just curious to see how to solve this issue only with config.
But nvm, thank you anyway :)
