### ISSUE TITLE
Page with Override Whole path segment leads to infinite redirect

### ISSUE THREAD

**Issue by hannesbochmann** [dmitryd/typo3-realurl#259]
I have the following page tree for 1 domain:

|- Customer ABC (uid 1, normal page)
|-- Domain ABC (uid 2, set as root page, contains correct domains)
|--- "Shortcut to first subpage" (uid 3, exclude from speaking URL)
|---- First Subpage (uid 4, override whole page path with "Shortcut to first subpage")

In the realconf configuration rootpage_id is set to 2 (integer).

A link to the pages with uid 3 and 4 would be the same  -> /shortcut-to-first-subpage
So realurl should determine that the link /shortcut-to-first-subpage is always decoded to page 4 because of the override feature. But instead it determins page 3 as correct. This leads to a infinite redirect as TYPO3 determins that page 3 is a shortcut and should be redirected to page 4 but realurl determins for that URL that the page must be 3 instead 4 which than again triggers the redirect of TYPO3 and so on.

This is because the configured rootpage_id is 2 but UrlDecoder::searchForPathOverrideInPages checks only if the first page in the rootline of page 4 is the same as the configured root page, which it's not in this case. In realurl 1.x it was checked if the rootpage_id was inside the rootline and not if the first page in the rootline matches the configured rootpage_id.

So I'm wondering if this is a bug or intended behaviour. Because this would mean that a root page of a domain always has to be on the root level in the page tree and not like in my scenario.

P.S. As soon as I set the configured rootpage_id to 1 the redirect is gone and the correct page is displayed but of course the URL is not the same as it contains now the segment for page 2. I could get around this by setting the page 2 to be excluded from the url but I'm still wondering if that's correct.

**Comment by dmitryd** [comment]
Item 3 [here](https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#limitations). I believe you hit the limitation, which is described in the documentation.

In general, try to be less clever when you use realurl. It is not made for extra complex page trees. The simpler you do, the better result you will have.

**Comment by hannesbochmann** [comment]
I understand that but for reasons of backwards compatibility to realrul 1.x I think it would be good to check the rootpage at that point like before. Meaning don't check if the page with the override set has the same rootpage as the configured rootpage_id but if rootpage_id exists somewhere in the rootline of the page with the overrides. I think the performance shouldn't be affected.

I provided a pull request for that and would be glad if you could merge that.

**Comment by dmitryd** [comment]
There is one little issue called "it must in all other cases too". Please, make sure it does. I do not want to break realurl due to this rarely used configuration.

**Comment by hannesbochmann** [comment]
I don't know how this could break other cases. Everything that was true by this check before is still true. So, I'm sure this bugfix is no problem and won't break anything.

**Comment by hannesbochmann** [comment]
Hi, any progress on this topic?

**Comment by dmitryd** [comment]
Not checked yet.

Question: does your page with uid=2 have "Use as Root Page" flag set? It has to be set.

**Comment by hannesbochmann** [comment]
Yes, the flag is set.

**Comment by dmitryd** [comment]
I quickly looked through the change. It makes sense. However I am not sure that this will definitely solve the issue because you still hit that limitation I mentioned before.

**Comment by hannesbochmann** [comment]
For the situation described it will solve the issue. The limitation you mentioned seems not to be a problem. I tested it on a site with much traffic for almost 2 months without any additional problems.

**Comment by hannesbochmann** [comment]
ping

**Comment by dmitryd** [comment]
I do not have any free time for realurl currently.

**Comment by darthnorman** [comment]
ping
I ran into that same problem and would like to see it resolved, the fix seems to be working

**Comment by dmitryd** [comment]
Well, I will resolve when I have time. This is a free project, so there are no guarantees or obligations of any kind.

**Comment by hannesbochmann** [comment]
Great work, thanks.
