### ISSUE TITLE
Documentation: wrong config cHashExcludedParameters

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#265]
Wiki page https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Developers states:

> // TYPO3 7.x
> $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['cHashExcludedParameters'] .= ',tx_myrandomnews[topic]';

I'm on TYPO3 7.6.11 and it is:
$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters']

**Comment by webian** [comment]
I add a better analysis...
default config is:
$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters'] => 'L, pk_campaign, pk_kwd, utm_source, utm_medium, utm_campaign, utm_term, utm_content'
can be changed in LocalConfiguration.php

To render a page TYPO3 first calls method setCacheHashOptions() and populate 
$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'] with an array of comma exploded from the string in $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters']

Then, eventually, this array $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'] can be changed in an ext_localconf.php

**Comment by webian** [comment]
The example on the wiki page should be:
$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'][] = 'tx_myrandomnews[topic]';

**Comment by dmitryd** [comment]
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Core/Bootstrap.php#L577-L582

Still thinking the same?

**Comment by webian** [comment]
Yes.

There's no 
`$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['cHashExcludedParameters']`
there is
`$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters']`

but also you can't use
`$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters']`
in a ext_localconf.php because ext_localconf.php is processed after setCacheHashOptions()

So the right way is to edit the array that setCacheHashOptions() already created with:
`$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'][] = 'tx_myrandomnews[topic]';`
in ext_localconf.php

**Comment by droomdre** [comment]
I also think:

> // TYPO3 7.x
> $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['cHashExcludedParameters'] .= ',tx_myrandomnews[topic]';

is definitively wrong

**Comment by dmitryd** [comment]
Documentation is updated.

**Comment by stoppeye** [comment]
I used the configuration for 6.x (according to the wiki page) in a TYPO3 6.2.29 installation and it didn't work (i.e. different cHash for URLs, where only the excluded param had changed).
But it did work, when I used the 7.x style of configuration. I don't know about older 6.x versions, but at least in the newer ones the configuration on the wiki page for 6.x doesn't work (anymore).
