### ISSUE TITLE
_DOMAINS L parameter overwrites parameter from PreVars

### ISSUE THREAD

**Issue by NightflyerHH** [dmitryd/typo3-realurl#266]
I hava a problem with the multi language and multi domain settings.

We use a multi language domain configuration.

domain.de -> DE Content
domain.de/en/ -> EN Content
domain.cn -> CN Content

But if we use the _DOMAINS Settings, this will overwrite the PreVars that we need for the first domain with multiple languages.

We tried to find the position in realurl ext and found the following in Classes/Decoder/UrlDecoder.php

`	protected function mergeWithExistingGetVars(array &$requestVariables) {
		if (count($_GET) > 0) {
			$flatGetArray = $this->parseQueryStringParameters($this->createQueryStringFromParameters(GeneralUtility::_GET()));
			ArrayUtility::mergeRecursiveWithOverrule($requestVariables, $flatGetArray);
		}
	}`

It it right that _DOMAINS Settings will overwrite PreVars? We would prefer to set another language with the URL.

**Comment by dmitryd** [comment]
It is not possible to mix both _DOMAINS and language preVar. Either one, or another.

For further help, please, check for available help channels here: https://github.com/dmitryd/typo3-realurl/wiki/Getting-help
