### ISSUE TITLE
2.0.15 and News 5.1.0, got every time the same News

### ISSUE THREAD

**Issue by Xippo** [dmitryd/typo3-realurl#268]
When im not logged in the BE i got every time the same news entry form cache but the url change correctly. With version 2.0.14 in work like charm :). Unfortunately i dont have the time to fix the bug my self but i think it has somthing to do with the new Version.  

The Typo3 Version was 7.6.9 maybe on the 7.6.11 it works fine.

**Comment by vertexvaar** [comment]
Experiencing the same issue here.
TYPO3 7.6.11, RealUrl 2.0.15, News 4.0.0 (not able to update because reasons)
When i have a valid BE session the News detail view works.
RealUrl Configuration is taken from the Wiki (it's exactly the same)

**Comment by vertexvaar** [comment]
@Xippo Workaround: Edit your News detail page, go to the "Behaviour" tab and check the "Cache: disable" checkbox.

**Comment by DrillSergeant** [comment]
I experience the same issue. Maybe it appears only with PHP 7?
I assume that because we have 2 cases of the same extension (TYPO3 7.6.11, news 4.2.1 and realUrl 2.0.15) one is running on PHP 5.5.9 (works fine) and PHP 7.0.9 (same issue: always same news is shown in detail-page, only working when change the page to be non-cachable).

**Comment by vertexvaar** [comment]
@DrillSergeant Did you ensure you are not logged into the Backend on both? Do you have mod_php, PHP-FPM or something else?
I detected the problem with PHP-FPM 5.5.9 on Ubuntu 14.04.5

**Comment by DrillSergeant** [comment]
It happens when logged into backend or not (does not matter here). We use PHP-FPM on Ubuntu 16.04.2

**Comment by DrillSergeant** [comment]
Ok, my case is not cause by realUrl, I deinstalled it and the problem still appears with not-mapped get-vars. Maybe the last security-release of TYPO3 causes this.

**Comment by toxsick** [comment]
maybe related to #263 ? For us it worked to change these lines:

https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Utility.php#L120

regards
Hannes

**Comment by dmitryd** [comment]
Not a realurl issue. Please, check existing issues, this was answered already.
