### ISSUE TITLE
news pagination breaks after page 9

### ISSUE THREAD

**Issue by ilomedia** [dmitryd/typo3-realurl#269]
Hi,

TYPO3 6.2.27
realurl 2.0.15
news  3.2.6 with advanced realurl configuration taken from example

pagination works like a charm until page 9, going to page/10.html displays page 1 without redirect > duplicate content.
I think it is realurl related since it works if i use the direct URL : ?id=12&tx_news_pi1[@widget_0][currentPage]=10
cHash is missing but page 10 is displayed if i force-clear the cache.

Do you need more feedback?

**Comment by dmitryd** [comment]
No. This was answered already in other bug reports. You are missing cHash. Not a realurl issue. Clear page cache and realurl *cache tables.

**Comment by ilomedia** [comment]
If only it was that simple, it isn't i'm afraid.

I have pages with a cHash in the tx_realurl_cache but pages are randomly recorded without cHash.
As for my last test with all cache cleared, everything worked until page 10 but it failed at page 11.

Of course i'm not logged to the BE

seems like a random bug and it pretty hard to find out where it comes from

**Comment by dmitryd** [comment]
Wait until 2.1.0 or downgrade to 2.0.14.
