### ISSUE TITLE
Core: Error handler (FE): PHP Warning: strpos(): Empty needle in typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php line 1057

### ISSUE THREAD

**Issue by abma** [dmitryd/typo3-realurl#270]
i have redirect_goodUpperDir enabled and when accessing a bad url i get an endless redirect and in the syslog the above error is shown.

can be reproduced with:

/de/someurl//someur/

/de/someurl/ must be a valid url.

**Comment by abma** [comment]
as workarround i added a redirect which removes double slashes from an url:

RewriteRule "^/(.+)\/\/(.+)$"  "$1"  [R=301]

**Comment by dmitryd** [comment]
This would be nearly impossible to solve if there are more than one empty segment. Your best way would be to avoid such situations. Do your configuration in a way that does not create empty segments.
