### ISSUE TITLE
useUniqueCache_conf properties not utilized

### ISSUE THREAD

**Issue by innologi** [dmitryd/typo3-realurl#271]
Despite its properties **strtolower** and **spaceCharacter** being described in the configuration reference as part of a [lookUpTable configuration](https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#lookuptable), as well as part of several examples within the same reference, these properties are never used for their documented purpose in RealURL v2.0.15.

The only place they are being used, is when passed on to the undocumented **encodeTitle_userProc** property of useUniqueCache_conf.

**Comment by dmitryd** [comment]
Fixed in the documentation, thanks.
