### ISSUE TITLE
 Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function linkData() on null

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#273]
With a PostVarSet config like this:
````
'postVarSets' => array (
    '_DEFAULT' => array (
        'postvarkey' => array (
            0 => array (
                'GETvar' => 'extension[var]',
                'lookUpTable' => array (
                    'table' => 'ext_table',
                    'id_field' => 'uid',
                    'alias_field' => 'title',
                    'addWhereClause' => ' AND deleted !=1 AND hidden !=1',
                    'useUniqueCache' => 1,
                    'useUniqueCache_conf' => array (
                        'strtolower' => 1,
                        'spaceCharacter' => '-',
                    ),
                    'enable404forInvalidAlias' => 1,
                ),
            ),
        ),
    ),
),
````

And if:

1. the set GETvar is in requireCacheHashPresenceParameters, like: `$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['requireCacheHashPresenceParameters'][] = 'extension[var]';`
2. Realurl cache empty
3. the url http://domain.ext/page/path/postvarkey/record-title/ is browsed before http://domain.ext/page/path/

Error:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function linkData() on null | Error thrown in file /typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php in line 6706. Requested URL: http://domain.ext/page/path/postvarkey/record-title/`

(There are also many `PHP Warning: Illegal string offset` before the error)

What happens:

1. Realurl can't find a cache entry for http://domain.ext/page/path/postvarkey/record-title/
2. It then creates a cache entry without cHash
3. It replaces the pageNotFoundHandler with its own
4. Since `TYPO3_CONF_VARS['FE']['cacheHash']['requireCacheHashPresenceParameters'][] = 'extension[var]'`, TYPO3 calls `reqCHash()`
5. And since `TYPO3_CONF_VARS['FE']['pageNotFoundOnCHashError']` is true by default, Realurl pageNotFoundHandler() is called
6. this method calls rebuildUrlFromTheCreatedCacheEntry() that calls typoLink_URL() that throws the error

**Comment by dmitryd** [comment]
Thank you. Just wondering, why do you set something to `$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['requireCacheHashPresenceParameters'][]`? It is not for regular plugins. Regular plugins should call `reqCHash()`.
