### ISSUE TITLE
Update script in EM - SQL Errors

### ISSUE THREAD

**Issue by GuillaumeG22** [dmitryd/typo3-realurl#274]
### First error : 
`   caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::sql_query' (53 chars)
   ERROR => 'You have an error in your SQL syntax; check the manual that corresponds to y
      our MySQL server version for the right syntax to use near 'TABLEtx_realurl_p
      athcache' at line 1' (171 chars)
   lastBuiltQuery => 'DROP TABLEtx_realurl_pathcache' (30 chars)`

Missing space in the SQL query

### Second error
`caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::sql_query' (53 chars)
   ERROR => 'Column count doesn't match value count at row 1' (47 chars)
   lastBuiltQuery => 'INSERT INTO tx_realurl_urldata SELECT * FROM tx_realurl_urlcache' (64 chars)`

I use MySQL 5.5. This is related to the problem?

### Third error

`caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::sql_query' (53 chars)
   ERROR => 'You have an error in your SQL syntax; check the manual that corresponds to y
      our MySQL server version for the right syntax to use near 'TABLEtx_realurl_u
      rlcache' at line 1' (170 chars)
   lastBuiltQuery => 'DROP TABLEtx_realurl_urlcache' (29 chars)`

Also missing space.

**Comment by dmitryd** [comment]
I will release 2.1.1 asap.

**Comment by GuillaumeG22** [comment]
The second error is not fix !

**Comment by dmitryd** [comment]
This means you did not do database update before. Only name was changed, not table definition.

**Comment by dmitryd** [comment]
Let me see if I can do it more universal...
