### ISSUE TITLE
rebuildUrlFromTheCreatedCacheEntry() doesn't return speaking url

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#276]
Related to #273, method `rebuildUrlFromTheCreatedCacheEntry()` doesn't return speaking url but the url with the link vars.

This happens because `$this->tsfe->config` is an empty string and so `isRealURLEnabled()` returns false and then `canEncoderExecute()` returns false aborting the encode process.
Also many `PHP Warning: Illegal string offset` are logged still because `$this->tsfe->config=''`,

**Comment by dmitryd** [comment]
Yes, it seems that This whole thing should not be executed if TYPO3 is not initialised completely.

**Comment by AndreasA** [comment]
I could be wrong but due to this handler being executed upon reqChash TSFE will never be fully initialized at this point as both initTemplate and getConfigArray are executed after makeCacheHash

Shouldn't it be enough to just also execute: $this->tsfe->getConfigArray() ?

**Comment by dmitryd** [comment]
> I could be wrong but due to this handler being executed upon reqChash TSFE will never be fully initialized at this point as both initTemplate and getConfigArray are executed after makeCacheHash

This is because the handler expects `reqCHash()` to be called from a cached plugin action, not from `makeCashHash()`.

> Shouldn't it be enough to just also execute: $this->tsfe->getConfigArray() ?

We never know what we may beed to call for every supported TYPO3 version. I prefer the code to have as little dependencies on a particular TYPO3 version. For example, earlier we had to call also `includeTCA`, than it was gone and the code had to be adjusted for various TYPO3 versions. This is what I want to avoid here.

**Comment by AndreasA** [comment]
Ah. OK. 
Fair enough. In that case you are correct, not doing anything as long as TSFE is not fully initialized is the correct way to go.

**Comment by dmitryd** [comment]
There is a PR to add this for Extbase plugins in the core. http://review.typo3.org/#/c/49976/

**Comment by AndreasA** [comment]
Ah. Nice. I didn't know there was a PR for that.
I really hope it also makes it into 7.6 because without it you can have pages that display the wrong content because of missing cHash (better to have a page not found error instead).
