### ISSUE TITLE
Case sensitive URLs throw 404 error page

### ISSUE THREAD

**Issue by heidenreichC** [dmitryd/typo3-realurl#278]
Only with active TYPO3 backend login I get an 404 page while calling an url like "www.example.com/Big-Letters/are-bad.html". Same URL works without active backend login.

I am using realurl 2.0.15 with TYPO3 6.2.27. This issue came up after upgrading from TYPO3 6.2.26 to 6.2.27 and realurl 1.13.x to 2.0.15 at the same time.

**Comment by droomdre** [comment]
I've got some Issues too when being logged. With the last version 2.1.x problems have been solved

**Comment by dmitryd** [comment]
Closing because now realurl always works like there is no BE login.
