### ISSUE TITLE
[BUG] 301 (permanent redirect) should not be used on missing cHash error

### ISSUE THREAD

**Issue by AndreasA** [dmitryd/typo3-realurl#279]
The redirect due to cHash error should not be HTTP Status 301 as 301 is reserved for permanent redirects like if I move a page from somewhere in the pagetree to somewhere else.
That way google knows to index the new URL.

But in our case it is more a temporary redirect as the next time, it should work fine.
Also I am not sure if using anything other than "Moved Permanently" is 100% correct when using the 301 redirect header.

**Comment by dmitryd** [comment]
> The redirect due to cHash error should not be HTTP Status 301 as 301 is reserved for permanent redirects

It does not make any difference in this case.

> Also I am not sure if using anything other than "Moved Permanently" is 100% correct when using the 301 redirect header.

https://tools.ietf.org/html/rfc2616#section-6.1

> The Status-Code is intended for use by automata and the Reason-Phrase is intended for the human user. The client is not required to examine or display the Reason-Phrase.

**Comment by AndreasA** [comment]
> It does not make any difference in this case.

Because it redirects to the same page? Otherwise, using permanent redirect could result in an endless loop as browser caches permanent redirects.
If so, I guess the ticket can be closed.

**Comment by dmitryd** [comment]
> Otherwise, using permanent redirect could result in an endless loop as browser caches permanent redirects.

Only on successful fetch.

**Comment by dmitryd** [comment]
Btw, redirect line is customised for troubleshooting. Sometimes redirects happen and it is unclear why. People can use `curl -I http://domain.tld/redirecting/url/` to see the response and understand if it is realurl or not.
