### ISSUE TITLE
Fix a syntax error in Resources/Private/Language/locallang.xlf

### ISSUE THREAD

**Issue by Chrissitopher** [dmitryd/typo3-realurl#281]
In file Resources/Private/Language/locallang.xlf, the language label "module.configuration.intro" has the square brackets placed incorrectly. With the brackets at the wrong place, on the translation server, the closing bracket is showing up as first sign of the text to be translated:

 ``]This module will show``

**Comment by dmitryd** [comment]
Thank you. It will be fixed in 2.1.2.
