### ISSUE TITLE
Blank EM after upgrading 2.1.1 to 2.1.2 // TYPO3 6.2.27

### ISSUE THREAD

**Issue by nico-w** [dmitryd/typo3-realurl#283]
I upgraded realurl from 2.1.1 to 2.1.2 on a TYPO3 6.2.27 system via extension manager - after that, my extension manager is blank, all other pages in Backend and Frontend work.

`[Mon Sep 26 09:57:04 2016] [error] [client x.x.x.x] PHP Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /srv/www/XX/XX/web/typo3conf/ext/realurl/class.ext_update.php on line 169`

Sounds like I have to upgrade my PHP 5.4 or is it a bug?

**Comment by mbrodala** [comment]
Additional info: this is due to the `::class` usage introduced with [a change](https://github.com/dmitryd/typo3-realurl/commit/aecb42339f21e2921791772d72746852b8f3a732) between 2.1.1 and 2.1.2. Since 2.x still supports PHP 5.4, this should be fixed.

**Comment by dmitryd** [comment]
Thank you. I have 5.4 currently, so I develop on 5.6. Easy to forget that this is missing in older versions...
