### ISSUE TITLE
Version 2.1.2 - makeCacheHash on rootPage with cHashIncludePageId fails verification

### ISSUE THREAD

**Issue by AndreasA** [dmitryd/typo3-realurl#284]
Due to the check isSpeakingUrl the UrlDecoder does not detect a URL that looks like this:
"http://www.example.com/?param1=foo&cHash=XXXX"
as speaking URL which results in the $_GET['id'] parameter being missing which results in an exception in the CacheHashCalculator as it requires the 'id' parameter.

**Comment by dmitryd** [comment]
This is not a speaking URL. Realurl does not process such URLs. Speaking URL contains at least one segment.

Inside realurl `CacheHashCalculator` is called only from the `isChashMissing` method, which is called from `runDecoding`, which is called only if `isSpeakingUrl` return `true`. So how can you get the exception in realurl if `isSpeakingUrl` returns false?

Do you have a stack trace? It seems that you just trying to pass a wrong cHash and correctly get a 404 due to `pageNotFoundOnCHashError`.

**Comment by AndreasA** [comment]
OK. I will try to improve my explanation:
1.) It doesn't look like a speaking URL
2.) It doesn't have an ID parameter
3.) The URL is on the rootpage of the site

So without realurl the URL would look like:
http://www.example.com/?id=1&param1=foo&cHash=XXXX

With realurl it looks like:
http://www.example.com/?param1=foo&cHash=XXXX

So we do not have "id" in the GET paramters.

Now due to cHashIncludePageId = true
\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::makeCacheHash
calls the \TYPO3\CMS\Frontend\Page\CacheHashCalculator::getRelevantParameters 
with GeneralUtility::_GET()

However, the $_GET array doesn't include the Page-ID as without realurl the URL would include the 'id' parameter.

Which then results in the exception:
> ID parameter needs to be passed for the cHash calculation! As a temporary not recommended workaround, you can set $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] to false to avoid this error.

**Comment by dmitryd** [comment]
Totally wrong. Uninstall realurl and call the same URL. See the same exception. Not related to realurl at all.

When you come to http://www.example.com/, do you have the `id` parameter? No. TYPO3 works fine without that parameter, it means "show the root page of the site". Now, if you add a query string parameter and a cHash, you get a 404 from the core, not from realurl. So how is it related to realurl?

**Comment by dmitryd** [comment]
You actually need to report it as a regression to the TYPO3 core because it does not work without realurl too.

Next time, try doing various tests before posting a new bug.

**Comment by AndreasA** [comment]
> TYPO3 works fine without that parameter, it means "show the root page of the site". Now, if you add a query string parameter and a cHash, you get a 404 from the core, not from realurl. So how is it related to realurl?

Yes BUT afterwards TYPO3 **always appends the id** to the URL, even for the root page.
Which is why without realurl the URL looks like this:
http://www.example.com/?**id=1**&param1=foo&cHash=XXXX

**Comment by dmitryd** [comment]
I have nothing more to say. I already showed you that the exception happens in the core even if there is no realurl. It should be solved there. Realurl cannot do anything about it.

There is no point in continuing this discussion further.

**Comment by AndreasA** [comment]
OK. Not that I disagree it is also a core bug but I think it is also a realurl bug as realurl removes the id.
On the other hand if the core bug is fixed, this will never be an issue.
So I concede your point.

**Comment by dmitryd** [comment]
https://review.typo3.org/#/c/50030/

**Comment by AndreasA** [comment]
Thanks

**Comment by dmitryd** [comment]
That core bug is fixed now and integrated to 6.2, 7.6 and 8.x

**Comment by AndreasA** [comment]
https://review.typo3.org/#/c/50030/
hasn't been merged yet. 
However, your other bugfix in regards to cHash calculation (empty parameter name) has been merged.
