### ISSUE TITLE
Feature: Add button to flush complete realurl cache

### ISSUE THREAD

**Issue by liayn** [dmitryd/typo3-realurl#285]

**Comment by dmitryd** [comment]
It is specially removed to prevent such actions. They are considered dangerous and harmful since 2.0.15.

**Comment by liayn** [comment]
Well, in general I agree, but after fixing the realurl config, clearing the cache  might be necessary. It's just rather cumbersome to access the DB directly. A Button in the module for admins only would be convenient. (also during development)

**Comment by dmitryd** [comment]
Makes sense, yes. I need to come up with something that will prevent people from hitting it from time to time just because it is there.

**Comment by liayn** [comment]
Maybe a Sony-Style yes/no question, three times with alternating button position. :-)

**Comment by dmitryd** [comment]
"Type the name of the TYPO3 founder with all proper national letters"...

**Comment by dmitryd** [comment]
Done here: https://github.com/dmitryd/typo3-realurl/commit/b30c2cd91f5d46378fadab3ea449d6d4c1bb2ee5
