### ISSUE TITLE
View of news sometimes produces a 404

### ISSUE THREAD

**Issue by droomdre** [dmitryd/typo3-realurl#286]
Typo3 7.6.11
Realurl 2.1.4
news 4.3.0

Pages generated trough following config:

> 'postVarSets' => array (
>             '_DEFAULT' => array (
>                 'page' => array(
>                     0 => array(
>                       'GETvar' => 'tx_news_pi1[@widget_0][currentPage]',//tx_news  
>                     ),
>                 ),
>                 'seite' => array(
>                     0 => array(
>                       'GETvar' => 'tx_news_pi1[currentPage]',//tx_news  
>                     ),
>                 ),
> ....

On some news categories i can paginate and on some i cannot. Hitting page 2 sometimes opens page 1 and sometimes i got a 404 or a blank page

**Comment by dmitryd** [comment]
Cannot help you with that. This is definitely a cHash-related error but now realurl does not manipulate cHash in anyway, so there is nothing that I can do. I can only suggest to remove all records in `tx_realurl_urldata` and see if it helps. If not, than something is not creating links correctly on your web site (missing cHash).

**Comment by droomdre** [comment]
My bad. It is with Realurl 1.13.6.
I need this version coz the last version Realurl 2.1.4 has some compatible issue with other extensions i'm using.

**Comment by runner78** [comment]
I have the same problem.

Typo3 7.6.11
Realurl: 2.1.4
news: 5.2.0

has tx_realurl_urldata no entry for a url, return  the path as news id:
![realurl-bug](https://cloud.githubusercontent.com/assets/7888460/18946955/6b27d5d4-8631-11e6-93db-4432803febbb.png)

config:
![config](https://cloud.githubusercontent.com/assets/7888460/18947045/c609ba12-8631-11e6-9a73-a2c0a56301cc.png)

**Comment by dmitryd** [comment]
> has tx_realurl_urldata no entry for a url, return the path as news id:

This is why the problem happens. Clear FE cache. Page content will regenerate and produce links in `tx_relurl_urldata`. Do not clear that table ever.

**Comment by runner78** [comment]
The problem is, i have ported a old page with 12000+ articles to Typo3 and the news extension. and direct links to article (and another detail-pages, not only news) ending to a 404 error.

**Comment by droomdre** [comment]
I've found out that the links are generated differently. 
With realurl 1.13.6, i have the following:
http://domain.tld/career/theme//page/2.html
and with realurl 2.1.4 : http://domain.tld/career/theme/chirurgy/page/2.html

As you can see the category "chirugy" is missing in the link generated trough 1.13.6.

My config:
> fixedPostVars' => array(
> 'newsCategoryConfiguration' => array(  //tx_news   	
>                         array(
>                                 'GETvar' => 'tx_news_pi1[overwriteDemand][categories]',
>                                 'lookUpTable' => array(
>                                         'table' => 'sys_category',
>                                         'id_field' => 'uid',
>                                         'alias_field' => 'title',
>                                         'addWhereClause' => ' AND NOT deleted',
>                                         'useUniqueCache' => 1,
>                                         'useUniqueCache_conf' => array(
>                                                 'strtolower' => 1,
>                                                 'spaceCharacter' => '-'
>                                         )
>                                 )
>                         )
>                 ),
> ...
> ),
>         'postVarSets' => array (
>             '_DEFAULT' => array (
>                 'page' => array(
>                     0 => array(
>                     	'GETvar' => 'tx_news_pi1[@widget_0][currentPage]',//tx_news   	
>                     ),
>                 ),
> ....
> )

**Comment by dmitryd** [comment]
Realurl 1.x is not supported any more.

**Comment by runner78** [comment]
UrlDecoder->convertAliasToId() generate a SQL query like this: ```
SELECT uid 
FROM tx_news_domain_model_news WHERE CONCAT(title, '-', uid)='news-title-12809' AND NOT deleted 
LIMIT 1
```
but this query ignores the spaceCharacter in the settings and other special characters.

**Comment by droomdre** [comment]
Ok i have a workaround for my problem. It took me time but i've figured out why i got this error.
Normally this issue still won't happen in normal case but i have unfortunately a special news configuration. All with these kind of configuration will be concerned.

>     |-Page 1
>     |- career
>     |-|-medicine(10) (news list - Exclude from speaking url)
>     |-|-|-Article(23) (news detail - has 'medicine' as alternative title and this is uses as alias_field in my realurl conf)

Now tx_realurl_pathdata has "career/medicine" twice:
career/medicine with page id 10
career/medicine with page id 23

Now when the page cache has been cleared and realurl try to generate the page career/medicine/top-10-uni.html again, the method doDecoding() look for path "career/medicine" in tx_realurl_pathdata and take the first one with page id 10. Since he cannot generate a detail view page with this, it ends up with an error.

My workaround was to rename my list page to have a different name than my detail page. All people who did such a config (detail and list view name the same) would have that problem.

My tip: look at your table tx_realurl_pathdata if the segment before your news is there twice. Realurl can't handle this actually

**Comment by dmitryd** [comment]
Well, this is expected than. What you do is called "same page title on the same logical level" and it is [described in the docs](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#page-titles) that realurl does not work with such configurations. So it is not a bug.
