### ISSUE TITLE
Adding parameter for Google analytics breaks the news detail view

### ISSUE THREAD

**Issue by droomdre** [dmitryd/typo3-realurl#287]
Before with realurl 1.13.6, i could have links like http://domain.tld/career/mycategory/mynews.html?utm_source=newsletter&utm_medium=E-Mail for my newsletter
I've added utm_source and utm_medium to the [FE][cHashExcludedParameters] in install-tool.

Now with 2.1.4 clicking on such links opens the first news in the category "mycategory" and not the news i want.

**Comment by dmitryd** [comment]
Please, see "Getting help" on the wiki. This place is for bugs only.

**Comment by droomdre** [comment]
I tought this is a bug since it only happens with realurl 2.1.4 (typo3 7.6.11, news 4.3.0)
I have no problem on the other installation running with the 1.13.6.

**Comment by jousch** [comment]
@droomdre I think https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Developers#working-with-chash-correctly-in-your-extension is where you get infos about excluding parameters from chash calculation.

**Comment by droomdre** [comment]
Thank you Jousch. actually in my Typo3 7.6.11 Installation, i just have tx_news 4.3.0 with realurl 2.1.4 installed. I was wondering why this doesnt work anymore. I did no special configuration. It's not with my own extension that this does not work. I think the news Extension does handle the chash pretty well actually.

**Comment by droomdre** [comment]
So i start to analyse this and i found out the following:
i have a news detail page at http://domain.tld/career/medicine/news/masterplan-pj/?tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Baction%5D=detail&cHash=32e69d8318d22bd361c72b7d076e6b8c
To render the page, realurl call runDecoding() and this take the url from cache with the method getFromUrlCache(). No problem.
Now if i have the google param added and my url looks like http://domain.tld/career/medicine/news/masterplan-pj/?tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Baction%5D=detail&cHash=32e69d8318d22bd361c72b7d076e6b8c&utm_source=test
realurl can't find this url in cache and so call the function doDecoding(). doDecoding() take the path "career/medicine/news/masterplan-pj" and try to find a cache in tx_realurl_pathdata. Since this is not there, he removes the last parameter until he find an entry for "career/medicine". That's why i got the listing view page of my category.
I tought realurl should have remove the parameter "utm_source=test" and so i would have get the same page as without that parameter.

**Comment by droomdre** [comment]
Ok i have a workaround for my problem. It took me time but i've figured out why i got this error.
Normally this issue still won't happen in normal case but i have unfortunately a special news configuration. All with these kind of configuration will be concerned.

> |-Page 1
> |- career
> |-|-medicine(10) (news list - Exclude from speaking url)
> |-|-|-Article(23) (news detail - has 'medicine' as alternative title and this is uses as alias_field in my realurl conf)

Now tx_realurl_pathdata has "career/medicine" twice:
career/medicine with page id 10
career/medicine with page id 23

Now when the page cache has been cleared and realurl try to generate the page career/medicine/top-10-uni.html again, the method doDecoding() look for path "career/medicine" in tx_realurl_pathdata and take the first one with page id 10. Since he cannot generate a detail view page with this, it ends up with an error.

My workaround was to rename my list page to have a different name than my detail page. All people who did such a config (detail and list view name the same) would have that problem.

**Comment by dmitryd** [comment]
Please, read about "limitations" on the wiki about same name on the same logical level. Your page setup is what you can**not** do with realurl.

**Comment by droomdre** [comment]
I know the limitation. The page medicine has "Exclude from speaking url", so in my understanding this should not figured in tx_realurl_pathdata since this will never be used to make a path.
The same configuration used to work with 1.13.6. Only since i've updated to 2.1.4, i've started having issues.

**Comment by dmitryd** [comment]
> The page medicine has "Exclude from speaking url", so in my understanding this should not figured in tx_realurl_pathdata since this will never be used to make a path.

What URL will your news list page have than? :)

**Comment by dmitryd** [comment]
That configuration did not work in 1.13.6. It never worked because "exclude" flag is always ignored for the target page. It is like that since this feature was added.

**Comment by droomdre** [comment]
I changed the page titles as u said:
> |-Page 1
> |- career
> |-|-medicine-all(10) (news list - Exclude from speaking url)
> |-|-|-medicine(23) (news detail) 

now i have 2 differents paths in tx_realurl_pathdata (career/medicine-all and career/medicine). Decoding works fine but i still have issues when using that utm_source Parameter or any kind of parameters.
If my url looks like http://domain.tld/career/medicine/top-unis.html?tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&cHash=9ac1c6a70f23c5b191548b9d070cc467&utm_source=test then i have the expected behaviour.  Adding "utm_source" sends me to the requested page and adding "utm_sourrrrce" throws a 404.
If i add the following to my configuration

> array(
>                                 'GETvar' => 'tx_news_pi1[action]',
>                                 'valueMap' => array(
>                                         'detail' => '',
>                                 ),
>                                 'noMatch' => 'bypass'
>                         ),
>                         array(
>                                 'GETvar' => 'tx_news_pi1[controller]',
>                                 'valueMap' => array(
>                                         'News' => '',
>                                 ),
>                                 'noMatch' => 'bypass'
>                         ), 
> 

then my url now looks like http://domain.tld/career/medicine/top-unis.html?utm_source=test. "utm_sourrrrce" outputs the first called news detail  on the category "medicine". (wrong behaviour) May be coz the chash is missing?

**Comment by dtondera** [comment]
Hi, you are right. The Problem is, the missing chash if a action is defined as cached action. A quickfix is to append &no_cache which slows down the site but after all shows the correct content.
