### ISSUE TITLE
Is their any possibility to find out where URL is cached from?

### ISSUE THREAD

**Issue by vaxul** [dmitryd/typo3-realurl#288]
Hi @dmitryd,

not really a problem of realurl itself. But how can I find out where the cached "URL Data" were from?

I have the situation that for specific single speaking URLs, two original URLs appears after a while. At first the correct URL with cHash is cached. After a while, god know where from, the same parameters without cHash get cached.

I looked for every code snippet, where an URL is generated to specific page with the same Extbase-Model and -Action.

The setup:
TYPO3 7.6.11
realurl v2.1.4
Extbase-Model with Fluid-Link-Viewhelper
`<f:link.action pageUid="{settings.targetPage}" action="show" arguments="{aModel: aModel}">{aModel.title}</f:link.action>`

I have no clue, why the 2nd URL without cHash appears.

Do you have an idea?

Best regards

vaxul

**Comment by dmitryd** [comment]
No, it is not possible.

**Comment by dmitryd** [comment]
Do you use indexed search, by the way? I had a case last week when it caused a couple of issues related to cHash.

**Comment by vaxul** [comment]
Hi, no I don't. 

First I thought it comes from my custom sitemap generator for the extbase objects with EXT:dd_googlesitemap. Indeed their was no cHash configured and the url parameter order was a bit different. So I re-ordered the parameters for controller and action and added to option useCacheHash for the cObj->typolink configuration.

With realurl disabled the generated urls within the sitemap are exact the same as the urls within the extbase object list-action.

But I still have the problem like described in the initial post.
