### ISSUE TITLE
Call to a member function getPageId() on null

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#29]
Using latest revision (c556cb167a89b0a4a73256799232707d431cda5a) with TYPO3 7.6.3:

When I try to access a page, I get the following error
```
Fatal error: Call to a member function getPageId() on null in typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php on line 389
```

This happens because UrlDecoder::decodePathByOverride may return null and the result is not checked before calling getPageId:
https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L388

Fix would be to check the result:
```
if ($result) {
    $currentPid = $result->getPageId();
}
```

**Comment by dmitryd** [comment]
https://github.com/dmitryd/typo3-realurl/pull/26 ?

**Comment by rvock** [comment]
Exactly.

I only checked the issues and not the pull-requests ;)

**Comment by dmitryd** [comment]
Ok :)
