### ISSUE TITLE
Consider settings in $GLOBALS['TYPO3_CONF_VARS']['FE']

### ISSUE THREAD

**Issue by maechler** [dmitryd/typo3-realurl#291]
1)
I feel like realurl should consider the settings in `$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashRequiredParameters']`. URLs should not be saved to `tx_realurl_urlcache` when they do not have a cHash and one of the parameters in `$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashRequiredParameters']` is present.

We recently had to flush the table `tx_realurl_urlcache` and now have the challenge that when search engines call an url to a detail view of a news record, that was not before generated by TYPO3, they get saved to `tx_realurl_urlcache` without a cHash. The cached entry remains there without a cHash even when later the url would have been generated with a cHash. That makes this news entry non cacheable and thus it can also not be indexed by indexed_search.

This is only an issue with the following settings:

```
$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashRequiredParameters'] = 'tx_news_pi1[news]';
$GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFoundOnCHashError'] = false;
```

2)
I also feel like realurl should consider the settings in `$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters']`. I think the check for the cached url should remove the excluded parameters first: https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L1316

If we do not do that we get a cHash error on an url that would be valid. Imagine the following scenario:

```
$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashRequiredParameters'] = 'tx_news_pi1[news]';
$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters'] = 'q';
```

A call to an url `http://example.com/path?tx_news_pi1[news]=1&q=hello+world` now requires a cHash. Even if `http://example.com/path?tx_news_pi1[news]=1` would have an entry in `tx_realurl_urlcache` with a cHash, we get a cHash error.

**Comment by mm-baer** [comment]
I've seen this problem too, but with news pagination:
On subpages (e.g. "/sub/") everything works as expected. But not on the rootpage ("/")
It also works on the rootpage when I insert the id into the url manually (e.g. "&id=5&chash=...") or if I deactivate realurl.
So maybe realurl doesn't return the id on the rootpage correctly? or is there any configuration problem on my side? (I don't believe so, because it works on subpages)
with best regards

Bernhard

**Comment by maechler** [comment]
@mm-baer 

Are you sure this is related to this issue? I do not think that the problem I described should have something to do with the path. It should not be that there is a problem under "/" but not under "/sub/" with the issue I described here.

**Comment by dmitryd** [comment]
Why don't you just generate your links correctly and stop asking realurl to recover for **your** errors? :)

**Comment by macjohnny** [comment]
@mm-baer your issue might be related to https://github.com/dmitryd/typo3-realurl/issues/297

**Comment by maechler** [comment]
I do not think that this is a problem with the generation of the links. These are real issues that occur with a special set of TYPO3 core settings. 
Number 1 is a problem that everybody faces when direct links to subpages are saved somewhere (e.g. in favourites or search engines). The solution of not saving those urls to the `tx_realurl_urlcache` would be quite an easy fix in my opinion.

**Comment by dmitryd** [comment]
> We recently had to flush the table tx_realurl_urlcache and now have the challenge that when search engines call an url to a detail view of a news record, that was not before generated by TYPO3, they get saved to tx_realurl_urlcache without a cHash. 

Not a problem anymore because the decoder will not save anything to caches starting from 2.1.5. So if all other links on the page are made correctly, there should be only correct entries on the page.

**Comment by macjohnny** [comment]
@dmitryd thanks. this solves quite some issues.
