### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by Nemo64** [dmitryd/typo3-realurl#293]
I'm in a situation where I want to render the favicon.ico using typo3. So far so good, I define `['fileName']['index']['favicon.ico']` in my realurl config. However there is line stopping me: https://github.com/dmitryd/typo3-realurl/blob/5cf8bc6fdd5647fc97e7e044a7911778a37ba29b/Classes/Decoder/UrlDecoder.php#L1213

My question, why is that there? One could argue that my idea of using typo3 to render a favicon is a bad one. But if i don't have a favicon.ico in my project it'll render the normal startpage with a 200 response. Wouldn't it be much better to just have no special case for the favicon and just having it render the normal 404 error?

**Comment by dmitryd** [comment]
In your `.htaccess`:

```apache
RewriteRule favicon.ico - [G,L]
```

**Comment by dmitryd** [comment]
Reason is quite simple. Realurl decoding is resource-intensive. If you have no `favicon.ico`, search engines and browsers will continue to ask for it endlessly. Each request will trigger URL decoding process and eat CPU uselessly. To prevent that RealURL does not process favicon.

Just get rid of it with 401 code as shown above to spare resources of your server.
