### ISSUE TITLE
Urls are not expired when translation of a page is renamed

### ISSUE THREAD

**Issue by liayn** [dmitryd/typo3-realurl#299]
Renaming a page translation (alternative page title) does not update the url in the cache.
This leads to weird 404 errors.

**Comment by dmitryd** [comment]
I just checked. Expiration is set on path and URL cache records in the current development version of realurl when you change the title for page translation.

Here is how it looks like on my test host after renaming:
<img width="1237" alt="renamed-page-cache" src="https://cloud.githubusercontent.com/assets/306133/19851853/070aa97e-9f71-11e6-9f08-baebf9e21ad7.png">

**Comment by liayn** [comment]
Where is your entry for the new name of the translation?
There is no L=1&id=3 entry that is not expired?

**Comment by dmitryd** [comment]
I did not visit FE before doing the screenshot. The check on the screenshot was to make sure that the right entry is expired.

**Comment by liayn** [comment]
I will double check that on the affected instance now, after upgrading to 2.5.1 version. Lets see.

**Comment by liayn** [comment]
Alright. Seems to work again. Great.

**Comment by dmitryd** [comment]
Thank you!
