### ISSUE TITLE
Duplicate tx_realurl_urldata records if language<>0 and page disabled

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#303]
### Assumptions:
1. We have a translated page with this url: http://domain.ext/en/title/
2. This page has a link to another page with uid=13
3. Page 13 is a child of a disabled page

### Steps to reproduce the bug:
1. Visiting http://domain.ext/en/ will generate its right tx_realurl_urldata record:
   (uid, pid, crdate, page_id, rootpage_id, original_url, speaking_url, request_variables, expire, request_uri) VALUES
   (748, 0, '19/10/2016 07:39:04', 1, 1, 'L=1&id=1', 'en/', '{"id":"1","L":"1"}', 0, '/en/'), 
2. Visiting http://domain.ext/en/title/ will generate a duplicate record for the speaking_url 'en/'
   (uid, pid, crdate, page_id, rootpage_id, original_url, speaking_url, request_variables, expire, request_uri) VALUES
   (760, 0, '19/10/2016 08:04:43', 13, 1, 'L=1&id=13', 'en/', '{"id":"13","L":"1"}', 0, '/en/title/')
3. Visiting http://domain.ext/en/ again will give 404

### Solution?

I don't know but the problem seems to be in the method createPathComponentUsingRootline() (of which I fail to understand the logic). When this method tries to handle the original url 'L=1&id=13' it can't populate array $components so then it doesn't appendToEncodedUrl().

**Comment by dmitryd** [comment]
That's right. Rootline will break if the page is disabled. There is nothing realurl can do about it.

**Comment by webian** [comment]
Can't Realurl avoid to save a wrong record in tx_realurl_urldata? (aka step 2 of "Steps to reproduce the bug")

**Comment by dmitryd** [comment]
Realurl encodes and decodes what you give to it. It cannot know if **your** data is right or wrong. If you give a wrong url to realurl, why do you expect it to do it right?

Your responsibility is to provide valid URLs to realurl. You give the input, you receive the output. If you forgot to add cHash in your typolink, that's not realurl's fault, right? :)

**Comment by webian** [comment]
This has nothing to do with cHash.

**Comment by dmitryd** [comment]
Right, sorry, not cHash. The rest stays: you get what you ask for. TYPO3 does not reveal titles of disabled pages but you explicitly asked to link to a page inside the disabled page. You got your result. What ask, that you get. Be happy :) If you are not happy, do not link to pages inside the disabled page.

**Comment by webian** [comment]
Let's suppose that the link to page with uid=13 (see first post as reference) was made one month ago by Timmy. That day all the parents of page 13 was enabled.

Today another editor named Jack disable a parent of page 13 for some reason (temporary disable an offer; mistake; emergency; etc)

One user of the website visits http://domain.ext/en/title/ and Realurl stores a wrong tx_realurl_urldata record.

Since now the english homepage will return a 404.
The only way to fix this is to edit manually to the DB to remove the wrong record.

This is only one example to demonstrate that the problem can arise even if not wanted but if you are happy with this behavior of Realurl then I give up.

**Comment by dmitryd** [comment]
I am not happy when people do errors and ask **me** to do workarounds for **their** errors in realurl.

The only thing I can do here is to remove realurl data records when "hidden" flag is changed.
