### ISSUE TITLE
clearing cache for several pages takes very long

### ISSUE THREAD

**Issue by hannesbochmann** [dmitryd/typo3-realurl#306]
The extension [clearcacheextend](https://github.com/DMKEBUSINESSGMBH/typo3-clearcacheextend) makes it possible to define more complex rules for the clear cache command in the backend. E.g. you can define rules to clear the cache on all pages that contain the plugin tt_news. This extension will clear the cache of realurl for every page with a tt_news plugin along with the page cache. Clearing the realurl cache can take very long although the url cache table is only ~80000 entries.

So I have 2 questions. Is it necessary to clear the cache of realurl for a page or is it enough to clear the page cache only? Is it normal that clearing the cache for let's say 20 pages in a foreach loop takes about 15 seconds for a cache table with ~80000 entries?

**Comment by dmitryd** [comment]
I cannot answer questions here. This place is for bugs only. I close the issue because there is a related issue where it will be solved (#308).
