### ISSUE TITLE
Separator appearing in tx_realurl_urldata with speaking_url of parent page

### ISSUE THREAD

**Issue by Juburin** [dmitryd/typo3-realurl#311]
I'm using Typo3 6.2 and realurl 2.1.4 and have the problem that menu separators appear in the tx_realurl_urldata table with the speaking url of the parent page.

My page tree is like this:

```
- Rootpage (id=1)
 - Home (id=2)
  - PageA (id=3)
  - PageB (id=4)
  ------- Seperator (id=20)
  - PageC (id=5)
  - PageD (id=6)
  ------- Seperator (id=21)
```

When I look at tx_realurl_urldata and search for `home/`as speaking url the table looks like this:

| uid | pid | crdate | page_id | rootpage_id | original_url | speaking_url | request_variables | expire |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| x | 0 | 0 | 2 | 1 | id=2 | home/ | {"id":"2"} | 0 |
| x | 0 | 0 | 20 | 2 | id=20 | home/ | {"id":"20"} | 0 |
| x | 0 | 0 | 21 | 2 | id=21 | home/ | {"id":"21"} | 0 |

As consequence typo3 shows the 404 error page.

**Comment by dmitryd** [comment]
It seems like somebody tried to link to the separator page. How this can be?

**Comment by dmitryd** [comment]
I disabled caching of these page types.

**Comment by Juburin** [comment]
Thank you! As a workaround I set the seperators to hidden. I am still looking which extension wants to generate URLs for the seperators.
