### ISSUE TITLE
realurl cut of a end of a string

### ISSUE THREAD

**Issue by rassloff** [dmitryd/typo3-realurl#312]
System: 

TYPO3 7.6.11
realurl 2.1.4

in tx_news_domain_model_news.title
is written: Bühnenlicht für Tanz- und Unterhaltungsmusiker: Was Sie für die perfekte Lichtshow wirklich brauchen

in tx_realurl_uniqalias.value_alias is written:

buehnenlicht-fuer-tanz-und-unterhaltungsmusiker-was-sie-fuer-die-perfekte-lichtshow-wirklich-brauc

and in tx_realurl_urldata.speaking_url too

buehnenlicht-fuer-tanz-und-unterhaltungsmusiker-was-sie-fuer-die-perfekte-lichtshow-wirklich-brauc

how can i solve the Problem ???

**Comment by dmitryd** [comment]
This place is for bugs. For general help, see "Getting help" on the wiki.
