### ISSUE TITLE
Infinite redirects on shortcuts 

### ISSUE THREAD

**Issue by Adan0s** [dmitryd/typo3-realurl#314]
Hey there,

I'm having a problem with shortcuts:

Root
- "Kontakt" (Shortcut to "Kontaktseite")
- Folder (excluded from speaking path)
-- "Kontaktseite" (Alternative Navigation Title "kontakt")

In this constellation, navigating to the "Kontakt" site does result in a infinite redirect. Now, if I remove the alternative navigation title of "Kontaktseite" and just set the page alias to "kontakt" it works.
Is this an expected behaviour?

**Comment by dmitryd** [comment]
Yes. Item #3 [here](https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#limitations). What you try to do is officially not supported and it is an error configuration.

**Comment by kanow** [comment]
Mahlzeit!

We have the same problem on some TYPO3 sites. Our workaround for this:
We are using a different value in "realurl path segment" for the shortcut page.
That's working.
At our site only the page title is showing in the link. Not the path-segment.
