### ISSUE TITLE
BE module URL data pagination does not work on first click

### ISSUE THREAD

**Issue by liayn** [dmitryd/typo3-realurl#317]
Loading the module and select the url data function.
Try to navigate to page 2
=> the module is reset to overview

The function needs to be selected again from the dropdown, then pagination works.
I guess some parameter is missing on the first load.

**Comment by liayn** [comment]
The URLs for the links are

not working:
`https://www.example.com/typo3/index.php?M=web_RealurlRealurl&moduleToken=737ff301b081787e711cc0535fe506048edf0b0a&id=1&tx_realurl_web_realurlrealurl%5B%40widget_0%5D%5BcurrentPage%5D=2`

working:
`https://www.example.com/typo3/index.php?M=web_RealurlRealurl&moduleToken=737ff301b081787e711cc0535fe506048edf0b0a&id=1&tx_realurl_web_realurlrealurl%5Baction%5D=index&tx_realurl_web_realurlrealurl%5Bcontroller%5D=UrlCache&tx_realurl_web_realurlrealurl%5B%40widget_0%5D%5BcurrentPage%5D=2`

Obviously controller and action is missing in the first one.

**Comment by dmitryd** [comment]
Did you try the latest development version? I believe this was solved in #102.

**Comment by liayn** [comment]
Yep, is fixed. Thank you!
