### ISSUE TITLE
preVars match full URI segment

### ISSUE THREAD

**Issue by morinfa** [dmitryd/typo3-realurl#321]
I have the following configuration :

> 

		'preVars' => array (
			array (
				'GETvar' => 'L',
				'valueMap' => array (
					''   => 0,
					'ja' => '1',
					'zh' => '2',
					'cn' => '3',
				),
				'valueDefault' => '',
				'noMatch' => 'bypass',
			)
		),

> 

If I request http://localhost/james, it will display the 404 page in japanese (language 1), instead of the 404 page in english (default language 0).

I have this problem with v1 and v2.

**Comment by dmitryd** [comment]
I do not think this is realurl related. Realurl does not display 404 pages. Unless you can prove this is a realurl issue, I will not look into this.

Also your configuration is incorrect. `''` is not a valid value inside `valueMap`.

**Comment by morinfa** [comment]
My bad, the problem was indeed in my 404 hook.
