### ISSUE TITLE
Exclude specific URLs from RealURL cache

### ISSUE THREAD

**Issue by morinfa** [dmitryd/typo3-realurl#323]
I know it's possible to use the configuration "tx_realurl_nocache" to exclude a page from RealURL cache.

But could you please add some kind of hook to have more control over that ?

Use-case could be a single page controlling multiple actions, and some URLs would be excluded (e.g. a myAccount page with a change password URL containing the username and a hash in the URL, no need to cache that in RealURL cache, while other actions URLs should be cached).

**Comment by dmitryd** [comment]
Please, read the documentation.
