### ISSUE TITLE
Superfluous question mark in some use cases

### ISSUE THREAD

**Issue by thorstenlbk** [dmitryd/typo3-realurl#327]
In Classes/EncodeDecoderBase.php in the function removeIgnoredParametersFromURL() the variable $queryString becomes NULL if there is no query string in the URL. So the condition `$queryString !== ''` in line 271 evaluates to TRUE, which leads to a superfluous "?" at the end of the speaking URL.

This question mark is still present when the pre decode hooks are called which can lead to exceptions on sites that were working with former versions of realurl.

**Comment by dmitryd** [comment]
Thank you!
