### ISSUE TITLE
Make originalUrlParameters accessible in UrlEncoder

### ISSUE THREAD

**Issue by MajPay** [dmitryd/typo3-realurl#33]
Hey,

thanks for Realurl!

It would be very useful, if some properties (originalUrlParameters for example) could be public or at least have a public getter method. I make use of ther userFunc pattern to get some path segment, but i dont have a change to see what language a link is for. My segments value would depend on the target language though.

The only way to solve this atm is to make those properties accessible via reflection but i assume this is very expensive.

Could you please add some getter methods to UrlEncoder to make url generation from userFunc parameters more transparent?

Kind regards,
Philipp

**Comment by dmitryd** [comment]
What userFunc do you mean?

**Comment by dmitryd** [comment]
No feedback provided, closing the issue.
