### ISSUE TITLE
HTTP 500 Error

### ISSUE THREAD

**Issue by rosf** [dmitryd/typo3-realurl#332]
Hi,
thanks for your work!
I installed realurl 2.1.5. Is it compatible with Typo3 7.6.9? 
It works fine with links but I don't find my css and js files. The path to fileadmin is wrong.
I tried to use realurl_autoconf.php and realurl_conf.php and I modified the .htaccess file too without succes  and I became an Internal Server Error 500 :-(.
Now the extension is inactive.
What can I do? is the release realurl 1.13.6 better fpr Typo3 7.6.9?

best regards

**Comment by dmitryd** [comment]
This place is for bugs, not for getting help. For help [see here](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
