### ISSUE TITLE
Caches being filled with bogus languages ID and SQL injections 

### ISSUE THREAD

**Issue by gaumondp** [dmitryd/typo3-realurl#333]
RealURL 2.1.4, PHP-FPM 7.x Apache 2.4 with TYPO3 7.6

Both RealURL caches (Data & Path) are getting filled with bogus languages` (L=999999) `and even SQL injections `(L=1%20union%20all%20select%20null%2Cnull%2Cnull%2Cnull%2Cnull--&id=25)`

Is there something we can do at RealURL level to limit those entries in the cache ?

At least I can add a TS condition (if L >1 then L=0 for example) but I'm a bit puzzled to the SQL injection one.

I'm adding a query to empty both RealURL caches every nights but that's not optimal.

**Comment by dmitryd** [comment]
Your installation is currently allowing arbitrary values for the `L` parameter. It is a security problem of your installation, which is mitigated by TypoScript configuration easily. [Corresponding configuration option](https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#linkvars) is available for years...

Realurl encodes what you give to it. It does not fix **your** errors. There is nothing to do here on realurl level. Configure your installation properly to make sure that TYPO3 passes correct parameters to realurl.

**Comment by dmitryd** [comment]
And there is no SQL injection here. Please, read what the term means before you use it.

**Comment by dmitryd** [comment]
And one more: if you disable realurl and try to call your page as `/index.php?L=1%20union%20all%20select%20null%2Cnull%2Cnull%2Cnull%2Cnull--&id=25` (as a typical attacker will do), you will see that all `L` values in all urls on your page are wrong. This will happen even without realurl.

It is truly a security issue at your installation that `config.linkVars = L(0-1)` will prevent easily.

**Comment by gaumondp** [comment]
Thanks @dmitryd for the headsup, I was not aware of linkvars being able to use `L(0-1)`.

I was never saying RealURL was open to SQL injections, I was saying people tried to do some on my site and it filled RealURL cache. I'm pretty aware of your high coding standards.

**Comment by dnsnx** [comment]
I was facing the same issue and had also set the value of `linkVars` set to `L`. It helped to avoid the URL issue.
But when I set the value to `L(0,1)`, it always switches back to German (default) language. With the value `L`, it added the language to the URL i.e. `domain.com/en/prices`. With the setting `L(0,1)`, it always switches back to `domain.com/prices`, which is the German translation of the page. Any idea how to set the value for `linkVars` in this case? Any help appriciated! Many thanks in advance!
