### ISSUE TITLE
Update Script fails

### ISSUE THREAD

**Issue by s-ude** [dmitryd/typo3-realurl#334]
The current update script (`class.ext_update.php`) of realurl is renaming the tables `tx_realurl_pathcache` and `tx_realurl_urlcache` to `tx_realurl_pathdata` and `tx_realurl_urldata`. However, it also does some updates on the tables afterwards and one of them is done on the old tablename `tx_realurl_urlcache`. Thus the following query fails:

```
DELETE FROM tx_realurl_urlcache WHERE original_url RLIKE '(^|&)(utm_[a-z]+|pk_campaign|pk_kwd)='
```

The updates can be found in `ext_update::main()`
```
$this->checkAndRenameTables(); // <- renames the tables
$this->checkAndUpdatePathCachePrimaryKey();
$this->updateRealurlTableStructure();
$this->removeUrlDataEntriesWithIgnoredParameters(); // <- update on tx_realurl_urlcache fails
```

I guess, the table name used in the latter method should be changed to `tx_realurl_urldata`.

**Comment by dmitryd** [comment]
Thank you.

**Comment by etobi** [comment]
Hej dmitryd,

any chance to get a regular release (2.1.16?) with this fix included? Would be very much appreciated.

kind regards
   Tobias

**Comment by dmitryd** [comment]
@etobi No deadline / free project / work in personal time / etc.
