### ISSUE TITLE
Translated URL Paths in Default Language

### ISSUE THREAD

**Issue by s-ude** [dmitryd/typo3-realurl#335]
I am actually not sure if this is a real issue, but I've had some trouble which seems related to this behaviour:

Assume I have a page called "Trouble Page" (ID: 123). It's German (language ID: 1) translation is "Problem-Seite".
When I view the default and the German version (not logged into the backend) I find all cache table entries I am expecting afterwards, but actually I get an additional entry.

Having a look at `tx_realurl_urldata` I see the following entries:
```
original_url | speaking_url
============================
id=123       | /trouble-page/
L=1&id=123   | /de/problem-seite/
L=&id=123    | /problem-seite/
```

The third entry is bugging me. It has the translated path segments but no language prefix.

As far as I can tell, this is not a problem in general since the first entry is used for generating links in the default language, but I did find some cases (though I do not know how to reproduce them exactly) in which this third entry showed up (on links generated in the default language). Some of those cases led to a 404 error, some were working (showing the default language version of the page).

Can you tell me, if this third kind of entry is generated on purpose?

/edit

Now I found a way to reproduce the problem in the front end using a bit of TypoScript. It's actually dead-simple.

```
10 = TEXT
10.typolink.parameter = 123
20 < .10
20.typolink.additionalParams = &L=1
30 < .10
30.typolink.additionalParams = &L=
```

The first link will point to the default version with the normal URL. The second will point to the translated version. The third will also point to the default version but it will be using the translated path segments.

**Comment by s-ude** [comment]
I dug into this problem a bit and I think I found where the problem is located:
`DmitryDulepov\Realurl\Encoder\UrlEncoder::setLanguage()` does not recognise `L === ''` as default language and is using the current language instead.

See pull request #336.

**Comment by dmitryd** [comment]
Please, make sure that you [read the documentation](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-languages) before submitting the bug. Your description is a typical symptom of misconfiguration.

**Comment by s-ude** [comment]
I do not see a misconfiguration in my case. I may have overlooked something but I don't know what this could be. Maybe you could give me a hint what I should be looking for. That would be great.

From the linked documentation I am using the first way of language handling - no prefix for the default language. It is working as expected in all cases except when the URL encoder is getting the parameter L with an empty string.

I have also tried to use the extension configuration `basic.enableAutoConf` and got the same results.


Just in case I wasn't able to communicate the issue properly, I will try to be more precise:

The default language (ID 0) is English (en). The first foreign language (ID 1) is German (de).
Having a typolink (I am clearing the URL caches for all tests)...
- with `additionalParams = &L=0` I get the URL `/trouble-page/` (which is fine)

- with `additionalParams = &L=1` I get the URL `/de/problem-seite/` (which is also fine)

- without any `additionalPrams` I get an URL dependent on the current language, thus either `/trouble-page/` or `/de/problem-seite/` (which is both fine)

- with `additionalParams = &L=` I do not get a language prefix and the language used for the path depends on the current language, thus on a German page I get the URL `/problem-seite/` and on an English page I get the URL `/trouble-page/`, while both URLs are leading to the English (default) version of the page.

**Comment by dmitryd** [comment]
>  Maybe you could give me a hint what I should be looking for. That would be great.

Usually I do not provide any free support beyond bug fixing.

> with additionalParams = &L=

I think you should check [this](https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#linkvars) if you `L` can get empty values...

**Comment by s-ude** [comment]
Thank you for your suggestions. I assumed that the empty L parameter is valid since the CMS (without realurl) is behaving as expected (showing the default language of the page). In typolinks I have seen it quite often when a language reset to default should take place. However, seeing something often doesn't make it right. Thanks for the clarification on this point. I have learned something today.

Yet, I would like to make one more suggestion for realurl, just to make its behaviour more compliant along with the CMS.
When using a non-speaking URL with an invalid L parameter, the CMS is ignoring the parameter and showing the default language version of the page.
Using realurl the generated speaking URLs  are decoded eventually and will then have the invalid parameter again and thus the default language version is shown as well. But this behaviour can also be applied to the language chosen in the UrlEncoder, which determines which language for the path segments shall be used.
Currently an invalid L parameter leads to the current language being used for the path segments. I would argue that the default language is a better choice for two reasons.

The first reason is that the resulting URL will lead to a page in the default language.

The second reason is that the resulting URL would be stable. Right now the generated URL depends on the language in which it is first generated (and then written to cache). It could change in the future if the cache is expired and the URL is encoded in another language context.

Current method:
```
class UrlEncoder {
	// ...
	protected function setLanguage() {
		if (isset($this->urlParameters['L']) && MathUtility::canBeInterpretedAsInteger($this->urlParameters['L'])) {
			$this->sysLanguageUid = (int)$this->urlParameters['L'];
		} else {
			$this->sysLanguageUid = (int)$this->tsfe->sys_language_uid;
		}
	}
	// ..
}
```

Suggested method:
```
class UrlEncoder {
	// ...
	protected function setLanguage() {
		if (isset($this->urlParameters['L'])) {
			if (MathUtility::canBeInterpretedAsInteger($this->urlParameters['L'])) {
				$this->sysLanguageUid = (int)$this->urlParameters['L'];
			} else {
				$this->sysLanguageUid = 0; // <- not sure if the default language has always ID 0
			}
		} else {
			$this->sysLanguageUid = (int)$this->tsfe->sys_language_uid;
		}
	}
}
```

Of course, saying that invalid input is nothing which needs to be handled at all is a valid answer, too. If you find this change unnecessary then this ticket can be closed.

**Comment by dmitryd** [comment]
Firsts, realurl encodes URLs as they are given by TYPO3 core.

Secondly, every piece of software has its own requirements. If you configure your system to meet realurl requirements, realurl will not work correctly for you.

Just do as described in the manual. It is not difficult.
