### ISSUE TITLE
data is retrieved from tx_realurl_urldata when cHash is wrong

### ISSUE THREAD

**Issue by taniamorales** [dmitryd/typo3-realurl#341]
To start let me tell you how much my colleges and I appreciate the efforts done lately on security level. But I have reviewed the latest commits and I was not able to find one that completely fits to the issue I am adding here so I am requested a feedback to be able to identify a proper solution.

I received a report that points out to a wrong functionality of the cHash mechanism as the tx_realurl_urldata table is flooded when links (potential harmful) to pages that use a wrong cHash value are requested.
for example: ../index.php?%25%3Cacx%3E%3CScRiPt_%3Eprompt(990364)%3C%2FScRiPt%3E=&cHash=af00923fd079986f875d2852b95e1627

the cHash will of course not match any page that can be cached but realurl tries to retrieve it.
SELECT * FROM tx_realurl_urldata WHERE rootpage_id=1 AND original_url='L=0%25%3Cacx%3E%3CScRiPt_%3Eprompt(990364)%3C%2FScRiPt%3E=&cHash=af00923fd079986f875d2852b95e1627

My colleagues questions are:
Why does the cHash with the injected prompt() script goes through? Why were pages cached? Why was realURL data cached? What do we need to do to prevent it?

Is it possible that something is done wrong on the configuration of the site itself that  could create this issue or do you think it can be reported as a bug?

Thanks for your feedback!

**Comment by dmitryd** [comment]
Closed because not a bug. Only bugs are allowed in the bug tracker.

See [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) if you need help.
