### ISSUE TITLE
Endless redirect loop for shortcuts with same name as linked page

### ISSUE THREAD

**Issue by greinerd** [dmitryd/typo3-realurl#344]
Hi! 

If you are using shortcuts (f.e. if you want to list pages from the main-navigation in a separate footer menu) the frontend ends up in an endless redirect loop if the name of the shortcut is the same as the linked page and the folder containing the shortcuts is "excluded from speaking url".

- Main-Navigation (Sysfolder)
-- Page 1
-- Page 2

- Footer-Navigation (Sysfolder, excluded from speaking url)
-- Page 1 as shortcut to Main-Navigation=>Page 1
-- Page 2 

I am on TYPO3 8.4.1 and EXT:realurl (master-branch, i tried the development branch too) 

Greetings
David

**Comment by dmitryd** [comment]
Please, read the documentation about limitations. You may not have the same titles on the same logical level with realurl. This is well documented for a long time.

Not a bug.
