### ISSUE TITLE
requireCacheHashPresenceParameters and 404 Response without cache entries

### ISSUE THREAD

**Issue by christophlehmann** [dmitryd/typo3-realurl#349]
Hi Dmitry,

I've updated a site (7.6.14) to realurl 2.1.5.

My configuration for a product extension is

`$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['requireCacheHashPresenceParameters'][] = 'tx_myproducts_switchproduct[product]';`

When i visit a product page (coming from google) and there is no cache entry in `tx_realurl_urldata` for that site i get a 404 with "Reason: Request parameters could not be validated (&cHash empty)".

When i first generate all cache entries for  `tx_realurl_urldata` by with visiting /sitemap.xml the page is visitable.

Is there a way so that it's not needed to generate the cache entries first?

On https://github.com/dmitryd/typo3-realurl/wiki/Differences-between-RealURL-1.x-and-2.x is mentioned that

> If URL entry is missing in the cache, RealURL will automatically recalculate cHash using the same functions that TYPO3 does, so cHash will be always correct.

Regards,
Christoph

**Comment by dmitryd** [comment]
Not a bug. This place is for bugs only. For any other help see [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
