### ISSUE TITLE
Several error log entries 

### ISSUE THREAD

**Issue by skydivematy** [dmitryd/typo3-realurl#35]
Hi Dmitry,
i have serval error log entries.

System is TYPO3 7.6.4
mariaDB, PHP 7
Running Ext.: 
realurl Development
tx_news Latest git
formhandler latest git svn
gridelements latest git
static_info_tables 6.3.9
toctoc_comments 8.1.1
tt_address 3.0 dev
yag latest

Maybe you can do something with this information.
About 4000 error log entries with these lines...

Cheers
Matthias

`Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /var/www/virtual/domingo/html/typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php line 309

	Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /var/www/virtual/domingo/html/typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php line 309 Changes in fields: include_static_file.

	Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /var/www/virtual/domingo/html/typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php line 309 Changes in fields: hidden,l18n_diffsource.

Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /var/www/virtual/domingo/html/typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php line 309 Changes in fields: CType.

Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /var/www/virtual/domingo/html/typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php line 309 Changes in fields: tags.

Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /var/www/virtual/domingo/html/typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php line 309 Changes in fields: pi_flexform.`

**Comment by dmitryd** [comment]
Thanks for reporting, I found the cause.

**Comment by skydivematy** [comment]
Ok. Fixed.
Thanks Dmitry
