### ISSUE TITLE
Prevent non-existent languages to enter cache

### ISSUE THREAD

**Issue by j6s** [dmitryd/typo3-realurl#354]
Currently non-existent languages are allowed to enter the cache, if the page is configured to redirect to the default language in such cases. This can potentially lead to some serious security implications.

Example:
An attacker may call the following url:
`GET http://mysite.com/en/news?L=dangerous`
This will create an entry in `tx_realurl_urldata` which looks like this:
- original_url: `[...]&L=dangerous&[...]`
- speaking_url: `en/news?L=dangerous`
- request_variables: `{[...] "L": "dangerous" [...]}`

Now, that's not bad as this speaking URL will never be retrieved from the cache because no regular user would add `L=dangerous` to his URL. However, the new language will also be used for some generated URLs on the page. For example, the following URL will also land in the cache:

- original_url: `[...]&L=dangerous&[...]`
- speaking_url: `en/news/my-detail`
- request_variables: `{[...] "L": "dangerous" [...]}`

As you can see this can potentially lead to attackers being able to insert arbitrary strings into the URL which may be a huge security concern. 

This is why I propose, that `L` values for languages are checked for correctness (against `sys_language`) before entering the cache.

**Comment by tdeuling** [comment]
Hi,
I'm not sure, but shouldn't such behaviour not easily be prevented by the following TypoScript (in this example for existing language 1, 2 and 3):
```
config {
	linkVars = L(1-3) 
}
```
Read more about linkVars: https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#linkvars

**Comment by j6s** [comment]
That is true, yes. But IMO invalid values should not be allowed to leak through the cache in the first place

**Comment by spillse** [comment]
See another example here: https://github.com/dmitryd/typo3-realurl/issues/358#issuecomment-266849760

If you use **L** = **1'A=0** as get parameter, this will gets saved in realurl caching table, which leads to generation of wrong language output of multilanguage websites.

The L parameter will be wrong and system do fallback to L not set (default language), when get parameters are rebuilt from cache tables using request with url based on realurl.

Solution is that realurl needs to check if parameters of L variable are correct/allowed, before writing the cache entry.

**Comment by dmitryd** [comment]
@spillse 
> Solution is that realurl needs to check if parameters of L variable are correct/allowed

No, it does not. It is you, who have to do your work properly and configure YOUR system correctly.
