### ISSUE TITLE
404 with "accidentally" cross domain links

### ISSUE THREAD

**Issue by SvenJuergens** [dmitryd/typo3-realurl#356]
hi,

it's a little bit difficult to explain and to reproduce...
We have a multi Domain Installation, with different languages.

Rootpage A has Domain A and languages de and en.
Rootpage B has Domain B and languages de and fr.

Now we habe some "teaser" elements on every Page, f.e. "here visity this subpage ( link to subpage link in current tree)".
One of the editors now copy an element from Domain A and paste it on Domain B, but forgot the change the Link from Domain A to B. typolinkEnableLinksAcrossDomains is disabled. this Cross Domain link should nit exist, it's a failure of the editor.

The generated speakingUrl to the subpage in Domain B is  www.domainB.com/ and in second language is ww.domainB.com/fr/

This results in cache(?) entry like this.
![wrongspeakingurl](https://cloud.githubusercontent.com/assets/20923295/21096984/a8564ad8-c062-11e6-858e-545f78c23f16.png)

The entry is saved on Domain A. 
The bigger problem now is, if i want to call the site www.domainB.com/fr/ i got a 404.
(www.domainB.com/fr/othersubpage is still working)

P.S. we use TYPO3 7.6.13 and realUrl 2.1.5

**Comment by icehawk-de** [comment]
We have a similar problem:
www.domain.de -> works
www.domain.de/de/ -> error 404
www.domain.de/de/subpages -> works

The last working version is the 2.0.15.

**Comment by icehawk-de** [comment]
Update: Also Problems with tt_news. Link to Detail-Page -> Error 404
2.0.15 is OK, no problems.

**Comment by dmitryd** [comment]
Linking across domains is only partially handled by realurl. It involves extra work for both TYPO3 and realurl. Therefore it has to be enabled specially.

Just enable it. Linking across domains will not work properly if it is not enabled.
