### ISSUE TITLE
Speaking path with override not decoded properly?

### ISSUE THREAD

**Issue by adrienjacob** [dmitryd/typo3-realurl#357]
Hi,

When setting the "speaking path" parameter with override, I noticed the URL would not be decoded properly, unless the page is actually displayed in a menu (and thus cached), or is a direct child of the root page.
Maybe I'm wrong, but I believe there's a problem in UrlDecoder.php with function getRootPageIdForPage (used by searchForPathOverrideInPages and searchForPathOverrideInPagesLanguageOverlay). This function is supposed to return the root page ID of the current page, but instead returns the topmost root page. Here's my setup : 
Root (not set as "is root")
-> Domain 1 (with "is root" set, domain record and root id configured in realurl_conf.php)
-->Page 1
--->Page 2
--> Page 3
-> Domain 2 (same)
etc.
getRootPageIdForPage(Page 2) returns "Root" instead of "Domain 1".

This fixed my problem :
```
	protected function getRootPageIdForPage($pageUid) {
		$rootLineUtility = GeneralUtility::makeInstance('TYPO3\\CMS\\Core\\Utility\\RootlineUtility', $pageUid);
		/** @var \TYPO3\CMS\Core\Utility\RootlineUtility $rootLineUtility */
		$rootLine = $rootLineUtility->get();
		
		// START CHANGE
		$result = 0;
		if (is_array($rootLine) && count($rootLine) > 0) {
			$index = count($rootLine)-1;
			while($index) {
				if ($rootLine[$index]['is_siteroot']) {
					$result=(int)$rootLine[$index]['uid'];
					break;
				}
				$index--;
			}
		}
		
		return $result;
		// END CHANGE
	}
```

**Comment by dmitryd** [comment]
Looks nice, the only thing I'd like to change is the loop direction. Starting from zero is most likely will reach the root page faster. It does not make much difference though.

I will have a look at it.

**Comment by adrienjacob** [comment]
Ok thanks... Otherwise I found https://github.com/hannesbochmann/typo3-realurl/commit/0cad20b4977be6d2664e406b4d1f3da8ff32e9d4 solves the same problem differently, maybe in a better way.

**Comment by dmitryd** [comment]
Yes, I merged that, so the issue can be closed :) Thank you.

Related #259.
