### ISSUE TITLE
Translated records wrongly stored in tx_realurl_uniqalias

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#361]
When is browsed the translated list of records (L=1), realurl creates tx_realurl_uniqalias records for the records but the value_id field is filled with the default language records uid instead of the translated records uid.

Then method `clearUrlCacheForAliasChanges` searches for a value_id equal of the uid of the translated record and then fails to find the tx_realurl_uniqalias records.

**Comment by webian** [comment]
I add that, when a default language record is updated, method `clearUrlCacheForAliasChanges` clears the cache also of the translated records, while it should not.

**Comment by dmitryd** [comment]
Value is stored correctly. The hook behaves incorrectly.

This will be fixed as #362 because this description is wrong.

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 12. März 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 13. März 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Bruno Buess (buess@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali

Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch
