### ISSUE TITLE
Speaking url doesn't update if alias_field is updated

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#362]
When the alias_field of a record is modified, its tx_realurl_uniqalias entry should be deleted too or else its speaking url will always be generated with the old alias_field value.

This should be configurable because it will generate a 404 if the old speaking url is browsed. If it is configurable then an administrator can choose between "updated alias but 404 for old alias" or "outdated alias but not 404".

Could be even better the presence of a feature that redirects old speaking urls to new speaking urls.

**Comment by dmitryd** [comment]
The correct behavior is to expire both alias and url data entry. Than when the new entry is added to the url data table, realurl should redirect to the new url.
