### ISSUE TITLE
Cache not updated when changing "override" or "exclude from speaking URL"

### ISSUE THREAD

**Issue by adrienjacob** [dmitryd/typo3-realurl#367]
When changing the value of "Exclude from speaking URL" or "Override the whole page path", the cache is not refreshed. I fixed it by changing line 182 of Hooks/DataHandler (in function expireCache)

```
if (isset($databaseData['hidden']) || isset($databaseData['tx_realurl_pathoverride']) || isset($databaseData['tx_realurl_exclude'])) {
		$expireCache = TRUE;
}
```

**Comment by dmitryd** [comment]
See #392
