### ISSUE TITLE
[TYPO3] 8.6.0-dev: $GLOBALS['TCA']['pages']['ctrl']['requestUpdate'] dropped and needs refactoring

### ISSUE THREAD

**Issue by jousch** [dmitryd/typo3-realurl#368]
https://github.com/TYPO3/TYPO3.CMS/blob/38a1bc5dd7990b63e45c0419065cd02fe91187e9/typo3/sysext/core/Documentation/Changelog/master/Deprecation-78899-TCACtrlFieldRequestUpdateDropped.rst

**Comment by dmitryd** [comment]
Good point but realurl is still compatible with TYPO3 6.2, so people will have to live with this warning.

This can only be fixed after realurl is migrated to Doctrine and no longer compatible with anything below 8.6. Since this is a huge work, there are no currently plans for it at all.

**Comment by dmitryd** [comment]
Done because this option is no longer needed due to #417.
