### ISSUE TITLE
Not compatible with powermail if used on frontpage

### ISSUE THREAD

**Issue by ColonelMillerSG21** [dmitryd/typo3-realurl#369]
I should mention that i'm using RealUrl with t3 v.6.1.
If i add the powermail extension to my rootpage, realurl seems to cut of the page id which leads to the page not loading when i submit my powermail form:
image
Is there any way to solve this?
![a55ba590-c80e-11e6-8140-59bf8ae3b916](https://cloud.githubusercontent.com/assets/11478472/21803868/5e90c280-d72c-11e6-97c4-ca10354d7f5a.png)

**Comment by dmitryd** [comment]
This place is not for support. Please, see "Getting help" in the wiki.
