### ISSUE TITLE
404 page after clearUrlCacheForAliasChanges

### ISSUE THREAD

**Issue by anjeylink** [dmitryd/typo3-realurl#370]
After updating record old alias stop woringk if  $GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFoundOnCHashError'] == true

because variables cache with "cHash" parameter get removed from "tx_realurl_urldata" table.

**Comment by dmitryd** [comment]
Yes, this is expected behavior. This cannot be avoided unfortunately. If the URL uses cHash is has to be in the tx_realurl_urldata table for correct decoding.

Visit the page with the list view after modifying the alias.
