### ISSUE TITLE
massive SQL server load by limitTableRecords() 

### ISSUE THREAD

**Issue by zechendorf** [dmitryd/typo3-realurl#371]
I am running a website with a very big amount of URL's (well above the 500.000 limit hard set in DatabaseCache.php).

Because of RealURL regularly deleting cached URLs if the number of URLs is larger than 500.000 the site became really sluggish (>20 sec load time per page).

Looking into the SQL processes i've found a lot of ``DELETE FROM tx_realurl_urldata`` queries which ultimately led me to commit c840ca5f41155182afee96335b8f6e302305edbb where this feature was introduced.

I've changed ``limitTableRecords()`` to just return false. Now the site runs like a charm.

```
protected function limitTableRecords($tableName) {
	return false;
}
```

@dmitryd - you should propably look into this - I suppose you've propably introduced this because of the URL cache flooding bug from last year. Since this was fixed recently, we can propably just remove the hard limit. Looking forward to feedback - very willing to give additional information.

**Comment by dmitryd** [comment]
See #339
