### ISSUE TITLE
pageNotFoundOnCHashError triggered

### ISSUE THREAD

**Issue by SventB** [dmitryd/typo3-realurl#372]
In version 2.1.5 of realurl, pageNotFoundOnCHashError is triggered for urls like this:
my-page/my-object/?tx_myext_pi1[feuser]=39917&cHash=80c756c68968214b32b3693c2b204c05

The non-speaking url is this one:
L=0&cHash=80c756c68968214b32b3693c2b204c05&id=931&tx_myext_pi1[object]=1&tx_myext_pi1[controller]=MyController&tx_myext_pi1[feuser]=39917

The second url is working, the first one only, if pageNotFoundOnCHashError set to "0".
Both urls are working in realurl version 2.1.4!

**Comment by dmitryd** [comment]
Please, use recent realurl version. I can;t help with this at all.
