### ISSUE TITLE
Caching issue with realurl and google adwards gcli-parameter

### ISSUE THREAD

**Issue by kreilinger** [dmitryd/typo3-realurl#377]
Hi,

i have the following site:
https://www.musterhauspark.at/de/aussteller/ which contains a plugin that lists objects. The detail view is located at the subpage /de/aussteller/hersteller/ und the realurl config uses the lookupTable to match the name.

```php
 'aussteller-ansicht' => array(
   array(
                    'GETvar' => 'tx_mhphaeuser_aussteller-ansicht[action]',
                    'valueMap' => array(
                        'show' => '',
                    ),
                    'noMatch' => 'bypass'
                    ),
                                array(
                    'GETvar' => 'tx_mhphaeuser_aussteller-ansicht[controller]',
                    'valueMap' => array(
                        'Hersteller' => '',
                    ),
                    'noMatch' => 'bypass'
                    ),
                                array(
                                        'GETvar' => 'tx_mhphaeuser_aussteller-ansicht[hersteller]',
                                        'lookUpTable' => array(
                                                'table' => 'tx_mhphaeuser_domain_model_hersteller',
                                                'id_field' => 'uid',
                                                'alias_field' => 'marke',
                                                'addWhereClause' => ' AND NOT deleted',
                            'useUniqueCache' => 1,
                            'useUniqueCache_conf' => array(
                                'strtolower' => 1,
                                'spaceCharacter' => '-'
                            )
                                        )
                                )
                        ),
```
this works like a charm and i can visit e.g. https://www.musterhauspark.at/de/aussteller/hersteller/elk/ or. /griffner/ . But when i add the google adwards gclid-parameter to the url (e.g. https://www.musterhauspark.at/de/aussteller/hersteller/elk/?gclid=xyz) the problem occurs. At the first visit with the parameter I get the correct page returned, but after that i always get the same page, no matter what "hersteller" i try to access. E.g. https://www.musterhauspark.at/de/aussteller/hersteller/griffner/?gclid=xyz returns the content from /elk/ or whatever page i visitied first with the ?gclid-parameter.

I added the gclid-parameter to TYPO3 config ([FE][cHashExcludedParameters]) and updated the realurl_conf.php with the following:
`'cache' => array(
  'banUrlsRegExp' => '/gclid|tx_kesearch_pi1|tx_solr|tx_indexed_search|(?:^|\?|&)q=/',
),`

Is this a bug in realurl? What leads to this behavior? I'm running TYPO3 v7.6.14 with realurl v2.1.5 on PHP 7.0.1.

**Comment by kreilinger** [comment]
Hate to push, but is there any chance you can tell me what the problem here is?

**Comment by dmitryd** [comment]
> At the first visit with the parameter I get the correct page returned, but after that i always get the same page, no matter what "hersteller" i try to access.

This sounds like you do not have cHash in your detail view urls.

**Comment by kreilinger** [comment]
I just disabled realurl und every link to a detail page i could find has a cHash in it. Appending the &gclid-parameter for adwords works like a charm until i re-enable realurl

**Comment by dmitryd** [comment]
You should not use `banUrlsRegExp` but `ignoredGetParametersRegExp`. Banning will completely disable caching of URLs for this URL. You do not want that for the detail page. Actually it must be cached if you want it to work correctly.

Modify your config as follows:
```php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] = array(
  'yourdomain.de' => array(
    'cache' => array(
      'ignoredGetParametersRegExp' => '/^(?:gclid|utm_[a-z]+|pk_campaign|pk_kwd|TSFE_ADMIN_PANEL.*)$/',
    ),
  ),
  ...
```

**Comment by amenk** [comment]
We still have that problem with the recent RealURL 2.2.1 version. As soon as we call

 curl -I "http://example.com/de/startseite/?gclid=CNbG87SR2MgCFQgFwwod_tEE8A&cHash=733179849e63234c5f744cfb9d03d3e3"

The cache gets messed up and we get a redirect loop.

We already have the config

            'cache' => array(
	            'ignoredGetParametersRegExp' => '/^(?:gclid|utm_[a-z]+|pk_campaign|pk_kwd|TSFE_ADMIN_PANEL.*)$/'
            ),


With ban it also does not seem to work. This is killing our site regularly.

**Comment by amenk** [comment]
I think I solved this - with removing gclid from the ignored and then banning it:


            'cache' => array( // https://stackoverflow.com/a/41967200/288568  - Ticket 25335
	            'banUrlsRegExp' => '/gclid|tx_solr|tx_indexed_search|(?:^|\?|&)q=/',
	            'ignoredGetParametersRegExp' => '/^(?:utm_[a-z]+|pk_campaign|pk_kwd|TSFE_ADMIN_PANEL.*)$/'
            ),

**Comment by dmitryd** [comment]
@amekn Add gclid to TYPO3 settings to ignore in cHash.
