### ISSUE TITLE
regeneration of configuration executed only once ever

### ISSUE THREAD

**Issue by kludikovsky** [dmitryd/typo3-realurl#381]
The regeneration of the configuration (autogen) as descirbed in https://github.com/dmitryd/typo3-realurl/issues/184 by deleting the config file does not work as it is IMHO executed only once ever by defintion.

`performAutomaticConfiguration` is executed whenever the ConfigurationReader is instantiated, but due to the 
`if (!isset($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']) && $this->extConfiguration['enableAutoConf'])` https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Configuration/ConfigurationReader.php#L289
the configuration is executed only once after installation, as `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']` is as of then set for all times (bascially always true).

**Suggestion**
Add in the setup of realurl another param (maybe called 'forceAutoGen') which can be set to true, which forces an autogen and is afterwards cleared (reset to false) This would give a single shot for the regen.

Or (and there I don't know enough, but have read about somewhere) have a button which triggers a autogen as part of the module settings. This could also avoid the permanent calling of the `performAutomaticConfiguration` .

**Env**
T3: 7.6.12
realurl: 2.1.5 (from TER)

**Comment by dmitryd** [comment]
> the configuration is executed only once after installation, as $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] is as of then set for all times (bascially always true).

Search for the extension that sets it. There are extensions that behave badly by doing something like this:
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT']['postVarsSets']['myext'] = array(...);
```

This breaks autoconfiguration and it is not a realurl's fault.

**Comment by kludikovsky** [comment]
It seems to be mindshape_seo, as
https://github.com/mindshape-GmbH/mindshape_seo/blob/master/ext_localconf.php does exactly what you said.

While multishop seems to do it correctly https://github.com/bvbmedia/multishop/blob/master/class.tx_multishop_realurl.php

**Comment by dmitryd** [comment]
@kludikovsky Thank you :)
