### ISSUE TITLE
Expiration questions

### ISSUE THREAD

**Issue by lochmueller** [dmitryd/typo3-realurl#382]
Hey RealURL guys. 

I take a look into the code of the expire settings of the tx_realurl_pathdata table. 
I also check the handling of the TableGarbageCollectionTask::handleTable function.

I have a few comprehension questions. 
The expire field is default "0" (no expiration) and is set to the date of expiration, right?

So there are a few questionable lines of code.

Why we check here the expire=0 and drop only valid entries and not the one that have also a expiration date?
https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Cache/DatabaseCache.php#L75

Should we add a "expire > 0" to drop only the expired one and not the entries that are still in "no expiration"?
https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Cache/DatabaseCache.php#L63

Regards,
Tim

**Comment by dmitryd** [comment]
> Why we check here the expire=0 and drop only valid entries and not the one that have also a expiration date?

Because expired path cache entries must remain. They exist for seo reasons to redirect from old paths to new paths.

> Should we add a "expire > 0" to drop only the expired one and not the entries that are still in "no expiration"?
Yes. Thank you for finding this!
