### ISSUE TITLE
UrlDecoder: Wrong path never throws 404

### ISSUE THREAD

**Issue by andreknieriem** [dmitryd/typo3-realurl#383]
In line 463 in UrlDecoder.php you set $currentPid = $this->rootPageId if no result is found. At the end
``
		if ($result || (int)$currentPid === (int)$this->rootPageId) {
			$pathSegments = $remainingPathSegments;
		} else {
			$this->throw404('Cannot decode "' . implode('/', $pathSegments) . '"');
		} 
``

This condition is always true and I always get the Startpage if a 404 error occured.

**Comment by dmitryd** [comment]
Firsts, if the condition is always true for you, it does not mean it is always true for everybody else :) There are a lot of cases when it may become false. Did you test with shortcuts and mount points, for example?

Secondly, I can get 404s for wrong paths (just tested). If this does not happen to you, it means there is something else. This particular place is not the pace that normally throws a 404. Normally you will either see a "not a postVar as expected" or a error message from TYPO3. Did you check that your 404 page is configured? If not, you will see the start page.

Sorry, this is not reproducible at the moment.
