### ISSUE TITLE
Automatic configuration is disabled while using spURL hooks

### ISSUE THREAD

**Issue by dustinjeuck** [dmitryd/typo3-realurl#389]
Classes\Configuration\ConfigurationReader.php (Line 288):
!isset($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'])

If you use "decodeSpURL_preProc" or "encodeSpURL_postProc" the automatic build of the realurl configuration file will be disabled.

Bug or feature? Can you explain, why this condition exists?

**Comment by dmitryd** [comment]
Realurl creates automatic configuration only if it does not exist (= not set as a php array). If you want to  set something to `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']`, you must set it after realurl does its work. Make your extension dependent on realurl. It will be loaded after realurl and will add hooks when the config is available already.
