### ISSUE TITLE
Language links include page title in wrong language

### ISSUE THREAD

**Issue by josh-makalo** [dmitryd/typo3-realurl#39]
If you are viewing a page in an alternative language and have a link included that is intended to switch to the default language (as is very common with a language selection menu), the RealURL encoding detects and includes the correct value for the L Get variable (whether as parameter or as preVar), but builds the pagePath from the alternative language page titles, instead of the default language ones.

A simple example: (sub)page with title "Contacto" (Spanish, default) or "Contact" (English, alternative, lang id 1). Being on the Spanish version, the language menu works perfectly (e.g. links "/contact**o**?L=0" and "/contact?L=1"). On the English version however, the links are "/contact?L=0" and "/contact?L=1"

This bug is new in RealURL 2. If found it after updating RealURL using TYPO3 7.6.4 with the _page.languageMenu_ viewhelper from the extension _vhs_. Later I tried it on a brand new 7.6.4 installation with the extension _sr_language_menu_, with the same effect.

**Comment by dmitryd** [comment]
Thank you for reporting. The next release with the fix will be made later today.
