### ISSUE TITLE
Possible bug within UrlDecoder->isSpeakingUrl()

### ISSUE THREAD

**Issue by vaxul** [dmitryd/typo3-realurl#398]
TYPO3 CMS 7.6.15
RealURL 2.1.5

Hi @dmitryd 

I have an installation with multiple sites/languages and a working _DOMAINS configuration in combination with domain records which looks like this:
```PHP
<?php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] = [
    '_DEFAULT' => [
        'init' => [
            'appendMissingSlash' => 'ifNotFile,redirect',
            'emptyUrlReturnValue' => '/',
        ],
        'pagePath' => [],
        'fileName' => [
            'defaultToHTMLsuffixOnPrev' => 0,
            'acceptHTMLsuffix' => 1,
            'index' => [
                'print' => [
                    'keyValues' => [
                        'type' => 98,
                    ],
                ],
            ],
        ],
        'preVars' => [
            [
                'GETvar' => 'L',
                'valueMap' => [],
                'noMatch' => 'bypass',
            ],
        ],
        'fixedPostVars' => [],
    ],
];

/*
 * Add _DOMAINS configuration related to application context
 * @see https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#_domains
 */

/**
 * @param array $langDomainMapping
 */
function projectRealUrlLanguageDomainMapping($langDomainMapping)
{
    /**
     * @var int   $languageUid
     * @var array $domainArray
     */
    foreach ($langDomainMapping as $languageUid => $domainArray) {
        foreach ($domainArray as $domain) {
            $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DOMAINS']['encode'][] = array(
                'ifDifferentToCurrent' => true,
                'GETvar' => 'L',
                'value' => $languageUid,
                'useConfiguration' => '_DEFAULT',
                'urlPrepend' => is_array($domain) ? $domain[1] : 'http://' . $domain,
            );
            $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DOMAINS']['decode'][is_array($domain) ? $domain[0] : $domain] = array(
                'GETvars' => array(
                    'L' => $languageUid,
                ),
                'useConfiguration' => '_DEFAULT',
            );
        }
    }
}

$currentApplicationContext = \TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext();
switch ((string)$currentApplicationContext) {
    case 'Production/Example':
        projectRealUrlLanguageDomainMapping([
            // DE
            '0' => [
                [
                    'proxy.de.example.de',
                    'https://www.example.de/,
                ],
                'de.example.de',
            ],
            // EN
            '1' => [
                [
                    'en-proxy.example.de',
                    'https://www.example.com/,
                ],
                'en.example.de',
            ],
        ]);
        break;
    case 'Production/AnotherExample':
        projectRealUrlLanguageDomainMapping([
            // EN
            '0' => [
                [
                    'en-proxy.another-example.de',
                    'https://www.another-example.com/en/,
                ],
                'en.another-example.com',
            ],
            // PL
            '2' => [
                [
                    'pl-proxy.another-example.com',
                    'https://www.another-example.com/pl/,
                ],
                'pl.another-example.com',
            ],
            // CZ
            '3' => [
                [
                    'cz-proxy.another-example.com',
                    'https://www.another-example.com/cz/,
                ],
                'cz.another-example.com',
            ],
            // HU
            '4' => [
                [
                    'hu-proxy.another-example.com',
                    'https://www.another-example.com/hu/,
                ],
                'hu.another-example.com',
            ],
            // CH
            '5' => [
                [
                    'ch-proxy.another-example.com',
                    'https://www.another-example.com/ch/,
                ],
                'ch.another-example.com',
            ],
            // AT
            '6' => [
                [
                    'at-proxy.another-example.com',
                    'https://www.another-example.com/at/,
                ],
                'at.another-example.com',
            ],
        ]);
        break;
    case 'Development/Example':
        projectRealUrlLanguageDomainMapping([
            // DE
            '0' => [
                'dg.example.develop.de',
            ],
            // EN
            '1' => [
                'dg.en.example.develop.de',
            ],
        ]);
        break;
    case 'Development/AnotherExample':
        projectRealUrlLanguageDomainMapping([
            // EN
            '0' => [
                'dg.en.another-example.develop.de',
            ],
            // PL
            '2' => [
                'dg.pl.another-example.develop.de',
            ],
            // CZ
            '3' => [
                'dg.cz.another-example.develop.de',
            ],
            // HU
            '4' => [
                'dg.hu.another-example.develop.de',
            ],
            // CH
            '5' => [
                'dg.ch.another-example.develop.de',
            ],
            // AT
            '6' => [
                'dg.at.another-example.develop.de',
            ],
        ]);
        break;
    default:
        break;
}
```

I am looking into the possibilities of removing the dependency of the domain records in TYPO3, because they are a lot and every new coworker has to add even more domain records. (It's error-prone and hard for the beginners.) In the example above, you only see the my development example-domains.

My first though was: I add the rootpage_id for each context. 

So I moved the _DEFAULT config to domain specific config and changed the context-switch a bit:
```PHP
<?php

/*
 * Add _DOMAINS configuration related to application context
 * @see https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#_domains
 */

/**
 * @param int $rootpageUid
 * @param array $langDomainMapping
 */
function medienwerftProjectRealUrlLanguageDomainMapping($rootpageUid, $langDomainMapping)
{
    /**
     * @var int   $languageUid
     * @var array $domainArray
     */
    foreach ($langDomainMapping as $languageUid => $domainArray) {
        foreach ($domainArray as $domain) {
            $_DEFAULT = [
                'init' => [
                    'appendMissingSlash' => 'ifNotFile,redirect',
                    'emptyUrlReturnValue' => '/',
                ],
                'pagePath' => [
                    'rootpage_id' => $rootpageUid,
                ],
                'fileName' => [
                    'defaultToHTMLsuffixOnPrev' => 0,
                    'acceptHTMLsuffix' => 1,
                    'index' => [
                        'print' => [
                            'keyValues' => [
                                'type' => 98,
                            ],
                        ],
                    ],
                ],
                'preVars' => [
                    [
                        'GETvar' => 'L',
                        'valueMap' => [],
                        'noMatch' => 'bypass',
                    ],
                ],
                'fixedPostVars' => [],
            ];
            $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][is_array($domain) ? $domain[0] : $domain] = $_DEFAULT;
            $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DOMAINS']['encode'][] = array(
                'ifDifferentToCurrent' => true,
                'GETvar' => 'L',
                'value' => $languageUid,
                'useConfiguration' => '_DEFAULT',
                'urlPrepend' => is_array($domain) ? $domain[1] : 'http://' . $domain,
            );
            $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DOMAINS']['decode'][is_array($domain) ? $domain[0] : $domain] = array(
                'GETvars' => array(
                    'L' => $languageUid,
                ),
                'useConfiguration' => '_DEFAULT',
            );
        }
    }
}

$currentApplicationContext = \TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext();
switch ((string)$currentApplicationContext) {
    // [...]
    case 'Development/Example':
        projectRealUrlLanguageDomainMapping(
            1
            ,[
            // DE
            '0' => [
                'dg.example.develop.de',
            ],
            // EN
            '1' => [
                'dg.en.example.develop.de',
            ],
        ]);
        break;
    case 'Development/AnotherExample':
        projectRealUrlLanguageDomainMapping(
            2
            ,[
            // EN
            '0' => [
                'dg.en.another-example.develop.de',
            ],
            // PL
            '2' => [
                'dg.pl.another-example.develop.de',
            ],
            // CZ
            '3' => [
                'dg.cz.another-example.develop.de',
            ],
            // HU
            '4' => [
                'dg.hu.another-example.develop.de',
            ],
            // CH
            '5' => [
                'dg.ch.another-example.develop.de',
            ],
            // AT
            '6' => [
                'dg.at.another-example.develop.de',
            ],
        ]);
        break;
    default:
        break;
}
```

If I login into the backend with each domain, the config looks fine within the configuration module. In the frontend nothing changed as expected while the domain records exists.

If I disable all domain records and try each domain I get the following result:
- All Example-Domains work, f.e.:
-- dg.example.develop.de
-- dg.en.example.develop.de
- All AnotherExample-Domains **doesn't** work, f.e.:
-- dg.en.another-example.develop.de: Shows dg.en.example.develop.de
-- dg.pl.another-example.develop.de: Shows "Page Not Found - Reason: Page is not available in the requested language.", while no PL translation exists for example.develop.de

So I've tried to debug the extension.

For dg.pl.another-example.develop.de the rootPageId in $this within this line https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L149 has the correct value of "2". 

I though it seems that the problem lies within $this->isSpeakingUrl(). Which is FALSE for the URL http://dg.corporate.pl.vg.webdev.medienwerft.de/.

After that I found out if I try to open a subpage like http://dg.corporate.pl.vg.webdev.medienwerft.de/test/, it work correct! *nearly happy* :-) 

Conclusion: Only the homepages of AnotherExample doesn't work. Sub-pages working fine.
http://dg.pl.another-example.develop.de/ - siteScript is '' => doesn't work
http://dg.pl.another-example.develop.de/test/ - siteScript is 'test/' => does work

But now comes the point why I'm writing you. I'm not so sure were, in which part of realurl, to suggest a good fix for the problem.

Do you have any idea?

Best regards

**Comment by dmitryd** [comment]
I cannot suggest anything because I only fix bugs here. If you are sure you found a bug, please post. If you need support from me, this is not free and you need to contact me by email for quote.

I have daily work, so any other work takes my free time. If I have to tell my family that I have to work more, I want to get something in return.

Bug fixing is free. Support is not.

**Comment by vaxul** [comment]
> I have daily work, so any other work takes my free time. If I have to tell my family that I have to work more, I want to get something in return.

I'm with you. It's only fair.

>  If you are sure you found a bug, please post.

I not as deep in realurl as you but I would declare my found as bug.

## Short summary
### System
- TYPO3 CMS 7.6.15
- RealURL 2.1.5
- Multi-Site/-Domain setup
- Correct defined rootpage_id within the domain configuration 
- **without** domain records in the page tree

### What it does
Frontend call from the homepage of the secondary website lead into an error:
http://dg.pl.another-example.develop.de/
_Page Not Found - Reason: Page is not available in the requested language._ It basically look in the wrong place (homepage from the first website).
Frontend call from an sub-page of the secondary website works correct:
http://dg.pl.another-example.develop.de/test/ 

### What it should do
A Frontend call from the homepage of the secondary website should lead to the correct homepage.

### Why
As far as I found out I think it's a bug in UrlDecoder->isSpeakingUrl(), since the property siteScript for the homepage is empty. For a sub-page the siteScript is f.e. 'test/'.

I like to try to help as much a possible.

**Comment by dmitryd** [comment]
Realurl does not decode the home page url because there is no url to decode (it is always empty for the home page). It returns to TYPO3 and than TYPO3 tries to find page id. It works like that for about 10 years (since the very first draft of realurl).

In your cases it seems that TYPO3 can't find root page for the domain. You should fine out why. May be, you do not have a proper domain record there.

**Comment by vaxul** [comment]
> In your cases it seems that TYPO3 can't find root page for the domain.

As I wrote initially:
> I am looking into the possibilities of removing the dependency of the domain records in TYPO3... 

Short: nearly all configuration lies in the provider extension and the domain records are defined in the DB and redundant to the realurl configuration.

As I explained in the initial post: The UrlDecoder knows the correct rootPageId. Could realurl not easy use this? 
Maybe this is a too simple though?
>  If no URL == homepage, than link to UID from rootPageId

**Comment by dmitryd** [comment]
> I am looking into the possibilities of removing the dependency of the domain records in TYPO3...

Well, you have to use them in multidomain configuration. You can as well look into possibilities to get rid of PHP and still use TYPO3. It is nearly the same idea.

>  domain records are defined in the DB and redundant to the realurl configuration.

Realurl uses domain records only if it cannot find proper domains in the configuration. However realurl does not replace or change TYPO3 algorithm for domain search.

> Could realurl not easy use this?

Well, realurl could do many things. But I do not see why it should duplicate existing TYPO3 functionality.

If you want such thing, you have to make another extension.

**Comment by vaxul** [comment]
> Well, you have to use them in multidomain configuration. You can as well look into possibilities to get rid of PHP and still use TYPO3. It is nearly the same idea.
However realurl does not replace or change TYPO3 algorithm for domain search.
Well, realurl could do many things. But I do not see why it should duplicate existing TYPO3 functionality.

Okay, here you really have a point. In this case we have to stick with the functionality. 

Thank you for the time for the answers.

Best regards
