### ISSUE TITLE
Redis caching

### ISSUE THREAD

**Issue by dmitryd** [dmitryd/typo3-realurl#4]
Look into implementing Redis support either directly or through the TYPO3 caching framework (whatever is best).

**Comment by stucki** [comment]
Support for using Redis (or anything else) through the caching framework would be great!

**Comment by mischka** [comment]
Support of the caching framework would be better

**Comment by dmitryd** [comment]
Read the FAQ before posting, please.

**Comment by dmitryd** [comment]
https://packagist.org/packages/dmitryd/typo3-realurl-cf
https://github.com/dmitryd/typo3-realurl_cf
