### ISSUE TITLE
 PHP Parse error ???

### ISSUE THREAD

**Issue by 7D** [dmitryd/typo3-realurl#40]
Hi,

I'm running Typo3 6.2.19 on PHP 5.4.16 an got the following:

**PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /***/www/typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php on line 1019**

Code:
$this->configuration = GeneralUtility::makeInstance(ConfigurationReader::class, ConfigurationReader::MODE_DECODE);
	
What am I doing wrong?
Is PHP >= 5.5 mandatory for realurl 2.x?

**Comment by dmitryd** [comment]
Thank you for reporting. The update will be released today.
