### ISSUE TITLE
expireDays configuration fails and expired entries have priority

### ISSUE THREAD

**Issue by robinson2** [dmitryd/typo3-realurl#400]
In former versions it was possible to set a value for expireDays in the pagePath-section of the manual configuration (You could also deactivate the redirects with negative value like '-1').

This does not work anymore. A value of 30 days is always set, when a page is renamed. 

Even if 30 days is a good default value for seo, it should be possible to set a custom value or deactivate the redirects.

Also there's an issue with those redirects:

1. Create a new page "test"
2. Rename it to "example". A 30-days redirect from "test" to "example" will be created automatically.
3. You have changed your mind and decided, that you want both pages "example" and "test", so now you create another page "test". This new page will not be available for the next 30 days, because "test" is already redirecting to "example"

**Comment by dmitryd** [comment]
Go and delete the entry in the realurl module.

**Comment by dmitryd** [comment]
Related: #373

**Comment by robinson2** [comment]
Thanks! Will it be possible to disable the redirects or modify the value of 30 days, again?

**Comment by dmitryd** [comment]
There is a feature request for this but I am not sure when it will be implemented.

By the way, people say at #373 that the problem is solved in the recent realurl version.

**Comment by robinson2** [comment]
Yes, because of #313 I thought it worked. 

I've tried it now and I can't confirm it.
My test scenario from above still redirects to the old (renamed page) instead of showing the newly created page, with v 2.1.7.

**Comment by dmitryd** [comment]
You need to make sure that new page address is in the realurl cache. You need to navigate to the sitemap, for example. If it is not in the cache, the old entry will be used.

**Comment by robinson2** [comment]
I thought I had seen the cache entry in the realurl-module, but I must have been wrong, because now it works in my newly created test environment. Sorry.

**Comment by dmitryd** [comment]
No problem. Good that it works :)
