### ISSUE TITLE
no_cache param in autoconfiguration

### ISSUE THREAD

**Issue by gilbertsoft** [dmitryd/typo3-realurl#404]
Why don't you add no_cache param in autoconfig as you do with languages or domains?

I had the case after updating boostrap_package from 6 to 7 that this config was deleted after refreshing the autoconfig of realurl because boostrap_package 7 not longer sets this for the moment.

Here is the example what they did at version 6.2.10 onwards:

        $params['config']['preVars'] = array(
            '0' => array(
                'GETvar' => 'no_cache',
                'valueMap' => array(
                    'nc' => '1',
                ),
                'noMatch' => 'bypass'
            ),
        );

**Comment by dmitryd** [comment]
Because you should no use `no_cache` anywhere in production. Your code should use non-cacheable actions or plugins instead.

**Comment by gilbertsoft** [comment]
Ok, thanks for the infos. It's already done with non-cachable actions but the no_cache param is added too what's not necessary as you say.

Is this a valid statement for every TYPO3 version from 6.2 up to 8?

**Comment by dmitryd** [comment]
If you use `no_cache`, you force the following to happen:
1. All typoscript is parsed (text parsing)
1. All fluid templates are parsed
1. All plugins are executed
1. All content is assembled to the page

If you just use uncached action, the following happens:
1. Content is fetched from the cache
1. Content for the non-cache plugins is generated and substituted in the previously cached content

You can decide what is better :)

`no_cache` is evil (in general).

**Comment by gilbertsoft** [comment]
Yes, normally clear, but we have a special case, it's used with pages types e.g. to get the stock for products or a status answer from a payment provider (text and json request and responses) and there is no other content on the page, only the plugin with a non-cacheable action. I had a look at the code generating the urls to this page (with examples in the urilBuilder params):

		$this->uriBuilder
			->reset()
			->setTargetPageUid( $target )
			->setCreateAbsoluteUri( true || false )
			->setTargetPageType( 191351524 || 191351525 )
			->setUseCacheHash( false )
			->setNoCache( false )
			->setArguments( $params );

This code generates a no_cache=1 param. Is this wrong or possible in that special case?

**Comment by gilbertsoft** [comment]
I deactivated all no_cache settings and tested with non-cachable actions only and everything worked fine. Thanks for your support!
