### ISSUE TITLE
'appendMissingSlash' 'redirect' doesn't work

### ISSUE THREAD

**Issue by Gernott** [dmitryd/typo3-realurl#405]
Redirect when slash is missing doesn't work.
Tested in Chrome after deleting all browser-cache data.

This URL:
http://www.xxxxx.de/referenzen/projekte
Should redirect to (but doesn't):
http://www.xxxxx.de/referenzen/projekte/

My config (Realurl Autoconfig):
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']=array (
  'www.xxxxx.de' => 
  array (
    'init' => 
    array (
      **'appendMissingSlash' => 'ifNotFile,redirect',**
      'emptyUrlReturnValue' => '/',
    ),
    'pagePath' => 
    array (
      'rootpage_id' => '2',
    ),
    'fileName' => 
    array (
      'defaultToHTMLsuffixOnPrev' => 0,
      'acceptHTMLsuffix' => 1,
      'index' => 
      array (
        'print' => 
        array (
          'keyValues' => 
          array (
            'type' => 98,
          ),
        ),
      ),
    ),
    'postVarSets' => 
    array (
      '_DEFAULT' => 
      array (
        'news' => 
        array (
          0 => 
          array (
            'GETvar' => 'tx_news_pi1[news]',
            'lookUpTable' => 
            array (
              'table' => 'tx_news_domain_model_news',
              'id_field' => 'uid',
              'alias_field' => 'title',
              'useUniqueCache' => 1,
              'useUniqueCache_conf' => 
              array (
                'strtolower' => 1,
                'spaceCharacter' => '-',
              ),
            ),
          ),
        ),
      ),
    ),
  ),
  'xxxxx.de' => 'www.xxxxx.de',
);

**Comment by dmitryd** [comment]
Tested, works fine for me.
