### ISSUE TITLE
Duplicates in `tx_realurl_urldata` lead to "cHash comparison failed" 404 error

### ISSUE THREAD

**Issue by sgrossberndt** [dmitryd/typo3-realurl#406]
We experience 404 errors with error message `Reason: Request parameters could not be validated (&cHash comparison failed)` on several websites using `realurl`.

For a single url, e.g. `foo/record-details/record/549/name/index.html` multiple entries exist in the `tx_realurl_urldata` table:

```
'uid','page_id','rootpage_id','original_url','speaking_url','request_variables','expire'
'119','25','2','cHash=7c95587071f915450b197843961ad842&id=25&tx_extension_pi[record][title]=name&tx_extension_pi[record][uid]=549','foo/record-details/record/549/name/index.html','{"id":"25","tx_extension_pi[record][uid]":"549","tx_extension_pi[record][title]":"name","cHash":"7c95587071f915450b197843961ad842"}','0'
'971','25','2','cHash=153b6d0930318049ec0e39e0470201ea&id=25&tx_extension_pi[detailType]=&tx_extension_pi[record][title]=name&tx_extension_pi[record][uid]=549','foo/record-details/record/549/name/index.html','{"id":"25","tx_extension_pi[detailType]":"","tx_extension_pi[record][title]":"name","tx_extension_pi[record][uid]":"549","cHash":"153b6d0930318049ec0e39e0470201ea"}','0'
'3958','25','2','cHash=07d274c226e9ed4b6af26a1234b7cb7f&id=25&tx_extension_pi[record][title]=name&tx_extension_pi[record][uid]=549','foo/record-details/record/549/name/index.html','{"id":"25","tx_extension_pi[record][title]":"name","tx_extension_pi[record][uid]":"549","cHash":"07d274c226e9ed4b6af26a1234b7cb7f"}','0'
```

For the second row its kind of understandable because of the additional empty variable `"tx_extension_pi[detailType]":""` but the entry created first (uid 119) and last (uid 3958) have exactly the same `original_url` - the only difference is in the `request_variables`: the order of the parameters is different.

Could sorting of the parameters in `request_variables` help?

**Comment by dmitryd** [comment]
No, it cannot.

It seems that `119` entry was created long time ago. Its cHash is different for the same set of parameters. Most likely it was created before [this security bulletin](https://typo3.org/teams/security/security-bulletins/typo3-core/typo3-core-sa-2016-022/) and you enabled id inclusion into cHash without clearing realurl tables, which is a user error. I see no other explanation to your data.

Clear realurl tables.

**Comment by sgrossberndt** [comment]
No, your assumption is wrong. All of the entries were created after `cHashIncludePageId` was set to true. I have truncated all realurl tables at least twice after that but the wrong chashes keep re-appearing. After filing the bug report 6 days ago I truncated the tables again to have the pages visible without an error again - I just looked them up again and there are multiple entries again.

**Comment by dmitryd** [comment]
Okay.

Realurl does not create cHash. It gets cHash from a `typolink` in TYPO3. This means that bad cHash is _passed_ to realurl by your php or typoscript code. You'll have to find where. Realurl can do nothing here. It just encodes what it is given.
