### ISSUE TITLE
realurl saves link generated in paginator without cHash

### ISSUE THREAD

**Issue by olek07** [dmitryd/typo3-realurl#411]
Hello!
Why does realurl save links generated in paginator to the table tx_realurl_urldata?
For example: /en/listing-for-transaction/?tx_gbaccount_transactions[@widget_0][currentPage]=2
If I add some get-parameter to it /en/listing-for-transaction/?tx_gbaccount_transactions[@widget_0][currentPage]=2&FOO=BAR, this link also is saving. Is it an error in realurl?

**Comment by dmitryd** [comment]
Please, see the wiki where you can ask support questions.
