### ISSUE TITLE
realurl saves links without cHash

### ISSUE THREAD

**Issue by olek07** [dmitryd/typo3-realurl#412]
Hello!

realurl saves in the table tx_realurl_urldata links without cHash, It makes possible the DB-flooding, if a hacker adds some get-parameter to the URL:

L=1&id=14&tx_gbaccount_transactions[@widget_0][currentPage]=3&foo=bar
L=1&id=14&tx_gbaccount_transactions[@widget_0][currentPage]=3&asd=123 etc

**Comment by dmitryd** [comment]
Realurl saves links as they are provided by TYPO3. Fix your installation.

This is not a bug in realurl.

**Comment by olek07** [comment]
No, not my extension is responsable for it. The fluid paginator generates the links like this:

`/transaction-list/?tx_gbaccount_transactions%5B%40widget_0%5D%5BcurrentPage%5D=2&cHash=a94821be437fbb7bd7d78c043d6b3809`

but if I modified the link in the browser to: 

`/transaction-list/?tx_gbaccount_transactions%5B%40widget_0%5D%5BcurrentPage%5D=2&asd=qwe`

the paginator generates the links to the another pages (1,3,4,5 etc) WITH this parameter. So it is possible to flood as well with cHash as without cHash.

**Comment by dmitryd** [comment]
Realurl does not add links to cache on decoding unless you use a very ancient version. It only adds links that actually exist on your site.

**Realurl processes only links that TYPO3 passes to it**. If realurl gets such bad links, it means you allow such bad links on your site. Also it means that **your** implementation is insecure. Realurl has no choice here. It **must** process everything that TYPO3 sends to it. If it gets such links, it means **you** made sure it can get wrong links. Your job is to ensure that all links are correct. Realurl will not do this work for you. It does not know what is correct and what is not. It just plain simple encodes what is given to it. If you give one link, it will encode and store one link. If you give one thousand links, realurl will encode and store one thousand links. **Realurl cannot know if the link is correct or not, it just encodes it as is.** That's all.

Do your job and secure your site.

**Comment by olek07** [comment]
yes, but there is no opportunity to prohibit the user to add some get-parameters to the URL. TYPO3 has also no mechanism for "white list" of the get-parameters. You can't say, don't take to URL any get-parameters beside of `asd`, `yxc`, `qwe `etc. And realurl has no configuration option for it. So the actual functionality of f:widget.paginate and realurl allows the DB-flooding

**Comment by dmitryd** [comment]
No flooding. There is a clean up for the database if it reaches too many entries.

Again: realurl will always encode what TYPO3 asks to encode. Make sure your site does not ask to encode bad URLs. Realurl will not do your work. It is your responsibility to ask to encode proper urls.

**Comment by dmitryd** [comment]
Added a [FAQ entry](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#i-see-a-lot-of-strange-entries-in-the-realurl-module).

**Comment by olek07** [comment]
ok. Thank you!

**Comment by olek07** [comment]
one more question. was is too many entries? When does realurl clean up the databases?
