### ISSUE TITLE
Backend breaks when trying to resolve root page id from domain record in a multidomain/multiroot setup.

### ISSUE THREAD

**Issue by marvin-martian** [dmitryd/typo3-realurl#413]
When trying to resolve the root page id from the backend in a multidomain/multi-root setup an exception would be thrown.

> 'RealURL was not able to find the root page id for the domain "' . $this->utility->getCurrentHost()

In such a situation the 'hostName' property in the \DmitryDulepov\Realurl\Configuration\ConfigurationReader was not being set. 

I made a quick fix for myself if you are interested.

```php
/**
 * Sets the root page id from domain records.
 *
 * @return bool
 */
protected function setRootPageIdFromDomainRecord() {
    $result = FALSE;
    $hostname = $this->hostName;
    if (empty($hostname)) {
        $rootLine = BackendUtility::BEgetRootLine($this->urlParameters['id']);
        $hostname = BackendUtility::firstDomainRecord($rootLine) or $this->utility->getCurrentHost() ;
    }
    $domainRecord = BackendUtility::getDomainStartPage($hostname);
    if (is_array($domainRecord)) {
        $this->configuration['pagePath']['rootpage_id'] = (int)$domainRecord['pid'];
        $result = TRUE;
    }
    return $result;
}
```
Of course there might be a better holistic approach of determining the correct root page id of the current page. Resolving the root page id from the first domain record from the current page rootline might be a general better approach though. I think it needs to be generally rethought to be more robust instead of throwing exceptions when things 'apparently' get too difficult.
Realurl versions affected 2.1.6+

**Comment by dmitryd** [comment]
Not a bug. You have to configure realurl manually for such cases or set domain records or set `is_siteroot` flags properly.

**Comment by marvin-martian** [comment]
I did configure it correctly and it was working with a previous version of realurl. So it is a introduced bug as it is a break of previous established behaviour. But easy... I managed to Xclass myself around the problem.

**Comment by dmitryd** [comment]
Realurl does not work in BE. Search for the extension that tries to use realurl directly there and get rid of it because it is not the right use.

**Comment by marvin-martian** [comment]
The extension is newsletter, quite a established extension, and the ONLY actively developed mass mailing extension available for Typo3. Many organizations may wish to send their own newsletters instead of using third party services. The need exists. The extension builds a HTML-Mail from a page record to send as a mass mailing. It renders the page from a BE context as the admin queues the newletter sending from the BE, it then gets fired off via the scheduler. 

It was working fine with Realurl in a multi-domain setup up until 2.1.6. If you do a diff between ConfigurationReader 2.1.5 and 2.1.6 there is a clear change of behaviour in the method. 

It is strange that you say it does not work in the BE because intentionally or not it **has** been working up until 2.1.5. Having it work in from a BE context is desirable for such purposes as the newsletter extension.

I also don't see any reasons why it shouldn't continue to do so. The establishment of "right use" seems to be a matter of opinion rather than technical possibility or merit. It is possible to make it work again.
