### ISSUE TITLE
Different encoding of query string in UrlEncoder and UrlDecoder results in page not found

### ISSUE THREAD

**Issue by RoyalKnight** [dmitryd/typo3-realurl#414]
Remaining query string parameters are handled differently in UrlEncoder and UrlDecoder. Whereas query string is rawurlencoded by UrlEncoder in method `addRemainingUrlParameters()` and therefore written rawurlencoded to the cache, UrlDecoder uses the urldecoded variant converted by `removeIgnoredParametersFromQueryString()` and later used to retrieve by `getUrlFromCacheBySpeakingUrl()`.

Example:
If a URL contains `foo[bar]=val`, this will be rewurlencoded and cached as `foo%5Bbar%5D=val` by UrlEncoder. Later the UrlDecoder tries to get result from cache with `foo[bar]=val`.

**Comment by RoyalKnight** [comment]
Changing
```php
protected function createQueryStringFromParameters(array $parameters) {
	return substr(GeneralUtility::implodeArrayForUrl('', $parameters), 1);
}
```
to
```php
protected function createQueryStringFromParameters(array $parameters) {
	return substr(GeneralUtility::implodeArrayForUrl('', $parameters, '', false, true), 1);
}
```
fixes this behaviour, but I'm not sure if this leads to a problem somewhere else.

**Comment by dmitryd** [comment]
Thank you. I checked usages of the function and all should be fine with this change.
