### ISSUE TITLE
Show "Speaking URL path segment" also if "Exclude from speaking URL" is enabled

### ISSUE THREAD

**Issue by vmans** [dmitryd/typo3-realurl#417]
Now, the field "Speaking URL path segment" is hidden if "Exclude from speaking URL" is enabled. But the field "Speaking URL path segment" must be visible and writeable all the time.

The path will not be visible in the frontend when a child page is currently active, but it is visible in the frontend when this page is currently active.

Now to make it work, we have to disable "Exclude from speaking URL" first which causes a "Save page" and that is not desired.

Thanks!

**Comment by dmitryd** [comment]
Thank you!
