### ISSUE TITLE
Shortcut leads to 404

### ISSUE THREAD

**Issue by markuskappe** [dmitryd/typo3-realurl#42]
When I configure a page as shortcut (first subpage or absolute page id), the page is not callable. Other pages work fine, the generated link look OK, but when I click the link in the menu, I get a 404.
When I enable "Exclude from speaking URL" on the shortcut page, everything works fine again (of course the link differs).
I use TYPO3 6.2.19; updated from the latest realurl 1; executed the database updates; use the autoconf (for debugging - my special configuration had the same problem)

**Comment by markuskappe** [comment]
Complete 404 message: 
Reason: Segment "mypagename" was not a keyword for a postVarSet as expected on page with id=1.

**Comment by dmitryd** [comment]
I cannot reproduce it. Please, post your config.

**Comment by markuskappe** [comment]
unserialized it for readability; generated by autoconf feature
```
array (
  '_DEFAULT' => 
  array (
    'init' => 
    array (
      'appendMissingSlash' => 'ifNotFile,redirect',
      'emptyUrlReturnValue' => '/',
    ),
    'pagePath' => 
    array (
      'rootpage_id' => '1',
    ),
    'fileName' => 
    array (
      'defaultToHTMLsuffixOnPrev' => 0,
      'acceptHTMLsuffix' => 1,
      'index' => 
      array (
        'print' => 
        array (
          'keyValues' => 
          array (
            'type' => 98,
          ),
        ),
      ),
    ),
    'postVarSets' => 
    array (
      '_DEFAULT' => 
      array (
        'news' => 
        array (
          0 => 
          array (
            'GETvar' => 'tx_news_pi1[news]',
            'lookUpTable' => 
            array (
              'table' => 'tx_news_domain_model_news',
              'id_field' => 'uid',
              'alias_field' => 'title',
              'useUniqueCache' => 1,
              'useUniqueCache_conf' => 
              array (
                'strtolower' => 1,
                'spaceCharacter' => '-',
              ),
            ),
          ),
        ),
      ),
    ),
  ),
)
```

**Comment by neonaut** [comment]
same problem here, I enabled automatic configuration.

**Comment by neonaut** [comment]
I get the same error msg with disabled pages in the rootline . I have a fresh Typo3 6.2.19 website with no own realurl configuration, just auto config.

**Comment by dmitryd** [comment]
Disabled pages in the rootline usually break the rootline and does not allow browsing.

**Comment by jdequeant** [comment]
Same problem, no page disabled in the rootline.

**Comment by Kephson** [comment]
Same problem for me only when I'm logged in in TYPO3 backend and it works when I'm not logged in.
TYPO3 7.6.4

**Comment by dmitryd** [comment]
Yes, reproduced. Going to fix.

**Comment by Kephson** [comment]
\DmitryDulepov\Realurl\Utility->getCache() produces the problem, I think you still found out the problem.
Why is the cache initialized as NullCache when backend user is logged in? Is there a strange behaviour or problems?

**Comment by dmitryd** [comment]
Cache must be null when the BE user is logged in because BE user can see some pages that normal visitors cannot see (for example, hidden pages). If it is not null, cache may get wrong entries.

**Comment by dmitryd** [comment]
Those, who want to help with testing, try this branch: https://github.com/dmitryd/typo3-realurl/tree/feature/bug_42

You will need to clear both path cache and url cache. Sorry about that. Alternatively delete cache entries for shortcut page (source).

To clear caches using sql:
```
truncate tx_realurl_urlcache;
truncate tx_realurl_pathcache;
```

**Comment by Kephson** [comment]
Hi Dmitry,
thanks for the fast update! I tested your branch with the fix and for me it's working like expected.

**Comment by dmitryd** [comment]
Okay, good. Let's see if works for somebody else too. If yes, I will merge it.

**Comment by jdequeant** [comment]
Works for me !! Thanks for all your hard work.

**Comment by dmitryd** [comment]
You can now update to release 2.0.3, which contains the fix.

**Comment by stekna** [comment]
i still get this error with fresh installed realurl 2.0.10 (typo3 is on 7.6.4). 
e.g. error on "normal page"
```
- shortcut-page
-- sub-shortcut-page
--- normal page (error)
```
e.g. no error on "normal page"
```
- shortcut-page
-- normal page (no error)
```

**Comment by ogrosko** [comment]
Can confirm
Same problem at typo3 v7.6.6 and realurl v2.0.14
