### ISSUE TITLE
Option init/pagePath/languageExceptionUids not working?

### ISSUE THREAD

**Issue by mbrodala** [dmitryd/typo3-realurl#430]
I just tried to set `init/pagePath/languageExceptionUids` but couldn't see any difference.

To test this I have a setup with German as default language and English as translation. Now I've set `    'languageExceptionUids' => '1'` and even flushed all entries but I still get URLs based on the English page titles. I did expect to get German URLs in English instead.

Am I missing something?

**Comment by dmitryd** [comment]
> even flushed all entries

Path data also?

**Comment by dmitryd** [comment]
Oh, you have a wrong option path :) It is not `init/pagePath/languageExceptionUids` but just `pagePath/languageExceptionUids`.

**Comment by mbrodala** [comment]
Dude, that's confusing. ;-) I'll try that.

**Comment by mbrodala** [comment]
Alright, that was the issue, works perfectly fine now.
