### ISSUE TITLE
Broken home page with realurl >2.0.15

### ISSUE THREAD

**Issue by Shentao83** [dmitryd/typo3-realurl#431]
Hi there, 

- I use Typo3 6.2.30
- realurl 2.0.15

Default language segments are enabled (like described here https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-languages)

Behaviour until now: When I enter the website, it goes directly to www.domain.com/de.html. Everything fine so far.

When i upgrade realurl to **anything** higher than 2.0.15, the website initally goes to www.domain.com instead of www.domain.com/de.html. 

When I manueally enter www.domain.com/de.html or when I click on the logo or breadcrumb to return to the home page, I get a 404. Other languages like www.domain.com/en.html still work fine. 

All other subpages are working fine, too.

**Comment by dmitryd** [comment]
Please, ask for help in places described in "Getting help" on the wiki.
