### ISSUE TITLE
Purpose of path cache?

### ISSUE THREAD

**Issue by mbrodala** [dmitryd/typo3-realurl#432]
I wonder what the purpose of the path cache is in addition to the URL data cache. It is seemingly redundant since path info is also present in the latter. Can you enlighten me?

And I also wonder why there is no button to flush the path cache (for development) similar to the URL cache. ;-)

**Comment by dmitryd** [comment]
Please, do not ask questions in the bug tracker. This place is only for bugs.

**Comment by mbrodala** [comment]
You're right, I'll ask in the TYPO3 Slack.
