### ISSUE TITLE
[FEATURE] Warning if another page uses same title => collidation

### ISSUE THREAD

**Issue by chrisi51** [dmitryd/typo3-realurl#434]
wouldnt it be smart to give a warning message in speaking urls backend module if another page have the same title and is collidating with the page which u r checking right now?

would help to debug human error

Best way would be to show the page ids with language uid, which share the same title and collidate with each other. 

We talked about in Slack: https://typo3.slack.com/archives/realurl/p1489400547958047

**Comment by dmitryd** [comment]
![url-conflict](https://cloud.githubusercontent.com/assets/306133/24396648/9b118eb2-13ac-11e7-80e7-153fa3dc78a7.png)

Current work in progress.

**Comment by adrienjacob** [comment]
Would be very useful & user friendly indeed, as some URL conflict
situations can be sometimes tricky to figure out (path override / exclude
from / mountpoints etc.).
Do you think the warning message could also appear in other back-end
modules (eg. page) ?

2017-03-28 10:49 GMT+02:00 Dmitry Dulepov <notifications@github.com>:

**Comment by dmitryd** [comment]
No because in realurl I have to scan only 10 entries for duplicates. But in any other module I will have to scan potentially thousands of entries for duplicates.

Problems usually happen on certain pages, so people may go to the Speaking Url module and check for the problematic page.

**Comment by dmitryd** [comment]
Final version:

![url-conflict-2](https://cloud.githubusercontent.com/assets/306133/24398537/7aece496-13b2-11e7-9a6a-dcbdd943d828.png)

**Comment by chrisi51** [comment]
great! thx ;)

**Comment by adrienjacob** [comment]
Thanks, works well. As it potentially involves giving access to the BE module to normal editors, I was wondering if there's a way to restrict access to the "Flush all entries" button ? I tried to find the setting in the docs, but couldn't find it.

**Comment by dmitryd** [comment]
@adrienjacob 

1. It is not related to this bug report
1. Please, ask question in the Slack channel in general
1. No, it is not possible currently and nobody has such feature request I think.

**Comment by adrienjacob** [comment]
Ok got it !
