### ISSUE TITLE
Error decoding wierd page path

### ISSUE THREAD

**Issue by mictre** [dmitryd/typo3-realurl#435]
In method "searchForPathOverrideInPages" from UrlDecoder, the sql query may return "null" instead of an array if there is a SQL error.

This may happen when user enters wierd characters in the url. Ex.: [domain]/test/SOMMAIRE%2520corrig%EF%BF%BD3%2520filtr%EF%BF%BDe_fichiers%5Ccolorschememapping.xml

This is a minor issue reported by a security testing tool. The method should check for null to avoid throwing a php error.

**Comment by dmitryd** [comment]
> This may happen when user enters wierd characters in the url. 

Did you actually see this happen? String escaping should take care of this.

**Comment by dmitryd** [comment]
Feedback is not provided, the issue is closed.
