### ISSUE TITLE
Bad "L" parameter handling

### ISSUE THREAD

**Issue by hannesbochmann** [dmitryd/typo3-realurl#436]
Since the last release the handling of bad "L" parameters was changed. I think it's not optimal to throw a exception when no valid language could be found. If someone tries to call the page with a bad "L" parameter (not through a link in the page as the configuration is fine and links are created correct but just by adding a bad L parameter to a existing link) a log entry is written and a exception is thrown. If the exception handling of TYPO3 is configured to log exceptions e.g. into the devlog, there is yet another log which gets filled. 
This way it's easy to pollute the logs with messages about something that can't be controlled except for banning users which pollute the log. I think it would be much better if you just trigger the page not found handling. This makes more sense in my opinion. A wrong "L" parameter should have the same result as a wrong page id parameter.

**Comment by dmitryd** [comment]
> I think it's not optimal to throw a exception when no valid language could be found

This happens only during encoding, which means that incorrect link was generated. So the site is not taking enough measures to valid incoming parameters. So the site is insecure. And an exception is a good thing to inform the developer and force him to make his work properly.

This exception will never occur for normal visitors.

> This way it's easy to pollute the logs with messages about something that can't be controlled 

This can be controlled. Read TYPO3 docs to find how.

> I think it would be much better if you just trigger the page not found handling.

This is not a right thing to do as a response to the wrong link during encoding.

**Comment by hannesbochmann** [comment]
I did some more research. When config.prefixLocalAnchors = all is set the method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::getUrlToCurrentLocation is called. In this method there is no way to add the "L" parameter to the excluded parameters. This is because the "L" parameter is invalid due to config.linkVars = L(0-2). Therefore $GLOBALS['TSFE']->linkVars is empty which leads to not having the "L" parameter excluded. So when the current URL get's a bad "L" parameter added, a link is indeed generated but from the core which can't be controlled. 
Or do I miss something?

**Comment by hannesbochmann** [comment]
I did some more research. When config.prefixLocalAnchors = all is set the method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::getUrlToCurrentLocation is called. In this method there is no way to add the "L" parameter to the excluded parameters. This is because the "L" parameter is invalid due to config.linkVars = L(0-2). Therefore $GLOBALS['TSFE']->linkVars is empty which leads to not having the "L" parameter excluded. So when the current URL get's a bad "L" parameter added, a link is indeed generated but from the core which can't be controlled. 
Or do I miss something?

**Comment by dmitryd** [comment]
Core problem?..

**Comment by dmitryd** [comment]
Related to #295

**Comment by hannesbochmann** [comment]
Yeah, I think that's a core problem, too. I created an [issue](https://forge.typo3.org/issues/80327). Thanks for your effort.
