### ISSUE TITLE
PHP Warning: strpos(): Empty needle in realurl/Classes/Decoder/UrlDecoder.php line 1095

### ISSUE THREAD

**Issue by sgrossberndt** [dmitryd/typo3-realurl#437]
This is the same problem as #270 

realurl_conf.php
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT'] = [
	'init' => [
		'appendMissingSlash' => 'ifNotFile',
		'postVarSet_failureMode' => 'redirect_goodUpperDir'
	],
	'preVars' => [
		[
			'GETvar' => 'L',
			'valueMap' => [
				'de' => '0',
				'en' => '1',
				'fr' => '2',
				'nl' => '3'
			],
		]
	],
	'fileName' => [
		'index' => [
			'index.html' => [
				'keyValues' => []
			]
		]
	]
];
```

If you now have a page `Impressum` which is available as `http://www.mydomain.org/de/impressum/index.html` and call

`http://www.mydomain.org/de/impressum//index.html` in your browser, you get a message about an endless redirect and an entry in `sys_log`: `Core: Error handler (FE): PHP Warning: strpos(): Empty needle in typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php line 1095` 

Each added `/` to the url adds one entry more on each request.

Using four slashes `http://www.mydomain.org/de/impressum////index.html` redirects to `http://www.mydomain.org/dimpressu///index.html` where some kind of mangling with the language parameter happens additionally.

This works up to eight slashes `http://www.mydomain.org/de/impressum////////index.html` where eight entries are written to `sys_log` for one request.

Using nine slashes `http://www.mydomain.org/de/impressum/////////index.html` results in a 404 page with the content `File not found.`

Using more than nine slashes results in a 500 error on my server.

While I understand it's not realurl's job to cope with empty parameter configurations added by extensions this issue needs to be addressed in my opinion. You can flood the `sys_log` table in the database of a system with that configuration. There must not be a endless redirect issued be realurl and requesting any url on a page with realurl must not create an PHP error.

**Comment by dmitryd** [comment]
> realurl must not create an PHP error

This is a warning, not an error :)
