### ISSUE TITLE
Configuration to disable cache does not work

### ISSUE THREAD

**Issue by cundd** [dmitryd/typo3-realurl#438]
The [wiki](https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#disable) mentions the possibility to disable the caching (which would be handy during creation of a custom configuration). Unfortunately the configuration is not used anywhere in the extension

https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#disable

**Comment by dmitryd** [comment]
Yes, that option is obsolete and no longer exists. It is now removed from the configuration reference.

Disabling cache is no longer possible because it is needed for the correct functionality of the decoder.
