### ISSUE TITLE
PHP 5.5 Code present while dependency says PHP 5.3.2-7.0.999

### ISSUE THREAD

**Issue by BoBaH83** [dmitryd/typo3-realurl#44]
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in Classes/Decoder/UrlDecoder.php on line 1019

also found in:
Classes/Encoder/UrlEncoder.php:927
Classes/EncodeDecoderBase.php:203
Classes/Configuration/ConfigurationReader.php:95

how to fix:
GeneralUtility::makeInstance('DmitryDulepov\\Realurl\\Configuration\\ConfigurationReader'
or simply
adapt PHP dependency to 5.5.X :)

**Comment by BoBaH83** [comment]
lol ... now its duplicate of #43

**Comment by BoBaH83** [comment]
hmm .. and #43 is a duplicate of #40 ... sorry, I wish I could delete my issue :)

**Comment by dmitryd** [comment]
No problem, closed as duplicate
