### ISSUE TITLE
Separate language Domains

### ISSUE THREAD

**Issue by derghostface** [dmitryd/typo3-realurl#441]
I've set up following _DOMAIN configuration (only relevant part here):
http://pastebin.com/6yCQfYjp

This configuration works with realurl version 1.x, but does not with 2.x, because the part with 'www.domain.com/fr/' is never taken into account. I think this is due to the check in getConfigurationKeyByDomainDecode() line 215 which only checks the host name.

Are there any chances to get this work with 2.x? As there is 8 LTS coming, I have several 6.2 websites with similar configuration which need to get updated.

Thanks for your great work!

**Comment by dmitryd** [comment]
No, you can only have domain name there. If you look to the manual of realurl 1.x, you will see that documentation also allows only domain name. Anything else is undocumented and unsupported usage.
