### ISSUE TITLE
SpaceCharacter replaces not only spaces - but also hyphens (dash)

### ISSUE THREAD

**Issue by andihuber** [dmitryd/typo3-realurl#442]
Hello,

i have latest version of Typo3 7 installed with realurl 2.1.9 - in earlier versions (but long time ago) the following worked (longer time ago), but now not:

I defined  'spaceCharacter' => '_',  in pagePath in realurl_conf.php

But Pages with Alias name and path segment like "opel-logo" are converted to opel_logo.html in the frontend.

SpaceCharacter should only change spaces to the defined character on my opinion.

**Comment by dmitryd** [comment]
> SpaceCharacter should only change spaces to the defined character on my opinion.

"Space character" is just a traditionally used name from the past. Also traditionally it replaces more characters than just space. This can't be changed because it would impact every site that uses realurl.

Sorry.

**Comment by dmitryd** [comment]
Btw, the option is not documented, so its behavior is undefined. It can be even removed completely in future.
