### ISSUE TITLE
Issue with alternative languages & cache expiration

### ISSUE THREAD

**Issue by adrienjacob** [dmitryd/typo3-realurl#445]
Here is a rather specific situation, clearly not a high priority one :
- On a multi-language website, create a page "ABC", but do not add its alternative language pages. Its speaking path in default is something like "/en/abc/", and in other languages "/fr/abc/", "/de/abc/" etc.
- Change the page title to "XYZ". Its speaking path in default language becomes "/en/xyz/", but in other languages it remains "/fr/abc/"

This is obviously not a problem if language overlays have been created, as they are meant to have different speaking paths. But it may get confusing for editors who created a page which doesn't have language overlays because it doesn't need to (eg folder), but still appears in the rootline of other pages.

I see where it happens (Hooks\DataHandler->expireCache), but I'm not sure what's the best approach to treat this specific case, as we may not want to systematically expire speaking paths in all languages when the default page title is changed (or do we ?).

**Comment by dmitryd** [comment]
I need time to think about it. Definitely not a good behavior but the fix will require complications.

**Comment by wtfred** [comment]
Hello,

I may be redundant with op, but the problem also happened if the editor rename a page in a different language, or simply create a new language overlay on an existing page
eg:
- english is default language, and you have french available
- you have a page /english-title, with no translation. You will end up with a speaking path /fr/english-title
- if the editor create a language overlay "french-title", the speaking path will remain /fr/english-title intead of /fr/french-title

**Comment by dmitryd** [comment]
It should not be like this. When you create/edit an alternative language, cache entries are expired for that language.

**Comment by wtfred** [comment]
Hmm it's working well with edition of alternative language, but not with creation. I'll make more tests and let you know if i found a problem on my side.

**Comment by wtfred** [comment]
Ok so more on this:
With realurl 2.1.5, creation/edition of alternative language is working well, as you said.
With realurl 2.1.9, creation doesn't work as it should, cache entries aren't expired

Can you confirm ?

**Comment by dmitryd** [comment]
I will test.

**Comment by dmitryd** [comment]
Just tested by renaming an "Alternative page language" record and records are expired.

Could you test with the git version? You can use `"dmitryd/typo3-realurl": "dev-development"` in composer for that.

**Comment by wtfred** [comment]
Did you test the creation of an alternative page language ? With 2.1.9, edition is working fine but not the creation.
I'm not at work anymore, and i'm on business travel for 2 days but i will test the git version on monday and let you know !

**Comment by adrienjacob** [comment]
I just tested with the development branch and the problem happens when creating an alternative language... Editing is indeed ok.

**Comment by wtfred** [comment]
Hello,
The bug label is already added, but to let you know, i tested this morning and got the "creation" bug on my installation with the development branch. Thanks @adrienjacob for reproducing my bug last week :)

**Comment by adrienjacob** [comment]
Thanks, the commit seems to solve the issue raised by @wtfred. However, the initial issue I submitted remains. This happens when no alternative language is created.
Steps to reproduce : 
- On a multi-language website, create a page "ABC", but do not add its alternative language pages. Its speaking path in default is something like "/en/abc/", and in other languages "/fr/abc/", "/de/abc/" etc.
- Change the page title to "XYZ". Its speaking path in default language becomes "/en/xyz/", but in other languages it remains "/fr/abc/"

**Comment by dmitryd** [comment]
Well, this would not be something that realurl can change I think. See how it goes:

* You create the page in the main language
* Your language selector makes links to all languages despite the fact that translations do not exist
* Realurl is asked to generate urls for such non-exsiting translations. It cannot find any, so it creates links using the main language title.
* Now you rename the page for the main language. So realurl expires saved entry for the main language.

This is how it works. Theoretically realurl can go and check that page translations do not exist and start expiring those... But why should it? If you made links to non-existing translations, this already sounds wrong to me. I do not have much motivation to go and add more checks for such scenarios. They will slow down the backend hook because it will require fetching alternative languages for every page.

**Comment by adrienjacob** [comment]
Thanks for your feedback... Makes sense not to manage URLs of non existing page translations indeed.

**Comment by wtfred** [comment]
Thanks for version 2.2.0 Dmitry, works fine now :)
And sorry @adrienjacob for hijacking your issue !

**Comment by adrienjacob** [comment]
no prob @wtfred, hopefully I indirectly helped shedding light on your issue, definitely more problematic than mine :)
