### ISSUE TITLE
Inconsistent behavior in regard to case sensitivity when URLs are cached

### ISSUE THREAD

**Issue by pdanzinger** [dmitryd/typo3-realurl#447]
I came across some weird behavior with realurl 2.1.9 and TYPO3 7.6.16.
Path segments in URLs are case sensitive when the URL is not cached, but case insensitive when it is cached.

As an example I've uploaded a simple page tree. It contains a root page and two sub pages, one is a normal page, the other one a shortcut.

When importing the page tree and callingthe URL /paGE, a 404 exception is thrown.
However, when /page is called and thus a cache entry (in tx_realurl_pathdata) is generated, the next call to /paGE will work.

URLs to shortcut pages aren't cached however, thus calling /shortCUT always results in a 404 error, even when /shortcut is called before.

I'm not sure if this is intended behavior (of whether URLs are supposed to be case sensitive), but it seems quite inconsistent.

[demo pagetree.zip](https://github.com/dmitryd/typo3-realurl/files/872443/demo.pagetree.zip)

**Comment by dmitryd** [comment]
Yes, it is. Working without cache is emergency for realurl. It tries to decode urls but it will fail in many cases. You should always make sure that your urls are cached. This is easy of you use a sitemap (either a TYPO3 sitemap on some page or a `dd_googlesitemap` extension called via scheduler).

**Comment by pdanzinger** [comment]
Thank you, that makes sense. I will try to find a solution involving typolinks then.

**Comment by stucki** [comment]
see https://github.com/dmitryd/typo3-realurl/pull/617
