### ISSUE TITLE
[FEATURE] Manage back-end access to "Flush all entries"

### ISSUE THREAD

**Issue by adrienjacob** [dmitryd/typo3-realurl#448]
Currently, any editor who has access to the realurl back-end module also has the ability to flush all realurl URL data cache.
It would be nice to be able to give access to the module, but without the "flush" button.

**Comment by dmitryd** [comment]
Reference for new options: https://github.com/dmitryd/typo3-realurl/wiki/TSConfig

**Comment by adrienjacob** [comment]
Thanks @dmitryd !
