### ISSUE TITLE
Could not fetch page data for uid 0

### ISSUE THREAD

**Issue by gabdullin** [dmitryd/typo3-realurl#45]
Installed Realurl 2.0.2
In the system log messages like:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1343589451: Could not fetch page data for uid 0. | RuntimeException thrown in file /var/www/html/typo3_src-7.6.4/typo3/sysext/core/Classes/Utility/RootlineUtility.php in line 249. Requested URL: https://elarum.ru/index.php?eID=dd_googlesitemap
As a result not displayed menu links. Website multilingual and multi-domain.

**Comment by gabdullin** [comment]
Using auto-configuration, analogously to

**Comment by dmitryd** [comment]
Waiting for somebody to confirm. Just tried with autoconfig & dd_googlesitemap -> could not reproduce.

**Comment by gabdullin** [comment]
I can give you access to my server, if needed

**Comment by marcusfellinger** [comment]
I'm using autoconfig without dd_googlesitemap and have the same problem.

**Comment by dmitryd** [comment]
@marcusfellinger, do you reproduce it with eID too?

**Comment by dmitryd** [comment]
First thing to do is to check your config.

Check:
* Do you use the most recent dd_googlesitemap version?
* Do you have domain records on your pages?
* Is site root set in page properties for your root pages?

**Comment by Caprico85** [comment]
I had the same problem. In my case it wasn't related to dd_googlesitemap (although it is installed).

Some of my pages failed with this error message because one of their subpages had an url alias (in the behaviour tab) set. I removed the url alias, set it as "Speaking URL path segment" and now it works.

**Comment by dmitryd** [comment]
Most likely the same as #48. Please, wait for release 2.0.4 and reply if it does not solve the issue.

**Comment by dmitryd** [comment]
2.0.4 is out now.

**Comment by gabdullin** [comment]
Updated to version 2.0.4 realurl
dd_googlesitemap displays the correct link, the error disappeared!
All the links in the menu on the site are displayed with the language identifier: domain.ru/ru/path/ or domain.com/en/path/
Section _DOMAINS the transition from realurl 1.13.6 I did not change
'_DOMAINS' => array (
	'encode' => array (
		array (
			'GETvar' => 'L',
			'value' => '0',
			'ifDifferentToCurrent' => 1,
			'useConfiguration' => 'elarum.ru',
			'urlPrepend' => 'https://elarum.ru',
		),
		array (
			'GETvar' => 'L',
			'value' => '1',
			'ifDifferentToCurrent' => 1,
			'useConfiguration' => 'elarum.com',
			'urlPrepend' => 'https://elarum.com',
		),
	),
	'decode' => array (
		'elarum.ru' => array (
			'GETvars' => array (
				'L' => '0',
			),
			'useConfiguration' => 'elarum.ru',
		),
		'elarum.com' => array (
			'GETvars' => array (
				'L' => '1',
			),
			'useConfiguration' => 'elarum.com',
		),
	),
),

**Comment by dmitryd** [comment]
If you use `$TYPO3_CONF_VARS`, change to `$GLOBALS['TYPO3_CONF_VARS']`.

**Comment by gabdullin** [comment]
Did yesterday to use the settings from realurl_сonf.php

**Comment by gabdullin** [comment]
I also noticed that the path for the English version of the site is formed from the name of the page, for example: domain.ru/ru/about/mission-strategy/ and domain.com/en/about-us/mission-and-strategy/

**Comment by gabdullin** [comment]
> All the links in the menu on the site are displayed with the language identifier: domain.ru/ru/path/ or domain.com/en/path/

It was possible to win the full manual cleaning of tables: tx_realurl_pathcache and tx_realurl_urlcache, clearing all caches and reboot nginx, php-fpm, memcached

**Comment by dmitryd** [comment]
Okay, good to know.

**Comment by gabdullin** [comment]
Dmitry, thanks for the help!
