### ISSUE TITLE
Not compatible with TYPO3 v8 LTS (8.7)

### ISSUE THREAD

**Issue by mbrodala** [dmitryd/typo3-realurl#453]
```
$ composer why-not typo3/cms:8.7.0
dmitryd/typo3-realurl  2.1.9  requires  typo3/cms-core (>=6.2.0,<8.7.0)
```

**Comment by haassie** [comment]
Fixed by https://github.com/dmitryd/typo3-realurl/commit/10bd7c74fe57eba6697ffda0e41e495726043f01

**Comment by mbrodala** [comment]
Great, looking forward to the next release. :-)

**Comment by dmitryd** [comment]
From Slack:

> Alexander Grein [10:29 PM] 
> Am I just unfit or is version 2.1.9 really not working under TYPO3 8.7.0? (edited)
>
> [10:30]  
> If I install it (ignoring the warning in extension manager) all links in menus become “/" (edited)
>
> [10:32]  
> Under TYPO3 master version some days ago (before 8.7.0 release) it still worked (edited)
>
> [10:33]  
> Can anybody confirm this?
>
> Dmitry Dulepov [11:35 AM] 
> Please, use composer name `dmitryd/typo3-realurl` and `dev-development`. See if this works for you.
>
> Alexander Grein [11:45 AM] 
> nope
>
> [11:46]  
> same problem

**Comment by mbrodala** [comment]
Update: multiple people have verified that the latest TER version is indeed working fine with TYPO3 8.7. The issue mentioned here was caused by misconfiguration.

**Comment by dmitryd** [comment]
Okay. Closing the issue.
