### ISSUE TITLE
Subpages not being translated

### ISSUE THREAD

**Issue by Anzumana** [dmitryd/typo3-realurl#457]
Hey,
we update typo to version 7.3 we followed the upgrade path that for the extention as described here https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x=
Initially we though everything worked out fine. It does so for the main pages.
But for subpages with different languages the real url is not updated to the correct string. resulting in page not found error.

Lets say i have a subpage test and i switch to english the page should be for instance test_eng.( based on title of the translated page )
When i switch the language back to the default it is not changing test_eng to test again.
The pages are standard pages so the described seperator should not be an issue.

I am not sure if this is a bug or if we had to do something differently.
( we applied a hotfix by manually adding the same speaking url to alll the subpages ) 

If there is something you need to know more about the issue please let me know.
Great work keep it up.

**Comment by paravista** [comment]
What is your current TYPO3 und RealUrl version? Don't think it is 7.3 as this is outdated. Current versions are 7.6.x and 8.7.x.

**Comment by Anzumana** [comment]
sorry my bad its 7.6 your right

**Comment by dmitryd** [comment]
Please, see "Getting help" on the wiki. This place is only for bugs, not for support or questions.
