### ISSUE TITLE
Realurl appends unwanted L and cHash url parameters

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#460]
Realurl appends L and cHash parameters if a domain has no preVars configured for L and an L=0 query parameter is passed.

It happens in method addRemainingUrlParameters() and causes an url that should be like:
pagePath/value_alias/
to be
pagePath/value_alias/?cHash=3ba47534bc69d5fc7b7e2d86c7585bac&L=0

**Comment by dmitryd** [comment]
The behavior is correct. If you do not configure those variables, realurl appends them. It does not remove anything from the url.
