### ISSUE TITLE
root-shortcut problem

### ISSUE THREAD

**Issue by loewae** [dmitryd/typo3-realurl#462]
hello;

```
/ root "domain.tld" (shortcut > homepage)
- page
- page
- page
--subpage "homepage" (Speaking URL path segment = ' "/" ')
--subpage
```

[A] without languages
..call: domain.tld > 302

[B] with 2 languages (preVars > valueMap > en / de)
..call: domain.tld > 307

i killed in _Classes/Decoder/UrlDecoder.php_ the lines

150: if ($this->isSpeakingUrl()) {
155: if ($this->speakingUri) {
158: }
159: }

than everything works fine for [B]
..call: domain.tld > domain.tld/en/ 

?!

**Comment by dmitryd** [comment]
This place is for bugs. Please, see "Getting help" on the wiki if you want to ask a question.

**Comment by loewae** [comment]
this is a bug.
