### ISSUE TITLE
Question: Frontpage is returned instead of 404 page.

### ISSUE THREAD

**Issue by hdj-typoconsult** [dmitryd/typo3-realurl#463]
Hi 

We have an issue where the rootpage is returned instead of 404 page for a non-existing url. 

https://thewebsite.dk/projects/foobar/
Segment "projects" exists. Segment "foobar" does not exist 
goes to 404 as expected. 

https://thewebsite.dk/foobar/
Segment "foobar" does not exist. The frontpage is shown instead of expected 404 page. 

We are using:
Typo3 7.6.18 and RealUrl 2.2.0 

We tried tracing what is going on in the DmitryDulepov\Realurl\Decoder\UrlDecoder class. 
It seems that this line 845:
ArrayUtility::mergeRecursiveWithOverrule($requestVariables, $this->decodePreVars($pathSegments));
behaves differently dependent on the pathsegments:

https://thewebsite.dk/projects/foobar/ - array $pathSegments is not empty (and returning 404 page correctly)

https://thewebsite.dk/foobar/ - array $pathSegments is empty resulting in pageId is set to rootpage in function decodePath which is then served. 
$pageId = $this->decodePath($pathSegments);

We have read and tried various settings from the documentation to no avail. Is this an error or do we have something not configured correctly.

Any help would greatly be appreciated. 

Regards

Henrik

**Comment by dmitryd** [comment]
This place is only for bugs. See "Getting help" on the wiki.

**Comment by ursbraem** [comment]
@hdj-typoconsult Could you get to the bottom of this? We have a similar Issue, not to say the same

**Comment by hdj-typoconsult** [comment]
Hi Urs

Yes. Dmitry was so kind to help out. It seems you have to set noMatch for type.

'preVars' => [
 		[
 			'GETvar' => 'L',
 			'noMatch' => 'bypass'
 		],
 		[
 			'**GETvar' => 'type',
 			'noMatch' => 'bypass',**
 		]
 	],

Remember that this will override it and give the behaviour you describe:
'init' => [
		'postVarSet_failureMode' => 'redirect_goodUpperDir',

Regards
Henrik

**Comment by ursbraem** [comment]
Hi Henrik – Thanks! My case seems to be different. I'll head over to slack.
