### ISSUE TITLE
Deleting a page-translation does not clear cache of correct page

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#465]
When you delete a page-translation (pages_language_overlay), the entries in `tx_realurl_pathdata` and `tx_realurl_urldata` will not be deleted. This means, the URL will still be resolved to the data saved in the urldata table.

There is a DataHandler Hook which tries to clear the cache, but it works on the wrong page:
[DataHandler:62](https://github.com/dmitryd/typo3-realurl/blob/2.2.0/Classes/Hooks/DataHandler.php#L62)

If a `pages_language_overlay` element gets deleted, the `$id` is the id of that element and not of the page. So the cache will be cleared for another page.

In our case an editor created a translation for a page and named it the same as another page on the same level. Of course this lead to two pages with the same URL. The editor noticed his problem and deleted one translation, but then the URL was resolved to the deleted translation.

**Comment by dmitryd** [comment]
Thank you.
