### ISSUE TITLE
Wiki: typo in lookUpTable code example

### ISSUE THREAD

**Issue by schi** [dmitryd/typo3-realurl#470]
Example code for "addWhereClause" has typo in word "deteled".

Wiki:
> addWhereClause is an additional WHERE clause that must start with ' AND'. For example: ' AND deteled=0 AND hidden=0'.

Fixed:
> addWhereClause is an additional WHERE clause that must start with ' AND'. For example: ' AND deleted=0 AND hidden=0'.

**Comment by schi** [comment]
I speculate which feedback you need. The typo is here:
https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#lookuptable

**Comment by webian** [comment]
@dmitryd: 'deleted' not 'deteled'

**Comment by dmitryd** [comment]
Wrong label, sorry :) I wanted to add "Documentation"

**Comment by dmitryd** [comment]
Fixed. Thank you!
