### ISSUE TITLE
URLs are not decoded correctly when a BE user is logged in and in a workspace other than LIVE

### ISSUE THREAD

**Issue by lg3001** [dmitryd/typo3-realurl#472]
Using TYPO3 7.6.18 and RealURL 2.2.0:

When a BE user is logged in and in a workspace other than Live, trying to navigate the FE in another tab using realurl speaking paths does not work. Page paths are ignored, and the content of the root page is always displayed (even though the speaking path is displayed in the browser). 

Speaking paths work correctly when the backend is switched to Live workspace.

Note: The problem was not present in TYPO3 6.2 and RealURL 1.3.X. Speaking path worked correctly while being connected to a draft workspace in the backend in these older versions.

We recently migrated to v7.6 and most of our users are only allowed to access the backend in a draft workspace, so this is a pretty serious problem for us...

**Comment by polar-lukas** [comment]
IIRC this is by design. See [this post](http://stackoverflow.com/questions/30298376/typo3-realurl-does-not-generate-link-in-workspace) on Stackoverflow.

**Comment by lg3001** [comment]
Thanks for the reference. It seems URL decoding has been deactivated on purpose in workspaces (https://github.com/dmitryd/typo3-realurl/issues/107)
 
If RealURL is completely turned off when the backend is in a workspace, I wonder why pages sometimes show links with RealURL encoded path in content (in menus for example)... cache problem?

**Comment by dmitryd** [comment]
See [Limitations](https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#limitations), item 2.
