### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Naberd** [dmitryd/typo3-realurl#474]
Strange but i have the following issue:
 i navigate to a page,  then i change language to another one it show me correct pages.  when i switch back to default language of the site  i get page not found error.
Page Not Found
Reason: Segment "over-simco-ion" was not a keyword for a postVarSet as expected on page with id=1.

this bug occurs at some pages. Not sure what is wrong since url path is same. have only removed language prefix from realurl_conf  file.

forgot to mention typo3 is 7.6.15 and real url 2.2.0

**Comment by dmitryd** [comment]
Please, ask for support as described in "Getting help" on the wiki.
