### ISSUE TITLE
config issue multiple domain/tree but each SAME structure

### ISSUE THREAD

**Issue by ZYZ64738** [dmitryd/typo3-realurl#475]
Hi,

i already googl... bla bla bla:

Facts:
- RealUrl 2.1.5 until 2.2.0
- two trees
- two domains
- both exactly same Page-Structures
- conf with:

rootpage_id: each rootpage uid from above
lookUpTable (either postVarsets or fixedPostVars)

Behave a)
 - useUniqueCache=0

Result i get (but i want with  lowercase , hyphen , conversion umlauts): 
domina-**a**.tld/detailpage/My Category/My Product Named Ü
domina-**b**.tld/detailpage/My Category/My Product Named Ü

Behave b)
 - useUniqueCache=1
 - useUniqueCache_conf[strtolower] =1 
 - useUniqueCache_conf[spaceCharacter] ='-' 

Result i get (but i DONTwant '-1'): 
domina-**a**.tld/detailpage/my-category/my-product-named-u
domina-**b**.tld/detailpage/my-category-1/my-product-named-u-1

How to achive what  i need:
domina-**a**.tld/detailpage/my-category/my-product-named-u
domina-**b**.tld/detailpage/my-category/my-product-named-u

Thnx in andvance

**Comment by dmitryd** [comment]
You can't. Uniqie aliases are unique.

**Comment by dmitryd** [comment]
Not a bug, support questions: see "Getting help" on the wiki.
