### ISSUE TITLE
Bug with URL alias on page options

### ISSUE THREAD

**Issue by t3premium** [dmitryd/typo3-realurl#48]
If a URL alias is set in the page options, the complete menu will not appear because of an error.
So if I deleted the URL alias from the page options, all works fine.

TYPO3: 7.6.4
RealURL: 2.0.3

Can you please fit this bug in the upcoming version, because URL aliases are very useful for SEO.

**Comment by dmitryd** [comment]
What is "complete menu"?

**Comment by dmitryd** [comment]
Will be fixed in version 2.0.4

**Comment by t3premium** [comment]
Thx :)
