### ISSUE TITLE
duplicate pathcache entries for same page_id but different rootpage_id

### ISSUE THREAD

**Issue by officeschwarts** [dmitryd/typo3-realurl#481]
Hi, 

I'm using 2.0.14 having issues with wrong pathcache entries for different rootpage_ids'.
Wrong rootpage_id leads to 404, I can't reproduce this issue on purpose so I'm not sure where to look for some kind of bug. In the realUrl config I have a $_SERVER['HTTP_HOST'] condition to set the right rootpage_id. 
Any Idea what can cause this issue?

thanks,
michael

**Comment by dmitryd** [comment]
Please, update 2.2.1.

**Comment by dmitryd** [comment]
https://github.com/dmitryd/typo3-realurl/wiki/Getting-help
