### ISSUE TITLE
URL-Data flooding by bruteforce hack-bots, leading to 404 in some cases

### ISSUE THREAD

**Issue by Moongazer** [dmitryd/typo3-realurl#483]
Today i discovered a very strage problem: some pages returned a 404, but they was working before (and we did not make any changes), for example our contact-page "contact.html > id=24". After looking around for a while, I found on our root-page (Uid 1) in Module "Speaking URLs" => "URL Data" a record "contact.html" pointing to "id=1". So if RealURL is looking for "contact.html", it finds the record at the root-page first because its higher in hierarchy which leads to the 404.

The question is, where does the URL-Data record come from? Turns out that the root-page is flooded with URL-Data records like the following:

admin.php
bbs.cgi
configbak.php
configurationbak.php
contact-us.aspx
contact-us.asp
contact.htm
**contact.html**
[...]

So it looks like a hack-bot was bruteforceing the website and for all URLs it tried, RealURL created a record here! Is this a right behaviour of RealURL? Its quite dangerous in my opinion if you can create so many records from the outside.... Or is this maybe a missconfiguration? Does someone of you discovered this problem too?

TYPO3 7.6.18
RealURL 2.2.0

**[EDIT:]**
I found this [bug-report](https://forge.typo3.org/issues/8681) related with RealURL and sr_language_menu, which describes exactly my issue here! The only thing is that I dont use the sr_language_menu extension, but the problem in RealURL is the same. Every GET parameter is put to the URL cache: requesting `/en/mypage.html?testParam=thisShowsUpInURLdata` becomes in backend:

Speaking URL: `/en/mypage.html?testParam=thisShowsUpInURLdata&cHash=da195d379098c327db204e307698c2da`
Original URL: `L=0&cHash=da195d379098c327db204e307698c2da&id=26&testParam=thisShowsUpInURLdata`
Root page id: 1 (Why ID 1? The mypage.html page has ID 26)

I had never issues like this before with RealURL, and I run several different pages for over 8 years... so strange!

**Comment by dmitryd** [comment]
Main thing to understand: realurl **only** creates links that TYPO3 asked it to create.

It means there is something in your site that calls `typolink` in typoscript or a Fluid viewhelper with such parameters.

Realurl does not know if the parameter is valid or not.

Realurl may not validate parameters, it simply processes them according to config to generate the URL and return to TYPO3.

This means that realurl may not help you to fight this. It was called by the TYPO3 core to make this link and it made the link, that's all. It cannot validate it, it cannot refuse to make it.

Most likely, you have `addQueryString` somewhere, which blindly appends all kind of parameters to links. Please, read [this](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#i-see-a-lot-of-strange-entries-in-the-realurl-module) for more information.

**Comment by Moongazer** [comment]
Oh wow, I'd never guessed that these can lead to the described issue. But you are right, in my TS I used the `addQueryString` exactly ONCE to generate an OpenGraph meta tag:

```
page.headerData {
  10 = TEXT
  10 {
    typolink {
      parameter.data = tsfe:id
      parameter.insertData = 1
      forceAbsoluteUrl = 1
      returnLast = url
      useCacheHash = 1
      addQueryString = 1
      addQueryString.method = get
      addQueryString.exclude = id
    }
    wrap = <meta property="og:url" content="|" />
  }
}
```

First: it works also without the `addQueryString` part, and second: it seems that GET parameter which I append to the URL not showing up in the URL data anymore! Unbelievable that such a small configuration causes such a trouble... Anyway, I hope its solved now.

**Thank you VERY much, I highly appreachiate your help and fast response!**

**Comment by dmitryd** [comment]
Thank you :)
