### ISSUE TITLE
[FEATURE] Speedup urldata queries

### ISSUE THREAD

**Issue by christianfutterlieb** [dmitryd/typo3-realurl#484]
Hi @dmitryd 

I'm currently upgrading a rather large TYPO3 installation (6.2 => 7.6), including an upgrade of realurl (obviously ;-)). I noticed a decrease of performance, analysis lead me to realurl, especially the queries to `tx_realurl_urldata`. Which was a surprise to me, because I never experienced such behaviour with realurl on other websites.
Digging deeper, I took a look at the indexes on that table, which seemed completely ok to me (testing with e91193221f77ffb742d6c2140a1092a0e15c631c improved the lookup even more).

Then: as far as I understand the index prefix specification (32) in `KEY pathq1 (rootpage_id,expire,original_url(32))`, it will cause mysql to add only the first 32 chars of `original_url` to the index. The installation in question hosts a large forum with few pages, but lots of different URLs produced by the forum plugin. When I did a lookup of the first 32 chars of `tx_realurl_urldata.original_url` it revealed, that almost every original_url starts with the same 32 chars:

```
+-------+----------------------------------+
| count | ind_url                          |
+-------+----------------------------------+
| 85689 | id=1&tx_myext_forum%5Baction%5D= |
|  ---- | cropped insignificant stuff here |
|     1 | id=14                            |
|     1 | id=13                            |
|     1 | id=12                            |
+-------+----------------------------------+
```
Using this query:
```mysql
SELECT
  COUNT(*) AS count,
  SUBSTR(`original_url`,1,32) as ind_url
FROM `tx_realurl_urldata`
GROUP BY SUBSTR(`original_url`,1,32)
ORDER by count DESC
```

Now, finally, to my point: I think it was a very strong improvement for realurl, when it would store, say, a sha1 hash of the `original_url` in a separate `CHAR (40)` field and put the appropriate index on it, for example `KEY pathq_hash (rootpage_id,expire,original_url_hash(10))`. This would make the index file much smaller and speed up the lookup. The same could apply for `tx_realurl_urldata.speaking_url`.

To develop the thought even further: the fastest solution would be to create a new table with only a reference of `tx_realurl_urldata.uid` and the hash(es), apply the indexes and query only this table and join `tx_realurl_urldata` by `uid`. This approach is even then faster, when `speaking_url` holds short values, which is not the case with the above proposal.

What do you think about this idea? When you like it, I'll be ready to put some work into this.

Regards, Christian

**Comment by christianfutterlieb** [comment]
Added an sql script for testing, see: https://gist.github.com/christianfutterlieb/1562b0923bd15d0c7761298a3d9765bb. Hope that helps :)

**Comment by christianfutterlieb** [comment]
Thanks for your reply. 

> Splitting the table may create consistency issues. TYPO3 does not support cascade delete, for example, so it is not easy to keep all tables in sync, especially when people use phpMyAdmin to remove data in them.

As realurl uses InnoDB engine, it would be easy to solve this with foreign key constraints. Afaik, TYPO3 does not support those in ext_tables.sql, so it would be necessary to set them up via ext_update. And: if people mess around by hand in the db tables, they might get other problems ;)

> Mysql uses only one index per query, so if the data stays in one table, the index has to be complex
> The longer the index, the less chances that mysql will use it because in such cases it usually thinks it can do the whole table scan in the same time

I'm not sure if I understand you correct: the index would get shorter anyway when it uses `original_url_hash(10)` instead of `original_url(32)`, wouldn't it? But: let's not focus on this as I don't really see a solution with one table, please see below.

> I would prefer to have a single table and improve the index. But if nothing helps, a separate table can be used to.

With one table only, there must be some additional logic in `DatabaseCache`. Namely to workaround the problem, that the proposed idea is significantly slower with short `original_url`s (you can check this for yourself using the sql script in the gist posted above). But I don't like that, a cache must be as straightforward as possible. 

What do you think of following solution: we introduce a switch in ext_conf_template.txt that en-/disables "Use hashed urldata cache" (or whatever naming) which is by default off. Enabling it would cause realurl to use a new cache class that extends `DatabaseCache`. Like this, the user can enable it if there is need for it. And the code can be transparently separated without switching in the cache-methods. And, nothing has to be changed with the current indexing of `tx_realurl_urldata`, as the new table would maintain its own index. The only "overhead" would be the possibly unused table and one single switch in `CacheFactory ` that decides which cache-class is used.

Appreciate your answer, Christian

**Comment by dmitryd** [comment]
> And: if people mess around by hand in the db tables, they might get other problems ;)

They do it all the time and than they put their problems to my shoulders. So I want to minimize that extra load.

With hash the index will be shorter, yes. This can be a solution.

Let me think.

**Comment by christianfutterlieb** [comment]
> They do it all the time and than they put their problems to my shoulders. So I want to minimize that extra load.

Sure, got it 👍 

Meanwhile I created a conceptual (3rd party) implementation, see: https://github.com/aaw-team/realurl-hashcache. With this extension active, I was able to drastically speed up page generation, in particular those pages with many links.

If you decide against an implementation inside realurl, I'd really be happy if you consider declaring the existing cache class as public API, to make it possible to provide such an extension in future.

> Let me think.

Yeah, that was it from me, I shut up now ;)

Thanks for your work anyway & regards

**Comment by dmitryd** [comment]
I had a similar case for the client. After testing on a 500,000 database I made solution, which selects exactly one record quickly and efficiently.

**Comment by christianfutterlieb** [comment]
Just took a look at a830abaf02917b6ca27f180c731abc641f5bd9ee, thanks for your work.

Meanwhile I had some time analyzing other instances. I found that in most installations, the value in `tx_realurl_urldata.original_url` begins with "cHash=" (apart from "id="). That means that the first characters of the cHash will be added to the index. This has some advantages over the solution in a830abaf02917b6ca27f180c731abc641f5bd9ee:

1. way better collision resistance than crc32
2. it is always being computed, so no need for additional calculations

While in those "special" conditions we sometimes encounter in the wild the change will bring drastically more speed, in most others (with correct cHash usage) it does not disturb anything at best. Because of this I'd like you to consider my previous proposal to add some kind of switch to en-/disable hashing of the urldata (disabled by default). Like I said before, this could be done with a minimum of complexity and performance cost.

Finally, I'd like to point to a problem in the change: using crc32() on 32bit platforms might return negative integers (see https://secure.php.net/manual/en/function.crc32.php), while in ext_tables.sql you define the fields as unsigned ints. It may be a better solution to use the suggested `sprintf('%u', crc32())`.

Regards, Christian

**Comment by dmitryd** [comment]
> This has some advantages over the solution in a830aba:

Try using `explain` on a large database first. Using the current solution it always yields just one row. With any string index it makes several thousands + filesort.

As I wrote, I tried on a 500,000 records database. Collisions are zero. The goal was not to provide something that totally avoid collisions but to narrow search as much as possible. This is why both `*_url_hash` ans `_url` are used in queries. I logged lots of requests with various string indexes and with the current solution before committing this. Current was the best. CPU load on the site was around 8 normally and peaked to 40 after cache clearing. Now the load is about 4.5 by just applying this change.

I consider this change enough.

**Comment by dmitryd** [comment]
> I found that in most installations, the value in tx_realurl_urldata.original_url begins with "cHash="

This depends on the site and this is valid only for sites that either has few pages and plugins or when plugins produce a lot of URLs. However not every site is like this. We have some sites that do not use plugins with cHash but have a lot of pages. Your proposal will not benefit such sites at all.

**Comment by christianfutterlieb** [comment]
> Your proposal will not benefit such sites at all.

True, the integer index is always faster.

While testing the change more deeply, I experienced 86 collisions out of ~350k records in `tx_realurl_urldata`. However with the additional check on  `original_url`, the final result was always one correct row. So no problems here.

Remains the question about the possible negative integers produced by php's `crc32()` as stated above. Or with a reusable construct like

```
function getPositiveCrc32($string) {
    return PHP_INT_SIZE == 8 ? crc32($string) : sprintf('%u', crc32($string));
}
```

What do you think?

**Comment by dmitryd** [comment]
`PHP_INT_SIZE` will be `4` on Windows platforms or on 32-bit Linux. Does anybody run 32-bit Linux these days on servers?

**Comment by dmitryd** [comment]
I guess insertion can be changed to `sprintf('%u', crc32(...))`.

**Comment by christianfutterlieb** [comment]
> `PHP_INT_SIZE` will be `4` on Windows platforms or on 32-bit Linux.

For Windows: only prior to PHP7 [according to the documentation](https://secure.php.net/manual/en/language.types.integer.php)

> Does anybody run 32-bit Linux these days on servers?

I don't know. But I'd rather put a notice in the system requirements doc if realurl won't work correctly on 32bit systems.

> I guess insertion can be changed to sprintf('%u', crc32(...)).

+1

**Comment by dmitryd** [comment]
>  But I'd rather put a notice in the system requirements doc if realurl won't work correctly on 32bit systems.

It will :) I added required code yesterday.
