### ISSUE TITLE
chash in speaking_url when "?type=xxx" is added

### ISSUE THREAD

**Issue by sinasita** [dmitryd/typo3-realurl#485]
I just updated from version 1.13.3 to 2.2.1 of realurl. For my ajax-requests, i need to append the type-parameter to some links, what i did via the uriBuilder and its setArguments. Now i get the links working, but there's a cHash appended at the end of the link and stored in the speaking_url column.

If i remove manually the appended cHash, the link works still fine and the caching as well. But why is it added and how can i get rid of it without adopting it manually in the tx_realurl_urldata-Table?

Example:
speaking_url
`mypage/newspager/22/?type=666&cHash=a0711b17eb2c41e0d2e3d74095f1f44a`

request_variables

`{"id":"5","L":"0","type":"666","tx_news_pi1[@widget_0][currentPage]":"22","cHash":"a0711b17eb2c41e0d2e3d74095f1f44a"}`

**Comment by sinasita** [comment]
Ok i added 

```
            'pagetype' => array (
                array(
                    'GETvar' => 'type',
                ),
            )
```

to the postVarSet to get rid of the cHash

**Comment by dmitryd** [comment]
Not a bug. Please, see [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) if you want answers to questions.
