### ISSUE TITLE
strange behavior with multidomain (realurl write url data into more than one page)

### ISSUE THREAD

**Issue by cosmox** [dmitryd/typo3-realurl#486]
Hi dimitry,
i have a multidomaininstallation, using the auth conf file from realurl.
Inside the Configuration i have an entry for every Domain with the right rootpage id.
If i call the pages with the rootpage id 1 and take a look into the rewrite Table inside the Backend, all seems fine. But if i call another page (with another Domain, rootpage id 800), realurl store the rewrite URL Data for Page id 800 AND for Page id 1 (so i see some rewrites for page id 800 inside page id 1), and then realurl tell me there ist a url conflict :)

Die you have any idea why this can be happen?

(I delete the wrong entrys today and will test tomorrow wheter the wrong entrys will be created again)

TYPO3 7.6.18
Realurl 2.2.1

**Comment by cosmox** [comment]
![realurl](https://cloud.githubusercontent.com/assets/2511351/26619253/e8e30b3a-45dd-11e7-889b-9f2abd60ae75.jpg)

**Comment by dmitryd** [comment]
Please, see here if you need answers to your questions: [Getting help(https://github.com/dmitryd/typo3-realurl/wiki/Getting-help). This place is only for bugs.
