### ISSUE TITLE
[Feature] No Url - Cache for Pages resulting in 404

### ISSUE THREAD

**Issue by nothdurfterf** [dmitryd/typo3-realurl#488]
Realurl 2.2.1
TYPO3 7.6.15

**My case:**
For a customers website we use RealUrl für generating pretty urls for the product tree. The Main url is /products. From here on we work with fixed Post vars. 
In the Configuration i bypass controller and action with "'noMatch' => 'bypass'"

`'GETvar' => tx_extension_pi1[action], 'noMatch' => 'bypass' `
`'GETvar' => tx_extension_pi1[controller], 'noMatch' => 'bypass' `

The Page "Products" contains only one contentelement with the Plugin "tx_extension_pi1" which maps to the controller "ProductController" and different Actions.

**My problem:**
Somewhere on the page a link to this Product - Page with a Parameter 
`tx_extension_pi1[controller] = Contact` is generated. Visiting this link leads to "Controller not allowed in Plugin" and outside of Debug - Mode to a 404. Realurl Caches this Url and because of "controller => bypass" the resulting url is /products
If everthing plays well together the Product - Page isn't reachable anymore because decoding results in the described case above aka 404.
I know that i need to remove this specific link. But I searched for a couple of hours and didn't find the specific place where this "Bad - Link" is located.

**My questing:**
Is ist possible to make a check before saving Url - Data if the Page is resulting in a 404? If thats the case, don't save the Url - Data. It would be great if this could be turned on in the realurl_conf.php

What are your thoughts on this? Does anybody else have a similar problem?

Thank you in advance
Franz

**Comment by dmitryd** [comment]
Not a bug. Please, read [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) if you need answers to questions.
