### ISSUE TITLE
do not use deprecated BackendUtility::getRecordsByField() 

### ISSUE THREAD

**Issue by tmotyl** [dmitryd/typo3-realurl#493]
BackendUtility::getRecordsByField() has been deprecated in TYPO3 8.7 and was dropped in 9.
In order to keep realurl compatible with v9, it should not use mentioned method.
see https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.7/Deprecation-79122-DeprecateBackendUtilitygetRecordsByField.html

**Comment by dmitryd** [comment]
Thank you!
