### ISSUE TITLE
Realurl no_cache = 1

### ISSUE THREAD

**Issue by prdt3e** [dmitryd/typo3-realurl#494]
With a typo3 8.7 installation I installed indexed search and wondered why nothing is indexed.
I found the following: index.php
  If ($ GLOBALS ['TSFE'] -> no_cache) echo "No cache is activated!";

After that I came across the following line:
UrlEncoder.php

Line: 1455 (UrlEncoder.php)
If (! $ IsValidLanguageUid) {
$ This-> tsfe-> set_no_cache (
Sprintf ('Bad "L" parameter ("% s") which is detected by realurl.'.
'Page caching is disabled to prevent spreading of wrong' L 'value.',
addslashes ($ sysLanguageUid)
)
);
}

Is that OK?
My language ID is 0.

**Comment by dmitryd** [comment]
See [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) if you want to ask questions.

**Comment by prdt3e** [comment]
I have made the configuration according to your description.
I have allowed L (1-6) and even with defaultGetVars as well as with bypass.

The problem only occurs in Typo3 8.7.

**Comment by SventB** [comment]
Same problem in TYPO3 7.6
If someone adds "?L=notexistinglanguage", the log file is created.
Second problem is the amount of data which is logged: One line in the log file needs ~4 MB.

**Comment by SventB** [comment]
See #549 for possible solutions.
