### ISSUE TITLE
realurl_conf: expireDays for pagePath will not used anymore

### ISSUE THREAD

**Issue by hannasophieungar** [dmitryd/typo3-realurl#500]
In older versions of realurl plugin it is possible to controle "expire" value for pagePaths over "expireDays" configuration of realurl_conf.php in node "pagePath".
In new version it use always a programmatically fix value of 30 days (see method expireCache). This have affect on tables  (in new tx_realurl_pathdata and tx_realurl_urldata) which are used to genereate redirects for pages (if moved, renamed). Is this a bug or a feature?

....
        'pagePath' =>
        array(
            'type' => 'user',
            'userFunc' => 'EXT:realurl/class.tx_realurl_advanced.php:&tx_realurl_advanced->main',
            'spaceCharacter' => '-',
            'languageGetVar' => 'L',
//            'rootpage_id' => '1',
            'segTitleFieldList' => 'tx_realurl_pathsegment,title',
            'expireDays' => 60,
            'firstHitPathCache' => 1,
            'autoUpdatePathCache' => true
        ),
...

**Comment by dmitryd** [comment]
Please, ask questions in the Slack channel.
