### ISSUE TITLE
[BUG] Multiple mapping on same page-id

### ISSUE THREAD

**Issue by Freshmeat-ch** [dmitryd/typo3-realurl#506]
This is a weird problem we have encountered on a multi-page installation (and so far only one installation). We are currently not sure wich circumstances causes the problem. Some pages contains content (insert content) that is shared trough the page-tree, some pages have the same name, some pages share the content of an other page (show content of page xx), sometimes even the startpage does get the error and and others are shortcuts to pages in the same page-tree. Its also not occurs immediately, sometimes its working and later on the error occurs (404 - page not found).
If the error occurs the backend module shows us the pages wich are wrong. So RealUrl knows wich pages are troubling.

We tried it with RealUrl 1.3.7 and everything is good (but other parts are not working with LTS 7). It is definitely related to the 2.x Version.

![image](https://user-images.githubusercontent.com/3501296/28367354-e0a7335e-6c90-11e7-83ed-dce9a4949db5.png)

**Comment by dmitryd** [comment]
RealURL 1.3.7 simply does not do any checks. These error messages were added in 2.2.x to help people see that there are issues in the installation (or with realurl).

**Comment by dmitryd** [comment]
Please, next time ask in the Slack channel first. This page is for bugs only and you will not get any help resolving the problem here. All help is only via Slack. See "Getting help" on the wiki to get a link to Slack.

**Comment by Freshmeat-ch** [comment]
Hi Dimitry

Those error messages in the backend are superb. But its still a mystery why those errors occur on this installation.

Can I delivery you some more information that you can dig into this problem. We have currently disabled the path_cache completely. This is stupid, but currently this errors is driving us crazy.

The message that appears is sometimes "Reason: Segment "XX" was not a keyword for a postVarSet as expected!" and then it changes to a TYPO3 related error message "pageType num=404 ist not configured"

**Comment by Freshmeat-ch** [comment]
Hi Dimitry

I think i've found the error. We had a _DEFAULT configuration and set the rootpage_id to 1. Afterwards we had an other mapping for a specific domain for the rootpage_id 1 again.

It looks that this doubled configuration had some special side effects on the realurl path generation.

Sorry for the inconvenience! Can be closed now.

**Comment by dmitryd** [comment]
Thanks for the information!
