### ISSUE TITLE
Single tree, two languages and domains

### ISSUE THREAD

**Issue by danaron** [dmitryd/typo3-realurl#512]
I need help with the RealURL Extension.

I do have to domains and two languages with a single tree approach:
http://www.deutsch.ch/ für Deutsch L=0
http://www.englisch.ch/ für Englisch L=4

Would like to make it work without prefixes like /de or /en

Here is my TS Setup 
# Default language:
page.config {
simulateStaticDocuments = 0
tx_realurl_enable = 1
prefixLocalAnchors = all
linkVars = L
sys_language_mode = content_fallback; 4,0
baseURL = http://www.deutsch.ch/
absRefPrefix = http://www.deutsch.ch/
sys_language_uid = 0
language = de
locale_all = de_CH
htmlTag_langKey = de
htmlTag_langKey = de-CH
}
# deutsch:
[globalString = ENV:HTTP_HOST=www.deutsch.ch]
page.config {
baseURL = http://www.deutsch.ch/
absRefPrefix = http://www.deutsch.ch/
sys_language_uid = 0
language = de
locale_all = de_CH
htmlTag_langKey = de
htmlTag_langKey = de-CH
}
[global]

# english:
[globalString = ENV:HTTP_HOST=www.englisch.ch]
page.config {
baseURL = http://www.englisch.ch/
absRefPrefix = http://www.englisch.ch/
sys_language_uid = 4
language = en
locale_all = en_US
htmlTag_langKey = en
htmlTag_langKey = en-US
}
[global]

Und in den Konstanten die Variablen definiert mit 
# global
meineVariable {
var81 = Hier schreiben um zu...
var83 = suchen
var37 = <a href="http://www.deutsch.ch/">Startseite</a>:
}
# de
[globalVar = GP:L = 0] 
meineVariable {
var81 = Hier schreiben um zu...
var83 = suchen
var37 = <a href="http://www.deutsch.ch/">Startseite</a>:
}
# en
[globalVar = GP:L = 4] 
meineVariable {
var81 = type here to...
var83 = search
var37 = <a href="http://www.englisch.ch/">Home</a>:
}
[global]

The variablen are only working when I click on the language switch and the L Parameter occurs. The homepage is in the default Parameters (var81 aso)

Could not find any link on the web and hope that someone here can help me.
Thank you very much.
Cheers
Dan Riesen

**Comment by dmitryd** [comment]
> Could not find any link on the web and hope that someone here can help me.

Wrong place. Please, see this: https://github.com/dmitryd/typo3-realurl/wiki/Getting-help
