### ISSUE TITLE
Table tx_realurl_urldata strange records - multilanguage page dont work - L=1

### ISSUE THREAD

**Issue by agendartobias** [dmitryd/typo3-realurl#518]
Hello every few days my english page (L=1) stop working. After research i found strange record in table tx_realurl_urldata, like: L=1.sql&id=2159
Can anybody help me?

Here is a screenshot: https://filebox.agenda.si/index.php/s/uAw6PphumUwliHd

**Comment by mithri** [comment]
Take a look at your allowed linkVars: https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#linkvars

**Comment by dmitryd** [comment]
See "Getting help" on the wiki.
