### ISSUE TITLE
Ban the create action of EXT:powermail leads to error on TYPO3 8.7

### ISSUE THREAD

**Issue by Konafets** [dmitryd/typo3-realurl#521]
Hi @dmitryd,

the error is `Page Not Found Reason: Request parameters could not be validated (&cHash empty)` error.

Therefore the url is not cached and can not be retrieved later on.

This is the commit https://github.com/dmitryd/typo3-realurl/commit/85d3e08b336aadb1c7afe9fecdfebbc248cf2850

**Comment by einpraegsam** [comment]
I can confirm this issue on the customers system (TYPO3 8.7.6). 

Here a more detailled description:
1) Install powermail (3.22.1) with a small form and set a redirect target in the plugin configuration. That's to show a different page on submit (same function as known from the old form in TYPO3).
2) Install and configure realurl (2.2.1)
3) Open the page with the form, add some values to the fields and press submit. The same page is rendered - there is no redirect. If I reload the page again in FireFox, the browser asks me to resend the POST-parameters and I choose "yes", the redirect just works.

How to prevent this bug in powermail with an overlay in the realurlconfiguration like:
```
$realURLConfig = [
    'init' => [
        ...
    ],
    'cache' => [
        'banUrlsRegExp' => '/tx_solr|tx_indexedsearch|tx_kesearch|(?:^|\?|&)q=/'
    ],
   'fileName' => [
      ...
```
