### ISSUE TITLE
Shortcut URL segments case sensitive

### ISSUE THREAD

**Issue by gvonderschmitt** [dmitryd/typo3-realurl#522]
I just recognized that all redirect URL segments are case sensitive. 

System: TYPO3 7.6.21, RealURL 2.2.1

https://www.genedata.com/Deep-Learning/ -> does NOT work
https://www.genedata.com/deep-learning/ -> works fine

I consider this as a bug as normal URLs are not case sensitive.

Best, Gregor

**Comment by upputter** [comment]
@gvonderschmitt How did you fixed it?

**Comment by gvonderschmitt** [comment]
I did not - I had to solve it by using Bitly - Problem is still there - I made a Test-Page for you to test/see

https://www.genedata.com/Test/ -> does not work
https://www.genedata.com/test/ -> works nind

Thanks in advance

Best, Gregor

**Comment by upputter** [comment]
I've found out, that the case sensitivity depends on if the page/path is in the pathcache or not.

at our setup we use doktype shortcut to send users to deeper nodes in our pagetree.

if you want example.com/MAIL and example.com/mail to be valid, you have to set a "path segment" for the page and activate the "path override" option too. it won't work without the option!

**Comment by gvonderschmitt** [comment]
Thanks for your help - I was able to solve the problem.

Best, Gregor
