### ISSUE TITLE
SQL Error in DataHandler hook:  ERROR => 'Column 'uid' in field list is ambiguous'

### ISSUE THREAD

**Issue by merzilla** [dmitryd/typo3-realurl#523]
Hi Dmitry,
in current branch `development` I get an error (pops up several times in SQL debug console in backend) when I save a record.
The error is:
```
caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::sql_query' (53 chars)
   ERROR => 'Column 'uid' in field list is ambiguous' (39 chars)
   lastBuiltQuery => 'SELECT uid,expire,url_cache_id FROM tx_realurl_uniqalias LEFT JOIN tx_realur
      l_uniqalias_cache_map ON tx_realurl_uniqalias.uid=alias_uid WHERE tablename=
      'tx_myextension_domain_model_person' AND value_id=15 AND lang=0' (221 chars)
   debug_backtrace => 'require(or/typo3/cms/typo3/sysext/backend/Resources/Priva......
```
where `debug_backtrace` leads to the hook in line 167.
This `'SELECT uid,expire,url_cache_id FROM ' .` should be
`'SELECT tx_realurl_uniqalias.uid,expire,url_cache_id FROM ' .` and also in the `ON` clause, line 168 should be:
`'tx_realurl_uniqalias LEFT JOIN tx_realurl_uniqalias_cache_map ON tx_realurl_uniqalias.uid=alias_uid ' .`
I hope this is okay here as issue. But let me know if you prefer a PR.
I´m using MariaDB 10.1.25.

Regards,
Ralf

**Comment by prixxx** [comment]
I can confirm this. 

Regards 
Prix
