### ISSUE TITLE
without redirects: valueDefault vs. duplicate content?

### ISSUE THREAD

**Issue by FireLizard** [dmitryd/typo3-realurl#527]
Hey,
I'm looking for a best practice to handle incomplete postVarSets.

At first my configuration:
```php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] = [
    '_DEFAULT' => [
        'postVarSets' => [
            '_DEFAULT' => [
                'foo' => [
                    [
                        'GETvar' => 'tx_myext_plugin1[foo]',
                        'valueDefault' => 'bar'
                    ]
                ]
            ]
        ]
    ]
];
```
(Should encode "tx_myext_plugin1[foo]={value}" to "/foo/{value}" )

Since there is no possibility to configure redirects (anymore), I have to do it myself. But how should I handle an URL like **https://.../foo/** (missing value)?

I will get the default value "bar" inside my extension but the url stays the same and duplicates the content by the canonical URL **https://.../foo/bar**.

So in favour of avoiding duplicate content I could remove the _valueDefault_-line and check for the empty value to trigger the redirection (with a proper default value). Would you do this as well?

Greetings
FireLizard

**Comment by dmitryd** [comment]
Please, ask questions in the TYPO3 Slack channel. You can find a link [here](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).

**Comment by FireLizard** [comment]
Hi @dmitryd,
my question was ignored on Slack... try it again.
Do you have any idea on this issue?
