### ISSUE TITLE
create CLI interface to delete realurl cache

### ISSUE THREAD

**Issue by sarah01mueller** [dmitryd/typo3-realurl#529]
Hi

We have multiple instances and had to delete the realurl cache on every instance due to a bug with our own extension. We use the command line interface to manage our instances.
It would be helpful if realurl provides more CLI options e.g. delete the realurl cache.  As TYPO3 is advertising the feature CLI at the moment, I think, it would be very recommended to support the feature more.

Thank you and kind regards Sarah

**Comment by dmitryd** [comment]
RealURL cache should not be touched. If entries are deleted without a reason, it will most likely break the site because decoding *requires* cache in many cases (for example, for news).
