### ISSUE TITLE
wrong cHash is cached

### ISSUE THREAD

**Issue by tjeske2017** [dmitryd/typo3-realurl#537]
If I attach a wrong cHash Get-Parameter to an url and pageNotFoundOnCHashError is set to 0, RealUrl caches this entry.
For example: www.website.tld/de/home.html?cHash=123
That means that all later requests to this page (without wrong cHash --> www.website.tld/de/home.html) will be loaded uncached. RealUrl should check every cHash specification before write the cache entry. Something like 

```
if ($requestVariables['cHash']) {
	$cacheHashCalculator = GeneralUtility::makeInstance('TYPO3\CMS\Frontend\Page\CacheHashCalculator');
	$cacheHashArray = $cacheHashCalculator->getRelevantParameters(GeneralUtility::implodeArrayForUrl('', $requestVariables));
	$cacheHash = $cacheHashCalculator->calculateCacheHash($cacheHashArray);
	if ($requestVariables['cHash'] != $cacheHash) {
		return;
	}
}
```
in class DmitryDulepov\Realurl\Cache\DatabaseCache

**Comment by dmitryd** [comment]
> If I attach a wrong cHash Get-Parameter to an url and pageNotFoundOnCHashError is set to 0, RealUrl caches this entry.

No, it does not. RealURL does **not** cache anything on decoding. There is just one case when it may happen but it is always a user error. This is when you use `typolink.addQueryString = 1` but forget `typolink.addQueryString.exclude = cHash`. Than wrong cHash will be appended to this link by TYPO3 core.

> RealUrl should check every cHash specificatio

No, it should not. If you attached wrong cHash, this is not RealURL's fault but yours. Do your homework better :)
