### ISSUE TITLE
Wrong path data in foreign languages

### ISSUE THREAD

**Issue by melaande** [dmitryd/typo3-realurl#540]
Hi,
unfortunately, we have some problems with our multidomain TYPO3 project using RealUrl.

Here's our setup:
- TYPO3 7.6.23
- RealUrl 2.2.1
- PHP 7

RealUrl creates wrong path data in foreign languages. Here are some examples:
- "en/aktivitaeten/winter/wintersport.html" instead of "en/activities/winter/winter-sports.html"
- "cz/en/zimni-sport.html" or "cz/nl/zimni-sport.html"  instead of "cz/zimni-sport.html"
- "activities/winter/winter-sports/snow-shoe-hikes.html" instead of "aktivitaeten/winter/wintersport/schneeschuhwandern.html"

Following such a link results in a 404-error-message.

Is there anyone with similar problems?

Thanks in advance,
melaande

**Comment by tantegerda1** [comment]
> Is there anyone with similar problems?

tbh: quite sometimes :-) But in hindsight it was **always** my fault misconfiguring either TYPO3 or RealURL. (granted, the config it is quite unforgiving and you have to read the docs **very** precisely)

Could you share some insights to your setup? (TYPO3 language configuration, RealURL config, …)

----

Side note: Dmitry quite clearly [states](https://github.com/dmitryd/typo3-realurl/blob/development/README.md#realurl-extension-for-typo3-cms): 
> "This place is only for bugs. Use TYPO3 mailing lists for questions!"

You might have better luck getting help on the TYPO3 mailing lists ([e.g. this one](http://lists.typo3.org/cgi-bin/mailman/listinfo/typo3-english)) or via Slack ([login](https://typo3.slack.com/) / [register](https://forger.typo3.org/slack)).

**Comment by melaande** [comment]
Hi @tantegerda1,

thank you for your response! I wasn't quite sure if it's a bug or just misconfiguration. 
I'll read the docs again and have a look at the mailing lists or Slack.

Best regards,
melaande
