### ISSUE TITLE
DB migration fails when updating from 2.2 to 2.3

### ISSUE THREAD

**Issue by hmccloy** [dmitryd/typo3-realurl#542]
When trying to update database in install tool, you geht the following errors:

Database update failed
Error: Incorrect table definition; there can be only one auto column and it must be defined as a key

Database update failed
Error: Key column 'uid' doesn't exist in table

The following changes are left in compare tool:
ALTER TABLE `tx_realurl_uniqalias_cache_map` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_realurl_uniqalias_cache_map` ADD PRIMARY KEY (uid)

**Comment by merzilla** [comment]
Hi @hmccloy 

maybe this helps:
https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x

Or just DELETE all realurl tables manually and let them install from scratch by install tool.

HTH
merzilla

**Comment by adrienjacob** [comment]
Maybe it's rather this article : 
https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#update-to-realurl-230-from-lower-2x-versions

**Comment by hmccloy** [comment]
Oh yes - thanks a lot. That helps!

**Comment by dietantejensen** [comment]
Had exactly the same issue during TYPO3 upgrade 7 to 8, and realurl 2.2 to 2.4. I had done the DB update mentioned above. 
DROP TABLE tx_realurl_uniqalias_cache_map;
did the trick.
