### ISSUE TITLE
Uppercase path not working in 2.3.0 anymore

### ISSUE THREAD

**Issue by Capaman** [dmitryd/typo3-realurl#543]
Uppercase realurl path not working after upgrading realurl from 2.2.1 to 2.3.0. Prior to the upgrade I ran this script as suggested:

https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#update-to-realurl-230-from-lower-2x-versions

... but now I can't access a record when using the uppercase path like:

domain/id/123D45WTA7/

I then get a page not found. The record and the link is working when using:

domain/id/123d45wta7/

... the original ID of the record is uppercase though: 123D45WTA7 ... and I need to access the record when entering uppercase url in the browser.

Any idea how I can access the record with uppercase again?

**Comment by dmitryd** [comment]
[Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
