### ISSUE TITLE
The path is not the default language for a site is formed from the name of the page

### ISSUE THREAD

**Issue by gabdullin** [dmitryd/typo3-realurl#55]
I noticed that the path for the English version of the site is formed from the name of the page, for example: domain.ru/ru/about/mission-strategy/ and domain.com/en/about-us/mission-and-strategy/
Multilingual and multi-domain site. Realurl 2.0.4

**Comment by dmitryd** [comment]
Try with cache disabled to see if it is a cache problem:

```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] = array (
	'xyz.com' => array(
		...
		'cache' => array(
			'disable' => true,
		),

```

**Comment by gabdullin** [comment]
I tried, nothing has changed

**Comment by dmitryd** [comment]
I have no ideas :confused:

**Comment by gabdullin** [comment]
Maybe I have a bad config?!
But it worked realurl 1.13.6

[realurl_conf.txt](https://github.com/dmitryd/typo3-realurl/files/164684/realurl_conf.txt)

**Comment by gabdullin** [comment]
![scr-032](https://cloud.githubusercontent.com/assets/4203660/13639766/4f4e0dc8-e623-11e5-9035-448b6e86092e.jpg)
![scr-033](https://cloud.githubusercontent.com/assets/4203660/13639773/580420ce-e623-11e5-8e24-38d70b6d7949.jpg)
![scr-034](https://cloud.githubusercontent.com/assets/4203660/13639780/5da55750-e623-11e5-9b57-6ab80c808042.jpg)


I want report the following:
1)
plugin realurl disable
links type:
https://domain.ru/index.php?id=info&L=0
https://domain.ru/index.php?id=info&L=1
work!
On this page we have links type:
https://domain.com/index.php?id=info&L=0
https://domain.com/index.php?id=info&L=1
work!
2)
plugin realurl enable
Enable automatic configuration
links type:
https://domain.ru/index.php?id=info&L=0
https://domain.ru/index.php?id=info&L=1
work!
On this page we have links type:
https://domain.com/index.php?id=info&L=0
https://domain.com/index.php?id=info&L=1
work!
links type:
https://domain.ru/info/
this page is a link:
https://domain.ru/en/information/   (!)
On this page we have links type:
https://domain.com/en/information/
https://domain.com/en/information/references/
                         ^                 ^
         (domain.com)          (not info)
[conf.lang.txt](https://github.com/dmitryd/typo3-realurl/files/165430/conf.lang.txt)
[realurl_conf.txt](https://github.com/dmitryd/typo3-realurl/files/165437/realurl_conf.txt)

P.S. I understand that are so many of words! I hope this helps!

**Comment by dmitryd** [comment]
Sorry for anybody, who reads this but we switch to our native language to understand the problem better. I will make a summary after resolving the issue.

***

Посмотри в `System>Configuration`, там на самом деле эта конфигурация? Картинка от другой проблемы, но поможет понять, где смотреть.

![rootpage2](https://cloud.githubusercontent.com/assets/306133/13640136/9dddc98c-e624-11e5-81d2-e6bd9c522907.png)

Или проблема в том, что страничные алиасы не работают?

**Comment by gabdullin** [comment]
Добрый вечер, Дмитрий!
Конфигурацию, проверил, это именно она. Корневая страница указана, и в конфиге, и на самой странице. Проблема именно в том, что не работают страничные алиасы. А свои исследования выше я привел, только для того, чтобы дать понять, что проблема возникает, и с автоконфигом, и с моей рабочей конфигурацией. Для контроля я также откатывался на typo3 7.6.3 и тоже проверил.
P.S. Неужели только у меня такая проблема?!
![scr-035](https://cloud.githubusercontent.com/assets/4203660/13645636/edadc148-e63c-11e5-82fa-8d5c06ad7d00.jpg)
![scr-036](https://cloud.githubusercontent.com/assets/4203660/13645639/ef461f82-e63c-11e5-8954-ae732a5243dc.jpg)

**Comment by dmitryd** [comment]
Алиасы были починены в 2.0.6. Похоже, у тебя в кэше старые ссылки остались просто. Попробуй полностью удаллить всё из обоих кэшей.

**Comment by dmitryd** [comment]
Sitemap будет работать, потому что он работает в режиме Backend, там кэши отключены.

**Comment by gabdullin** [comment]
Очистил все кеши, очистил таблицы realurl, перезапустил nginx, php-fpm, memcached, очистил кеши браузеров
Ничего не изменилось.
Удалил realurl, удалил все таблицы и поля realurl, установил снова, перезапустил nginx, php-fpm, memcached, очистил кеши браузеров
Ничего не изменилось.
Включил кеш realurl, перезапустил nginx, php-fpm, memcached, очистил кеши браузеров
Ничего не изменилось.
Убрал галку "Always prepend this domain in links" для домена domain.ru, выключил кеш realurl, перезапустил nginx, php-fpm, memcached, очистил кеши браузеров
Ничего не изменилось.

**Comment by gabdullin** [comment]
Добрый день, Дмитрий!
На другом домене развернул новую инсталяцию typo3 с использованием готовой сборки "The official Introduction Package" для пары страниц указал алиасы и сделал "переводы" на два языка, немецкий и датский. Получил следующее:
https://domain.ru/en/customize/
https://domain.ru/de/besonders-anfertigen/
https://domain.ru/dk/tilpasning/
Что-то мне подсказывает, что алиасы починились не до конца.

**Comment by dmitryd** [comment]
А что именно это подсказывает?

**Comment by dmitryd** [comment]
https://github.com/dmitryd/typo3-realurl/issues/69 ?

**Comment by gabdullin** [comment]
![scr-039](https://cloud.githubusercontent.com/assets/4203660/13724131/43531fb6-e88c-11e5-9e91-1d17e7d3358e.jpg)

Я имел ввиду, что алиас (обведено на картинке) работает только на дефолтном языке, на языках отличных от такового, алиасы не работают для формирования ссылки.

**Comment by gabdullin** [comment]
> #69 ?
Только что смотрел, не совсем понял, предлагается для нескольких сотен страниц дополнительно задавать еще и Speaking URL path segment? А если у кого пару тысяч страниц?

**Comment by dmitryd** [comment]
В общем-то, верно, что не используется. Alias – штука не переводимая, а для переведённых страниц используются поля c переводом. Используй speaking url path segment.

**Comment by gabdullin** [comment]
Я так понимаю при переходе от realurl 1.хх к 2.хх поменялась концепция в целом в этом смысле и возврата к концепции существовавшей в realurl 1.хх уже не будет?

**Comment by gabdullin** [comment]
Может какую-нибудь галку в настройках придумать, типа использовать алиасы основного языка?

**Comment by dmitryd** [comment]
Надо подумать.

**Comment by dmitryd** [comment]
Думаю, что починил. Если нет, откроем заново.

**Comment by gabdullin** [comment]
Дмитрий, добрый день!
Отлично! Пути теперь формируются из алиаса страницы для всех языков. Но появилась новая проблема. На дефолтном языке все пути работают без проблем, для других языков (не дефолтных) при попытке перейти по любой внутренней ссылке, попадаешь на главную страницу данного языка.

**Comment by dmitryd** [comment]
Да, есть ошибка.

**Comment by dmitryd** [comment]
В 2.0.9 поправлено.

**Comment by gabdullin** [comment]
Аллилуйя!
Дмитрий - Вы гений!!!

**Comment by gabdullin** [comment]
Дмитрий еще одна проблемка образовалась. Сейчас dd_googlesitemap в карте сайта для недофолтных доменов, формирует ссылки с дефолтным доменом. При реалурл 2.0.7 такого точно не было, на 2.0.8 и 2.0.9 появилось.

**Comment by gabdullin** [comment]
Дмитрий, добрый день!
И еще одна проблема выявилась. Как только включаешь кеширование  реалурл страницы с недефолтного языка (https://domain.com/sitemap/) показывают содержимое страницы дефолтного языка (https://domain.ru/sitemap/) хотя в адресной строке остается (https://domain.com/sitemap/). Кеши чистил, таблицы реалурл очищал полностью.
Так-что, в итоге, две проблемки.

**Comment by dmitryd** [comment]
Это с версией из репозитория?

**Comment by gabdullin** [comment]
2.0.9

**Comment by dmitryd** [comment]
Та, что в TER? С версией из TER у меня работает, а вот с текущей из git – проблема есть.

**Comment by gabdullin** [comment]
Я не совсем понимаю, что такое TER, я брал версию отсюда: https://typo3.org/extensions/repository/view/realurl скачал и установил, это TER? А как брать версию из git я не знаю.

**Comment by dmitryd** [comment]
Да, та ссылка, это TER (TYPO3 Extension Repository).

/sitemap/ - это обычная страница?
Для dd_googlesitemap язык надо указывать явно, там домены не работают.

**Comment by gabdullin** [comment]
> /sitemap/ - это обычная страница?

Да, это обычная страница, просто первое, что под руку попалось, а в целом аналогичная картина и по другим страницам сайта.

> Для dd_googlesitemap язык надо указывать явно, там домены не работают.

Понял, учтем, просто до версии 2.0.6 включительно и с доменами работало.

**Comment by dmitryd** [comment]
> Да, это обычная страница, просто первое, что под руку попалось, а в целом аналогичная картина и по другим страницам сайта.

Очень странно... Не могу воспроизвести.

> Понял, учтем, просто до версии 2.0.6 включительно и с доменами работало.

Не-а, никогда не работало и не должно было. dd_googlesitemap инициализирует TYPO3 так, чтобы realurl не включался на декодирование вообще. Там между ними есть проблема курицы и яйца, которую сложно решить.

**Comment by gabdullin** [comment]
> Не-а, никогда не работало и не должно было. dd_googlesitemap инициализирует TYPO3 так, чтобы realurl не включался на декодирование вообще. Там между ними есть проблема курицы и яйца, которую сложно решить.

Честное слово работало, много лет на realurl 1.хх и до 2.0.6 включительно, однозначно. Это не в качестве спора, а для информации :) В восьмом сообщении сверху есть скрин, как факт.

**Comment by dmitryd** [comment]
Странно. Это было убрано ещё в 2012-м году: https://github.com/dmitryd/typo3-dd_googlesitemap/commit/2db7396d1c73d4043ea8fbac885ae18276d8c0ff

**Comment by gabdullin** [comment]
> Очень странно... Не могу воспроизвести.

На чистой установке проверить не могу, у меня там домен только один, основной, привязан, а без  доменов все работает корректно. Подскажите, пожалуйста, Дмитрий, а галка "Always prepend this domain in links" для дефолтного домена должна стоять или нет?

**Comment by dmitryd** [comment]
> галка "Always prepend this domain in links" для дефолтного домена должна стоять или нет?

Вообще никогда не должна стоять.

**Comment by gabdullin** [comment]
У меня не стоит, уточнил на всякий случай.
