### ISSUE TITLE
indexed_search doesn't work with current version of realurl

### ISSUE THREAD

**Issue by bavarianbytes** [dmitryd/typo3-realurl#555]
TYPO3: 8.7.8
indexed_search: 8.7.8
realurl: 2.3.0

Fresh installed instance with some demo content. Indexing via `page.config.index_enable = 1` enabled. Cache is enabled, search marker are outputed in the HTML markup. Realurl with auto config.

If i switch realurl off, indexing of pages work, if i switch on indexing doesn't index anything.

**Comment by fazzyx** [comment]
I did not use this setup before, but did you try to use separate browser (not tabs) or logoff from TYPO3 backend while calling the frontend?
Maybe indexing is off while a user is logged in.

**Comment by bavarianbytes** [comment]
Yes, tried in another browser where wasn't logged in in the backend.

**Comment by dmitryd** [comment]
Please, [use Slack](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) to ask questions. This place is for confirmed bugs.
