### ISSUE TITLE
Page cache disabled with current version of Realurl

### ISSUE THREAD

**Issue by ccmbrother** [dmitryd/typo3-realurl#557]
Typo3 8.7.7.
Realurl 2.3.0. (tried both master and latest development from scratch)

In setup I have:
config.absRefPrefix = /
config.tx_realurl_enable = 1
config.simulateStaticDocuments = 0

Tried automatic and manual configuration but no luck. Cache is disabled. 
`<?php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']=array (
  '_DEFAULT' => 
  array (
    'init' => 
    array (
      'appendMissingSlash' => 'ifNotFile,redirect',
      'emptyUrlReturnValue' => '/',
    ),
    'pagePath' => 
    array (
	'spaceCharacter' => '-',
    'expireDays' => '3',
     'rootpage_id' => '1',
    ),
    'fileName' => 
    array (
      'defaultToHTMLsuffixOnPrev' => 0,
      'acceptHTMLsuffix' => 1,
      'index' => 
      array (
        'print' => 
        array (
          'keyValues' => 
          array (
            'type' => 98,
          ),
        ),
      ),
    ),
    'preVars' => 
    array (
      0 => 
      array (
        'GETvar' => 'L',
        'valueMap' => 
        array (
          'sl' => '3',
          'en' => '4',
        ),
        'noMatch' => 'bypass',
     ),
	array(
		'GETvar' => 'no_cache',
		'valueMap' => array(
			'nc' => 1,
		),
		'noMatch' => 'bypass',
	),
),
    'postVarSets' => 
    array (
      '_DEFAULT' => 
      array (
        'news' => 
        array (
          0 => 
          array (
            'GETvar' => 'tx_news_pi1[news]',
            'lookUpTable' => 
            array (
              'table' => 'tx_news_domain_model_news',
              'id_field' => 'uid',
              'alias_field' => 'title',
              'useUniqueCache' => 1,
              'useUniqueCache_conf' => 
              array (
                'strtolower' => 1,
                'spaceCharacter' => '-',
              ),
            ),
          ),
        ),
      ),
    ),
  ),
);
`

**Comment by ccmbrother** [comment]
Sorry, I already solved my problem. It was due to "Page caching is disabled to prevent spreading of wrong "L" value." 

There was no error until I have set [FE][disableNoCacheParameter] = true. 
After this I was able to find the true problem.

**Comment by sitevertreiber** [comment]
How do you solved your problem? I have the same problem witch realurl 2.3.0 and T3 7.6.23:
no caching/no indexing.
