### ISSUE TITLE
default language handled incorrectly in 2.3.0

### ISSUE THREAD

**Issue by M-K-ay** [dmitryd/typo3-realurl#558]
TYPO3: 7.6.23
RealURL: 2.3.0

- Patched RealURL from version 2.0.15 to 2.3.0
- Update script and manual DB updates were handled correctly
- adjusted the config file accordingly

Some TypoScript:
config.absRefPrefix = /
config.linkVars = L(0-4)
config.sys_language_uid = 0
[globalVar = GP:L = 1]
config.sys_language_uid = 1
[...]

Some config:
'preVars' => array(
		array(
			'GETvar' => 'L',
			'valueMap' => array(
				'de' => '0',
				'en' => '1',
[........]

Default language is DE (L=0), other languages are EN (1), [...some more up to L=4]

Handled by RealURL correctly:
index.php?id=123&L=1 results in /en/url-of-the-page/
index.php?id=633&L=4 results in /pt/url-of-other-page/

However, the default language is handled incorrectly. WITHOUT config.linkVars = L(0-4):
index.php?id=123&L=0 results in index.php?id=123&L=5
WITH config.linkVars = L(0-4):
index.php?id=123&L=0 results in index.php?id=123

If I deactivate RealURL all the links in the menu (and text) are correct.
So all links besides L=0 are handled correctly.

Migrated back to 2.0.15 using configuration from 2.3.0 --> Everything works

**Comment by tantegerda1** [comment]
what puzzles me, ist that
> index.php?id=123&L=0 results in index.php?id=123&L=5

could you post the whole `preVars` array?

**Comment by dmitryd** [comment]
Please, configure your system [according to the documentation](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-languages).

In future, [use Slack](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) to ask questions.
