### ISSUE TITLE
ext_localconf.php uses in_array() without checking if the second parameter is an array

### ISSUE THREAD

**Issue by mkarulin** [dmitryd/typo3-realurl#562]
ext_localconf.php uses in_array() without checking if the second parameter ($GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters']) is set and is an array.
This causes an error when activating the extension and excludedParameters is not (yet?) defined.

Realurl 2.3.0
TYPO3 7.6.23

**Comment by markuspoerschke** [comment]
Same as #559, #504?

**Comment by mkarulin** [comment]
Saw its fixed in #559
