### ISSUE TITLE
Feature: Allow multiple userFunc

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#567]
I'm in the situation where I need to have one userFunc for decode and userFunc for encode for the same postVarSets variable. I need 2 userFunc because each one have to extend respectively UrlDecoder and UrlEncoder to use their private functions.

Could it be an useful feature to have the possibility to configure multiple userFunc or one userFunc for decode and a different one for encode?

**Comment by dmitryd** [comment]
You can make your own dispatcher inside the single userFunc depending on the function mode. But the current interface cannot be changed because it is stable for years. Sorry.
