### ISSUE TITLE
Documentation: Language Domains configuration

### ISSUE THREAD

**Issue by lorenzulrich** [dmitryd/typo3-realurl#573]
The language domains configuration part of the Wiki has some (possible) issues:

https://github.com/dmitryd/typo3-realurl/wiki/Language-Domains#encode-configuration

Do I really need the `preVars` block for this scenario? Isn't this a contradiction to the initial statement that it's either a language domain or a language segment?

https://github.com/dmitryd/typo3-realurl/wiki/Language-Domains#encode-configuration

The code example has some missing commas after closing array brackets which makes it fail on copy and paste.

**Comment by dmitryd** [comment]
> Do I really need the preVars block for this scenario?

Yes, you need it.

Not a bug.

> The code example has some missing commas after closing array brackets which makes it fail on copy and paste.

I only see missing comma after `'noMatch' => 'bypass'` but this is a valid php syntax.

**Comment by lorenzulrich** [comment]
There are commas missing here which is not valid syntax as far as I know:

![image](https://user-images.githubusercontent.com/1816023/33239747-d0efa242-d2a8-11e7-972c-fd43cfa6fd74.png)

**Comment by lorenzulrich** [comment]
Another thing that popped up when using multiple root pages: 

In the reference, the parameter `rootpage_id` is not documented as a parameter of an `encode` configuration. It helps RealURL to correctly distinguish multiple encoding configurations for the same language UID.

I updated my Gist with a complete working example for a multi-domain/multi-language setup which also has working links across domains:
https://gist.github.com/lorenzulrich/eccef0bc1dd68a5daf17

**Comment by dmitryd** [comment]
Thank you, all fixed.
