### ISSUE TITLE
Default using L path segment does not work / exclude root page from path

### ISSUE THREAD

**Issue by merzilla** [dmitryd/typo3-realurl#58]
Hi Dmitry,
as described in the "Notes for integrators" section i´d like to have the language path segment in the URLs also for the default language. I´ve set the valueMap with "de => 0" and als the TypoScript configures the defaultGetVars.
The link to the root page contains the title of the root page, meaning I have:
http://my.domain.tld/page-title/
But i would expect it without "page-title". It even stays as it is if I set "Exclude from speaking URL" in the page properties.

I use TYPO3 7.6.4 and the latest realurl 2 from Git.

Thanks a lot and regards
Ralf

**Comment by dmitryd** [comment]
> The link to the root page contains the title of the root page, meaning I have:

It mean that it is not a root page but a page below the root page. Most likely you have a shortcut from root to this page.

"Exclude from speaking URL" does not work for the last segment. It works only for segments before the last. Otherwise it would not be possible to distinguish between the last segment and its parent page.

For the language problem, I suggest to check & clear URL cache entries and try again.

**Comment by merzilla** [comment]
Thanks for the quick advises. Clearing cache did not help, also truncated the realurl tables manually.

This is my page tree:
<img width="220" alt="bildschirmfoto 2016-03-07 um 15 35 31" src="https://cloud.githubusercontent.com/assets/636309/13572428/9a71dbea-e47a-11e5-9b8d-0b748687262b.png">

There is no shortcut. The page "websites" was a menu separator, but according to (just closed) #54 I chose doctype sysfolder now. But still same behavior.

In frontend it generates "mydomain.tld/home-page" for L=0. The subpages "Produkte, etc.." do not include "home-page".
What we also do: In htaccess we force URLs without "/de/" to be redirected to with "/de/".

As default L ist not set, this leads to an error for the home page. So "/de/home-page/" leads to this error:
"Reason: Segment "home-page" was not a keyword for a postVarSet as expected on page with id=3."
Whereas the links like "/produkte" are redirected to "/de/produkte/" and this works.

I´ve updated from 1.x to 2.x with the given advices: First altered tables, then update code, then DB compare etc. The realurl_configuration was adapted from autoconf, but the right valueMap for GETvar L has been set.

Thanks for giving more hints what could be the problem. Should I provide more information?

**Comment by dmitryd** [comment]
1. Check that `Websites` **does not** have the following flag set: `Use as Root Page`. This checkbox should be cleared there:
![rottpage](https://cloud.githubusercontent.com/assets/306133/13572826/6877c0e2-e48d-11e5-9fa3-5cb016d7c8ad.png)
1. Check that `Home page` **has** this flag set or has a domain record.

It looks like realurl is unable to find a proper root page id for your site. You can also check that in `Systems > Configuration`:

![rootpage2](https://cloud.githubusercontent.com/assets/306133/13572968/24c99932-e48e-11e5-80f9-e39f2975d833.png)

I believe in your case it is either incorrect or missing.

**Comment by merzilla** [comment]
It´s really strange. I even checked in table "pages" that "home page" is the only page with "is_siteroot = 1" flag set.
In TYPO3_CONF_VARS the right rootpage_id = 3 is set.

This is the realurl_conf.php file:
`<?php
/***************************************************************
 *  Copyright notice
 *  (c) 2016 Ralf Merz <ralf.merz@inm.ch>, INM AG
 *  All rights reserved
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

// add domain and rootpage UID here
$configureDomains = array(
        '_DEFAULT' => 3,
        'mydomain.tld' => 3
);

foreach ($configureDomains as $configureDomain => $rootpageId) {
    $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$configureDomain] = array(
/*
            'cache' => array(
                    'disable' => true,
            ),
*/
            'init' =>
                    array(
                            'appendMissingSlash' => 'ifNotFile,redirect',
                            'emptyUrlReturnValue' => '',
                    ),
            'pagePath' =>
                    array(
                            'rootpage_id' => $rootpageId,
                    ),
            'fileName' =>
                    array(
                            'defaultToHTMLsuffixOnPrev' => 0,
                            'acceptHTMLsuffix' => 1,
                            'index' =>
                                    array(
                                            'print' =>
                                                    array(
                                                            'keyValues' =>
                                                                    array(
                                                                            'type' => 98,
                                                                    ),
                                                    ),
                                            'robots.txt' => array(
                                                    'keyValues' => array(
                                                            'type' => 201
                                                    )
                                            )
                                    ),
                    ),
            'preVars' =>
                    array(
                            0 =>
                                    array(
                                            'GETvar' => 'L',
                                            'valueMap' =>
                                                    array(
                                                            'de' => 0,
                                                            'en' => 1,
                                                            'fr' => 2
                                                    ),
                                            'valueDefault' => 'de'
                                    ),
                    ),
            'postVarSets' =>
                    array(
                            '_DEFAULT' =>
                                    array(
                                            'article' =>
                                                    array(
                                                            array(
                                                                    'GETvar' => 'tx_news_pi1[action]',
                                                            ),
                                                            array(
                                                                    'GETvar' => 'tx_news_pi1[controller]',
                                                            ),
                                                            array(
                                                                    'GETvar' => 'tx_news_pi1[news]',
                                                                    'lookUpTable' =>
                                                                            array(
                                                                                    'table' => 'tx_news_domain_model_news',
                                                                                    'id_field' => 'uid',
                                                                                    'alias_field' => 'title',
                                                                                    'useUniqueCache' => 1,
                                                                                    'useUniqueCache_conf' =>
                                                                                            array(
                                                                                                    'strtolower' => 1,
                                                                                                    'spaceCharacter' => '-',
                                                                                            ),
                                                                            ),
                                                            ),
                                                    ),
                                    ),
                    ),
    );
}`

In TypoScript is:
`config {
    sys_language_uid = 0
    language = de
    defaultGetVars {
        L = 0
    }
    locale_all = de_CH.UTF-8

  //.....

    [globalVar = GP:L = 1]
    config.linkVars = L
    config.sys_language_uid = 1
    config.language = en
    config.locale_all = en_EN.utf8
[global]

[globalVar = GP:L = 2]
    config.linkVars = L
    config.sys_language_uid = 2
    config.language = fr
    config.locale_all = fr_FR.utf8
[global]
}`


Any hints how I can do more debugging etc?

**Comment by dmitryd** [comment]
`config.linkVars = L` must be global. Otherwise you will not get it in the url automatically. Now it is configred to be there only for L=1 and L=2, which does not make much sense because it will be there anyway. However if you make links like:

```
typolink {
  parameter = 5
  additionalParams = &x=y
}
```

than you will not have L=0 in the link because `config.linkVars` is not set.

Let's fix that first. Please, remove it from conditions and move to global scope.

**Comment by merzilla** [comment]
Oh my! Yes! ```config.linkVars``` was not in global scope for default language. Damn... so sorry for that. The project was "reconfigured" and i guess due to a copy-paste error this was missed.

Now "de" is in path by default. Great!
What is still not working is the "home page". E.g. the logo of the homepage is an image that is linked with typolink to ```typolink.parameter = 3``` 
But it renders ```http://mydomain.tld/de/home-page/``` now.

What I would need is ```http://mydomain.tld/de/```

**Comment by dmitryd** [comment]
Fix should be in 2.0.5 :smile:

**Comment by merzilla** [comment]
Hi Dmitry,

thank you very much for the fast bugfix. I can confirm that the link to the "home page" is now correct.

Greets
Ralf
