### ISSUE TITLE
Page URLs are not unique

### ISSUE THREAD

**Issue by sascha-egerer** [dmitryd/typo3-realurl#580]
If there a 2 pages with the same title the generated url is not unique an points always to the first match.

Create this Page tree to reproduce:
<pre>
 - ID: 1, Title: Root page
   - ID: 2, Title: Page A
   - ID: 3, Title: Page B
   - ID: 4, Title: Page A
</pre>

Now access the first Page A (ID 2). Generated url will be `root-page/page-a`. Now access the page with id 4. Generated url will also be `root-page/page-a`. If you now call `root-page/page-a` it'll always point to ID 2.

**Comment by dmitryd** [comment]
Please, read the docs before posting your reports.

**Comment by sascha-egerer** [comment]
@dmitryd Very helpful information. Would you be so kind and add a link to the correct part of the docs?

**Comment by fazzyx** [comment]
@sascha-egerer Take a look at the wiki entry here.

**Comment by sascha-egerer** [comment]
Did you forgot to add the link? 
Just found https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#page-titles now which looks like it describes the problem. That should be linked in the Configuration part...

**Comment by dmitryd** [comment]
@sascha-egerer 
> Very helpful information. Would you be so kind and add a link to the correct part of the docs?

I gave it so many times in the past that I am already tired of repeating the same thing again and again :)
