### ISSUE TITLE
2.3.1 changes behaviour of redirect to subpage

### ISSUE THREAD

**Issue by pniederlag** [dmitryd/typo3-realurl#581]
Our Page-Tree:
...
/root(id=1) [shortcut to page id=4]
/root/homepage(id=4)
...

On version 2.3.0 we get a redirect to
de/startseite.html

On version 2.3.1 we get a redirect to
index.php?id=4&L=0

Looking at the changes from 2.3.0 to 2.3.1 I do have no clue what's going on here...

**Comment by pniederlag** [comment]
maybe related #577 as stated, for us it as git reset --hard 2.3.0 -> fine, git reset --hard 2.3.1 -> broken.

**Comment by fgerards** [comment]
getting it here too, #577 is the right thread to respond

**Comment by pniederlag** [comment]
closing as duplicate of #277
