### ISSUE TITLE
Support for Finnish language in titles (suomi)

### ISSUE THREAD

**Issue by pixelbrackets** [dmitryd/typo3-realurl#584]
The method ```convertToSafeString()``` takes page titles and replaces special characters like german umlauts (e.g. »ä« to »ae«).

In Finland however, »ä« is also present in the language (suomi) and should be converted to »a« instead. See example page:
* Title: »Näe ja koe« URL: https://www.myhelsinki.fi/fi/nae-ja-koe/

The method should support this.

**Comment by dmitryd** [comment]
The conversion from `ä` to `ae` is done by the TYPO3 core by the function named `specCharsToASCII`. Please, report the issue for the TYPO3 core. RealURL can't change anything in this case.

https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Utility.php#L107

**Comment by pixelbrackets** [comment]
Okay. Issue on Forge https://forge.typo3.org/issues/83438
