### ISSUE TITLE
[Bug] Processing of config.absRefPrefix string

### ISSUE THREAD

**Issue by kludikovsky** [dmitryd/typo3-realurl#588]
Processing of the config.absRefPrefix should be terminated at the first white-space or be put under quotes. Otherwise any additional characters including comments are included in the url.

**Details** 
According to the [update instructions](https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#enabling-the-extension) 

>config.absRefPrefix = /
shoud be set.

I had in my TS
>config.absRefPrefix =&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;

which resulted in the output as 

> \<link rel="stylesheet" type="text/css" href="/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#typo3temp/compressor/ionicons.min-55bb841e2de83280b612a858dbd23497.css?1494938320" media="all">

_To be honest I have not tried to use quotes._

**Comment by dmitryd** [comment]
Why don't you put `#` onto another line?

**Comment by kludikovsky** [comment]
I've done that.
It just took me some time to figure out why my working site failed suddenly.

I just found out that there is **no inline comment**, which I used (from whichever example ;- ))  see [Typo Script documentation](https://docs.typo3.org/typo3cms/TyposcriptSyntaxReference/Syntax/TypoScriptSyntax/Index.html))

So I close this issue.
