### ISSUE TITLE
Add devLog calls

### ISSUE THREAD

**Issue by dmitryd** [dmitryd/typo3-realurl#59]
Add devLog (or some other log if no devlog extensions available) for devIP mask.

It should be triggered either by extconf or by TS conf and lo all kind of info about decoding and encoding process.

**Comment by sneopu** [comment]
Maybe you can use the [TYPO Logging API](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Logging/Index.html).

**Comment by dmitryd** [comment]
No, that's not devLog :) `GeneralUtility::devLog()` is the way to go because it can be displayed with `EXT:devlog` or similar extensions. If I use TYPO3 logging API, it will log always and it will be too much output. Devlog can be installed on demand, only when needed.
