### ISSUE TITLE
No realurl-conversion at link over shortcat-pages

### ISSUE THREAD

**Issue by rreichen** [dmitryd/typo3-realurl#592]
Calling a page 123 of type "shortcut" with a direct link to page 456 the URL of that page 456 is not realurl-converted. Its form is like /index.php?id=456. 
Calling that page 456 directly the URL is realurl-converted.

**Comment by rreichen** [comment]
I forgot to give an information about the tested versions: 
TYPO3: 8.7.9
realurl: 3.2.1

**Comment by twllndr** [comment]
Have a look at this issue: https://github.com/dmitryd/typo3-realurl/issues/577

**Comment by dmitryd** [comment]
Closed as duplicate.
