### ISSUE TITLE
defaultGetVars is not respected

### ISSUE THREAD

**Issue by ksamedia** [dmitryd/typo3-realurl#597]
Hello we need to force the language segment for sys_language_uid = 0

Typoscript:
config.linkVars = L
config.defaultGetVars {
L = 0
}
realURL:
        'GETvar' => 'L',
        'valueMap' => 
        array (
          'de' => '0',
'fr' => '1',
          'nl' => '2',
          'en' => '3',
        ),
        'noMatch' => 'bypass',

But this configuration has no effect on URL-Rewriting.

Disabling realURL will produce urls like this:
www.example.com/?id=2&L=0

Expected URL:
www.example.com/de/pagename

Setting defaultGetVars.L = 1 will produce the expected language segment

Any hints will help. thanks

**Comment by dmitryd** [comment]
Help: [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)
