### ISSUE TITLE
Wrong 404 Handling with RealURL

### ISSUE THREAD

**Issue by lochmueller** [dmitryd/typo3-realurl#599]
Hey guys,
I have some trouble with RealURL in combination with 404 handling.
The problem is:
http://realurl.vm/sfdshkjghsfdkghfsdkgksdjghjkfdsgdg.jsp
http://realurl.vm/de-de/agdasjgdjahsdg/deasdd.jsp

Both URIs are wrong (and are not part of the TYPO3 installation). The first one render the home page and the last one the 404 page.

In both cases I follow the function graph to \DmitryDulepov\Realurl\Decoder::runDecoding. There is no valid cache entry in both cases. But the first one get a pseudo cache entry and the last one not. Do you know why this problem exists? I think the segments ("/") are the difference in "decodePath" but I don't get the error....

Regards,
Tim

**Comment by dmitryd** [comment]
Don't ask questions in the bug tracker, please. See "Getting help" on the wiki for available support channels.

**Comment by lochmueller** [comment]
Hey @dmitryd 
this was not question. EXT:realurl break the 404 handling for URLs without any "/" in it.

If there is at least one "/" in the wrong URL, TYPO3s 404 handling work. If there is no "/" in the wrong URL, realurl decode the wrong URL to the current domain homepage (this is the bug).

I thought it is a bug obviously. 
Could you reopen the issue?

Regards,
Tim

**Comment by lochmueller** [comment]
I found the problem.

If you call a URL like this "/asdasdhjasdasd.html" the "decodeUrlParameterBlockUsingValueDefault" (in decodePreVars/decodeSingleVariable) function of my Language prevar replace the only segment, because my "L" preVar use "valueDefault".

So I have to replace the valueDefault for my language configuration with "'noMatch' => 'bypass'" to avoid this problem.

Perhaps this should be part of the documentation. If noMatch bypass is missing, this will break the 404 handling:
 https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#prevars

**Comment by chesio** [comment]
Hi @lochmueller ,

there is (or at least it used to be [last time I checked](https://github.com/dmitryd/typo3-realurl/issues/239#issuecomment-256041149)) one catch with using "'noMatch' => 'bypass'" this way: if you have default language set (for example `de`) and there's an existing page under `/de/something`, then a request to `/something` will not trigger 404 page, but instead serve the page under `/de/something`, which might be not what you want... :-)

Greets,
Česlav

**Comment by dmitryd** [comment]
@lochmueller 

> Perhaps this should be part of the documentation.

It is there for years. http://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-languages
