### ISSUE TITLE
Ugly URL's with complex postVarSets with all defined GETvars

### ISSUE THREAD

**Issue by tobiasklepp** [dmitryd/typo3-realurl#601]
After updating from realkurl 1.x to 2.x I run into a big issue of changing behaviour, how URLs are generated. I read all the available documentation to find out, if my configuration is wrong, but I cant find an error. Looks like the behaviour changes and the result is in my opinion not good. I use TYPO3 8.7.10, PHP 7.0, MySQL 5.5 and realurl 2.3.1.

I have realurl configured in the init section with `'emptySegmentValue' => '-',`. I need this configuration, because otherwise urls didn't work correct, if they are inside of an email or will be blocked by some firewalls, if multiple slashes following with no values between. For example MS Outlook automatically changes url like http://www.domain.com/page/my_key///2/ to http://www.domain.com/page/my_key/2/. So the plugin receives to value 2 not for skip but for show.

For the postVarSets I use the following configuration:

```
'postVarSets' => [
    '_DEFAULT' => [
        'my_key' => [
            [
                'GETvar' => 'tx_myext_pi1[show]',
            ],
            [
                'GETvar' => 'tx_myext_pi1[episode]',
            ],
            [
                'GETvar' => 'tx_myext_pi1[skip]',
            ],
            [
                'GETvar' => 'tx_myext_pi1[media]',
            ],
            [
                'GETvar' => 'tx_myext_pi1[sort]',
            ],
        ],
    ],
],
```
The URL looks now like this.
TYPO3: `index.php?id=1&tx_myext_pi1[show]=1`
Realurl 2.x: `http://www.domain.com/page/my_key/1/-/-/-/-/`
Realurl 1.x: `http://www.domain.com/page/my_key/1/`

If I combine it also with a output type, ge get the following url.
TYPO3: `index.php?id=1&tx_myext_pi1[show]=1&type=444`
Realurl 2.x (emptySegmentValue: -): `http://www.domain.com/page/my_key/1/-/-/-/-/rss.xml`
Realurl 2.x (emptySegmentValue: not set): `http://www.domain.com/page/my_key/1/////rss.xml`
Realurl 1.x: `http://www.domain.com/page/my_key/1/rss.xml`

The url `http://www.domain.com/page/my_key/1/////rss.xml` can not handled by Apache and return an 500 Internal Server Error.

**Is there a missing or wrong configuration on my side or is this the wanted behaviour?**

**Comment by dmitryd** [comment]
Please, see [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help) on the wiki.

**Comment by tobiasklepp** [comment]
I created as pull request #637 that solves this issue.

**Comment by dmitryd** [comment]
Solution is given [here](https://github.com/dmitryd/typo3-realurl/pull/637#issuecomment-619373111).
