### ISSUE TITLE
No 404 redirect with only one path segment

### ISSUE THREAD

**Issue by GuidoJansen** [dmitryd/typo3-realurl#605]
I want to have a 404 page with the setting in LocalConfiguration.php

```
$GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFound_handling'] => 'REDIRECT: /404';
```

For this to work I have to deactivate good upper dir in realurl_conf

```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT']['init']['postVarSet_failureMode'] => '';
```

This works fine on URLs with multiple path segments, but if I only have one path segment, the content of the root page is shown with no redirect.

Example:
https://example.org/qwerty => shows root page content
https://example.org/qw/er/ty => redirects to /404

What we need.
The first example should redirect to the /404 page as well.

The problem seems to be in the UrlDecoder class. In the decodePath method the variable `$currentPid` is set to the root page id and then the `$pageId` is set to the `$currentPid` later in the code. This happens on certain conditions that I do not understand.

TYPO3: 7,6.24
RealURL: 2.2.1

**Comment by GuidoJansen** [comment]
FYI: The error is still there after update to 2.3.1

**Comment by dmitryd** [comment]
Most likely related to `preVars` in your config. Please, ask for help in the appropriate channel in Slack as described on the wiki.

**Comment by GuidoJansen** [comment]
I found the issue on my behalf.
I have got a tx_news setting in _fixedPostVars_. After I moved that to the _postVarSets_ section, it did work as intended.
