### ISSUE TITLE
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT'] is now null

### ISSUE THREAD

**Issue by DanielRuf** [dmitryd/typo3-realurl#606]
With the update ~2 hours ago `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT']` is not set by default now.

I guess this is a regression.

**Comment by dmitryd** [comment]
Most likely you use `$TYPO3_CONF_VARS` instead of `$GLOBALS['TYPO3_CONF_VARS']` in your config.

**Comment by DanielRuf** [comment]
> With the update ~2 hours ago $GLOBALS['TYPO3_CONF_VARS']



> Most likely you use $TYPO3_CONF_VARS instead of $GLOBALS['TYPO3_CONF_VARS'] in your config.

This is not the case.

**Comment by DanielRuf** [comment]
Just take a look at the linked PR and the other comments which reference and comments at https://github.com/dmitryd/typo3-realurl/pull/517

**Comment by dmitryd** [comment]
Sure, I did look to your PR:
```
$TYPO3_CONF_VARS['EXTCONF']['realurl'] = [
```

Not the case?..

**Comment by DanielRuf** [comment]
I guess you miss the point.

You use `require_once` but forgot to define the globals.
See https://github.com/dmitryd/typo3-realurl/pull/517#issuecomment-328125980

https://github.com/dmitryd/typo3-realurl/commit/ab6a5cf5c5fed1bf804ed1119a469ed72406c0c6

**Comment by DanielRuf** [comment]
This
`global $T3_SERVICES, $T3_VAR, $TYPO3_CONF_VARS;`
is clearly missing and so the current version breaks setups.

**Comment by dmitryd** [comment]
Try using `$TYPO3_CONF_VARS` in `ext_localconf.php`. It worked before but now it does not. Didn't it break setups than? :) Always use `$GLOBALS`. It would be faster if you just go and fix it on your site than write comments here :)

**Comment by DanielRuf** [comment]
> than write comments here :)

That's why I've provided a PR.
You forgot the `global` definitions. About 6 months ago you wrote that `require_once` is not enough and would be a regression and break setups.

3 months later you change it to `require_once`, the way that you said before is not the solution.

Your change will break other setups too. Don't you want to add the `global` definitions then or revert the change and apply the proposed change?

Not sure why you are like this but your patch release breaks several setups. And it is definitely a bug in your code (missing `global` definitions).

Sorry but so far you do not seem to be very cooperative.

**Comment by dmitryd** [comment]
Well, yeah, I guess investing hundreds of hours of my free time (taken from family and rest!) since 2006 for you all to use realurl in your commercial projects is not cooperative. I promise to seriously think about it and adjust my priorities.

PR is merged, so enjoy my cooperation.
