### ISSUE TITLE
URL conflict, but other page is hidden

### ISSUE THREAD

**Issue by vmans** [dmitryd/typo3-realurl#608]
If I set "Speaking URL path segment" in page A, copy that page to page B (which includes "Speaking URL path segment") and page B remains "hidden", there is a duplicate. A URL conflict warning appears.

I expected that the "hidden" page would not give a conflict. At least, my customers - the editors that work with the CMS - don't understand this behaviour.

Result: page A gives a 404 error.

What is it, a bug?

**Comment by dmitryd** [comment]
[Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)

**Comment by vmans** [comment]
I see other issues in the list that might relate to this, but since RealURL is a perfect piece of software by now... cool response ;-)

**Comment by dmitryd** [comment]
Before you post to the bug tracker, please, be sure this is a bug and not intended behavior. How do you know this? Ask in one of listed support channels.

Processing each report takes time from actual fixing. So the more reports like this, the less time remains to fixing.

**Comment by vmans** [comment]
Thanks. I understand your point. And in that case, you should answer 95% of the issues here like that.

But how do I know this?

It's the first time since 2000 (yes, really) that I see a setting in a hidden page as being used in the frontend like this. May be it's my ommission.

Sorry for bothering. TYPO3 has more and more become "solving issues constantly" in stead of "building websites", so again, I get your point.

**Comment by vmans** [comment]
There is a path issue with a page that has been deleted from the page tree. So perhaps you should take a closer look?

I'm not closing out that I'm missing something. Explaining to editors that this is intended behavior is impossible, however.

![screenshot 2018-03-23 23 14 11](https://user-images.githubusercontent.com/25581914/37912668-48bb8f8e-3113-11e8-9ade-6f177458d778.png)

**Comment by dmitryd** [comment]
This is a different issue. Please, post that separately.
