### ISSUE TITLE
Uncaught TYPO3 Exception: #1420480928: RealURL was not able to find the root page id 

### ISSUE THREAD

**Issue by thomasmstein** [dmitryd/typo3-realurl#61]
I use port numbers (mainly for testing) and have two domain records for each website one with and one without port number. The start page is in a subdir "cms" which is included in the domain record e.g. "www.xxxxxxx.com:8157/cms/"
The page id for the root is found in the realurl_autoconfig.php 
Thanks
Thomas

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1420480928: RealURL was not able to find the root page id for the domain "www.xxxxxxx.com:8157" | Exception thrown in file /srv/www/sakia/cms/typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php in line 389. Requested URL: http://www.xxxxxxx.com:8157/cms/functionality/

**Comment by dmitryd** [comment]
That's wrong. Domain record may not contain subfolders. The field name clearly says "Domain", not "Domain and path".

Fix your system. This is not a realurl issue but incorrect TYPO3 setup.

**Comment by dmitryd** [comment]
Added to docs: https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-root-pages-for-realurl

**Comment by thomasmstein** [comment]
Hmm ... sorry this is what my subpage addition was based ont on ;-)
**Quote** from the Typo3 extended Help (Inline User Manual) on Domain (clicking on Domain in the domain record):
"Notice, if you run TYPO3 from a subdirectory of the domain name, you must include the subdirectory as well, eg. "www.my-domain.org/typo3_subdir/" "

PS: Removed the subdir path and got it to work now.
Thanks
Thomas

**Comment by ogrosko** [comment]
Hey dmitryd

After update realurl from 1.13.6 -> 2.0.10

I got same error
> Uncaught TYPO3 Exception
#1453732574: RealURL was not able to find the root page id for the domain "my-domain.local" (More information)
Exception thrown in file
/typo3conf/ext/realurl/Classes/EncodeDecoderBase.php in line 213.

I have only one domain with page uid = 1

Trying all Configuring root pages for RealURL with no effect and got same error
Do you have any idea where could be the problem?

**Comment by dmitryd** [comment]
> Do you have any idea where could be the problem?

No. It is installation-specific. Cannot tell without knowing anything about the installation.

**Comment by ogrosko** [comment]
I do the update according [https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x](this)
also runs all Compare database scripts

typo3 v7.6.4

**Comment by atnexxt** [comment]
Make a change at the beginning of your 2nd line:

`$TYPO3_CONF_VARS['EXTCONF']['realurl']['_DEFAULT'] = array(`

has to be correctly:

`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT'] = array(`

**Comment by ogrosko** [comment]
@atnexxt you are right :+1:

**Comment by kludikovsky** [comment]
Have the same issue with a T3 7.6.4.and Realurl 2.0.10


What happend: 

- Had  a problem with Realurl (maybe since last update on 11.3.)
- updated again
- got error
- found this issue
- check the for the config file, but could not find one.
- re-executed the setup proc with the standard settings
  - means with 
    - Enable automatic configuration
    - basic.enableAutoConf
- Result: 
  - there is no config file in typo3conf
