### ISSUE TITLE
regarding url isssue of typo3

### ISSUE THREAD

**Issue by prakashkorat** [dmitryd/typo3-realurl#612]
Hello,

My website is http://hero-pet.de

I have use typo3 ver. 8.0.

My currently url http://hero-pet.de/index.php?id=1. This is typo 3 url formate but my client requirement is something like:

ex.
www.Hero-Pet.de/de
Here you can see the Country Germany / Deutschland

www.Hero-Pet.de/at
Here you can see the Country Austria / Österreich

www.Hero-Pet.de/ch
Here you can see the Country Switzerland / Schweiz

I have install realurl extension and configuration but not change URL. I have also use .htaccess to rewrite url but this not working.

Thank you

**Comment by dmitryd** [comment]
Not a bug.
