### ISSUE TITLE
URL conflict, but other page is deleted

### ISSUE THREAD

**Issue by vmans** [dmitryd/typo3-realurl#616]
A deleted page can be detected as conflicting with one of the pages and this gives a frontend error.

![image](https://user-images.githubusercontent.com/25581914/38245639-4696b9a4-373f-11e8-8936-408f9f564f77.png)

This also coccurs wit hidden pages.
Related origin is #608.

**Comment by iseries** [comment]
Is there a fix? I have the same problem

**Comment by yogurtcu** [comment]
Me too, any idea how to solve this?

**Comment by dmitryd** [comment]
This would be possible only with direct sql calls, like `delete from tx_realurl_urldata where page_id=6521;`

**Comment by dmitryd** [comment]
I fixed it for future such cases but existing cases still have to be solved manually.
