### ISSUE TITLE
Data saved over tx_realurl_urldata when no chash is provided

### ISSUE THREAD

**Issue by instruccionesaldorso** [dmitryd/typo3-realurl#619]
**TYPO3 8.7.12**
**EXT:realurl 2.3.1** (NOT latest **2.3.2**) &
**EXT:news 6.3.0**

Good morning,

I got a press news list with pagination. 
Having in RealURL configuration over *postVarSets* section, the next setting to convert news pagination into a friendly url:

```
'postVarSets' => [
    '_DEFAULT' => [
	'page' => [
            [
                'GETvar' => 'tx_news_pi1[@widget_0][currentPage]',
            ],
        ],
    ],
],
```

And over TYPO3 core the next setting to:

```
[FE][cHashRequiredParameters] = 'tx_news_pi1[news],tx_news_pi1[@widget_0]';
```

1. I call my news page with:
_/index.php?id=123&L=1_
and the speaking url is saved into _tx_realurl_urldata_ table as:
_/de/presse/pressemitteilungen/_

2. I call my news page with widget pagination 0 (this is not possible internally from my configuration, but it seems some crawlers outside try that parameter) and NO Chash parameter:
_/index.php?id=123&L=1&tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=0_
and immediately the same speaking url as 1) is saved into tx_realurl_urldata table as well.
(?)

3. Clear all caches in FE (top navigation in BE).

4. Call frontend url:
_/de/presse/pressemitteilungen/_
and 404 page occurs.

Why RealURL saves in step 2) the URL in the table if _cHash_ field should be mandatory in the URL and no _cHash_ is provided in that case?

```
# select * from tx_realurl_urldata where speaking_url like 'de/presse/pressemitteilungen/';

+------+-----+------------+---------+-------------+------------------------------------------------------------+-------------------------------+----------------------------------------------------------------+--------+-------------------+-------------------+
| uid  | pid | crdate     | page_id | rootpage_id | original_url                                               | speaking_url                  | request_variables                                              | expire | original_url_hash | speaking_url_hash |
+------+-----+------------+---------+-------------+------------------------------------------------------------+-------------------------------+----------------------------------------------------------------+--------+-------------------+-------------------+
|  217 |   0 | 1523950581 |     123 |           7 | L=1&id=123                                                 | de/presse/pressemitteilungen/ | {"id":"123","L":"1"}                                           |      0 |         361415184 |        4087533679 |
| 1165 |   0 | 1523957543 |     123 |           7 | L=1&id=123&tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=0 | de/presse/pressemitteilungen/ | {"id":"123","L":"1","tx_news_pi1[@widget_0][currentPage]":"0"} |      0 |        3962851367 |        4087533679 |
+------+-----+------------+---------+-------------+------------------------------------------------------------+-------------------------------+----------------------------------------------------------------+--------+-------------------+-------------------+
```

This causes a URL conflict between both and my default news list page stops working.

**Comment by dmitryd** [comment]
RealURL encodes and decodes links as TYPO3 provides. It does not validate URLs in any way. Your job is to pass correct URLs for realurl.

For help, ask in Slack.
