### ISSUE TITLE
Postvarsets broken

### ISSUE THREAD

**Issue by klodeckl** [dmitryd/typo3-realurl#62]
Since I upgraded to Realurl 2, the following postvarsets do not work anymore (error 404 instead):

    'postVarSets' =>
    array (
      '_DEFAULT' =>
      array (
        'news' =>
        array (
          0 =>
          array (
            'GETvar' => 'tx_news_pi1[news]',
            'lookUpTable' =>
            array (
              'table' => 'tx_news_domain_model_news',
              'id_field' => 'uid',
              //'alias_field' => 'title',
              'alias_field' => "concat(FROM_UNIXTIME(datetime,\"%Y%m%d\"),uid,'-',IF(path_segment!='',path_segment,title))",
              'useUniqueCache' => 1,
              'useUniqueCache_conf' =>
              array (
                'strtolower' => 1,
                'spaceCharacter' => '-',
              ),
            ),
          ),

        ),
      ),
    ),

**Comment by dmitryd** [comment]
I am using this config (default for EXT:news):
```
'postVarSets' => array(
	'_DEFAULT' => array(
		'news' => array(
			array(
				'GETvar' => 'tx_news_pi1[news]',
				'lookUpTable' => array(
					'table' => 'tx_news_domain_model_news',
					'id_field' => 'uid',
					'alias_field' => 'title',
					'useUniqueCache' => 1,
					'useUniqueCache_conf' => array(
						'strtolower' => 1,
						'spaceCharacter' => '-',
					),
				),
			),
		),
	),
),
```
URLs in the list view look like: `http://typo3_7-6.dev/en/news-detail-page/news/test-item-2.html` and when I click on it, it opens without errors. I tested with/without logged in to BE, with/without url cache.

Please, post exact 404 error message.

**Comment by dmitryd** [comment]
By the way, this is invalid SQL: `IF(path_segment!=''`. Unlike PHP, "not equals" is SQL is `<>`, not `!=`. It may work in MySQL but not in every configuration.

**Comment by dmitryd** [comment]
Please, see if the probem still happens in realurl 2.0.6.

**Comment by klodeckl** [comment]
Thanks, after upgrading to 2.0.6 it works again. 
And thanks for the SQL hint, I corrected it. 
By the way I use this configuration to have a unique id in the url (for Google News).
