### ISSUE TITLE
L parameter instead of internal page link  ?L=0

### ISSUE THREAD

**Issue by christianarenz** [dmitryd/typo3-realurl#623]
With the latest realurl 2.3.2 all internal page links (multilingual website, single tree) are replaced by a L parameter. realurl 2.3.1 it works as expected. We use Typo3 Version 8.7.13. 

Example link: 
www.domain.com/?L=0
www.domain.com/?L=1
...

**Comment by agendartobias** [comment]
Is this related with our error to? 

URL conflict detected: '?L=0' is also used on page(s): v8.7.13 and 2.3.2

**Comment by dmitryd** [comment]
Solved privately.
