### ISSUE TITLE
Aliases for records with languageId -1 are not expired on rename

### ISSUE THREAD

**Issue by tomahi** [dmitryd/typo3-realurl#624]
With the Bugfix for issue #362 the languageId was added to the where clause in the select query for the alias in tx_realurl_uniqalias: https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Hooks/DataHandler.php#L168

**Problem**
The entries in tx_realurl_uniqalias never have the languageId -1, they always have a specific languageId (which means zero or higher). But for records with languageId -1, the where clause of the SQL-query is though limited to -1. Therefore the resultset is always empty and none of the aliases will be expired. As a result the existing speaking url(s) will also not be expired, so it is necessary to deleted them in the backend module to get an updated url.

**Solution**
Ignore the languageId if it's lower than zero to expire the existing aliases in all languages:
```
...
'AND value_id=' . $recordId . ($languageId < 0 ? '' : ' AND lang=' . $languageId)
...
```

**Comment by AMartinNo1** [comment]
I can confirm the issue with `-1`.
@dmitryd suggested to change `typo3conf/ext/realurl/Classes/Hooks/DataHandler.php::168` to `'AND value_id=' . $recordId . ' AND lang IN (' . $languageId . ',-1)'`. However, in my setup with realURL v2.5.0 and T3 v8.7.27 my SEO URL is not updated after changing.
