### ISSUE TITLE
array_diff problem with path with same segments

### ISSUE THREAD

**Issue by romanleitner** [dmitryd/typo3-realurl#626]
I found a bug in path decoding.
Lets say we have a url: www.example.com/at/home/countries/at/
URL is not found in urldata table, so plugin starts decoding.

It finds only root page "at/" in page Path ( method searchPathInCache() ), so it generates 2 arrays:
$pathSegments = ['at', 'home', 'countries', 'at'];
$remainingPathSegments = ['home', 'countries', 'at'];
PHP array_diff method returns empty array.

So the $nextResult it finds for "home" segment is stored in pathData table with pagePath "home" instead  of correct "at/home", and those www.example.com/home returns page "home" instead of 404 page.

Would suggest to replace array_diff with:
`foreach ($array2 as $value) {
  if(in_array($value, $array1)) {
    unset($array1[array_search($value, $array1)]);
  }
}
print_r($array1);
`

**Comment by dmitryd** [comment]
Nice one, thanks!

**Comment by romanleitner** [comment]
Hi Dmitry
thanks for taking a look at this issue.
I made a pull request #630 to it.
