### ISSUE TITLE
speaking path for extensions is not working anymore after the update to v2.3.2

### ISSUE THREAD

**Issue by medarob** [dmitryd/typo3-realurl#627]
Hi,

After I updated from realURL 2.3.0 to 2.3.2 the path/url for extensions like news, sf_event_mgt or jobfair is not resolved anymore.

The first part is correct, for example www.domain.com/page1/news/ but then it continues like ?tx_news_pi1%5Bnews%5D=7065&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Baction%5D=detail&cHash=c9019ef23475e0081dcda1183b8af5f5 which results in the following url:

www.domain.com/page1/news/?tx_news_pi1%5Bnews%5D=7065&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Baction%5D=detail&cHash=c9019ef23475e0081dcda1183b8af5f5

The same happens for other extensions like sf_event_mgt and jobfair as well so I assume it's a general error? When I downgrade to realURL 2.3.0 again, the speaking path for extensions works again.

Does anyone have an idea what can cause that behaviour?

I use Typo3 7.6.27 and the latest news extensions available for version Typo3 7.6 - which is 6.3.

**Comment by medarob** [comment]
using $GLOBALS['TYPO3_CONF_VARS'] instead of $TYPO3_CONF_VARS seems to do the trick and it's working again... :)

**Comment by M-arcus** [comment]
@medarob Where did you change $TYPO3_CONF_VARS to $GLOBALS['TYPO3_CONF_VARS'] ?

**Comment by M-arcus** [comment]
@medarob Thanks for your quick answer, I have the some problem. 
Sadly your fix didn't work for me, were there other changes?
