### ISSUE TITLE
postVarSet / Backend

### ISSUE THREAD

**Issue by stockwerk** [dmitryd/typo3-realurl#63]
When logged in the Typo3 backend (7.6.4) realurl 2.0.5 doesn't work. The message 'Segment [...] was not a keyword for a postVarSet as expected on page with id=1.' appears.
After log out everything works fine.

**Comment by dmitryd** [comment]
Incomplete error message --> cannot help.

**Comment by stockwerk** [comment]
The complete message is "Page Not Found
Reason: Segment "aktuelles" was not a keyword for a postVarSet as expected on page with id=1."

**Comment by dmitryd** [comment]
Okay. Do you have single news view on the page with id=1?

**Comment by dmitryd** [comment]
`aktuelles` -> is it a page name or a postVarSet name?
Is it possible that you have pages with the same name on the same tree level?

**Comment by stockwerk** [comment]
Yes there are single news views on the page with id=1.
"aktuelles" is a page name.
As I wrote - when I'm logged out of the backend or I take an other browser realurl works fine.

**Comment by dmitryd** [comment]
> As I wrote - when I'm logged out of the backend or I take an other browser realurl works fine.

This not relevant at the moment. Let me see if I can reproduce it...

**Comment by dmitryd** [comment]
How does the URL look like?

**Comment by stockwerk** [comment]
The URL looks like http://domain.tld/path/aktuelles

**Comment by dmitryd** [comment]
Is "Aktuelles" a subpage of "Path"? May be, you can just attach a picture of the page tree? It is very hard to understand what goes on there.

**Comment by stockwerk** [comment]
Yes, "aktuelles" is a subpage of "path". But this problem is on every page. As long as i've been logged in the backend, realurl doesn't work on the frontpage. After log out realurl is working fine on the frontend.

**Comment by dmitryd** [comment]
Please, see if the probem still happens in realurl 2.0.6.

**Comment by stockwerk** [comment]
Sad to say, but the problem still happens in realurl 2.0.6.

**Comment by PatrickNd** [comment]
Same problem by me. But I could recognize an effect.

First my page tree:
Root [1]
- Home[3]
- …
- News[5] (Hidden)
- - Detail page [14]
- ...

While I'm login at the Backend the Detail page shows me:
„Reason: Segment "neuigkeiten" was not a keyword for a postVarSet as expected on page with id=1.“
After I log out from the Backend, everything works fine.
If I set the Page News[5] to show, it works also while I’m login in the Backend.

**Comment by dmitryd** [comment]
`neuigkeiten` - is it a postVar name or is it a page?

> If I set the Page News[5] to show

What do you mean?

**Comment by PatrickNd** [comment]
"neuigkeiten" is a page. News = neuigkeiten
The News page is hidden.

**Comment by dmitryd** [comment]
In you page tree I do not see any `neuigkeiten` :(

If you hide a News page (5) but try to link to detail page (14), this will not work in all cases. You need to unhide News page.

**Comment by PatrickNd** [comment]
Sry I translate my tree for you but forgot to put neuigkeiten as news in the message.
The problem is, it function while I’m not logged at the backend.

**Comment by dmitryd** [comment]
When you are **not** logged in to Backend, information about URL is taken from cache. This is why you it works. Encoding does not care of the page is hidden and puts the URL to the cache.

When you are logged in to the Backend, cache is disabled, so the decoder has to find the page. It cannot find anything behind hidden pages.

**Comment by PatrickNd** [comment]
It makes sense, now I understand it.
**Thanks** :D

**Comment by dmitryd** [comment]
you are welcome :)
