### ISSUE TITLE
Typo3 9 compatibility

### ISSUE THREAD

**Issue by JavierYD** [dmitryd/typo3-realurl#632]
Is it possible to raise the required Typo3 versions to allow installations on version 9?

**Comment by dmitryd** [comment]
No. RealURL is not compatible with TYPO3 v9 and it cannot be compatible because TYPO3 v9 broke page translations comparing to all previous TYPO3 versions. Thus RealURL will not work with TYPO3 v9.

**Comment by JavierYD** [comment]
Ok, thanks for the answer.

**Comment by peterkraume** [comment]
Hi Dmitry,
will there be TYPO3 9.x compatible version of EXT:realurl, maybe when LTS is published?
The upload comment from the latest release today in TER suggest that there will be a compatible version:
`Maintanance release before dropping TYPO3 6.2 support and adding TYPO3 9.0`
Cheers
Peter

**Comment by dmitryd** [comment]
This is an error. There will be no v9 version. At least, none planned so far. There is too much to change. There is no sponsoring for it, so all work goes in my free time. I do not have much free time for this unfortunately.

Things may change if I get a client, who needs this. But it is a large work and will cost a certain amount of money.

**Comment by dmitryd** [comment]
I will keep this open because people will ask questions anyway.

**Comment by Patta** [comment]
@peterkraume Routing will be a core feature in 9 LTS

**Comment by peterkraume** [comment]
@Patta I'm aware of that feature for TYPO3 9.x. But there are number of reasons to have RealURL for 9.x as well:
- so far nothing is available for the core
- I assume the feature set of routing in the core will be limited in 9.x
- RealURL is proven and stable

**Comment by dmitryd** [comment]
If I remember correctly, routing was supposed to be out in April 2018 and now it is pushed to September. I hope they can make it... I also heard that it will be for pages only. So nothing like `/news/detail/my-news-item-title/`. But it could change already. I do not really follow what happens there.

**Comment by christophlehmann** [comment]
With 9.5 page records are linkable: https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html

**Comment by Pistil-Studio** [comment]
hi @dmitryd can you give me a quotation for develop the typo 9.x compatibility ? I need this for a big project

**Comment by dmitryd** [comment]
@Pistil-Studio 5000€

**Comment by schuberttobias** [comment]
Hi @dmitryd , is there any update on this?
Is compatibility for Typo3 9 LTS still not planned?

**Comment by dmitryd** [comment]
@schuberttobias Not planned. This will not happen due to lack of time and money.

**Comment by schuberttobias** [comment]
@dmitryd I understand - thank you for the quick response.
