### ISSUE TITLE
URLs not callable

### ISSUE THREAD

**Issue by Thoemel42** [dmitryd/typo3-realurl#635]
Hi,

I have URLs like domain.com/type/name. After deleting the realurl-cache, it's not possible to open the URL domain.com/type/name directly. The decoder always needs the information from the urldata table and the cache_map table.
When the URL domain.com/type is called, the encoder generates all the entries in the cache tables and opening domain.com/type/name works again.
Is there a way to call domain.com/type/name directly after clearing the cache?

**Comment by dmitryd** [comment]
> After deleting the realurl-cache

I told this many times on slack: do not delete realurl data because realurl needs it!

For help, please, ask on Slack as described in the "Getting help" page in the wiki above. This place is ONLY for bugs.
