### ISSUE TITLE
URL decoding caches wrong page

### ISSUE THREAD

**Issue by romanleitner** [dmitryd/typo3-realurl#638]
**url:** test.com/products/prod123
**structure:**
|- root [uid 1]
|-- products [uid 2]
|--- pro123 [uid 3] - Menu separator with "Exclude from speaking URL" set to 1
|---- prod123 [uid 4]
   
I have a parent/child page with the same url path segment.
Parent page prod123 [uid 3] has "Exclude from realurl path segment" set to 1.

If pathdata cache is empty, RealUrl while deconding does not check "Exclude from realurl path segment", and stores in tx_realurl_pathdata table for "**url /products/pro123**" page_id **3** instead of **4**.

Is there a reason why check of "page type" and "Exclude from speaking url" is in encoding process, but not in decoding?

**Comment by dmitryd** [comment]
1. RealURL does not cache anything on decoding.
1. Your case is described in "Limitations" in the docs [here](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#page-titles). Basically you are doing what you cannot do with RealURL.

**Comment by dmitryd** [comment]
You should not use menu separator for this. Use folder instead.
