### ISSUE TITLE
2 out of 3 is not enough

### ISSUE THREAD

**Issue by AureliusHogan** [dmitryd/typo3-realurl#639]
I've got a realy strange problem with my realurl configuration in one project. The following typoscript:

```
linkVars := addToList(L(0-2))
sys_language_uid = 0
sys_language_overlay = 1
sys_language_mode = content_fallback
language = de
locale_all = de_DE.UTF-8
htmlTag_langKey = de-DE
# for real url
defaultGetVars {
    L = 0
}
[globalVar = GP:L = 1]
	config {
		sys_language_uid = 1
		language = en
		locale_all = en_EN.UTF-8
		htmlTag_langKey = en-EN
	}
[global]

[globalVar = GP:L = 2]
	config {
		sys_language_uid = 4
		language = fr
		locale_all = fr_FR.UTF-8
		htmlTag_langKey = fr-FR
	}
[global]
```

My realurl configuration results in:

```
    'preVars' => 
    array (
      0 => 
      array (
        'GETvar' => 'L',
        'valueMap' => 
        array (
          'en' => '1',
          'fr' => '2',
        ),
        'noMatch' => 'bypass',
      ),
```

So far everything seams correct. But the following links are created:
domain.com/start.html
domain.com/en/home.html
**domain.com/index.php?id=1&L=2**

How do I get the french link to be encoded correctly, which would be?
**domain.com/fr/debut.html**

I cleared all of the caches (realy all of them), but it didn't help. Is there a way to exclude a language from _translation_?

My configuration:

- Typo3 V 8.7.18
- PHP 7.2.7
- Apache 2.4.29
- RealUrl 2.4.0
- CS_SEO 3.0.2
- ...

**Comment by dmitryd** [comment]
This place is only for bugs. Help is provided here: https://github.com/dmitryd/typo3-realurl/wiki/Getting-help#community-help-free
