### ISSUE TITLE
Saving URLs with wrong cHash is not a bug, not a feature, but a big problem

### ISSUE THREAD

**Issue by RozbehSharahi** [dmitryd/typo3-realurl#643]
This topic was already mentioned quite often and the best issue record for this is in my opinion:

https://github.com/dmitryd/typo3-realurl/issues/537

It might be right, that without an addQueryString in combination with pageNotFoundOnCHashError = false this can be prevented but ...

It is meither wrong to use pageNotFoundOnCHashError nor a TYPO3-Bug to have the cHash included in addQueryString. The problem is following:

If I find a TYPO3 webpage with RealUrl enabled and multilanguage and i try calling a page with a wrong cHash cache and this page does not throw a 404 the door is quite open for me to mess around with the database and causing a lot of not cached pages. 

In my opinion this is at least a security issue. I understand that it might not be easy to solve in a performant way. I understand all arguments about the problem that it is actually also not a clear bug by realurl. Nevertheless, at least I would not close this ticket and keep it as known issue / security issue.

A small suggestion: What about just implementing a warning if pageNotFoundOnCHashError=false and RealUrl is activated and say something like "keep in mind always to exclude cHash when using addQueryString with pageNotFoundOnCHashError deactivated?

Following is just a debug notice for those that come from google:

1) You probably have pageNotFoundOnCHashError=false
2) Go to a page on TYPO3 (on dev environment) and remove all urldata entries
3) Clear cache and call your page by typing the url in the browser as following: /my/url/path?cHash=whatever
4) Do the same with ?cHash=whatever2
5) Do the same with ?cHash=whatever3
6) ...
7) Check if your urldata table fills up with all this URLs
8) If yes, you should go and find all places where you use addQueryString and add addQueryString.exclude=cHash and/or activate pageNotFoundOnCHashError to avoid more problems
9) Now find out a way to determine all the urldata entries that will either cause a 404 page or non cached page on your setup
10) Good luck with SEO because turning on pageNotFoundOnCHashError will probably cause 404 pages while you won't even notice!

Kind regards

**Comment by dmitryd** [comment]
Please, see "Getting help" on the wiki about where to ask questions.
