### ISSUE TITLE
Update of non-unique URLs with new uid, Detailpage is not accessible anymore.

### ISSUE THREAD

**Issue by mpruy** [dmitryd/typo3-realurl#646]
Hello @dmitryd,
i have a big problem with non-unique paths in RealUrl. On our page we have detail-pages for various items. We get the Details via API and it is possible to renew an item. We generate our path with an "publication-id", this id is not the uid in the database. when the customer updates an item via api, the old database-entry is deleted and a new will be generated. This entry has the same "publication-id", but a new uid. The detail-path is named "xyz/detail/<publication-id>". That means, i can not switch to unique-path, because with an update the new path would be "xyz/detail/<publication-id>-1", but the old path is publicated via e-mail.

With the old version of RealUrl we used in an old page, everything worked. But now we relaunched the page and use realurl v2. Now when the news is posted at first time, it works. When the news is postet for the second time, that means the old database-entry is deleted and a new is gererated (with an new uid), we can not reach the detail-link, because there is still the old path in the realurl-cache, beside the new. But we get an error, that the (old) uid can not be found.

When i delete the entry in the realurl-cache at the update manually, the detail-page can not be found since someone clicks the link in list-page, so users who have the deeplink can not find the detailpage.

Is there any workaround in realurl to solve such a problem or do i have an error in my configuration?

**Comment by dmitryd** [comment]
I believe the issue is already discussed in Slack and solved.
