### ISSUE TITLE
Segments paths for news don't work after the upgrade

### ISSUE THREAD

**Issue by MariaGheorghe** [dmitryd/typo3-realurl#647]
Hi all,

After an upgrade from 6.2 to 8.7.13  we lost the segments paths from news. We imported the news from tt-news to news with the news importer plugin, configured everything like the manual says and tried with different versions of for plugins but without any result. 
We also repeated the upgrade on another server.
The realurl works except for news.
We did the same things for other sites and each time worked smoothly.
Did someone from you have problems with this too?

**Comment by dmitryd** [comment]
See "Getting help" in the wiki.
