### ISSUE TITLE
Problem with RealUrl combined with staticfilecache

### ISSUE THREAD

**Issue by borisdittebrandt** [dmitryd/typo3-realurl#648]
Hello @dmitryd,
we have a problem with RealUrl combined with staticfilecache. 
When we look at the staticfilecache status in the info module (no matter which page), it always shows the warning "config.no_cache is true" if realurl is enabled. If realurl is disabled, the warning message is gone. Do you have any idea what could cause this behavior? 
Thank you in advance!
Boris

TYPO3 8.7.19
realurl 2.4.0
staticfilecache	5.2.0

Our realurl_conf.php:

`<?php
// Summary: Main Conf for the domains
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT']  = array(
    'init' => array(
        'enableCHashCache' => true,
        'appendMissingSlash' => 'ifNotFile, redirect',
        'enableUrlDecodeCache' => true,
        'enableUrlEncodeCache' => true,
        'respectSimulateStaticURLs' => false,
        'emptyUrlReturnValue' => '/',
    ),
    'pagePath' => array(
        'type' => 'user',
        'userFunc' => 'EXT:realurl/class.tx_realurl_advanced.php:&tx_realurl_advanced->main',
        'spaceCharacter' => '-',
        'languageGetVar' => 'L',
        'firstHitPathCache' => 1,
        'expireDays' => 7,
    ),
    'preVars' => array(
        0 => array(
            'GETvar' => 'L',
            'valueMap' => array(
                'en' => 1
            ),
            'valueDefault' => 'de',
            'noMatch' => 'bypass',
        )
    ),
    'fixedPostVars' => array(
            'newsDetailConfiguration' => array(
                    array(
                            'GETvar' => 'tx_news_pi1[action]',
                            'valueMap' => array(
                                    'detail' => '',
                            ),
                            'noMatch' => 'bypass'
                    ),
                    array(
                            'GETvar' => 'tx_news_pi1[controller]',
                            'valueMap' => array(
                                    'News' => '',
                            ),
                            'noMatch' => 'bypass'
                    ),
                    array(
                            'GETvar' => 'tx_news_pi1[news]',
                            'lookUpTable' => array(
                                    'table' => 'tx_news_domain_model_news',
                                    'id_field' => 'uid',
                                    'alias_field' => 'title',
                                    'addWhereClause' => ' AND NOT deleted',
                                    'useUniqueCache' => 1,
                                    'useUniqueCache_conf' => array(
                                            'strtolower' => 1,
                                            'spaceCharacter' => '-'
                                    ),
                                    'languageGetVar' => 'L',
                                    'languageExceptionUids' => '',
                                    'languageField' => 'sys_language_uid',
                                    'transOrigPointerField' => 'l10n_parent',
                                    'expireDays' => 180,
                            )
                    )
            ),
            'newsCategoryConfiguration' => array(
                    array(
                            'GETvar' => 'tx_news_pi1[overwriteDemand][categories]',
                            'lookUpTable' => array(
                                    'table' => 'sys_category',
                                    'id_field' => 'uid',
                                    'alias_field' => 'title',
                                    'addWhereClause' => ' AND NOT deleted',
                                    'useUniqueCache' => 1,
                                    'useUniqueCache_conf' => array(
                                            'strtolower' => 1,
                                            'spaceCharacter' => '-'
                                    )
                            )
                    )
            ),
            'newsTagConfiguration' => array(
                    array(
                            'GETvar' => 'tx_news_pi1[overwriteDemand][tags]',
                            'lookUpTable' => array(
                                    'table' => 'tx_news_domain_model_tag',
                                    'id_field' => 'uid',
                                    'alias_field' => 'title',
                                    'addWhereClause' => ' AND NOT deleted',
                                    'useUniqueCache' => 1,
                                    'useUniqueCache_conf' => array(
                                            'strtolower' => 1,
                                            'spaceCharacter' => '-'
                                    )
                            )
                    )
            ),
            '10' => 'newsDetailConfiguration',
            '237' => 'newsDetailConfiguration',
    ),
    'postVarSets' => array(
        '_DEFAULT' => array(
            'nc' => array(
                'type' => 'single',
                'GETvar' => 'no_cache',
            ),
            // News
            'cpage' => array(
                array(
                    'GETvar' => 'tx_news_pi1[%40widget_0][currentPage]'
                ),
            ),
            // news current page
            'currentpage' => array(
                array(
                    'GETvar' => 'tx_news_pi1[@widget_0][currentPage]'
                ),
            ),
            // news controller and action
            'news' => array(
                 array(
                     'GETvar' => 'tx_news_pi1[controller]',
                     'noMatch' => 'bypass',
                 ),
                 array(
                     'GETvar' => 'tx_news_pi1[action]',
                     'noMatch' => 'bypass',
                 ),
            ),
            // powermail controller
            'send' => array(
                array(
                    'GETvar' => 'tx_powermail_pi1[controller]',
                ),
            ),
            // powermail action
            'mail' => array(
                array(
                    'GETvar' => 'tx_powermail_pi1[action]',
                ),
            ),
            // joboffers
            'job' => array(
                array(
                    'GETvar' => 'tx_tanjoboffers_tanjoboffers[job]',
                    'lookUpTable' => array(
                        'table' => 'tx_tanjoboffers_domain_model_job',
                        'id_field' => 'uid',
                        'alias_field' => 'title',
                        'addWhereClause' => ' AND NOT deleted',
                        'useUniqueCache' => 1,
                        'useUniqueCache_conf' => array(
                            'strtolower' => 1,
                            'spaceCharacter' => '-',
                        ),
                    ),
                ),
                array(
                    'GETvar' => 'tx_tanjoboffers_tanjoboffers[controller]',
                    'noMatch' => 'bypass',
                ),
                array(
                    'GETvar' => 'tx_tanjoboffers_tanjoboffers[action]',
                    'noMatch' => 'bypass',
                ),
            ),
            // ke_search
            // ke_search sword
            'sword' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[sword]',
                ),
            ),
            // ke_search kepage
            'kepage' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[page]',
                ),
            ),
            'kefilter11' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[filter][1][1]'
                )
            ),
            'kefilter12' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[filter][1][2]'
                )
            ),
            'kefilter111' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[1][1][1]'
                )
            ),
            'kefilter212' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[2][1][2]'
                )
            ),
            // ke_search resetFilters
            'resetFilters' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[resetFilters]',
                ),
            ),
            // ke_search sortByField
            'sortByField' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[sortByField]',
                    'noMatch' => 'bypass',
                ),
            ),
            // ke_search sortByDir
            'sortByDir' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[sortByDir]',
                    'noMatch' => 'bypass',
                ),
            ),
            // ke_search redirect
            'redirect' => array(
                array(
                    'GETvar' => 'tx_kesearch_pi1[redirect]',
                ),
            ),
        ),
    ),
);
// Summary: Domain settings
$domainSettings = array(
    // Corporate website
    1 => array(
        'domains' => array(
            'xyz.com',
        ),
        'defaultLanguage' => 'de-de',
    )
);

// Summary: Set the domainsettings

foreach ( $domainSettings as $rootPageId => $settings ) {
    $defaultLanguage = (isset($settings['defaultLanguage']) ? $settings['defaultLanguage'] : NULL);
    foreach ( $settings['domains'] as $domain ) {
        $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$domain] = $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT'];
        $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$domain]['pagePath']['rootpage_id'] = $rootPageId;
        if ( isset($defaultLanguage) ) {
            $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$domain]['preVars'][0]['valueDefault'] = $defaultLanguage;
        }
        if ( isset($settings['valueMap']) && is_array($settings['valueMap']) ) {
            $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$domain]['preVars'][0]['valueMap'] = $settings['valueMap'];
        }
    }
}
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT']['init']['postVarSet_failureMode'] = '';
$GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFound_handling_statheader'] = 'HTTP/1.0 404 Not Found';
if (preg_match('/\/en-en\//', $_SERVER['REQUEST_URI']) || $_GET['L'] == 1) {
    $GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFound_handling'] = '/en/404/';
} else  {
    $GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFound_handling'] = '/404/';
}`

**Comment by dmitryd** [comment]
I do not know why staticcache shows that. Shouldn't question about staticcache be asked from staticcache developers?

**Comment by dmitryd** [comment]
No feedback
