### ISSUE TITLE
Ignore new Facebook Url Parameter - fbclid

### ISSUE THREAD

**Issue by WorksDev** [dmitryd/typo3-realurl#649]

**Comment by dmitryd** [comment]
Thank you!

**Comment by Outdoorsman** [comment]
This is a breaking change on a lot of websites... just a +1 for getting this into a version update so we don't have to go through every website to use `dev-master` only to revert again.

**Comment by dhuf** [comment]
@Outdoorsman I agree, but to fix it I used the composer-patch in case it might help

**Comment by uocnma** [comment]
Is it planned to release a version 2.4.1 to TER which includes this fix ? We don't have the possibility to install via composer. realURL 2.4 does not include the fix yet.

Kind regards,
Nelson.

**Comment by sypets** [comment]
On a related note: What I did is remove fbclid entirely in Webserver configuration entirely, for example in Apache:

```
RewriteCond %{QUERY_STRING} ^(.*&)?fbclid=[^&]*(?:&(.*))?$ [NC]
RewriteRule ^ %{REQUEST_URI}?%1%2 [L,R=301,NE]
```

Unless you plan to use this in some way, I see no benefit of passing this along to TYPO3 in the first place. Benefits:
* use redirects, so you get final URL without fbclid and prevent people linking to this
* works whatever version of realurl or other URL generation you currently use. 
* simple solution that requires no extra configuration in TYPO3
