### ISSUE TITLE
URL Cache and Path Cache showing different Root page ids for same page 

### ISSUE THREAD

**Issue by thomasmstein** [dmitryd/typo3-realurl#65]
Version 2.0.6 and before

In the backend realurl section **URL Cache** and **Path Cache** pointing to different Root page ids for same page e.g. 53. The correct root page with the domain entry has the id 37. 

Another root page with the id 1 exist but is deactivated. 

Page 53 was created at an earlier stage before domain entries were added. Newly created page receive correct reference to their root page. 

If I delete the cache entry beside e.g. the 'infocard' entry I get the message that the cache entry was removed but the entries do not disappear.

**_Current setup_**

_Active site_
- Site ONE (root id= 37, domain record)
	- Page 'infocard' (id=53)

_ALL deactivated sites (deactivated  on root level)_
- Site TWO (root id=60, domain record)
- Site THREE (root id=65, domain record)
- Site FOUR (root id=1, NO domain record)
![image6](https://cloud.githubusercontent.com/assets/17682916/13622131/bed40b1c-e5f0-11e5-88af-4505c2ad98bd.jpg)
![image7](https://cloud.githubusercontent.com/assets/17682916/13622135/ca135956-e5f0-11e5-9c80-8b861b277385.jpg)

**Comment by dmitryd** [comment]
> If I delete the cache entry beside e.g. the 'infocard' entry I get the message that the cache entry was removed but the entries do not disappear.

Did you upgrade from realurl 1.x? If yes, did you rin sql queries as required [here](https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x)? If you didn't, you will have all kind of problems including ones with removal of cache entries.

**Comment by dmitryd** [comment]
No feedback provided.
