### ISSUE TITLE
Update from 2.2.1 to 2.4.0 throws "error in your SQL syntax"

### ISSUE THREAD

**Issue by r3h6** [dmitryd/typo3-realurl#652]
Directly after install the new version (2.4.0) on a TYPO3 7.6 through the backend module I got following message:

Error: You have an error in your SQL syntax;ALTER TABLE tx_realurl_uniqalias_cache_map ADD uid int(11) NOT NULL auto_increment, ADD PRIMARY KEY (uid);

Just before updating the old version (2.2.1) I updated the table structure as described here:
https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#update-to-realurl-230-or-newer-from-lower-2x-versions

**Comment by dmitryd** [comment]
Yes, this is because TYPO3 is unable to process changes to primary keys. You need to remove that field manually and run Database compare in the Install tool.

**Comment by dmitryd** [comment]
```sql
ALTER TABLE tx_realurl_uniqalias_cache_map ADD uid int(11) NOT NULL  auto_increment PRIMARY KEY ;
```
