### ISSUE TITLE
Deleting non expired alias leads to inconsistent state in urldata

### ISSUE THREAD

**Issue by simare** [dmitryd/typo3-realurl#653]
Deleting an active (non-expired) alias leads basically to the same behaviour as described in #362.
The entry in urldata remains with `expired = 0` and changes to title etc. have no effect.

**Comment by dmitryd** [comment]
Possibly you are using the old realurl version because I tested this about 2 weeks ago for a client.

**Comment by dmitryd** [comment]
Not reproducible.
