### ISSUE TITLE
Set compatibility to PHP 7.3.x

### ISSUE THREAD

**Issue by MartinH0** [dmitryd/typo3-realurl#657]
I'm using this extension under PHP 7.3.1 at Typo3 8.7.x and have never had a problem! Everything is working fine as it should :)
Pls change compatibility to PHP 7.3 so also People who run this extension with PHP 7.3 get the Updates, if not Updates are not shown in extensionmanager as requirements are not meet

**Comment by dmitryd** [comment]
There is another ticket where people have warnings with 7.3. If you do not have the problem, it does not mean nobody else will. This has to be tested before the version can be raised.

**Comment by M4rt1n17** [comment]
@dmitryd thanks. Then I would please you to see this as "it's working for me".

**Comment by LeoniePhiline** [comment]
@dmitryd Searching for "7.3" or "Warning" in the open issues yielded no result. Is the ticket you mentioned closed by now?
