### ISSUE TITLE
subtitle in page fields lookup for segment construction

### ISSUE THREAD

**Issue by matthaa** [dmitryd/typo3-realurl#659]
Hi,
is it possible to use the subtile as page fields lookup for segment construction? If I include the subtitle in "basic.segTitleFieldList (String)" in EM, e.g. "tx_realurl_pathsegment, alias, subtitle, nav_title, title, uid" the subtitle is ignored.
Thanks,
Matthias

**Comment by dmitryd** [comment]
Questions to go the Slack channel. Please, see "Getting help" in the wiki.
