### ISSUE TITLE
Use lookUpTable with external database

### ISSUE THREAD

**Issue by Oktopuce** [dmitryd/typo3-realurl#660]
The 'lookUpTable' function doesn't work with an external database.
 
If you have a configuration like this in LocalConfiguration.php :

```
'DB' => [
    'Connections' => [
        'Default' => [
            'charset' => 'utf8',
            'dbname' => 'default-db',
            'driver' => 'mysqli',
            'host' => '127.0.0.1',
            'password' => 'xxx',
            'port' => 3306,
            'user' => 'xxx',
        ],
        'theExternalDb' => [
            'charset' => 'utf8',
            'dbname' => 'external-db',
            'driver' => 'mysqli',
            'host' => 'localhost',
            'password' => 'xxx',
            'port' => 3306,
            'user' => 'xxx',
        ],
    ],
    'TableMapping' => [
        'MyexternalTable' => 'theExternalDb',
    ]
]

```
and you want to get data from the external DB in RealUrl > lookUpTable :

```
'GETvar' => 'tx_aimsmembers_manage[member]',
'lookUpTable' => [
    'table' => 'MyexternalTable',
    'id_field' => 'uid',
    'alias_field' => 'MyField',
    'useUniqueCache' => 1,
    'useUniqueCache_conf' => [
        'strtolower' => 1,
        'spaceCharacter' => '-',
    ],
],

```
it result in an error because RealUrl tries to read data from default database and not external database.

The problems comes from the use of old Typo3 API : $GLOBALS['TYPO3_DB']->exec_SELECTgetSingleRow() for example.

**Comment by dmitryd** [comment]
Yes, it does. RealURL is 7.6 compatible. 7.6 does not have the new API, so RealURL uses what is available on all platforms.

I see two possible solutions for you.

The first is: you have to implement lookup yourself or make a wrapper for the database connection, which will dynamically switch queries between connections. We did it for a project some time ago.

The second: probably I can port all those queries to new API but definitely not going to make this for free. And RealURL will loose compatibility with 7.6 after that.
