### ISSUE TITLE
Url data within mounted tree sometimes has an entry without MP parameter leading to a 404 in FE

### ISSUE THREAD

**Issue by foobar13372** [dmitryd/typo3-realurl#663]
We have a tree outside any siteroot/domain, but this tree is mounted in several actual siteroot/domain trees (shared content on several domains).

We noticed that sometimes realurl creates an entry in the urldata table with the correct speaking url but without the MP parameter in the original URL.

This seems to happen if the entry for this page is not avaiable and someone in the backend clicks on "preview" on a mounted subpage. I'm not so much into the "magic" that happens then, but this is how we observed it: TYPO3 opens `index.php?id=123` (without MP parameter obviously) and does a redirect to the first domain it finds that has this page mounted (I think it's the first, at least it's not the one used for the backend login), and then does a reidrect to `/` on this domain (no idea how this works). The link to the page is also rendered in a menu, I assume this is the moment realurl creates the speaking url. But then occasionally the entry without the MP parameter is created.

If we now click on the menu link to the exact same page we were just seeing with only the `id` Parameter, we see that the speaking url is perfectly correct, but leads to a 404.

If we delete the "MP-less entry", do not use the preview button again, but navigate through the frontent to the page, everything works fine, the speaking URL is created with MP parameter.

Of course, we as devs can avoid clicking "preview" in mount pages, but we can not forbid/train this to several hundreds of editors that are working on this installation.

I'm not sure if this is actually a realurl bug, if we are misisng some kind of configuration regarding mounted pages or if this is a "conceptual hole" of how TYPO3 works internally (but in general realurl works perfectly fine on this setup, just these occasional "mount point 404s" are gving us headaches).

Maybe #644 is releated.

We are using realurl 2.5.0 on TYPO3 8.7.24.

**Comment by michaelscheel** [comment]
We're experiencing the same problem, but it is not related to the backend preview button. We added a timestamp (ON CREATE) to tx_realurl_pathdata to further analyze the problem, but so far we had no luck. It seems completely random to us.

**Comment by foobar13372** [comment]
@michaelscheel 
We also more and more get the impression that it is "random". We noticed it by using the preview button, but we never could fully confirm that this is the only (or even actual) situation when it happens.

**Comment by michaelscheel** [comment]
@foobar13372 After making the following changes to UrlDecoder.php it seems to work more reliable. I'm not sure what side effects this has, but the solution makes sense to me. Records generated by the UrlEncoder are always correct.

```php
if ($this->mountPointVariable !== '') {
    $result->setMountPoint($this->mountPointVariable);
}
if ($originalMountPointPid !== 0) {
    // Mount point with mount_pid_ol==1
    $this->mountPointVariable = $page['uid'] . '-' . $originalMountPointPid;
    // No $this->mountPointStartPid here because this is a substituted page
}
elseif ((int)$page['doktype'] === PageRepository::DOKTYPE_MOUNTPOINT) {
    $this->mountPointVariable = $page['mount_pid'] . '-' . $page['uid'];
    $this->mountPointStartPid = (int)$page['mount_pid'];
}
```

to

```php
if ($originalMountPointPid !== 0) {
    // Mount point with mount_pid_ol==1
    $this->mountPointVariable = $page['uid'] . '-' . $originalMountPointPid;
    // No $this->mountPointStartPid here because this is a substituted page
}
elseif ((int)$page['doktype'] === PageRepository::DOKTYPE_MOUNTPOINT) {
    $this->mountPointVariable = $page['mount_pid'] . '-' . $page['uid'];
    $this->mountPointStartPid = (int)$page['mount_pid'];
}
if ($this->mountPointVariable !== '') {
    $result->setMountPoint($this->mountPointVariable);
}
```

**Comment by foobar13372** [comment]
@michaelscheel 
I tested some more, and yes, your proposal seems to work.

I also found out the exact circumstances when a 404 occurs:
When urldata has NO entry for the urldata, but pathdata has an entry without MP parameter.
Actually realurl writes both entries into pathdata (with and without MP parameter) and when somehow the according urldata entry vanishes (don't know how/when - for us it appears randomly every few weeks on a big website) then a 404 occurs (because it finds the MP-less entry in pathdata).

@dmitryd 
Is there a reason why 
```
if ($this->mountPointVariable !== '') {
    $result->setMountPoint($this->mountPointVariable);
}
```
happens BEFORE actually setting `$this->mountPointVariable`?

**Comment by michaelscheel** [comment]
We're still experiencing this issue – less common, but it still happens every few days.

**Comment by perltwiesekt** [comment]
Currently facing the same problem in our TYPO3 installation consisting of ~80 domains. What we've tried: changed the configuration from automatic to manual and reduced the size of die configuration file (copied array the root page to all domains). The issue is still happening sometimes, but not as often as prior to that change. A second installation seems to be unaffected as it only includes 20 domains. Also i found an early issue #140 which fixed the same problem in TYPO3 7.6, unfortunately the mentioned bugfix release v2.1.7 isn't available for v8.

Our setup: TYPO3 8.7.26 + RealURL 2.5.0

**Comment by dmitryd** [comment]
I must tell that this is most likely not possible to fix. The problem here is that url is opened from the Backend without the `MP` parameter. RealURL only builds url from what TYPO3 gives to it. If the `MP ` parameter is not present when the page is viewed, it will not be appended to any links and it will not be received by RealURL too. So RealURl will not be able to build a page with a proper mount point.

Sorry :(

**Comment by michaelscheel** [comment]
Okay, but the issue even occurs if no one is using the backend. Could it be connected to a scheduler job (e.g. solr indexing)?

**Comment by dmitryd** [comment]
@michaelscheel realurl encodes data as is. So if url comes without `MP`, realurl will use it like that and store like that.

**Comment by dmitryd** [comment]
Decision: not fixable by realurl if `MP` is not provided.
