### ISSUE TITLE
Probably superfluous database query upon banUrlsRegExp requests

### ISSUE THREAD

**Issue by virtuaris** [dmitryd/typo3-realurl#664]
Hi Dmitry,

is there any technical reason why in `UrlEncoder::executeEncoder()` when encoding a URL, which contains a pattern provided in `banUrlsRegExp`,  the cache table is checked for that URL (`$this->fetchFromUrlCache()`) though it's determined that the URL will never be stored in the cache since `$this->canCacheUrl()` will return `false`?
Seems to me that `$this->fetchFromUrlCache()` triggers an unnecessary database lookup in that case but maybe i don't see the bigger picture?

Bests

Harald

**Comment by dmitryd** [comment]
@virtuaris 

If data can be fetched from the cache, it is used without checking for `banUrlsRegExp` because it is faster. Usually it is justifief because typically there are many more requests to urls that are not banned.
