### ISSUE TITLE
alias_field is saving IF(path_segment!='',path_segment,title) as string in the DB (tx_news)

### ISSUE THREAD

**Issue by alexthunder3** [dmitryd/typo3-realurl#665]
Hey,
As stated in the title, I have a typo3 7.6 installation with realurl 2.5.0 and news 6.2.1. I've used the default tx_news config as stated in the tx_news manual 
https://docs.typo3.org/typo3cms/extensions/news/6.2.1/AdministratorManual/BestPractice/Realurl/#alias-field-variations 
and also seen referred to in some issues here 
https://github.com/dmitryd/typo3-realurl/issues/62 

I'm not entirely sure if this is causing any problems or is intended as I've only a handful of news to work with and they all work so far.
I'm seeing ``` IF(path_segment!="",path_segment,title)``` saved in the tx_realurl_uniqalias table under field_alias. Is this intended?
![Screenshot from 2019-04-12 11-03-32](https://user-images.githubusercontent.com/20271194/56026364-46333180-5d14-11e9-937e-b453357a51c7.png)

Thanks and regards,
Alex.

**Comment by kvonspiczak** [comment]
thats intended and shouldnt cause any trouble. i have the same behavior on a 8.7.24 installation

**Comment by alexthunder3** [comment]
Nice. Thanks!
