### ISSUE TITLE
Wiki: Scheduler suggestion outdated

### ISSUE THREAD

**Issue by Ceremony64** [dmitryd/typo3-realurl#668]
The wiki page for [cache clean up](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#cache-clean-up) is outdated: Both tx_realurl_urlcache and tx_realurl_pathcache no longer exist in the most recent version (2.5.0). Please update the section to reflect the new table names. Thanks!

**Comment by dmitryd** [comment]
@Ceremony64 In newer versions of realurl it is actually harmful to remove data from those tables. So I removed cleanup information from the wiki completely.

Thank you.
