### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by instruccionesaldorso** [dmitryd/typo3-realurl#669]
Can the latest version of the extension be checked against PHP 7.3 compatibility?

https://github.com/dmitryd/typo3-realurl/blob/development/ext_emconf.php#L29
https://github.com/dmitryd/typo3-realurl/blob/development/composer.json#L28

**Comment by LeoniePhiline** [comment]
@dmitryd We are using the extension for quite a while on PHP 7.3.
Please release a new version with adjusted restraints for 7.3 on packagist, so everyone can let go of the obnoxious `--ignore-platform-reqs`.

Thank you!

**Comment by instruccionesaldorso** [comment]
Any update on this issue? The only extension with no PHP 7.3 restraint we have in our systems is this one.

**Comment by PowerKiKi** [comment]
This is a duplicate of #657 and should be closed.

**Comment by dmitryd** [comment]
There was a report in TYPO3 slack that somebody had problems with php 7.3 and regexp used in realurl.

**Comment by dmitryd** [comment]
Merged the PR.
