### ISSUE TITLE
Speaking URL management in TYPO3 6.2.

### ISSUE THREAD

**Issue by MichiBeck** [dmitryd/typo3-realurl#67]
I´m running TYPO3 6.2.19 and updated RealUrl to 2.0.6. It looks fine but I can´t clear caches because the "Speaking URL management"-Tab is missing in WEB-Section and also in Info, where it was till 2.0. In TYPO3 7.6.4 it appears.

![realurl](https://cloud.githubusercontent.com/assets/15154464/13668768/23e89cf6-e6bf-11e5-95ac-fffaf087ab52.JPG)

Does anyone else has this problem?

**Comment by dmitryd** [comment]
1. It never was there before 2.0 for the official realurl.
1. Backend modules work only with TYPO3 >= 7.6.0. They do not work in 6.x and there are no plans to make them work there.

Not a bug.

**Comment by MichiBeck** [comment]
I know that it never was there. I thought it should...
Thanks.
