### ISSUE TITLE
Documentation on on wiki.typo3.org

### ISSUE THREAD

**Issue by linawolf** [dmitryd/typo3-realurl#670]
There are still some information and examples on the TYPO3 wiki. The documentation team is trying to clean up the wiki and I am helping.

Do we still need the following documentation and examples:

https://wiki.typo3.org/RealURL (last changed 2016)
https://wiki.typo3.org/Realurl/examples L (last changed 2017)
https://wiki.typo3.org/Realurl/manual (Last changed in 2018)
https://wiki.typo3.org/Realurl/testing (Last changed in 2016)

And if yes should I move it to the wiki in your git?

Greetings Lina

**Comment by dmitryd** [comment]
@linawolf Most of information on wiki.typo3.org is obsolete. You can simply leave a message there with a link to wiki here.
