### ISSUE TITLE
Registered hooks are unset when auto conf is generated

### ISSUE THREAD

**Issue by smichaelsen** [dmitryd/typo3-realurl#676]
The registered hooks are unset when automatic configuration is created, because the `realurl_autoconf.php` is included after creation and overwrites any hooks that may have been registered. That means that this page request has no hooks available.

If you rely on a hook to decode URLs that means the current request will result in an error.
If you rely on a hook to encode URLs that means that wrong URLs will be generated (and cached) during the current request.

I suggest to reset the hooks after creation of the automatic configuration.

**Comment by smichaelsen** [comment]
Edit: Please bear with me. I'm doing additional tests and thinking over this report - this may be a non-issue. I will close it immediately if that is the case.

**Comment by dmitryd** [comment]
Hooks unset???

**Comment by dmitryd** [comment]
Closing because no feedback provided.
