### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by boeschung** [dmitryd/typo3-realurl#678]
Hello,

in a TYPO3 8.7 project we use the latest version of the realurl extension via composer. Now the server on which the website is hosted should be updated, including the PHP version to 7.3. Now the problem is that we can no longer install realurl because the PHP requirements for realurl are "5.4.0 - 7.2.999" and this leads to a conflict.

When can we expect a realurl version that is compatible with PHP 7.3? I saw in the dev branch that it is marked as 7.3 compatible.

Best regards

**Comment by alappe** [comment]
We're having the same issue and would appreciate a `v2.5.1` with updated php requirements.

**Comment by GitHubbler-to-go** [comment]
Same with us. Could you provide support please? Thanks a lot.

**Comment by Patta** [comment]
Just add php 7.2 to platform config in composer.json

https://getcomposer.org/doc/06-config.md#platform

**Comment by michael-binder** [comment]
You can also just use the development branch and check if you have problems with it.

**Comment by dmitryd** [comment]
Already included into development branch.
