### ISSUE TITLE
XML codes at website home

### ISSUE THREAD

**Issue by Dsud** [dmitryd/typo3-realurl#680]
hi,
Recently the home page of my website displays XML codes
I flushed all entries of the Speaking url plugin, it has worked well for a period but I have noticed that The number of Data URLs increases and at certain times an XML page display on site
Any idea
Thanks

**Comment by merzilla** [comment]
Hi @Dsud ,
would you mind to first ask on TYPO3 Slack's realurl channel? As this is for real issues and not a "can i get help" here. On slack you'll find help, however.
I write this because opening such false issues here always notifies a lot of people. Thanks.
