### ISSUE TITLE
ext_emconf.php 2.6.1 is not written well!!

### ISSUE THREAD

**Issue by t3webman** [dmitryd/typo3-realurl#681]
quite a few quotation marks are missing ...

**Comment by mbrodala** [comment]
What exactly do you mean? This file is fully valid:

https://github.com/dmitryd/typo3-realurl/blob/2.6.1/ext_emconf.php

**Comment by t3webman** [comment]
the file I pulled from the repository had all the trailing quotation marks missing ...
I install manually ... no idea where that happened. only that when I tried to handle the extension in the BE I got errors ...

**Comment by linawolf** [comment]
I can confirm. The Version of the file as pulled from TER has quotation marks missing and crashes an installation. For example the quotation mark at the end of description is missing.

**Comment by mbrodala** [comment]
Indeed, [that version](https://extensions.typo3.org/extension/download/realurl/2.6.1/zip) is broken:

```php
<?php

/**
 * Extension Manager/Repository config file for ext "realurl".
 *
 * Auto generated 27-04-2020 11:18
 *
 * Manual updates:
 * Only the data in the array - everything else is removed by next
 * writing. "version" and "dependencies" must not be touched!
 */

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Speaking URLs for TYPO3,
	'description' => 'Makes TYPO3 URLs search engine friendly. Donations are welcome to dmitry.dulepov@gmail.com. They help to support the extension!,
	'category' => 'services,
	'shy' => 1,
	'version' => '2.6.1,
	'priority' => ',
	'loadOrder' => ',
	'module' => ',
	'state' => 'stable,
	'uploadfolder' => 1,
	'createDirs' => ',
	'modify_tables' => 'pages,pages_language_overlay,
	'clearcacheonload' => 1,
	'lockType' => ',
	'author' => 'Dmitry Dulepov,
	'author_email' => 'dmitry.dulepov@gmail.com,
	'author_company' => ',
	'CGLcompliance' => ',
	'CGLcompliance_note' => ',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-8.9.999,
			'php' => '5.4.0-7.3.999,
			'scheduler' => '6.2.0-8.9.999,
		),
		'conflicts' => array(
			'cooluri' => ',
			'simulatestatic' => ',
		),
	),
);

```

**Comment by mbrodala** [comment]
@dmitryd Is there anything you can do here or does this need a fix in TER?

**Comment by dmitryd** [comment]
@mbrodala 

>  Is there anything you can do here or does this need a fix in TER?

As you can see in the [tagged version](https://github.com/dmitryd/typo3-realurl/blob/2.6.1/ext_emconf.php), the file is correct.

If I remember correctly, `ext_emconf.php` does not exist in TER at all. It is generated by TER when the user downloads the extension. So I cannot do anything regarding TER. You can also indirectly see a confirmation of it because comment at the top of TER file is different from the comment in git.

I would recommend to use composer and `"dmitryd/typo3-realurl"` package, not TER.

**Comment by rl-saen** [comment]
I am running into the same problem at the moment when downloading `dmitryd/typo3-realurl` from packagist.
