### ISSUE TITLE
tx_realurl_uniqalias not beeing updated

### ISSUE THREAD

**Issue by derBoogie** [dmitryd/typo3-realurl#682]
Hi,
im my custom extension a SEO-title can be defined for an project, which is shown on a detail project page. The title should be updated by realurl, but it isn't. 
My realurl_conf:
```
...
array (
	'GETvar' => 'iid',
	'lookUpTable' => array(
		'table' => 'user_projects',
		'id_field' => 'uid',
		'alias_field' => 'CONCAT(seotitle, "-", uid)',
		'addWhereClause' => ' AND NOT deleted',
		'useUniqueCache' => true,
		'useUniqueCache_conf' => array(
			'strtolower' => 1,
			'spaceCharacter' => '-',
		),
	),
),
...
```
As I can see, the db-field "value_alias" is not being updated in table tx_realurl_uniqalias, when the seotitle changes.

TYPO3 8.7.32, realurl 2.5.0

Can anyone help?

**Comment by dmitryd** [comment]
> Can anyone help?

https://github.com/dmitryd/typo3-realurl/wiki/Getting-help

**Comment by dmitryd** [comment]
> The title should be updated by realurl

No, it should not because `alias_field` is not `seotitle`.
