### ISSUE TITLE
Because pathdata.pid is on the pages.uid now non-admins can not delete any page with pathdata on it

### ISSUE THREAD

**Issue by foobar13372** [dmitryd/typo3-realurl#685]
The DataHandler deletion check on pages fails because `tx_realurl_pathdata` is not an allowed table for non-admins (all tables on this pid are checked, pathdata among them). However, you can also not allow it in the `be_groups.tables_modify.`

**Comment by christophlehmann** [comment]
We have the issue too with 2.5.0. (Latest version 2.6 currently does not work for us because of #687)

**Comment by dmitryd** [comment]
Temporary solution: give users modify rights to realurl tables via BE group.

**Comment by PeaceSfiSh** [comment]
> Temporary solution: give users modify rights to realurl tables via BE group.

```
page {
    TCEFORM {
        be_groups {
            tables_modify {
                addItems := addToList(tx_realurl_uniqalias,tx_realurl_urldata,tx_realurl_pathdata)
            }
        }
    }
}
```
