### ISSUE TITLE
"RealURL was not able to find the root page id " after deploying a new TYPO3-enviroment 

### ISSUE THREAD

**Issue by padina** [dmitryd/typo3-realurl#70]
German
Ein Jenkenis-Prozess installiert per Composer die gesamte TYPO3-Umgebung in einem separaten Branch und switch dann einen Current-Symlink auf die neue TYPO3-Umgebung. 
Nach diesem Prozess wirft realUrl die Fehlermeldung 
#1453732574: RealURL was not able to find the root page id for the domain "autohus.intern.neusta.de" (More information)
Nach einem einmaligen Deactivieren und Reactivieren von RealUrl taucht der Fehler nicht mehr auf.

--------------

(D)English
I install the envoiroment of TYPO3-site with a via a jenkenis process via composer. The new   environment is written into a new folder. If the process was an success, at last the symlink for the current enviroment with switch to the new folder. 
After this process RealURL raises the following error message
"# 1453732574: RealURL what not able to find the root page id for the domain "..." (More information)
The error will disappear, if I activate and deactive RealUrl one time, .

**Comment by jloderhose** [comment]
I have had that same issue just yesterday. It turned out that it pays to follow the configuration reference closely. ;-)

> **rootpage_id**
> 
> type: integer
> default: empty
> This option is strongly recommended to be set in all cases. _While RealURL is often able to discover root page id correctly from domain records_, it is better to set this value manually in the configuration.

Check your realurl_conf.php (or what ever your config file ist named). Is "rootpage_id" in section pagePath set?

**Comment by padina** [comment]
Hi. 
Hi Jan, 
I used the automaticly realurl_autoconf to generate my realurl_conf.php.
It looks like 
`
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']=array (
  '_DEFAULT' => 
  array (
    'init' => 
    array (
      'appendMissingSlash' => 'ifNotFile,redirect',
      'emptyUrlReturnValue' => '/',
    ),
    'pagePath' => 
    array (
      'rootpage_id' => '1',
    ),
....`

**Comment by padina** [comment]
Remark: 
If you have no pageNotFound-page defined and you try to surf to an not existing page, you get the normal TYPO3-error-page. After that the error comes every time, until I resolve it in the described way.
_"#1453732574: RealURL was not able to find the root page id for the domain ..."_

Dieter

**Comment by dmitryd** [comment]
If you get that error, it means your config is not right. Realurl is not a "install & forget". You must ensure that certain requirements are met, config is right, etc.

This is not a bug.

**Comment by padina** [comment]
Hello Dimitry,
German 
die Fehlermeldung tritt nur nach einem fehlerhaften Zugriff oder nach der Neu-Installation von TYPO3 + Extensions auf. Wenn sie auftritt, dann ist sie hartnäckig und zerschießt jeden Link.
Vielleicht ist es eine Missconfiguration, ich wüsste dann aber nicht, wo der Fehler zu suchen ist. 
Meine LocalConf hat folgenden Aufbau.
Ich werde einen kleinen Check machen. Ich bin, wie der Blick im TYPO3-Forum zeigt, nicht der einzige, der mit solchen Problemen zu kämpfen hat. 
English
the error message occurs only after a failed access or after reinstallation of TYPO3 Extensions +. If it occurs, it is sticky and the message occurs every time.
Maybe. itm could be a wrong configuration, I did not know, where I should look for the mistake. I have done the same think, i did every time.
But I will make a small reseach.
If you look in the german forum, you will see more people with the same problem.

My LocalConf has the following structure
_$TYPO3_CONF_VARS['EXTCONF']['realurl_404_multilingual'] = array(
    '_DEFAULT' => array(
        'errorPage' => 'pagenotfound/',
    ),
);
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']=array (
  '_DEFAULT' => 
  array (
    'init' => 
    array (
      'appendMissingSlash' => 'ifNotFile,redirect',
      'emptyUrlReturnValue' => '/',
    ),
    'pagePath' => 
    array (
      'rootpage_id' => '1',
    ),
    'fileName' => 
    array (
      'defaultToHTMLsuffixOnPrev' => 0,
      'acceptHTMLsuffix' => 1,
      'index' => 
      array (
        'print' => 
        array (
          'keyValues' => 
          array (
            'type' => 98,
          ),
        ),
      ),
    ),
    'preVars' => 
    array (
      0 => 
      array (
        'GETvar' => 'L',
        'valueMap' => 
        array (
            'en' => '1',
            'fr' => '2',
            'ru' => '3',
            'es' => '4',
            'it' => '5',
            'pl' => '6',
            'ro' => '7',
        ),
        'noMatch' => 'bypass',
      ),
        1 =>
            array (
                'GETvar' => 'busi',
                'valueMap' =>
                    array (
                        'busi' => '2',
                        '' => '0',
                        'priv' => '1'
                    ),
                'noMatch' => 'bypass',
            ),
    ),
  ),
);
_

**Comment by dmitryd** [comment]
1. Please, check in System>Configuration that you really have this config
1. If you are upgrading, you should run the update script in the Extension Manager.

**Comment by padina** [comment]
ad 1. goo idea
I miss the RealUrl-Configuration in the Systemconfiguration after the rebuild of the System. The configuration will be loaded after the deactivate-activate-process of the extension. 

ad. 2
The Website is a new website. A migration is not nessessary.
