### ISSUE TITLE
missing urlencode with f:form VH

### ISSUE THREAD

**Issue by pi-phi** [dmitryd/typo3-realurl#71]
with TYPO3 7.6.4 and realurl 2.0.9:
using the form VH 
`<f:form pageUid="{searchPid}" action="search" method="post" id="tx_indexedsearch_mini" noCacheHash="true" extensionName="indexedsearch" pluginName="pi2" controller="Search">` 
results in the incorrect url:
`<form method="post" id="tx_indexedsearch_mini" action="/suche/?tx_indexedsearch_pi2[action]=search&amp;tx_indexedsearch_pi2[controller]=Search">` 
where the urlencoding of `[` and `]` is missing.

**Comment by pi-phi** [comment]
realurl 1.13.6 is working correct

**Comment by dmitryd** [comment]
Thank you for reporting. It will be fixed in the next update.
