### ISSUE TITLE
config.tx_realurl_enable not evaluated for URLdecoding

### ISSUE THREAD

**Issue by liayn** [dmitryd/typo3-realurl#72]
We used to have realurl installed on our dev machines as well, but disabled it by using TS like this:
```
[applicationContext = Development*]
  config.tx_realurl_enable = 0
[end]
```

realurl 2.0.9 still tries to decode URLs and fails (`#1420480928: RealURL was not able to find the root page id for the domain "kleindev"`) due to missing domain configuration.

In my opinion realurl must NOT take any action (not even looking at the configuration) if it is disabled.

**Comment by dmitryd** [comment]
Not possible. When decoding runs, there is no TypoScript yet: TypoScript is processed for a specific page and page is not known yet (not decoded). That option works only when URL is encoded.

You have to either uninstall realurl or configure it correctly.

**Comment by liayn** [comment]
Ok understandable, but not really funny of course.

It would be much more convenient to have a setting. What about an EM setting?

**Comment by liayn** [comment]
Nevertheless I just wonder why realurl tries to fetch some config at all, since it should be able to detect that this is not a speaking url: `http://kleindev/76/index.php?id=165`

**Comment by dmitryd** [comment]
No, I do not think so. If you installed realurl, than you did it on purpose. If you do not want to use it, just uninstall it. But better fix issues because you will face them in production anyway. How do you plan to go live with the project if you do not run it with full functionality daily? You actually should always have realurl enabled to spot any problems with urls.

**Comment by dmitryd** [comment]
> Nevertheless I just wonder why realurl tries to fetch some config at all, since it should be able to detect that this is not a speaking url: http://kleindev/76/index.php?id=165

Actually this *is* a speaking URL :) But a completely wrong one.

**Comment by liayn** [comment]
Multi-staging. On local dev, no realurl, on staging full realurl, on prod full realurl.
We cannot uninstall realurl for local dev, since it is required in our sitesetups, which ensures that all exts we use on production are installed automatically.

What is speaking here?? T3 simply runs in a subfolder of docroot.

**Comment by dmitryd** [comment]
/76/ looks like a speaking URL to realurl.

**Comment by liayn** [comment]
well, then the check is wrong. sitepath needs to be considered first!

**Comment by liayn** [comment]
We talk about this line, so to say: https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L1078

**Comment by dmitryd** [comment]
The check is identical to realurl 1. Nothing is changed in that piece of code.

**Comment by liayn** [comment]
Still something must have been different with 1.x, since it worked in exactly this setting. realurl installed on dev, disabled via TS. Maybe some other parts have been improved to do better/harder validation, but at least this is broken.
And not checking for possible subdirectories (which is a totally valid usecase to run T3 in a subdir or docroot) is definitely a bug.

**Comment by liayn** [comment]
I'm looking into the issue now, and will check what the Core returns here for 
`$this->siteScript = GeneralUtility::getIndpEnv('TYPO3_SITE_SCRIPT');` in our case.

**Comment by dmitryd** [comment]
Config checking became more strict. The reason for this is simple: I get too many false requests due to wrong config. Realurl 2 is more strict and always requires valid root page id now.

For the subdirectories: unfortunately I have no time for that. This project is free, as you know, and I do in the time, which I also share with my family. I'd rather play with kids that try to fix every non-standandard installation.

If you can submit a pull request for this, I am willing to look at it but I cannot promise anything. It depends on available time and complexity.

**Comment by liayn** [comment]
I appreciate strict config checking! No question about that.

Dmitry, stay professional please:
> fix every non-standandard installation
This is by far not a non-standard installation! I fully understand that you're spammed with reports/questions/etc, but running a website in a subdirectory is really a very basic, and very normal thing.

I'm looking forward to your feedback on a possible PR.

**Comment by liayn** [comment]
Ok, PR coming in a minute. The solution is dead-simple.

Wrong:
```
			$this->initialize();
			if ($this->isSpeakingUrl()) {	
```

Right:
```
			if ($this->isSpeakingUrl()) {
				$this->initialize();
```

https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L129

**Comment by dmitryd** [comment]
> Dmitry, stay professional please:

It is strange to read that after hundreds hours of my personal time invested to this code, its improvement and support during past days (including weekends). I find that offensive :(

**Comment by liayn** [comment]
I do the same as you might know and I find it quite offensive of you to call an installation in a subdir a "non-standard" instance. But I'm not here to waste our time with offenses. Let's keep those emotions aside and focus on getting the issue sorted out.

**Comment by dmitryd** [comment]
FYI: I removed offtopic from the issue report.

**Comment by dmitryd** [comment]
Fixed by merging the PR. Thank you for contribution!

**Comment by liayn** [comment]
Thanks.

**Comment by dmitryd** [comment]
I'll have to revert it because it breaks language-based domains :disappointed: or do something else to fix it...

**Comment by liayn** [comment]
Are you sure that this change is responsible? I looked at the code and couldn't find any dependency of the init() function. So I wonder how this is related.

**Comment by dmitryd** [comment]
Configuration sets $_GET when using language domains.

**Comment by dmitryd** [comment]
But I know how to fix it. No worries. There will be no exception.

**Comment by liayn** [comment]
Ok perfect. Thx.
