### ISSUE TITLE
spaceCharacter in pagePath not respected?

### ISSUE THREAD

**Issue by janslu** [dmitryd/typo3-realurl#73]
Because of historical reasons I am using 

'pagePath' => array(
            'type' => 'user',
            'segTitleFieldList' => 'tx_realurl_pathsegment,alias,title',
            'spaceCharacter' => '_',

in my configuration. On my testsite running current 7.6 installation and realurl 2.0.9 it is not respected and urls contain dash (-) as a space substitute instead of the underscore. Is this setting deprecated or is this is a bug?

**Comment by dmitryd** [comment]
https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#pagepath

**Comment by dmitryd** [comment]
Added but deprecated.

**Comment by janslu** [comment]
Thank you! This will give me enough time to make a transition plan. Much appreciated.
