### ISSUE TITLE
Set server variable QUERY_STRING fails

### ISSUE THREAD

**Issue by sneopu** [dmitryd/typo3-realurl#75]
I have a problem with the UrlDecoder. In the function setRequestVariables() realurl override the $_SERVER['QUERY_STRING']. 
`Line 1352: $_SERVER['QUERY_STRING'] = $this->createQueryString($requestVariables);`

This is fine but it doesn't work in my case, because of the caching of the environment variables.
In the function createQueryString() realurl call GeneralUtility::getIndpEnv('QUERY_STRING') at this time the $_SERVER['QUERY_STRING'] is empty and get cached as empty value. After this call $_SERVER['QUERY_STRING'] get overriden with the correct value by setRequestVariables(). But if there is later a typolink who get the $_SERVER['QUERY_STRING'] from GeneralUtility::getIndpEnv('QUERY_STRING'), he get the cached empty value instead of the correct value from  $_SERVER['QUERY_STRING']. 
The caching happens in GeneralUtilility::getIndpEnv($getEnvName)

As workaround I made following modification, maybe it could be a final solution.
In function createQueryString() instead of 
`$queryString = GeneralUtility::getIndpEnv('QUERY_STRING');`
I  use 
`$queryString = $_SERVER['QUERY_STRING'];`

Realurl: v2.0.9
TYPO3 v7.6.4

**Comment by dmitryd** [comment]
Thank you for reporting!

**Comment by sneopu** [comment]
Thanks a lot for your hard work. It is really amazing to see how fast and professional you fix the small bugs in realurl 2.x.

**Comment by dmitryd** [comment]
:smile:
