### ISSUE TITLE
Resolve to invalid page id because of bad cache entries

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#76]
When deleting a page in TYPO3 the cache entry in tx_realurl_urlcache will not be deleted.

When recreating a page with the same name, the old cache entry will be returned when resolving the URL:
![Database Entries](https://cloud.githubusercontent.com/assets/209159/13746776/44818840-e9f5-11e5-9025-49db01bc2904.png)

I think the DatabaseCache::getUrlFromCacheBySpeakingUrl method should check that the page still exists, when resolving the page_id. It would be enough to enough to join on `pages` and use BackendUtility::deleteClause and BackendUtility::BEenableFields

**Comment by dmitryd** [comment]
Yes, the bug exists. As a workaround you can rename the old page first. I hope to fix this soon.

**Comment by dmitryd** [comment]
Should be in 2.0.10.

**Comment by rvock** [comment]
Thank you :) That was quick
