### ISSUE TITLE
Wiki: little error in documentation

### ISSUE THREAD

**Issue by peterkraume** [dmitryd/typo3-realurl#77]
In the first paragraph it says:

> The following features are missing from RealURL 2.x comparing to RealURL 2.x:

Which should be:

> The following features are missing from RealURL 2.x comparing to RealURL 1.x:

I would have fixed that with a pull request but found no way to edit the wiki.

**Comment by dmitryd** [comment]
Thank you, fixed :)

https://github.com/dmitryd/typo3-realurl/wiki/Differences-between-RealURL-1.x-and-2.x
