### ISSUE TITLE
Translated pages with activated tx_realurl_exclude -> 404

### ISSUE THREAD

**Issue by Gernott** [dmitryd/typo3-realurl#80]
If you activate the checkbox tx_realurl_exclude in pageproperties in defaultlanguage, all subpages of it in other languages don't work:
- The url is generates correct: /en/contact/
- On clicking, this appears: 
Page Not Found
Reason: Segment "contact" was not a keyword for a postVarSet as expected on page with id=1.

My contact-page have not uid 1.
If i disable the checkbox, it works, and the url is: /en/footer/contact/
The default language always works fine.

realurl 2.0.9

**Comment by nothdurfterf** [comment]
Same Problem here! For me this bug only occurs if i'm currently logged into TYPO3 Backend, otherwise the pages work as expected.

realurl 2.0.9
TYPO3 6.2.19

**Comment by dmitryd** [comment]
Thank you for reporting!
