### ISSUE TITLE
Nested domains

### ISSUE THREAD

**Issue by ursbraem** [dmitryd/typo3-realurl#82]
Hi 
I just read this

> There must be no "nested domains". This means that there can be only one domain record from the current page down to the root of the page tree. RealURL does not support nested domains!

Was that already the case for 1.x, or is that just for 2.x?

**Comment by dmitryd** [comment]
https://github.com/dmitryd/typo3-realurl/wiki/Contributing#bug-reporting

**Comment by ursbraem** [comment]
got it, sorry!
