### ISSUE TITLE
TYPO3 6.2.19: Module not visible, Info Module not working 

### ISSUE THREAD

**Issue by woodyc79** [dmitryd/typo3-realurl#83]
Hello!

I got this error after updating to latest realurl version:
exec_SELECTquery
caller	TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery
ERROR	Unknown column 'cache_id' in 'field list'
lastBuiltQuery	SELECT page_id, language_id, pagepath, cache_id FROM tx_realurl_pathcache WHERE page_id IN (241) AND language_id = 0 ORDER BY language_id ASC, expire ASC
debug_backtrace	require(typo3/sysext/info/mod1/index.php),typo3/mod.php#32 // TYPO3\CMS\Info\Controller\InfoModuleController->main#37 // TYPO3\CMS\Backend\Module\BaseScriptClass->extObjContent#95 // B13\SeoBasics\BackendModule\SeoModule->main#367 // B13\SeoBasics\BackendModule\SeoModule->loadPathCache#200 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_SELECTquery#429 // TYPO3\CMS\Core\Database\DatabaseConnection->debug#305

Regards,
Chris

**Comment by dmitryd** [comment]
It looks like you upgraded to version 2. Backend modules in version 2 only work with TYPO3 7.6. They do not appear in 6.2. This is how it is (not a bug).

The error message does not come from realurl: `B13\SeoBasics\BackendModule\SeoModule` is not realurl. Please, contact the author of that extension regarding this error.

There is nothing that can be fixed here.
