### ISSUE TITLE
Automatic RealUrl configuration creates wrong link for news single view

### ISSUE THREAD

**Issue by phifa** [dmitryd/typo3-realurl#85]
I am running TYPO3 7.6.2 with RealUrl 2.0.1 and News 4.2.0. I used the auto configuration and it created this. Problem is with the news single view. It outputs a wrong link: 

```
<?php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']=array (
  '_DEFAULT' => 
  array (
    'init' => 
    array (
      'appendMissingSlash' => 'ifNotFile,redirect',
      'emptyUrlReturnValue' => '/mydomain.de/',
    ),
    'pagePath' => 
    array (
      'rootpage_id' => '1',
    ),
    'fileName' => 
    array (
      'defaultToHTMLsuffixOnPrev' => 0,
      'acceptHTMLsuffix' => 1,
      'index' => 
      array (
        'print' => 
        array (
          'keyValues' => 
          array (
            'type' => 98,
          ),
        ),
      ),
    ),
    'preVars' => 
    array (
      0 => 
      array (
        'GETvar' => 'L',
        'valueMap' => 
        array (
          1 => '1',
        ),
        'noMatch' => 'bypass',
      ),
    ),
    'postVarSets' => 
    array (
      '_DEFAULT' => 
      array (
        'news' => 
        array (
          0 => 
          array (
            'GETvar' => 'tx_news_pi1[news]',
            'lookUpTable' => 
            array (
              'table' => 'tx_news_domain_model_news',
              'id_field' => 'uid',
              'alias_field' => 'title',
              'useUniqueCache' => 1,
              'useUniqueCache_conf' => 
              array (
                'strtolower' => 1,
                'spaceCharacter' => '-',
              ),
            ),
          ),
        ),
      ),
    ),
  ),
);

```

This is the link it created: 
`http://mydomain.de/news/news-detail/news/ich-bin-auch-eine-news/?tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&cHash=b72f8e389f2d901418a6097a5f6fc8bd`

But it should be (I guess, since this works): 
`http://mydomain.de/news/news-detail/news/ich-bin-auch-eine-news/`

**Comment by dmitryd** [comment]
Please, contact the [author](https://forge.typo3.org/users/128) of `EXT:news`. Configuration is provided to realurl by that extension. Realurl does not know anything about news extension or about any other extension. It only provides a way to extensions to _add_ their config to realurl.

Some links:
* [RealURL in the `EXT:news` documentation](https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/Realurl/Index.html)
* [Code that creates this configuration inside `EXT:news`](https://forge.typo3.org/projects/extension-news/repository/revisions/master/entry/Classes/Hooks/RealUrlAutoConfiguration.php)
