### ISSUE TITLE
Cache tables remain empty

### ISSUE THREAD

**Issue by DenisMir** [dmitryd/typo3-realurl#86]
Ok I got a weird error. 

I got a bare TYPO3 7.6.4 LTS setup in composer mode with the default `.htaccess` file. The only extension I have installed via composer is `realurl` version 2.0.9. 

I made a minimal setup with one page configured as site root called `Website` and a ts template with `config.tx_realurl_enable = 1`. 

In the end the page tree looks like: 

Website (site root configured to `shortcut first subpage`)
|---- Home

When I'm accessing `/` in the browser I'm getting the first subpage correctly translated to `/home`. But when looking at the caching tables I'm seeing nothing. When looking at the backend module I'm getting the same: 

![bildschirmfoto 2016-03-17 um 15 25 40](https://cloud.githubusercontent.com/assets/157281/13849124/102fd224-ec55-11e5-882a-2a8bb0fd96ee.png)

Do I lack some more configuration for this absolutely basic setup to get the caching working correctly? Or do I miss something else here?

**Comment by dmitryd** [comment]
Log out from the Backend :) Cache is not enabled when you are logged in to the Backend.

**Comment by DenisMir** [comment]
Ok this thing got me one more time. *grr* 

Thank you very much :+1:
