### ISSUE TITLE
Menu separator caused error 404

### ISSUE THREAD

**Issue by kreativpower** [dmitryd/typo3-realurl#88]
If you use menu separator, you get a 404 error.

As an example:

404 Page not found!
Reason: Segment " menu-seperator " was not a keyword for a postVarSet as expected on page with id=1.

Current URL: /en/menu-seperator/contact.html

**Comment by dmitryd** [comment]
Menu separator is a menu separator, it is not a container for subpages. You should use folder.

Specially for people, who like to use things in a wrong way there is a check box in the extension properties, which is named "Enable bad behavior" :smile: It will allow you to use separator for storing subpages.

But it is a bad choice.
