### ISSUE TITLE
none url when short cut of other root page

### ISSUE THREAD

**Issue by DavidsWONG** [dmitryd/typo3-realurl#91]
when the x root page （1.domain.com）have some shortcuts from other rootpage（ps 2.domain.com），i get the URL “/”
it's boring for me.

**Comment by DavidsWONG** [comment]
it can be work in realURL 1 and typo3 6
but now i using realurl2 and typo3 7.6.4

**Comment by dmitryd** [comment]
I cannot understand anything here :(
