### ISSUE TITLE
Redirects still work, but should not -> documentation

### ISSUE THREAD

**Issue by thomaszbz** [dmitryd/typo3-realurl#92]
Towards a documentation/wiki enhancement:

I'm using realurl 2.0.10, TYPO3 CMS 6.2.19, PHP 5.6, Apache 2.4.10.

https://github.com/dmitryd/typo3-realurl/wiki/Differences-between-RealURL-1.x-and-2.x#redirects claims that redirects as a feature were removed. Indeed, table `tx_realurl_redirect` is marked for removal via install tool's DB-compare after update (I did not remove it yet to not loose the information). When I add a new entry to `tx_realurl_redirect` [with SQL](https://www.slicewise.net/php/realurl-redirects-mit-sql-automatisch-erzeugen/), this redirect does not work which is perfectly fine according to realurl's new feature set in version 2.x+.

However, I tried to request redirects which existed _before_ the update to 2.x. Such an old entry in the unused table `tx_realurl_redirect` was

    SELECT url, destination, has_moved FROM tx_realurl_redirects where uid=60;
    +-------------------------------------------+--------------------------------------+-----------+
    | url                                       | destination                          | has_moved |
    +-------------------------------------------+--------------------------------------+-----------+
    | anwendungsentwicklung/anwendungssoftware/ | /web-engineering/anwendungssoftware/ |         1 |
    +-------------------------------------------+--------------------------------------+-----------+

After realurl update, I cleared all the TYPO3 caches, including the cache-clear button in the install tool and opcode cache. I also restarted Apache. I could not clear realurl's cache because the Info module is gone in 6.2 (#83).

Still, I got a redirect via http status 302 from realurl:

> wget https://www.example.com/anwendungsentwicklung/anwendungssoftware/
--2016-03-19 19:27:53--  https://www.example.com/anwendungsentwicklung/anwendungssoftware/
Auflösen des Hostnamen »www.example.com (www.example.com)«... 62.1.2.3
Verbindungsaufbau zu www.example.com (www.example.com)|62.1.2.3|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 302 TYPO3 RealURL redirect for expired page path
Platz: https://www.example.com/web-engineering/anwendungssoftware/ [folge]
--2016-03-19 19:27:53--  https://www.example.com/web-engineering/anwendungssoftware/
Wiederverwendung der bestehenden Verbindung zu www.example.com:443.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 14876 (15K) [text/html]
In »»index.html.8«« speichern.

Using `wget` with no proxy in between and therefore no cache in between, there is no reason for the 302 redirect which comes from realurl according to the http status message.

However, there still is an entry in `tx_realurl_pathcache`

    select page_id, pagepath from tx_realurl_pathcache where uid=428;
    +---------+------------------------------------------+
    | page_id | pagepath                                 |
    +---------+------------------------------------------+
    |      34 | anwendungsentwicklung/anwendungssoftware |
    +---------+------------------------------------------+

Could you please document via https://github.com/dmitryd/typo3-realurl/wiki/Differences-between-RealURL-1.x-and-2.x#redirects how the behaviour of realurl _should_ be? If the redirect feature is gone, I'd expect that redirects no longer work. Now that it still works on a cache table, it should be documented, under which circumstances it still works and how long this will be the case. E.g. will it stop on clearing realurl's cache (wiping out all the old entries in `tx_realurl_pathcache`)? Maybe users should be aware of it, or at some time in the future they clear the realurl cache and out of a sudden all the old redirects don't work any more. That could easily happen to 6.2 users who can't access a backend module to clear caches after updating and a scheduler task for clearing realurl caches potentially pops up one day in the future.

**Comment by dmitryd** [comment]
Redirects in realurl 2.x do not work for `tx_realurl_redirect` because there is no code that handles redirects. If you look carefully, you will see that status is: ` TYPO3 RealURL redirect for expired page path`. It is expired page path, not the database table entry.

**Comment by thomaszbz** [comment]
I see. Now that I know what is meant with `expired`, I still think it should be documented that expired redirects can and/or will be lost as soon as someone clears realurl's cache in the future, wiping out all the expired entries (at least if that's the case. You should come clear on that and document it, which basically is the concern of this issue.).

Hardly anyone will notice the `expired` message in the response and know what it means, until expired redirects disappear one day and e.g. google's Search Console (aka webmaster tools) complains about missing redirects.

To avoid such a surprise, integraters should clear the cache after updating to 2.x to wipe out all the expired entries after e.g. the [migration](https://www.slicewise.net/php/htaccess-redirects-von-realurl-mit-sql-erzeugen/) towards redirects via `.htaccess`. As a workaround for the missing Info module / Scheduler Task, cache could eventually be cleared with a SQL statement.

**Comment by dmitryd** [comment]
> I still think it should be documented that expired redirects can and/or will be lost as soon as someone clears realurl's cache in the future, wiping out all the expired entries (at least if that's the case. You should come clear on that and document it, which basically is the concern of this issue.).

Just leave cache alone :) Realurl manages it as needed.

**Comment by thomaszbz** [comment]
After converting realurl's redirects to `.htaccess` redirects, clearing caches with

    TRUNCATE tx_realurl_urlcache;
    TRUNCATE tx_realurl_pathcache;

did the trick for me, so there's no surprises for me in the future.
