### ISSUE TITLE
Doktype "Mount Point" fails with server error 500 "To many redirects"

### ISSUE THREAD

**Issue by sneopu** [dmitryd/typo3-realurl#93]
We have a TYPO3 installation with subtrees from mountpoints. It works fine with realurl v1 or without realurl. But with realurl v2.0.10 we got a error 500. I deleted all realurl tables after updating from v1 and create them again with the db compare tool.

```
example.com
-- private (uid: 3, [?id=3], {private/})
---- page1 (uid: 135, [?id=135], {private/page1/})
------ subpage1 (uid: 165, [?id=165], {private/page1/subpage1/})
------ subpage2 (uid: 164, [?id=164], {private/page1/subpage2/})
-- business (uid: 111, [?id=111], {business/})
---- page1 (uid: 380, mountpoint to page1, [id=135&MP=135-380], {business/page1/})
------ subpage1 (no separate uid, from mounpoint, same privat/subpage1, [id=165&MP=135-380], {business/page1/subpage1/})
------ subpage2 (no separate uid, from mounpoint, same privat/subpage2, [id=164&MP=135-380], {business/page1/subpage2/})
```

In brackets [] are the parmeters without realurl encoding.
In curly braces {} the realurl paths.

The page 380 {business/page1/} has the doktype "Mount Point", the setting "Show Content from" is set to "Mounted Page" and the "Mounted Page" is 135 {private/page1/}
The page 380 {business/page1/} fails with a error 500 "To many redirects". The subpages {business/page1/subpage1/} or {business/page1/subpage2/} working fine.

Server error log shows a bunch of follwing entries:
192.168.111.156 - qqq_extern [22/Mar/2016:09:00:09 +0100] "GET /business/page1/ HTTP/1.1" 307 414 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"

Thanks for analyzing this behavior.

**Comment by sneopu** [comment]
Umm. Wait, it seems to work right now. There was some strange caching in the browser. I do further analyse the problem.

**Comment by sneopu** [comment]
Did some further testing. Works fine with clean browser cache.

**Comment by sneopu** [comment]
New facts on this. The error happens only if there is a backend user logged into TYPO3 Backend. This is the reason why it works with a clear browser cache (incognito mode). Could you reproduce this behavior?

**Comment by dmitryd** [comment]
Thank you for reporting. I am on vacation now and will be able to check it only in a week or two.

**Comment by sneopu** [comment]
Thanks a lot. It works like a charm now with 2.0.11
