### ISSUE TITLE
Cross Domains Links not working

### ISSUE THREAD

**Issue by gdnwp** [dmitryd/typo3-realurl#94]
Links across Domains (pagetrees) are not working. Realurl generates only "/".

I think because only the Config of the current Host is loaded and $this->rootPageId is always the rootpage of the current page and not of the target-page.

So in UrlEncoder -> createPathComponentUsingRootline Line 431:
$page['uid'] == $this->rootPageId
is never true.

**Comment by DanielHaring** [comment]
I ran into the same issue today.

As long as this malfunction persists, I’m XCLASSing the Configuration Reader and overwrite the host if a specific page is called.

Please note that this fix creates an additional instance of the Rootline Utility and queries the database for sys_domain records. There may be a more performant way by reusing already fetched data. This is why I’m not creating a Pull Request.

The Xclass is used in one of my projects (feel free to use it):
https://github.com/DanielHaring/TYPO3-Crystalis/blob/master/Classes/Xclass/ConfigurationReader.php

Greetings,
Daniel

**Comment by Kephson** [comment]
I'm using realurl 2 in a project with two trees and two domains and cross domain linking works as expected. Is this a special configuration?

**Comment by DanielHaring** [comment]
Not that I know of. I have 3 trees and 3 domains. When I’m linking from one tree to another, the whole page path gets lost.

No matter what subpage I’m trying to link to, the generated link always will direct to the home page (while the domain itself is accurate though).

As I see it, the central issue is the way RealURL determines the host:

```php
GeneralUtility::getIndpEnv('HTTP_HOST‘)
```

In further consequence the root page identifier of the **current** domain will be used when compared to the rootline of the **target** domain.

As *gdnwp* figured out, the generation of the path effectively fails in \DmitryDulepov\Realurl\Encoder\UrlEncoder on line 428 (a719c7f, master).

**Comment by gdnwp** [comment]
I don't think, i have a special configuration.

btw: It "works", if you set the "Speaking URL path segment" override for the whole path.
But the Cache entries are set incorrectly with the wrong rootpage_id.

The big problem is that realurl2 uses always the current realurl-config and not the config of the target page.

**Comment by dmitryd** [comment]
Give me some time, ok? :smile: This is a free project and I do not have much free time. I know how to fix it. I just need to find time for it.

**Comment by sebastian-krebs** [comment]
I am also facing problems with the cross domain link in version 2.0.14.

My setup is one root page with 4 sub-pages. The main template is located on the root page, the domain records are located on the sub-pages. Below each sub-page with domain record the real content pages are located. Please see the screenshot attached.

![screen shot 2016-05-20 at 10 23 28](https://cloud.githubusercontent.com/assets/8245249/15421684/f275a0a4-1e74-11e6-9165-0efd486eb8be.png)

RealURL is configured with the different domain records and it seems the problems only appeared after upgrading to 2.x. If I link from the tree Family (let's say page "Das WE") to the page SAP Fakten I only receive a link to the proper domain (the first domain record within the branch sub-page "Consulting") but not to the proper page but only to /.

Is this mentioned fix already working in version 2.0.14 or is there still an issue with this kind of setup?

**Comment by Kephson** [comment]
For me it worked fine with 
config.typolinkCheckRootline = 1
config.typolinkEnableLinksAcrossDomains = 1
and correctly setup of the domains in realurl configuration.

**Comment by sebastian-krebs** [comment]
Ok... I also see it working. The issue came from a not properly working auto configuration. I found the hint in this video: https://www.youtube.com/watch?v=DvpUjiyS_Ks

**Comment by gautamsinh** [comment]
Hello ,
I have use below configuration ,but steel its not working for me , 
config.typolinkCheckRootline = 1
config.typolinkEnableLinksAcrossDomains = 1

Is there need any additional settings required??
Please help 
Thanks in advance

**Comment by olegkarun** [comment]
In my case it was:

RealUrl configuration` basic.enableAutoConf` shoud be off and `realurl_autoconf.php` - deleted
