### ISSUE TITLE
title, nav_title uniqueInPid

### ISSUE THREAD

**Issue by stephangrass** [dmitryd/typo3-realurl#95]
Hi,
you add $GLOBALS['TCA']['pages']['columns']['nav_title']['config']['eval'] .= ',uniqueInPid'. This might be good, but not if you have a multisite page, where all website-pages are on the same level. 

I will be a good feature to prevent duplicate path parts but I think, that the system should not check duplicate title and nav_title of pages set "Use as Root Page".

**Comment by dmitryd** [comment]
See #106
